### PR TITLE
Add optional mobile guide toast

### PR DESCRIPTION
**Pull request by jryans**
This adds an optional toast which Element deployments can enable to nudge users towards the mobile apps once they are inside the app. It will only appear on iOS and Android web browsers.

image

Part of https://github.com/vector-im/element-web/issues/16283
Documented in https://github.com/vector-im/element-web/pull/16301

### CODE REVIEW

**Review by benparsons — APPROVED** [review]
(discussed in room separately)
lgtm

**Review by dbkr — APPROVED** [review]

**Comment by jryans** [comment]
Okay, since this is only optional, I'm going to go ahead and merge it.

**Comment by niquewoodhouse** [comment]
👋 @jryans just a couple of (super small) concerns from design, but they're nothing major at all/anything worth blocking shipping.  I'm probably just missing some context around why a toast etc, so just commenting in case helpful, but feel to free to not respond if busy.

**- When does this appear? Is it noticeable enough?**  

If people's experience of Element will be broken, they'll be more likely to decide not to return/think of the product as useful.  So, if we have a modal component, I'd suggest it might be better to block people briefly, but at least be sure they know we have stable options somewhere?

Basic example
Screenshot 2021-01-29 at 12 16 24

**- Copy**
Some copy changes could improve clarity.  
As a user, I wouldn't be sure what learn more does, does it go to a page to learn more/does it open the app store? And the heading "mobile experience" doesn't say much.  Something like the following might help encourage interaction:

- Use apps for a better mobile experience ~~Mobile experience~~ 
- Element web is experimental on mobile.  For a better experience and the latest features, use our free app ~~Element web is....~~
- Download app ~~Learn more~~

**Comment by jryans** [comment]
@niquewoodhouse Thanks for the feedback! To clarify slightly, this toast is an off-by-default thing we're trialling with some deployments, so it's at least not going out to the entire user base at once, which I think buys us a bit more time for iterating and improving.

About it being a full-screen overlay instead of toast... I used a toast partly out of expediency and partly because we want to still allow a 3PID room invite to be completed on screen. It's certainly a messy UX for sure, so we should aim for something better / more holistic where there's more time available. I'll copy these notes to a separate issue for the future.

About the copy changes, those look good to me, so I'll add those now. 😄

**Pull request merged**
