### PR TITLE
Trigger lazy loading when filtering using spaces

### PR DESCRIPTION
**Pull request by t3chguy**
so that the filtered DMs are correct

Fixes https://github.com/vector-im/element-web/issues/17002

### CODE REVIEW

**Comment by jryans** [comment]
Hmm, so this basically negates lazy loading for anyone using Spaces...? 🤔

**Comment by t3chguy** [comment]
No, its similar to when you click on a room it loads the members, now any spaces you are filtering to also have their lazy loaded members loaded, without this we have no way of knowing what members are in that space and thus which DMs to show you as being in that space. The traverse method by default only lands on spaces

**Comment by jryans** [comment]
Hmm okay, but is my understand correct that it runs even a space is just selected for filtering and you are not explicitly view the space details?

If yes to the above, what happens when the Home space is selected?

**Comment by t3chguy** [comment]
This runs for the space you select for filtering in the space panel yes, as without knowing members we have no way to build the lists of DMs in that space so the DMs list in the Room List for that Space would be partial, only showing the members the server picked for you


> If yes to the above, what happens when the Home space is selected?

https://github.com/matrix-org/matrix-react-sdk/pull/5882/files#diff-19f002b14c45418de617a433f9f64d8d3ab0fe8790896008081e35d4163ac30bR42 would be null so nothing

**Review by jryans — APPROVED** [review]
Thanks for walking me through the concepts, looks good to me!

**Pull request merged**
