### PR TITLE
WIP: Add Reply Button on Hover

### PR DESCRIPTION
**Pull request by martindale**
First time `matrix-react-sdk` contributor.  I thought the "reply" button would be better suited as a single-click interaction, as opposed to hidden behind a context menu.

Please advise as to improvements and integration!

### CODE REVIEW

**Comment by bwindels** [comment]
Hi @martindale, thank you for the PR and great to see a new contributor! I like the idea of having a dedicated reply button, and the code looks pretty good to me. I need to check how this could fit in the redesign we're planning though, and if our designer has any thoughts on it. @dbkr you have any thoughts on this?

**Comment by dbkr** [comment]
Main thing to bear in mind here is that design tweaks are generally the most contentious changes. It's always best to discuss potential changes first but for design tweaks, doubly so.

As some general technical feedback, watch what changes you're including in your PR: you have an unrelated commit in there from Matthew too. Also you would need to do the DCO signoff.

**Comment by bwindels** [comment]
Checked and the new design has a dedicated reply button like proposed here. So the design will change in the future, but the functionality remains.

**Comment by jryans** [comment]
Thanks for making this contribution a while back. Since the code base has changed since this was opened, it no longer applies cleanly, and I don't think there's a need to keep it open in this state, as we can always find the code here again if needed. If you are still interested in pursuing this feature, please discuss with us in #riot-dev:matrix.org to find a good approach forward.

**Pull request closed without merging**
