### PR TITLE
Don't redact state events for "Remove recent messages"

### PR DESCRIPTION
**Pull request by robintown**
Closes vector-im/element-web#17445.

### CODE REVIEW

**Comment by t3chguy** [comment]
I think it is intentional that membership events get redacted in case the user had an abuse displayname/avatar

**Comment by robintown** [comment]
:thinking: That makes sense… are membership events the only exception?

**Comment by robintown** [comment]
Okay, I think the solution then should be a checkbox to "keep state events from this user", and also avoid redacting m.room.encryption since that came up in the issue in particular

**Comment by turt2live** [comment]
Redacting the encryption event (and probably server ACLs) sound like a definite bug

**Pull request closed without merging**
