### PR TITLE
Initial go at making typing notifs appear in timeline

### PR DESCRIPTION
**Pull request by lukebarnard1**
This is as designed - instead of "A and B are typing..." this adds a ghost tile to the end of the timeline if people are typing. The next step will be making new messages animate as if they are coming from the ghost tile.

- [ ] Animation of ghost message tile to real message

Looks like this: 
2017-02-28-174848_493x141_scrot

### CODE REVIEW

**Comment by ara4n** [comment]
as per chat on #riot-dev, i think there's confusion here - the desired behaviour (as per iMessage etc) is that there is *no animation when transitioning from the typing notification to the final message*.

There is an (optional) transition when the message bubble is displayed - either as a typing notification or as a new message (if typing notifs are turned off); but the idea is that notifications just get replaced by the message contents without any motion.  Here's a video to show iMessage in action.

https://matrix.org/_matrix/media/v1/download/matrix.org/ZoXMwxeSowCsClLNnUsdtxgA

**Comment by lukebarnard1** [comment]
@ara4n it seems I've invented a third end to the stick and gone with it :) also, I can't see .mov files on dev box but I _could_ invest time into getting the right codecs..

**Comment by lukebarnard1** [comment]
So many conflicts ;_;

**Comment by lukebarnard1** [comment]
Closing this as I'm not working on it currently and it's not a priority and many conflicts.

**Pull request closed without merging**
