### PR TITLE
Hide algorithm from the message about turning on encryption

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/riot-web/issues/8829

Before:
Screen Shot 2020-01-07 at 11 34 40 AM

After:
Screen Shot 2020-01-07 at 11 34 54 AM

### CODE REVIEW

**Comment by nadonomy** [comment]
Also LGTM! :)

**Comment by ara4n** [comment]
might be worth keeping the info around somewhere though (perhaps hidden behind a <details/>)?
what happens if someone sends an m.room.encryption with an unrecognised algorithm? we don't want to claim the room is encrypted if the client then can't actually encrypt for that algorithm.

**Comment by uhoreg** [comment]
I think the information should still be available in the "View Source" for the event, for those who care about it?

**Comment by aaronraimist** [comment]
Would need https://github.com/matrix-org/matrix-doc/pull/2184

**Comment by nadonomy** [comment]
> I think the information should still be available in the "View Source" for the event, for those who care about it?

This seems reasonable. Is it tractable for us to also display the encryption algorithm being used in Room Settings?

**Comment by turt2live** [comment]
(shouldn't need spec support - we can render whatever we want)

**Comment by aaronraimist** [comment]
> what happens if someone sends an m.room.encryption with an unrecognised algorithm? we don't want to claim the room is encrypted if the client then can't actually encrypt for that algorithm.

This would be something for another issue. This problem already exists.
Screen Shot 2020-01-07 at 11 57 11 AM

**Comment by uhoreg** [comment]
I think that for the average end-user, just removing the algorithm is no worse than what we have security-wise, since they don't know what algorithm is right.  We should probably have another issue for displaying an error message for when the algorithm is something we don't understand.  The room decoration should probably also be something that reflects that we don't understand the encryption algorithm (maybe the same decoration as an unencrypted room?).

**Comment by turt2live** [comment]
This is blocked on design/product oversight to settle the `<details>` or no `<details>` argument.

**Comment by jryans** [comment]
> This is blocked on design/product oversight to settle the `<details>` or no `<details>` argument.

I've requested @nadonomy's review in hopes of getting a decision on this.

**Comment by jryans** [comment]
While chatting more with @ara4n, he would like to have some kind of handling of unknown algorithms at the same time as the propose hiding here. I think he came up with a decent approach:

* When the algorithm is the one we expect (`m.megolm.v1.aes-sha2`), hide the algorithm as in this existing PR: %(senderName)s turned on end-to-end encryption.
* For anything else, show the algorithm as unrecognised: %(senderName)s turned on end-to-end encryption (unrecognised algorithm %(algorithm)s).

@aaronraimist, could you update the PR to that, if it seems reasonable to you as well?

**Comment by jryans** [comment]
@aaronraimist, thanks again for working on this! We've decided we want to have this resolved for FOSDEM, so I've opened https://github.com/matrix-org/matrix-react-sdk/pull/3936 with the approach mentioned above. Sorry for the delay in reaching as decision here.

**Pull request closed without merging**
