### PR TITLE
Enable Login Customization | Automatic access_token GUI Login

### PR DESCRIPTION
**Pull request by palmtown**
Add the ability to specify login type via SdkConfig.  Will allow users to enable/disable login types based on there preferences.

### CODE REVIEW

**Comment by turt2live** [comment]
@palmtown thanks for the contribution! I'm a little confused as to what the use case for this is - what sort of problem are you looking to solve?

Please also take some time to read the [CONTRIBUTING.rst](https://github.com/matrix-org/matrix-react-sdk/blob/master/CONTRIBUTING.rst) and [code_style.md](https://github.com/matrix-org/matrix-react-sdk/blob/master/code_style.md)

**Comment by palmtown** [comment]
Hello Travis,

Thanks for your reply.  In short, the use case is to allow developers to efficiently standardize the login method based on industry standards via a configuration options rather than modifying the code which require more time and experience. 

In short, in my case, as in just about all well known collaboration environments, users login with email and password.  It is very unlikely that they will use an ID (e.g. matrix id), or even their cell phone.  Therefore, a developer can quickly simplify the login process and deploy an industry standard solution by only enabling email login, as in my case.

When a user sees multiple login methods, it can be overwhelming to the novice tech.

**Comment by palmtown** [comment]
Hey Travis,

I made a modification based on https://github.com/matrix-org/matrix-react-sdk/blob/master/code_style.md to use single quotes, however, also, implemented the ability to automatically login to Riot Web by passing an access_token.  Currently code only seems seems to accept loginToken in this.props.realQueryParams.

**Comment by palmtown** [comment]
Will use in my project, may not be useful to others.

**Pull request closed without merging**
