### PR TITLE
Revert "Fix regression around FacePile with overflow (#11527)"

### PR DESCRIPTION
**Pull request by germain-gg**
This reverts commit 93ccccc03d3911c525d31f8e5bb8ad3d483b2b55 for https://github.com/vector-im/compound/issues/215

Blocked on https://github.com/vector-im/compound-web/pull/82 being merged and subsequently the Compound package updated.

Fixes https://github.com/vector-im/element-web/issues/26209 because Compound has been updated

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Revert "Fix regression around FacePile with overflow (#11527)" ([\#11634](https://github.com/matrix-org/matrix-react-sdk/pull/11634)). Fixes vector-im/element-web#26209.

### CODE REVIEW

**Review by t3chguy — COMMENTED** [review]
The changes look sane but the sheer quantity of snapshot updates does not, what's the story there. Why are all the compound avatar classes changing? Can we have some stability either upstream or via forcing them to something less random in the snapshots?

**Comment by germain-gg** [comment]
That is the intetion, i created https://github.com/matrix-org/matrix-react-sdk/pull/11634

**Review by t3chguy — CHANGES_REQUESTED** [review]
Actually sorry, playing with it, it overlaps with the button

image

**Review by t3chguy — APPROVED** [review]

**Comment by andybalaam** [comment]
Force merging to facilitate release, and because CI is still flaky

**Pull request merged**
