### PR TITLE
Moved read receipts to the bottom of the EventTile.

### PR DESCRIPTION
**Pull request by krkc**
Fixes vector-im/riot-web#4377

I've moved the message read receipts to the bottom of the EventTile.

Signed-off-by: Christopher Kurek kurekc@hotmail.com

### CODE REVIEW

**Comment by t3chguy** [comment]
Needs sign off from design :)

Attaching screenshots to the PR would be great

+1000

**Comment by krkc** [comment]
Screenshot_2020-01-21_18-26-52
Screenshot_2020-01-21_18-27-03

**Comment by bwindels** [comment]
Haven't run lint or tests on this but as the changes are mostly css, it seems fine to just merge.

**Comment by bwindels** [comment]
Running https://buildkite.com/matrix-dot-org/riot-web/builds/2180 before merging

**Comment by bwindels** [comment]
Tests are failing because your branch is behind develop. Could you rebase please @krkc ?

**Pull request merged**
