### PR TITLE
Add a confirmation modal before account deactivation

### PR DESCRIPTION
**Pull request by jaiwanth-v**
Closes vector-im/element-web#17422

image

Signed-off-by: Jaiwanth jaiwanth2011@gmail.com

### CODE REVIEW

**Comment by t3chguy** [comment]
So the difficulty here is that there is already a modal, but we need to ask the server whether it accepts password or SSO for confirmation and the only way to do that is to hit the /deactivate endpoint, which sometimes the server will just do implicitly if you performed UIA/logged in recently.

image

So with this change, you may end up with two warnings. The one added here and then also the one in my screenshot, depending on the state of the server.

**Comment by jaiwanth-v** [comment]
> So the difficulty here is that there is already a modal

Yes, I knew about this. I tested this with one of my test accounts, the modal disappeared immediately and it was deactivated in no time with the settings panel still being active.
> So with this change, you may end up with two warnings. The one added here and then also the one in my screenshot, depending on the state of the server.

Yeah, I think it would be better if we have two warnings as this is related to account deletion.

**Comment by aaronraimist** [comment]
Regardless of whether there should be one warning or two warnings, it should be consistent. There should always be the same number of warnings. Some users should not get one warning while others get two.

**Comment by jaiwanth-v** [comment]
I agree, but as mentioned in the issue, this is just a temporary workaround to prevent accidental deletions. We would probably remove this warning in the future.

**Comment by MadLittleMods** [comment]
Is this still relevant now that https://github.com/matrix-org/synapse/pull/10184 is merged which will not skip UI auth for account deletion? The other modal will now show always AFAICT.

**Comment by jaiwanth-v** [comment]
No, it isn't. Closing this.

**Pull request closed without merging**
