### PR TITLE
Align buttons in encrypted event dialog

### PR DESCRIPTION
**Pull request by jryans**
Fixes vector-im/riot-web#7642.

Signed-off-by: J. Ryan Stinnett <jryans@gmail.com>

### CODE REVIEW

**Comment by jryans** [comment]
Example dialogs with changes applied:

enc-event-info

unknown-devices

**Comment by turt2live** [comment]
(test failures unrelated)

**Comment by aaronraimist** [comment]
This is much better, and it appears to be fixed in Chrome, but is still slightly off in Safari
screen shot 2018-11-08 at 11 50 43 am

**Comment by turt2live** [comment]
I vote zooming out in Safari and taking away that guide :p

**Comment by jryans** [comment]
> still slightly off in Safari

Thanks for pointing that out! I'll see what I can do to keep all the browsers happy. 😁

**Comment by jryans** [comment]
#2274 should take care of Safari as well.

**Pull request merged**
