### PR TITLE
Make buttons in verify dialog respect the system font 

### PR DESCRIPTION
**Pull request by tawfiek**
Fixes vector-im/element-web#16038

### CODE REVIEW

**Comment by tawfiek** [comment]
Screenshot from 2021-03-21 14-13-02

**Review by turt2live — APPROVED** [review]
Thanks!

**Comment by turt2live** [comment]
argh, @tawfiek when you get the chance please sign off on these changes. Easiest way is to leave a comment like this:

```
Signed-off-by: Your Name <email@example.org>
```

Thanks.

**Comment by tawfiek** [comment]
```
Signed-off-by: tawfiek tawfiek.108@gmail.com
```

**Pull request merged**
