### PR TITLE
Remove :not() pseudo class from mx_EventTile_line:hover of ThreadsList

### PR DESCRIPTION
**Pull request by luixxiul**
This PR removes `:not()` pseudo class from `mx_EventTile_line:hover` of `ThreadsList`. The event tiles on `ThreadsList` has group layout only, therefore it is not necessary to consider IRC / bubble layouts inside the list.

|Before|After|
|---------|------|
|before|after|
|(unchanged)|after|

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: task

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
it can have `data-layout=bubble` when message bubbles are enabled. These rules appear to be actually doing something, I think.

**Comment by luixxiul** [comment]
On `mx_ThreadsList`, only `data-layout=group` is enabled. `data-layout=irc` nor `data-layout=bubble` can be enabled inside a thread, but not on the threads list, which is why the thread tiles on the threads list is not displayed in IRC or message bubble layout.

after

**Review by turt2live — APPROVED** [review]
Going to wait until after the RC is cut on this one out of paranoia

**Comment by turt2live** [comment]
@luixxiul can you merge develop back into this PR or enable the ability for maintainers to make edits please?

**Pull request merged**
