### PR TITLE
Remove seams from pin icon

### PR DESCRIPTION
**Pull request by robintown**
Before:

Screenshot 2021-08-04 at 18-43-56 Element #element-dev matrix org

After:

Screenshot 2021-08-04 at 18-56-34 Element totd

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Thank you 💯

**Comment by t3chguy** [comment]
This should really be done in the source of truth (Figma)

@matrix-org/design can we import this svg in Figma to fix the seams?

**Comment by nadonomy** [comment]
Just checked and the seams aren't visible in the design system upstream. We actually have a few variants of the pin icons, we can export from the source of truth/clean this up appropriately when we look closer at pinning bring it out of labs.

**Comment by t3chguy** [comment]
Last time I checked (iirc with Nique) we couldn't spot the seams in Figma either, but once exported they were visible

**Comment by niquewoodhouse** [comment]
This has bugged me for so long!


>  we can export from the source of truth/clean this up appropriately when we look closer at pinning bring it out of labs.

I'm not 100% sure but I think this is used also in widgets in the room details view, where you can pin widgets too.

**Comment by nadonomy** [comment]
> I'm not 100% sure but I think this is used also in widgets in the room details view, where you can pin widgets too.

Yeah; that's the portrait orientation of it. Haven't inspected to see if it's the same core nodes (but, I guess it would be!)

@t3chguy @niquewoodhouse when you were debugging before did you try running the fresh output through SVGO? [SVGOMG](https://jakearchibald.github.io/svgomg/) lets you try easily. I've found it usually fixes a lot of these kind of issues.

If it helps, we could consider either using a [Figma plugin](https://www.figma.com/community/plugin/782713260363070260/Advanced-SVG-Export) to add it to our workflow or looking into ways to run SVGO when compiling?

**Comment by niquewoodhouse** [comment]
> @t3chguy @niquewoodhouse when you were debugging before did you try running the fresh output through SVGO? SVGOMG lets you try easily. I've found it usually fixes a lot of these kind of issues.

I didn't do anything, just avoided touching the icon completely as I wasn't sure if when this was made such a thing was intended. We were just looking at pinning in labs.

Maybe I'm being a bit old school but I think just more QA of the shapes in Figma should be enough?  For example, those seams exist in the icon

image

But not in other pin icons

image

**Comment by nadonomy** [comment]
> Maybe I'm being a bit old school but I think just more QA of the shapes in Figma should be enough? For example, those seams exist in the icon

No you're right. No idea why the nodes are so messy. Guessing a poor export from when they were originally authored in illustrator.

**Comment by janogarcia** [comment]
> No you're right. No idea why the nodes are so messy. Guessing a poor export from when they were originally authored in illustrator.

It's probably related to how overlapping shapes in Illustrator where translated to Figma's own [vector networks](https://help.figma.com/hc/en-us/articles/360040450213-Vector-Networks).

**Comment by janogarcia** [comment]
It's a bit tricky to fix in Figma, but it was easy to get rid of the seam in a non vector network-based editor, where you get separate shapes instead of a mesh. I'm updating it in Compound.

**Comment by janogarcia** [comment]
Done. 👍

Compound – Figma

**Pull request merged**
