### PR TITLE
Remove Gemini Scrollbars

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/10474

TODO (are proving to be a PITA):
- [x] TagPanel
- [x] GroupView

Needs loads of testing on various browsers, tested on Chrome and Firefox on Windows 10.

### CODE REVIEW

**Comment by jryans** [comment]
@dbkr Did you test in other browsers? 

If more testing is still needed, an ad-hoc build would be nice to have.

**Comment by t3chguy** [comment]
Adhoc build up at: http://riots.im/adhoc/gemini1/

**Comment by dbkr** [comment]
Only bug I found was that the scrollbars appearing on hover causes the width of the room tile to change:

scrollbars

**Comment by t3chguy** [comment]
The above mentioned bug already exists as the Room Lists were already gemini-free

**Pull request merged**
