### PR TITLE
Implement MSC4039: Add an MSC for a new Widget API action to upload files into the media repository

### PR DESCRIPTION
**Pull request by dhenneke**
https://github.com/matrix-org/matrix-spec-proposals/pull/4039

Depends on:

* https://github.com/matrix-org/matrix-widget-api/pull/86

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Type: enhancement

---
Here's what your changelog entry will look like:

## ✨ Features
 * Implement MSC4039: Add an MSC for a new Widget API action to upload files into the media repository ([\#11311](https://github.com/matrix-org/matrix-react-sdk/pull/11311)). Contributed by @dhenneke.

### CODE REVIEW

**Review by t3chguy — COMMENTED** [review]
Given this is an MSC implementation it'll likely want to go behind labs. As per the comments in the widget API, it can be removed at any point.

**Comment by Johennes** [comment]
I've updated the time sheeting label on this pull request. Reviewers, please take this into account when filling your sheets.

**Comment by dhenneke** [comment]
We would be happy to receive some feedback and/or reviews 🙂.

**Review by t3chguy — APPROVED** [review]
Looks sane

**Pull request merged**
