### PR TITLE
Support star, fix riot-web issue #2938

### PR DESCRIPTION
**Pull request by gotmyname2018**
This is part of work to fix [riot-web issue 2938](https://github.com/vector-im/riot-web/issues/2938).
The basic idea is reuse the search function, but enhance it with search expression support.
The synapse side work [Support search expression](https://github.com/matrix-org/synapse/pull/2826) explains the search expression syntax.
A "Search starred" button was added to room header, once clicked, all starred messages will show as search results.
A "Cancel" button will be shown at AuxPanel to be used to close the search result panel.

### CODE REVIEW

**Comment by t3chguy** [comment]
This would surely require a spec proposal as synapse is not the only homeserver

**Comment by gotmyname2018** [comment]
Whether raise a issue (improvement type) in matrix-doc, and a pull request with a updated matrix-doc/specification/modules/search.rst is enough?

**Comment by t3chguy** [comment]
I'd suggest first getting feedback on this approach, as in whether using /search for this is wanted by the wider community/core devs. Knowing your reasoning for this approach could shed some light on it

**Comment by gotmyname2018** [comment]
Ya, so let me explains my reasoning :)
I first considered using specific api end point to fetch all starred messages, but after carefully study the current implementation (both riot-web, matrix-react-sdk and synapse), I find reuse /search gives many advantages:
  - You can combine plain key word and :starred to precisely look for specific starred messages, and in the future with even more search criteria.
  - The current rich functions of search result panel (such as pagination) could be bring to starred list with minimal cost
  - And this approach could be easily extended for future features (other tags: for e.g. a read it latter list)
  - And finally, it's a backward compatible change, the original searching semantic does not break.

**Comment by jryans** [comment]
Thanks for making this contribution a while back. Since the code base has changed since this was opened, it no longer applies cleanly, and I don't think there's a need to keep it open in this state, as we can always find the code here again if needed. If you are still interested in pursuing this feature, please discuss with us in #riot-dev:matrix.org to find a good approach forward.

**Pull request closed without merging**
