### PR TITLE
Prevent peeking members from reacting

### PR DESCRIPTION
**Pull request by jaiwanth-v**
Fixes vector-im/element-web/issues/16439
ezgif com-gif-maker (12)

Signed-off-by: Jaiwanth <jaiwanth2011@gmail.com>

### CODE REVIEW

**Comment by SimonBrandner** [comment]
Maybe add a dialog or something to explain why the user can't react

**Comment by aaronraimist** [comment]
Or change the cursor when it is disabled so it doesn't look like it is clickable

**Comment by SimonBrandner** [comment]
> Or change the cursor when it is disabled so it doesn't look like it is clickable

Sounds much better and easier to implement :+1:

**Comment by jaiwanth-v** [comment]
Sure. I'll modify the styles.

**Review by gsouquet — APPROVED** [review]
Thank you for your contribution!
That looks pretty reasonable to me 👍

**Pull request merged**
