### PR TITLE
chore: Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by nathannaveen**
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
lgtm assuming CI passes - thanks!

**Comment by turt2live** [comment]
looks like something is preventing static analysis from working?

**Comment by nathannaveen** [comment]
> looks like something is preventing static analysis from working?

I don't have time for now, would you be able to cherry pick? Thanks

**Comment by turt2live** [comment]
cherry pick which? There's only one commit here?

**Comment by nathannaveen** [comment]
> cherry pick which? There's only one commit here?

Pick this commit into another PR.

**Comment by turt2live** [comment]
I don't personally have the time available to investigate either, so if you're also unable to maintain it then we'll just close it for now. 

I've opened an issue for someone to pick up if they happen to have time: https://github.com/vector-im/element-web/issues/22729

**Pull request closed without merging**
