### PR TITLE
Improve consistency among effects

### PR DESCRIPTION
**Pull request by ColonisationCaptain**
This changes the message type of a message sent "with snow" to be of the form `nic.custom.XXX` which is used by the other effects. Instances of "snowfall" are replaced with "snow" in the English translation, as on Android (this noun is more appropriate in this case, given the other effects are "with confetti" and "with fireworks"). Wasn't sure whether to replace these two strings everywhere, or just to change the English translation, so I did the latter.

### CODE REVIEW

**Comment by ColonisationCaptain** [comment]
hmm, perhaps it is necessary to rename all instances of these strings

**Comment by turt2live** [comment]
@ColonisationCaptain this change will need sign off before we can review it properly.

Also, this is a bit of a question for the namespace: the snowfall effect was added under the Element namespace deliberately. Changing that would need either a spec change or a theoretical transfer of authority to the `nic.custom` namespace.

As for the failing checks, run `yarn i18n` to make it happy.

**Comment by ColonisationCaptain** [comment]
Running `yarn i18n` reverts the strings back to "snowfall" instead of "snow".

> Also, this is a bit of a question for the namespace

To me it seems necessary to change this namespace, as there is no reason for this effect to be an outlier from the others. Besides, using the same message type for the same effect allows it to be triggered cross-platform.

**Comment by ColonisationCaptain** [comment]
Signed-off-by: Arseny Uskov <arsenyuskov@gmail.com>

**Comment by turt2live** [comment]
Android's implementation would be considered the bug here: the message types are allowed to vary, even if a bit ugly.

**Comment by ColonisationCaptain** [comment]
Why would different chat effects be allowed to have different message types? Is this just due to the fact that the snowfall effect was initially introduced under the element namespace?

> Android's implementation would be considered the bug here

Would you suggest changing the namespace [here](https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/model/message/MessageType.kt) then?

**Comment by turt2live** [comment]
indeed - the snowfall effect was implement by Element whereas the other two were not, originally. 

I'm not familiar enough with the android repo to really comment on where the change needs to be, but it would be somewhere in the android app.

**Comment by ColonisationCaptain** [comment]
Hmm, this may be a naive take but it seems to me that the Android effect was implemented first, on the [15th of December](https://github.com/vector-im/element-android/pull/2535), whereas snow was added to Element on the [21st](https://github.com/matrix-org/matrix-react-sdk/pull/5511).

**Comment by turt2live** [comment]
There's a whole lot of undisclosed history for this. I'll talk to the android team.

**Comment by turt2live** [comment]
alright, I've mentioned it to them and they seem to have a plan to fill in the gap - thanks for raising this in any case!

**Comment by ColonisationCaptain** [comment]
Thank you! I'd also appreciate the text strings being made consistent across both platforms!

**Pull request closed without merging**
