### PR TITLE
Maintain file order when uploading files.

### PR DESCRIPTION
**Pull request by turt2live**
This may address vector-im/riot-web#1459

Upload order is acheived by using a collection of promises that are used to block the promise chain. The chain is only blocked until the upload immediately prior to the desired upload has been completed. Blocking the promise chain is to still permit concurrent uploads, otherwise the sending of files would have been blocked instead.

Signed-off-by: Travis Ralston <travpc@gmail.com>

### CODE REVIEW

**Comment by ara4n** [comment]
@dbkr - can you take a look at this one please?

**Comment by dbkr** [comment]
Hmm - I think the issue you linked is just talking about the order the files are displayed in the confirmation dialog, which this doesn't address. I'm not certain it is desirable to block all file uploads behind one that was started before: eg. if you upload a large video file, then a small image, is it more important to preserve ordering or deliver messages as soon as possible? If so, why block content messages but not regular textual messages? (this code would also prevent you from uploading anything else in any room since it's not per room).

**Comment by turt2live** [comment]
@dbkr as far as I can tell, the order of the dialog is correct, although the files were not uploaded in that order. Do you (or anyone else) happen to have more information on the issue?

**Comment by turt2live** [comment]
Closing - this doesn't actually solve any problem it tries to.

**Pull request closed without merging**
