### PR TITLE
Fix space lock icon size

### PR DESCRIPTION
**Pull request by weeman1337**
closes https://github.com/vector-im/element-web/issues/24128

Fixes icon size + icons are now vertically centered

image

Also fixed aspect ratio of

image

PSF-1827

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix space lock icon size ([\#9854](https://github.com/matrix-org/matrix-react-sdk/pull/9854)). Fixes vector-im/element-web#24128.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Code looks good to me 👍

**Comment by weeman1337** [comment]
> Any chance of percy snapshots to prevent this regressing again in the future?

Added

**Comment by t3chguy** [comment]
The way the snapshot is targeted isn't ideal for review:

image

**Comment by weeman1337** [comment]
> The way the snapshot is targeted isn't ideal for review, and this is the wrong screen entirely, it doesn't include the padlock icon
> 
> image

Already fixed :wink:

**Comment by weeman1337** [comment]
Any idea why the snapshot looks unstyled @t3chguy ?

image

**Comment by t3chguy** [comment]
@weeman1337 presumably because the CSS styles include some parent selector which isn't in the DOM snapshot you're targeting. You might need to snapshot a parent element, or snapshot everything and use percyCSS to exclude things

**Comment by weeman1337** [comment]
Got it

image

**Pull request merged**
