### PR TITLE
Iterate space panel toggle collapse interaction

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/20079

image
image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Iterate space panel toggle collapse interaction ([\#7335](https://github.com/matrix-org/matrix-react-sdk/pull/7335)). Fixes vector-im/element-web#20079.

Preview: https://61b7426d8d16ffdc1ea990ef--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
Thanks for iterating the design so quickly. Just some minor amends.

- [ ] .mx_SpacePanel .mx_SpacePanel_toggleCollapse:not(.expanded) +  .mx_SpacePanel .mx_SpacePanel_toggleCollapse
   - [ ] height and width: 18px
   - [ ] right: -8px

- [ ] icon
   - [ ] mask size: 18px

**Review by niquewoodhouse — APPROVED** [review]
Could th

**Comment by yozhic** [comment]
Sorry, the Expand/Collapse button doesn't appear on MacOS Mojave 10.14.6 (Element 1.9.8).
button-issue-true

**Comment by t3chguy** [comment]
@yozhic https://github.com/vector-im/element-web/issues/20279

**Pull request merged**
