### PR TITLE
Live location sharing - fix square border for image-less avatar (PSF-1052)

### PR DESCRIPTION
**Pull request by kerryarchibald**
Before:
Screenshot 2022-05-24 at 16 19 53

After:
Screenshot 2022-05-24 at 16 17 55

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Live location sharing - fix square border for image-less avatar (PSF-1052) ([\#8679](https://github.com/matrix-org/matrix-react-sdk/pull/8679)). Contributed by @kerryarchibald.

### CODE REVIEW

**Comment by t3chguy** [comment]
Can we please keep the allchange automated changelog in mind when writing issue titles, `LLS` may not be clear to users reading the changelog, nor is PSF-1052

**Review by t3chguy — APPROVED** [review]
LGTM other than the title comment

**Comment by kerryarchibald** [comment]
> Can we please keep the allchange automated changelog in mind when writing issue titles, `LLS` may not be clear to users reading the changelog, nor is PSF-1052

Fair enough for LLS, fixed that. The ticket number is to help us with reporting in PS

**Comment by t3chguy** [comment]
In that case please use `Notes: <text>` in the description to override the Allchange changelog entry.

**Pull request merged**
