### PR TITLE
MELS: either expanded or summary, not both

### PR DESCRIPTION
**Pull request by lukebarnard1**
Fixes vector-im/riot-web#3097

### CODE REVIEW

**Comment by lukebarnard1** [comment]
With the referenced SCSS, this looks like:
2017-02-09-151218_569x35_scrot
when collapsed and
2017-02-09-151213_574x128_scrot
when expanded.

**Comment by ara4n** [comment]
so, the point of #3097 was both to avoid showing the duplicate MEL info between the summary & the expanded form... and to avoid wasting vertical space.  Would it be possible to keep it simpler and just put the 'collapse' link at the end of the first line when expanded (e.g. `@135542:matrix.org joined the room` in your screenshot example)?

**Comment by ara4n** [comment]
(aesthetically i quite like your proposal, but it does waste vertical space, and i'm not sure we need yet another visual idiom involved - especially as the HR looks a bit like a section break or similar)

**Comment by lukebarnard1** [comment]
>Would it be possible to keep it simpler and just put the 'collapse' link at the end of the first line when expanded

This would be obscured by read receipts, hence it being above instead.

**Pull request merged**
