### PR TITLE
Don't show the prompt to enable desktop notifications immediately after registration

### PR DESCRIPTION
**Pull request by hughns**
I noticed that the `DesktopNotificationsToast` was showing up immediately after user registration even though it attempts to wait until 24 hours at https://github.com/matrix-org/matrix-react-sdk/blob/61076c333177390b67e3f6f48d0f7868c067d461/src/components/structures/MatrixChat.tsx#L1409-L1411

On investigating I found two issues:

1. `mx_registration_time` would never be present in `LocalStorage` at the time being checked. I believe this is because LocalStorage is being cleared during one of the calls to `Lifecycle.doSetLoggedIn()`.
2. `userRegisteredWithinLastHours()` would always return `false` because the string value for `mx_registration_time` from `LocalStorage` was not being parsed properly (at least in Chrome): `new Date("" + Date.now()) === Invalid Date`

To address I have moved the tracking out of `LocalStorage` and doing it purely in memory (like how `currentUserIsJustRegistered()` is implemented).

I've also added some test cases to help maintain this in future.

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Don't show the prompt to enable desktop notifications immediately after registration ([\#8274](https://github.com/matrix-org/matrix-react-sdk/pull/8274)). Contributed by @hughns.

Preview: https://pr8274--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by hughns** [comment]
For the record, this is what you currently see after registering a new user on app.element.io before you have done anything else:

image

**Comment by t3chguy** [comment]
> To address I have moved the tracking out of LocalStorage and doing it purely in memory (like how currentUserIsJustRegistered() is implemented).

This changes the behaviour, as now if the user refreshes at any point within 24 hours they'll be shown the prompt

**Review by t3chguy — COMMENTED** [review]
See above

**Comment by hughns** [comment]
It looks I accidentally inverted some of the logic. I've reverted to localStorage based and taken steps to preserve the state during `setLoggedIn()`

**Review by t3chguy — APPROVED** [review]
Awesome, thanks! :shipit:

**Pull request merged**
