### PR TITLE
make MemberTiles actually update in realtime

### PR DESCRIPTION
**Pull request by ara4n**
Fixes https://github.com/vector-im/vector-web/issues/730 and all its dups

### CODE REVIEW

**Comment by ara4n** [comment]
i am very unsure on how this was ever meant to work, as MemberTile's render() method resets the timers which mean that shouldComponentUpdate() never fires on the EntityTile...

**Comment by richvdh** [comment]
Has this got a spurious change which is nothing to do with the PR?

**Comment by ara4n** [comment]
yes. ignore the spurious change.

**Comment by Kegsay** [comment]
LGTM

**Pull request merged**
