### PR TITLE
Change room list sorting to activity and unread first by default

### PR DESCRIPTION
**Pull request by gsouquet**
Fixes https://github.com/vector-im/element-web/issues/24014

Related to the Get Your Update cycle in Delight.
Activity based sorting is the norm in chat application. If folks feel strongly they can still choose alphabetical, but activity should be the default.

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Change room list sorting to activity and unread first by default ([\#9773](https://github.com/matrix-org/matrix-react-sdk/pull/9773)). Fixes vector-im/element-web#24014.

### CODE REVIEW

**Review by weeman1337 — APPROVED** [review]
Looks good. Tested on the deployment :+1: 

Also I personally welcome this change :partying_face:

**Comment by turt2live** [comment]
Has product signed off on these changes? There was a ton of research that went into choosing alphabetical before :(

**Review by turt2live — APPROVED** [review]
lgtm from a technical perspective.

**Comment by gsouquet** [comment]
> There was a ton of research that went into choosing alphabetical before :(

@turt2live links to previous research/rationale would be greatly welcome! Activity based sorting is the norm today in most chat applications

This has product sign-off and is awaiting a green tick before a merge

**Comment by daniellekirkwood** [comment]
I'm unsure about forcing unreads to the top of the list on behalf of our users - this may be confusing if the last unread is a few days back but there's been other activity in other rooms... However, we need to rethink how unreads work on Web given the new updates to the mobile app (and bring the 2 platforms to alignment with each other) so we will have the opportunity to revisit this in the future... It's also a toggle that users can shut off if they don't want it this way.

Happy to add a tick - will do now

**Review by daniellekirkwood — APPROVED** [review]

**Pull request merged**
