### PR TITLE
Make invitation dialog scrollable when infos are too long

### PR DESCRIPTION
**Pull request by nurjinjafar**
when the room name is too long or there is a meeting series, with all the information provided in the invitation dialog. the dialog gets too big and not functionable, since the actions buttons are hidden. 
therefore we added more styling to the invitation dialog so it would be scrollable.

screenshots:
before:
Screenshot 2023-10-16 at 12 46 07

after:
Screenshot 2023-10-16 at 12 47 21

Screenshot 2023-10-16 at 12 47 39

note: this should not change the behaviour of how a normal envitation will look like this even after the changes:
Screenshot 2023-10-16 at 13 29 40

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Make invitation dialog scrollable when infos are too long ([\#11753](https://github.com/matrix-org/matrix-react-sdk/pull/11753)). Contributed by @nurjinjafar.

### CODE REVIEW

**Comment by t3chguy** [comment]
Blocking this on design, I believe we should be truncating to 2 lines like we do in other places (e.g. right panel)

**Comment by nurjinjafar** [comment]
hi @t3chguy, are there any updates regarding this PR? should i truncate the title as it is done in the right panel? or are we waiting on a review / desicion from "a team"?

**Comment by t3chguy** [comment]
> or are we waiting on a review / desicion from "a team"?

Indeed that, its pending design review

**Comment by americanrefugee** [comment]
I agree with @t3chguy : Truncate to 2 lines with "..." at the end of the last visible word

**Comment by t3chguy** [comment]
Thanks @americanrefugee

**Comment by nurjinjafar** [comment]
@t3chguy, i felt free to do the same with the InviteDialog component. because that as well was not usable.
 however, i kept the dialog scrollable for such cases (see screenshots please!)
Screenshot 2023-10-17 at 10 27 44
/github.com/matrix-org/matrix-react-sdk/assets/34133773/6e225b91-f29b-4a7b-9d72-5672aea63c27)

**Pull request merged**
