### PR TITLE
Let Element Call widget receive m.room.create

### PR DESCRIPTION
**Pull request by AndrewFerr**
This allows the widget to check the room version without prompting the user to grant that capability, so the widget can know about version-specific auth rules (namely MSC3779).

Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>

## Checklist

-   [x] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [x] Linter and other CI checks pass.
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Comment by AndrewFerr** [comment]
Related change: https://github.com/element-hq/element-call/pull/2457
This lets Element Call widgets actually request this capability.

**Review by toger5 — APPROVED** [review]
Thank you.

**Comment by dbkr** [comment]
The change itself looks fine but I'm not sure I understand why the other changes to the test?

**Comment by AndrewFerr** [comment]
> why the other changes to the test?

The "fail fast" changes are just to make the test's failure condition be an `expect` failure instead of a timeout (due to waiting for a "grant permission" modal dialog to be interacted with).

With that said, it's not strictly related to this PR, so I'll split it out of here.

**Review by dbkr — APPROVED** [review]

**Comment by dbkr** [comment]
Okay, thanks - that seems fine then!

**Pull request merged**
