### PR TITLE
Improve Voice Broadcast header layout

### PR DESCRIPTION
**Pull request by weeman1337**
Part of https://github.com/vector-im/element-web/issues/23282

- Fix Live badge position
- Prevent room name / broadcaster name overflow

**Before**

image

**After**

image

## Checklist

* [x] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by robintown — APPROVED** [review]

**Review by kerryarchibald — COMMENTED** [review]
Screenshot 2022-10-17 at 16 34 12

The tile overflows with a long room name

**Comment by kerryarchibald** [comment]
> The tile overflows with a long room name

This is not caused by this PR, so not blocking.

**Comment by weeman1337** [comment]
> Screenshot 2022-10-17 at 16 34 12
> 
> The tile overflows with a long room name

Thanks for finding this. Will include a fix for that…

**Review by kerryarchibald — APPROVED** [review]
Screenshot 2022-10-17 at 16 57 33

**Comment by t3chguy** [comment]
Force merging due to wedged test

**Pull request merged**
