### PR TITLE
Support dynamic room predecessors in OwnBeaconStore

### PR DESCRIPTION
**Pull request by andybalaam**
Part of https://github.com/vector-im/element-web/issues/24417.

Towards [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946)

---
Here's what your changelog entry will look like:

## ✨ Features
 * Support dynamic room predecessors in OwnBeaconStore ([\#10339](https://github.com/matrix-org/matrix-react-sdk/pull/10339)). Contributed by @andybalaam.

### CODE REVIEW

**Comment by andybalaam** [comment]
I've tested this by sharing my live location and then toggling the MSC3946 feature flag on and off, and verified that I am still able to stop sharing via the banner at the top of the screen.

@kerryarchibald I don't have much clue how `OwnBeaconStore` is supposed to work so would appreciate your eyes on this if you get a chance - thanks!

**Review by kerryarchibald — APPROVED** [review]
Code looks good, one small comment about public/private.

You're halfway done now, but might it have been better to create a utility function that wraps `getVisibleRooms` with the setting? Seems quite easy for future new uses of `getVisibleRooms` to forget to account for the setting.

**Comment by andybalaam** [comment]
> Code looks good, one small comment about public/private.

I don't see a comment?

> You're halfway done now, but might it have been better to create a utility function that wraps `getVisibleRooms` with the setting? Seems quite easy for future new uses of `getVisibleRooms` to forget to account for the setting.

Good Idea. I might do this as a separate change.

**Comment by andybalaam** [comment]
On second thoughts, I think a utility wouldn't add much. Quite a few places in the code don't actually check the setting at the time they make the call, and anyone copy-pasting this code will find the pattern already. Since we can't put the utility in js-sdk (because it doesn't know about settings) I don't think it would add much...

**Pull request merged**
