### PR TITLE
Update stripped emoji and bump emojidata to 4.0.2

### PR DESCRIPTION
**Pull request by TheTimeWalker**
Since emojione has been updated in the mean time, the script to fetch and strip the new data has been rerun to correct a few shortcode regressions, notably `:blush:`.

This also bumps up the emojidata dependency to 4.0.2 which was a minor fix.

### CODE REVIEW

**Comment by t3chguy** [comment]
stripped-emoji.json is a generated file from emoji data-base, it needs to be fixed upstream

**Comment by t3chguy** [comment]
Hah I totally forgot I made that change to emojibase upstream 🤦‍♂ 

If you're bumping package.json then would be great to bump yarn.lock also: https://github.com/matrix-org/matrix-react-sdk/blob/dc75290ffa7dfdddd036b06f93de4ab333d9169e/yarn.lock#L2711

just so it makes sense

**Comment by jryans** [comment]
@TheTimeWalker Running `yarn install` should update the lock file like @t3chguy suggests.

**Comment by TheTimeWalker** [comment]
I have amended the commit to include the yarn.lock bump

**Comment by t3chguy** [comment]
This looks great, thanks :D

**Pull request merged**
