### PR TITLE
Polls: Creation form & start event

### PR DESCRIPTION
**Pull request by turt2live**
This does not render the start event (that's a later story), but it at least sends the event for processing by other clients.

**Code reviewer**: The commits are roughly split out by feature/story, if that's easier (let me know).

MSC: https://github.com/matrix-org/matrix-doc/pull/3381

Features:
* New dialog from Figma Compound design (only the scrollable one - the larger one isn't implemented yet).
* Composer button only works if you have permission to send the start event. 
* Question is required and cannot be empty/whitespace.
* At least 2 valid options must be specified.
* Empty/whitespace options do not count as valid (and are ignored during submission).
* Default 2 option fields.
* Maximum 20 option fields (disable 'Add Option' button at 20).
* Numbering always starts at one for option fields.
* Can go down to zero options, but cannot submit the form (lacking 2 valid options).
* Unstable prefixing on the event representation.
* After clicking the 'Add Option' button, it is scrolled into view to remain always visible.

image
image
image

With no options entered (placeholders must be shown):
image

---

Links:

* https://element-io.atlassian.net/browse/PSFD-423
* https://element-io.atlassian.net/browse/PSFD-325
* https://element-io.atlassian.net/browse/PSFD-328
* https://element-io.atlassian.net/browse/PSFD-316

---
Here's what your changelog entry will look like:

## ✨ Features
 * Polls: Creation form & start event ([\#7001](https://github.com/matrix-org/matrix-react-sdk/pull/7001)).

Preview: https://618040304c91288b400290cc--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by gaelledel** [comment]
> @gaelledel I couldn't reproduce the footer being transparent issue - which browser was that with? Looks like there's also a second scrollbar on the overall dialog which might be causing it.
> 
> The remainder should be fixed.

It was Chrome

**Review by gaelledel — COMMENTED** [review]
There is a very similar bug to the previous one when you add a new option in the modal 
Using Chrome on Mac OS. 
See below: As soon as I press on "add option" the Footer bar height is enlarged and subsequently, the add option button gets miss placed.
Screenshot 2021-11-01 at 15 39 38
S

**Comment by gaelledel** [comment]
Screenshot 2021-11-01 at 15 50 34
The title and close area at the top also seem to disappear after you fast scroll. It is meant to be a static section behaving similarly to the bottom section.

**Comment by turt2live** [comment]
@gaelledel I can't reproduce that, and a quick poll (hah) within the team shows similar results. I'm tentatively going to blame something to do with our preview tooling and possibly an extension in the browser. I'll land this so it shows up in a develop/nightly build where we can eliminate some of the variables a bit more easily - if you see issues there, please let me know.

**Pull request merged**
