### PR TITLE
Standardize errors about localpart structure

### PR DESCRIPTION
**Pull request by turt2live**
Fixes https://github.com/vector-im/riot-web/issues/5833

This also includes changing some Jira references that aren't searchable anymore, and a thing to replace the spinner on the SetMxidDialog as per https://github.com/vector-im/riot-web/issues/5833#issuecomment-445323177

### CODE REVIEW

**Comment by turt2live** [comment]
Looks like the regex is failing on the login page and that's causing it to not continue normally.

Going to have to spend some time figuring this one out though:
```
SAFE_LOCALPART_REGEX.test("lowercase")
true
!SAFE_LOCALPART_REGEX.test("lowercase")
true
```

**Comment by jryans** [comment]
> Going to have to spend some time figuring this one out though:
> 
> ```
> SAFE_LOCALPART_REGEX.test("lowercase")
> true
> !SAFE_LOCALPART_REGEX.test("lowercase")
> true
> ```

Yikes... I guess parens do the right thing:

```
!(SAFE_LOCALPART_REGEX.test("lowercase"))
false
```

but yeah... that's pretty strange. 😰

**Comment by jryans** [comment]
Oh wait, the `test` method is stateful somehow...?

```
SAFE_LOCALPART_REGEX.test("lowercase")
true
SAFE_LOCALPART_REGEX.test("lowercase")
false
SAFE_LOCALPART_REGEX.test("lowercase")
true
SAFE_LOCALPART_REGEX.test("lowercase")
false
```

**Comment by jryans** [comment]
Ah, it's the [global flag on the regex](https://stackoverflow.com/a/11477448/486978). If you remove that, it works:

```
const SAFE_LOCALPART_REGEX = /^[a-z0-9=_\-./]+$/;
undefined
SAFE_LOCALPART_REGEX.test("lowercase")
true
SAFE_LOCALPART_REGEX.test("lowercase")
true
SAFE_LOCALPART_REGEX.test("lowercase")
true
```

**Comment by turt2live** [comment]
Huh, I didn't realize that the expression actually stores state (and that the global flag interferes that badly). Thanks for taking a look into it - I've committed the change.

**Pull request merged**
