### PR TITLE
Simplify nodes on `ThirdPartyMemberInfo`

### PR DESCRIPTION
**Pull request by luixxiul**
For https://github.com/vector-im/element-web/issues/13817

This PR suggests to simlify nodes to understand how it should be updated.

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by alunturner** [comment]
Hello, thanks for the contribution.

This looks ok to me, but I'm slightly confused about one aspect. I'd expect a couple of snapshot tests (ThirdPartyMemberInfo) to require updates and I can't see that in this PR. I'm also surprised that the jest tests passed CI, but I could be missing something obvious here.

**Comment by luixxiul** [comment]
Hello, thanks for having a look at this!

I have not checked, but it might be `ThirdPartyMemberInfo` does not have a Jest snapshot test as it has not been updated for a long time. I'm going to add either Percy or Jest snapshot to track diffs.

**Comment by alunturner** [comment]
Ahh - I was looking at the current develop and that does indeed have snapshot tests. I wonder if they were added after you branched to do your work.

**Comment by luixxiul** [comment]
Yes exactly, I found it just now after pulling upstream!

**Review by alunturner — APPROVED** [review]

**Pull request merged**
