### PR TITLE
Align thread summary button with bubble messages on the left side

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/vector-im/element-web/issues/21873

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

From:
before2

To:
after2

On the right side: 
after1

As the thread button aligns with bubble message on the right side, the button should also align on the left side.

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Align thread summary button with bubble messages on the left side ([\#8388](https://github.com/matrix-org/matrix-react-sdk/pull/8388)). Fixes vector-im/element-web#21873. Contributed by @luixxiul.

Preview: https://pr8388--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by robintown** [comment]
Moving the thread summary will require design input

**Comment by luixxiul** [comment]
It looks like the width of the right and left info button is not same- I'll work on that.

**Review by t3chguy — APPROVED** [review]
Awesome, thanks!

**Comment by luixxiul** [comment]
The overflow issue on a narrow window is going to be addressed with another PR :smile:

**Comment by luixxiul** [comment]
@t3chguy I think this also can be safely merged :smiley:

**Comment by t3chguy** [comment]
It has been marked as needing design review

**Review by niquewoodhouse — APPROVED** [review]
👍

**Pull request merged**
