### PR TITLE
Auto-Element: Instant account registration and bookmark-based account login, for easier new user onboarding.

### PR DESCRIPTION
**Pull request by techmindful**
Implemented the concept of auto-account for Element.

Auto-account is the idea that a web service, whose purpose is communication, social media, and the like, can make the experience of onboarding new users easier, by inviting a new user with a link. After the new user visits the link, the web service generates a random username and password, automatically uses them to create an account for the new user, encodes them in a new link (account link), and sends it back to the new user. The new user saves the account link, in a convenient place like a bookmark. Then whenever the user needs to log into their account, they can visit the account link. The web service extracts the username and password from the account link, and authenticates the user. Auto-account saves the user from having to come up with a new username, and secure enough password.

I've made a video demo here: https://vimeo.com/597549392

https://user-images.githubusercontent.com/558581/171520077-d43792f9-9d23-43d4-b705-15abf0488aa3.mp4

There's another pull request on `vector-im/element-web` which is necessary for this feature to work: https://github.com/vector-im/element-web/pull/18900

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

### CODE REVIEW

**Review by turt2live — COMMENTED** [review]
Thanks for the contribution! This sort of change needs to pass through our design and product teams before code review to ensure it's something we'll be able to land successfully. Their review can take a while, unfortunately, but it'll be on their queue to look at.

**Comment by techmindful** [comment]
@turt2live Hi, thanks for the fast response :zap: For sure, it's also my intention to see if this feature fits the project. I appreciate if you can let me know if it doesn't, so I can plan something else. I'd like to ask a few questions:

1. For this feature, I also made some code change in `vector-im/element-web`. Should I make a pull request there too, and reference each other?
2. Do you have an estimate of how long the design review will take?
3. Meanwhile, I noticed all of Element's repositories have new commits very fast. Should I keep merging and maintaining my branch?

Thanks for your time!

**Comment by turt2live** [comment]
Opening a partner PR on the `element-web` repo would be great - be sure to cross-reference them between the two PR descriptions. 

Unfortunately I don't have an estimate on design review, but some internal processes should help speed it up over time. Until this review is done, merging `develop` back in is probably more trouble than it's worth: I'd wait until github says there's conflicts and resolve those as they appear instead, at your own pace.

**Comment by kittykat** [comment]
@techmindful could you please make the video viewable without login?

**Comment by techmindful** [comment]
> @techmindful could you please make the video viewable without login?

Sorry for a late response. I just checked and I was able to view the video without logging into Vimeo at all. Can you try again, or share a screenshot of the problem?

**Comment by MadLittleMods** [comment]
Closing as https://github.com/vector-im/element-web/pull/18900 was closed

**Pull request closed without merging**
