### PR TITLE
Fix issue with en-* reported by JigmeDatse

### PR DESCRIPTION
**Pull request by MTRNord**
If a browser sends en-US or en-GB it fails as it doesn't match en. We only got en and english is the only language which has this issue, so just rewrite en-* to en.

### CODE REVIEW

**Comment by turt2live** [comment]
there's also en-CA (:canada:) and I'm sure others. Actually replacing en-* with en would probably be okay.

```
if (preferredLangs[i].indexOf("en-") === 0) preferredLang = "en";
```

**Comment by MTRNord** [comment]
@turt2live oh my list did not list them :) I will change that. thanks for pointing that out

**Comment by t3chguy** [comment]
@turt2live get with the times, it's
`preferredLangs[i].startsWith("en-")`
;)

**Comment by MTRNord** [comment]
@t3chguy fixed/changed

**Comment by t3chguy** [comment]
Haha you take me too literally, I was just annoying Travis ;P

**Comment by MTRNord** [comment]
@t3chguy but I use functions that are available :P It propably internal does exactly the same :)

**Comment by ara4n** [comment]
i'm a bit confused by this.  Shouldn't the behaviour be that if I request any kind of dialect (e.g. `es-AR` for Argentinian Spanish), it should default to a general `es` if `es-AR` isn't available?  So similarly `en-GB` should default to `en`, rather than needing to be special-cased for `en`?

This would imply that we should call the base translation `en` rather than `en_EN`?

**Comment by MTRNord** [comment]
@ara4n basicly you are right. I could check if a stripped version exists of a language. But that would cause problems with for example chinese as chinese traditional vs simplified is quite different.

**Comment by ara4n** [comment]
This seems infinitely preferable to special-casing `en`.  In the case of Chinese, I'd still have thought that degrading to `zh` from `zh-Hans` or whatever would be preferable, even though the languages are completely different.

**Comment by dtygel** [comment]
Well, the way I implemented this was in the following way: the first language is the full language, like 'en-CA', and the second language is 'en'. This is done in `getNormalizedLanguageKeys` (lines 111-113 in languageHandler). Then, when trying to fetch the languages, `setLanguage` will first try to find the full language (first element in the array), and if it's not found, will get the second language (the general one, with only 2 characters). This is done in lines 57-62.

So I don't see the reason of this fix.

**Comment by ara4n** [comment]
okay, i guess there's a bug in the logic then. @JigmeDatse @MTRNord - what were the actual symptoms here? 

I'm assuming that @JigmeDatse's language settings are something like en_US, en_CA, fr_FR.  In which case perhaps it's hitting fr_FR as the first full language (even though it's lower priority), given we 'only' have en_EN defined?

**Comment by MTRNord** [comment]
@ara4n yes it falls back to fr which is wrong. It should use en as language. Because it would match en_US and en_BR in the case of  @JigmeDatse . So we need to define that en_* has to use en

**Comment by dtygel** [comment]
I confess that I don't understand the bug. For example: "en_GB" would try first en_GB.json. Since it doesn't exist, it will try "en". Isn't it right? How did it become fr?

**Comment by JigmeDatse** [comment]
I was looking at our translations, and I'm not sure if there issue was that it had en-EN, but my preferred list has en-GB, en, en-US (I couldn't set en-CA) but no en-EN.  If I understand, the available translation of en-EN is the English (country) variation of English (language), and may, or may not fall back to en generic version of English.  I will test shortly to see if I'm getting things in English.

**Comment by dtygel** [comment]
Oh, now I understand: one way to solve this is to have as fallback a 'en.json' file, and not 'en_EN.json' anymore. Does weblate allow for a 'en,json' language? If so, then I can PR a `mv en_EN.json en.json` and make __en__ the fallback language in `languageHandler`.

**Comment by MTRNord** [comment]
@dtygel weblate should auto handle the change

**Comment by ara4n** [comment]
@MTRNord, @dtygel do we want to get this in before the final release (due either late tonight or first thing tomorrow, once folks have caught up on the final translations?)

**Comment by MTRNord** [comment]
Am I correct this has been fixed as someone added en-US?

**Comment by dbkr** [comment]
OK - either way this isn't going to work now we have en-EN and en-US since it would prevent anyone from getting the en-US translation.

**Pull request closed without merging**
