### PR TITLE
fix avatar stretched on 1:1 call

### PR DESCRIPTION
**Pull request by I-lander**
Fixes https://github.com/element-hq/element-web/issues/27427

In a 1:1 private conversation with another person, when receiving a call, the avatar icon is stretch :

As it is:

As it should be:

The issue is due to the flex box of the parent element > mx_IncomingLegacyCallToast
As there is no align-item property, the elements can be strectched.

To test:
1. Call anybody in a 1:1 room

Signed-off-by: I-lander Ilan.varillon@gmail.com

### CODE REVIEW

**Review by florianduros — CHANGES_REQUESTED** [review]
Thank you for your contribution.
I tested the change and it is working.

We need you to [sign-off](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md#sign-off) your contribution.

**Comment by I-lander** [comment]
> Thank you for your contribution. I tested the change and it is working.
> 
> We need you to [sign-off](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md#sign-off) your contribution.

**Comment by I-lander** [comment]
> Thank you for your contribution. I tested the change and it is working.
> 
> We need you to [sign-off](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md#sign-off) your contribution.

I signed off the pr

**Review by florianduros — APPROVED** [review]
Perfect!

**Pull request merged**
