### PR TITLE
Make the Add option button look disabled when it is

### PR DESCRIPTION
**Pull request by andybalaam**
**Update**: no "not-allowed" pointer after design review

image

Fixes https://github.com/vector-im/element-web/issues/19701

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

Preview: https://6197926e71185ddc210541e5--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by t3chguy** [comment]
With that opacity it looks like it won't pass WCAG contrast

**Comment by andybalaam** [comment]
> With that opacity it looks like it won't pass WCAG contrast

That opacity is the same as our other buttons when they are disabled.  I am guessing it is considered OK when the button is disabled for it to be hard to read?

**Comment by gaelledel** [comment]
@t3chguy  I'm not sure disabled states often pass WCAG. We will soon have design  capacity to do a thorough accessibility audit for existing components.

**Comment by andybalaam** [comment]
@t3chguy are you OK to review given we've got approval from Gaelle?

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
