### PR TITLE
Fix devtools textbox height

### PR DESCRIPTION
**Pull request by nilootpal**
Fixes https://github.com/vector-im/element-web/issues/22306

although the outer div had fixed dimensions the inner text area was resizable which is fixed

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Type: [Task]

The text area highlighted by red(only for development purpose) was resizable and could be resized to change the height. I have change the CSS to disable the resize option

Before:
Screenshot 2023-02-06 at 11 36 57 PM

After:
Screenshot 2023-02-06 at 11 35 07 PM

Signed-off-by: Nilootpal Das <nilootpaldas@gmail.com>

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix devtools textbox height ([\#10082](https://github.com/matrix-org/matrix-react-sdk/pull/10082)). Fixes vector-im/element-web#22306. Contributed by @nilootpal.

### CODE REVIEW

**Comment by t3chguy** [comment]
> Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md?rgh-link-date=2023-02-04T18%3A37%3A42Z))

Missing sign off, checking the box is not enough, see the linked document.

**Review by richvdh — CHANGES_REQUESTED** [review]
^

**Comment by dbkr** [comment]
See also the rest of that document, in particular, please use the correct 'fixes' annotation and remember screenshots for visual changes.

**Comment by nilootpal** [comment]
Thanks for the review, I will look into that immediately

**Review by richvdh — CHANGES_REQUESTED** [review]
Per #22306, I couldn't reproduce the issue, but in any case I don't see how this would fix it?

**Comment by richvdh** [comment]
It seems like the original issue is already fixed, so I'm going to go ahead and close this.

**Pull request closed without merging**
