### PR TITLE
Make the show more button do a clean cut on the room list while transparent

### PR DESCRIPTION
**Pull request by turt2live**
Known issues:
* Causes scroll jumps when the button gets added to DOM
* Resize handle is invisible when there's a show more button

TODO:
* Clean up comments
* Clean up useless code (all the padding stuff isn't needed)

For https://github.com/vector-im/riot-web/issues/13635

### CODE REVIEW

**Comment by turt2live** [comment]
@bwindels for context: design wants a smoother transition than tiles disappearing, so this attempts to move the show more button out of the resize box and adjust the handle as needed. Another possible approach is somehow detecting when a button should be shown and adding a tile for it, replacing the last room tile.

**Comment by bwindels** [comment]
I'm working on this PR to try and make it mergeable.

**Comment by bwindels** [comment]
showmoremoremore

**Comment by turt2live** [comment]
merging against advice of CI - will monitor buildkite.

**Pull request merged**
