### PR TITLE
Don't use deprecated `room.currentState` in useRoomState.

### PR DESCRIPTION
**Pull request by toger5**
Signed-off-by: Timo K <toger5@hotmail.de>

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Comment by t3chguy** [comment]
Honestly with the advent of getters in modern JS I think we should undo the deprecation and just have it call the right thing for us, just like we did with `get timeline` on the Room object

**Comment by toger5** [comment]
I did find the `currentState` shortcut useful so I like this proposal.
Is the diff sth that you have as an PR. Or should I go ahead and patch this PR to look more like what you propose?

**Comment by t3chguy** [comment]
It is just a bodged patch, untested

**Comment by toger5** [comment]
Adding the changes i am wondering how this would behave with event emitters?
Since `currentState` returns a new obj on each call registering event listeners to it might be confusing?
Especially since `RoomEvent.CurrentStateUpdated` and `RoomEvent.OldStateUpdated` would not be emitted anymore:
```
const previousOldState = this.oldState;
        const previousCurrentState = this.currentState;

        // Let people know to register new listeners for the new state
        // references. The reference won't necessarily change every time so only
        // emit when we see a change.
        if (previousOldState !== this.oldState) {
            this.emit(RoomEvent.OldStateUpdated, this, previousOldState, this.oldState);
        }

        if (previousCurrentState !== this.currentState) {
            this.emit(RoomEvent.CurrentStateUpdated, this, previousCurrentState, this.currentState);
            ...
```

**Comment by t3chguy** [comment]
> Since currentState returns a new obj

Does it? Assuming the same LiveTimeline the same state object would be returned.

> Especially since RoomEvent.CurrentStateUpdated and RoomEvent.OldStateUpdated would not be emitted anymore:

Yes that would need fixing via some other means as you need to know when the RoomState is changed out from under you

**Comment by toger5** [comment]
> Does it? Assuming the same LiveTimeline the same state object would be returned.

Sure only if the oldState changed.

Is it as simple that whenever there is a new state object both (current and old) get changed?

**Comment by t3chguy** [comment]
> Is it as simple that whenever there is a new state object both (current and old) get changed?

No, the each EventTimeline has 2 RoomState objects, they never change. They are set in the c'tor only. So only when your EventTimeline changes would you need to update room states. Except whatever magic `forkLive` is clones and replaces it

**Comment by toger5** [comment]
It seems we never use the `RoomEvent.CurrentStateUpdated` and `RoomEvent.OldStateUpdated` events.
Is there a potential case we need those? Could those be deprecated? Is there a project using them?

**Comment by t3chguy** [comment]
I think the emitted events could possibly be deprecated, but we'd still need the logic for reEmitter.stopReEmitting, reEmit, etc so they might as well stay given they are in the same place

**Pull request closed without merging**
