### PR TITLE
Apply design to image thumbnails

### PR DESCRIPTION
**Pull request by dbkr**
Border & rounded corners

https://github.com/vector-im/riot-web/issues/7565

### CODE REVIEW

**Comment by dbkr** [comment]
argh, having resized the window to take a screenshot I have just realised this doesn't work at all :(

**Comment by turt2live** [comment]
I guess that means screenshots are now part of our official testing procedure

**Comment by turt2live** [comment]
I'm curious as to what made this not work

**Comment by jryans** [comment]
Thanks for making this contribution a while back. Since the code base has changed since this was opened, it no longer applies cleanly, and I don't think there's a need to keep it open in this state, as we can always find the code here again if needed. If you are still interested in pursuing this feature, please discuss with us in #element-dev:matrix.org to find a good approach forward.

**Pull request closed without merging**
