### PR TITLE
Show failures when sending messages

### PR DESCRIPTION
**Pull request by dbkr**
This is useful for the spam checking where otherwise you don't
really know why your message has failed to send

### CODE REVIEW

**Comment by lukebarnard1** [comment]
I'd prefer to use an error type as with the UDE. Is there no scope for that?

**Comment by dbkr** [comment]
Well, so the problem here is that the spam checking is done by a synapse plugin and so there won't be a fixed list of ways in which it could go wrong, eg. the antiscam stuff has things like, "you're not allowed to post bitcoin addresses" etc.

**Comment by lukebarnard1** [comment]
> so there won't be a fixed list of ways in which it could go wrong

That's not great for i18n but I guess we already have that problem with synapse in general.

Also, if there's more than one unsent message and they're unsent for different reasons, the first error might be confusing.

**Comment by dbkr** [comment]
Yeah, I'm not sure how to do it better, really.

If there's more than one pending message, it'll just show the old, generic error

**Comment by lukebarnard1** [comment]
Ok, LGTM with the caveat that we must start sending more specific error codes from the homeserver.

Separately it'd be interesting to consider a UI for showing errors related to individual unsent messages.

**Pull request merged**
