### PR TITLE
Initial Space Room View and Creation UX

### PR DESCRIPTION
**Pull request by t3chguy**
image
image
image
image
image

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
screenshots/gifs would make this a lot easier to review

**Comment by t3chguy** [comment]
Possibly, but the UX isn't going to survive the end of the week so there's not much point focusing on it :P

**Comment by turt2live** [comment]
I've heard those words many times in the past.

> `StopGap*` should be deleted in a couple weeks at worst

> The communities v2 prototype will be deleted in a month or so

> Message pinning will be implemented properly shortly

> This should hold us over until the new year

Long story short, nothing is ever temporary.

**Review by turt2live — APPROVED** [review]
thanks for adding the screenshots - makes the CSS easier to review :)

**Pull request merged**
