### PR TITLE
Set image thumbnail height in `render` rather than `componentDidMount`

### PR DESCRIPTION
**Pull request by ollieh**
Calculates the width of the timeline panel based on which panels are collapsed and the width of the window, rather than measuring it in the DOM after rendering. This width is then used to work out what height image thumbnails should be. This hopefully helps with: https://github.com/vector-im/riot-web/issues/2646

### CODE REVIEW

**Comment by lukebarnard1** [comment]
Hi @ollieh, thanks for the PR

I'm not convinced we should be passing `chatWidth` all the way through several components and I really don't think we should be calculating the it in `LoggedInView` based on whether the left or right panels are collapsed/expanded. 

I _totally_ agree that the height should be calculated when we `render`, so I would suggest that we still do your `calculateHeight` in the `render` of `MImageBody` but instead of using `chatWidth`, we just continue to use `this.refs.body.offsetWidth` as before.

**Comment by ollieh** [comment]
@lukebarnard1 I don't like the passing through of the width either, but I'm not sure what other options there are. I tried using `this.refs.body.offsetWidth` initially, the trouble is it's not available until everything is rendered. I'll have a fiddle and see if there's another way of doing it.

**Comment by lukebarnard1** [comment]
@ollieh ah, I see. Actually, in theory it should be sufficient to call `onWidgetLoad` once the height has been recalculated in `MImageBody` (and I'm surprised that we don't already do that).

**Comment by lukebarnard1** [comment]
Hey @ollieh, I'm pretty convinced this is the wrong approach so I'm going to close this now. 

MImageBody.js has subsequently been changed such that `onLoad={this.onWidgetLoad}`, which might have helped to remove this problem anyway.

**Pull request closed without merging**
