### PR TITLE
Replace plain text emoji at the end of a line

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes [#4872](https://github.com/vector-im/element-web/issues/4872)

Peek 2021-04-18 10-15

### CODE REVIEW

**Comment by t3chguy** [comment]
I believe https://github.com/matrix-org/matrix-react-sdk/pull/5659 is a more accessible solution to the end-of-message case, where enter is used to confirm completion, not to send message + unexpectedly confirm completion

**Comment by SimonBrandner** [comment]
Ahhhhhhh, how did I manage to forget about that!? :D Yeah, that looks much better than this! :+1: What is it missing (i.e. why is it a draft)?

**Comment by t3chguy** [comment]
Stakeholder approval for such a usability change

**Comment by SimonBrandner** [comment]
Ah, okay. I am going to close this in favour of [#5659](https://github.com/matrix-org/matrix-react-sdk/pull/5659) and hope it gets merged in a reasonable amount of time :D

**Comment by t3chguy** [comment]
My pr doesn't handle the newline (shift enter) case though

**Comment by t3chguy** [comment]
Discord treats shift-enter as an autocomplete confirmation
Slack just inserts a newline, I'd argue following Slack would be best and thus the newline case can be ignored as it already works as expected

**Pull request closed without merging**
