### PR TITLE
Fix jest intellisense in VSCode

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/17743

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
Seems sane

**Comment by t3chguy** [comment]
Except the unhappy CI

**Comment by t3chguy** [comment]
Hmm, I think just a type cast would be clearer, otherwise all of the `jest.fn()`s in test-utils are redundant

**Comment by turt2live** [comment]
for the places where we're not testing/checking that the function was interacted with, just override it using vanilla JS: `.doThing = () => 42;`

**Comment by t3chguy** [comment]
Sure, that's another solution, the point of using `mockImplementation` is that its already a Jest Mock as spat out by test-utils mkStubRoom

**Comment by turt2live** [comment]
right, but the types don't know that per #element-dev

**Comment by SimonBrandner** [comment]
Hopefully, this should be a bit better now

**Comment by SimonBrandner** [comment]
Closing as the issue has been solved by @gsouquet

**Pull request closed without merging**
