### PR TITLE
Fix bug where global "Never send to unverified..." is ignored

### PR DESCRIPTION
**Pull request by lukebarnard1**
Codep https://github.com/matrix-org/matrix-js-sdk/pull/616

### CODE REVIEW

**Comment by turt2live** [comment]
:( I tested this at the time of writing and confirmed it worked. Did something change in the crypto stuff since November?

**Comment by lukebarnard1** [comment]
@turt2live this is a race, so it's possible you were caught on the happy side of it.

**Comment by turt2live** [comment]
well that's not a fun race to be winning. Thanks for poking it.

**Comment by lukebarnard1** [comment]
ok, so the fix for this is a lot simpler - we block on the matrix client actually starting before emitting client_started

**Comment by lukebarnard1** [comment]
See https://github.com/matrix-org/matrix-react-sdk/pull/1772

**Pull request closed without merging**
