### PR TITLE
Revamp UserInfo call to actions and look & feel

### PR DESCRIPTION
**Pull request by gsouquet**
Fixes https://github.com/vector-im/element-web/issues/22096

This pull request achieves two thing, a visual refactor to have clear actions when landing in the product with a matrix.to link. And a code refactor to split out the humongeous `UserInfo` component in more manageable pieces.

The idea was to re-use the design language that already exists in the `RoomSettings` and not to reinvent anything new. There are many improvements to the crypto section that could be made, but they will be left to the crypto team who will be better placed to tackle those.

<table>
<tr>
	<td><h3>Before 🚫</h3>
	<td><h3>After ✅</h3>
<tr>
	<td>Screenshot 2022-12-01 at 14 11 01
	<td>Screenshot 2022-12-01 at 15 55 03
</table>

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Revamp UserInfo call to actions and look & feel ([\#9687](https://github.com/matrix-org/matrix-react-sdk/pull/9687)). Fixes vector-im/element-web#22096.

### CODE REVIEW

**Comment by t3chguy** [comment]
Admin tools looks a little neglected compared to https://github.com/vector-im/element-web/issues/22096#issuecomment-1333398182

**Comment by gsouquet** [comment]
The screenshot I added was not final, and it was decided against using the icons there as there's no clear iconography set in the app or those actions and it's probably out of the scope of this task to define these.

**Review by amshakal — CHANGES_REQUESTED** [review]
Hey! Looking good. Here are my comments:

1. In the security section, can we change the copy of the buttons to:
- Verify user
- View sessions 

2. Can we change the icons for Verify user and View sessions to the ones added below

3. Can we change the vertical spacing of where 'offline for 34min' sits? 

Attaching screenshot and [figma link](https://www.figma.com/file/4ZhXpRiOyMZV1pflvkRFJc/%5BMatrix.to%5D-Deep-link-to-the-right-place?node-id=236%3A16504&t=cLs7ghLKQLcA7BSt-1). 
Screenshot 2022-12-01 at 4 28 55 pm

**Review by turt2live — COMMENTED** [review]
clearing code review while draft

**Comment by gsouquet** [comment]
@amshakal I have changed bullet point 1. and 3. where applicable. 
However I don't think we should do number 2, the reason is the icons are color coded and add some extra context that is used across the app. 
I would be more comfortable if those changes were tackled by the crypto team

**Comment by amshakal** [comment]
Okay that's fine. In the spirit of incremental changes, this is good :)

**Comment by gsouquet** [comment]
Will need to restart this one from scratch, as it as stalled and is not usable anymore

**Pull request closed without merging**
