### PR TITLE
Show a tile at beginning of visible history

### PR DESCRIPTION
**Pull request by robintown**
When the user has reached the beginning of visible history in a room, show them a room intro to explain why messages before that point are unavailable and reassure them that the timeline has loaded.

Examples:

Screenshot_2021-05-04 Element #lojban

Joining an old DM to which the keys have been lost:

Screenshot_2021-04-19 Element robin-test(1)

Type: enhancement

Closes vector-im/element-web#16818.
Closes vector-im/element-web#16679.
Closes https://github.com/vector-im/element-web/issues/19888.

---
Here's what your changelog entry will look like:

## ✨ Features
 * Show a tile at beginning of visible history ([\#5887](https://github.com/matrix-org/matrix-react-sdk/pull/5887)). Fixes vector-im/element-web#16818 vector-im/element-web#16679 and vector-im/element-web#19888. Contributed by @robintown.

Preview: https://61bce26c585a780919fdf2e8--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by robintown** [comment]
Let me know if the date separator should preferably be above the room intro, in which case I could put the logic into the member event grouper instead.

**Comment by robintown** [comment]
I went ahead and did that, since the room intro was unintentionally showing up in the file list as well.

**Comment by jryans** [comment]
I'd like to hear Design's opinion before the code review here.

**Comment by robintown** [comment]
I believe this also fixes vector-im/element-web#16679

**Comment by SimonBrandner** [comment]
> I believe this also fixes vector-im/element-web#16679

Probably add it to the description so that Github picks it up

**Comment by ShadowJonathan** [comment]
I think the "topic" part needs to have an extra linebreak/distance/seperation between that and the room history boilerplate

**Comment by robintown** [comment]
@ShadowJonathan agreed, though also the "normal" room intros don't have a line break currently. I'll just have to see what design says.

**Review by turt2live — COMMENTED** [review]
just filling in the code review so it clears from the queue while design makes a round trip.

**Comment by HarHarLinks** [comment]
does this hide the crypto error from the room list "Show previews of messages" as raised in vector-im/element-web#19888?

**Comment by robintown** [comment]
@HarHarLinks Ah, no it doesn't. Would you mind opening a separate issue for that?

**Comment by niquewoodhouse** [comment]
I think I like the idea of showing the room intro at the beginning of your experience with a room but I was wondering if people would be blind to see the 'you can't see earlier messages' bit, as they become accustomed to that area being` blah blah` information.  Using a tile event might make that information stand out more as part of the timeline.  


https://user-images.githubusercontent.com/1587166/146554818-cdf63c04-5979-4d56-bc00-a45637a6d255.mp4

**Comment by robintown** [comment]
@niquewoodhouse Updated, this is how it's looking now:

Screenshot 2021-12-17 at 14-11-28 Element #nim

**Review by niquewoodhouse — APPROVED** [review]
Thanks!

**Review by andybalaam — APPROVED** [review]
Fantastic change - a real improvement, thank you!

**Comment by andybalaam** [comment]
Code quality is impressive, thank you @robintown for such a careful and well-designed contribution.

**Pull request merged**
