### PR TITLE
Fix typo error

### PR DESCRIPTION
**Pull request by EECvision**
### Bug Fixes

**Fix a typo error in the matrix-react-sdk README.md file.**

Before:
issue4-b

After:
issue4

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

Preview: https://pr8214--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by EECvision** [comment]
This PR fixes: https://github.com/vector-im/element-web/issues/21635

**Review by gsouquet — CHANGES_REQUESTED** [review]
The diff does not match the description

**Comment by EECvision** [comment]
I think I checkout out to a new branch from the previous pull request I made. That's why I have an unmatched git diff

I am fixing it now.

**Comment by EECvision** [comment]
Thank you, I am happy I could contribute.

**Pull request merged**
