### PR TITLE
Phase 3 controller merging

### PR DESCRIPTION
**Pull request by Kegsay**
This PR merges all molecules which had controllers into components. This involves slurping up vector logic for things like velocity bouncing and contextual menus, but this is Okay according to @ara4n (We can always sort it out at later date).

This PR also *renames* various components. The naming convention for components which represent `m.room.message` `msgtypes` has been changed to have the suffix "Message" instad of "Tile" at @ara4n 's request. This was requested to avoid confusion between other tiles like `MemberTile`. We also however display non-message things like member changes and call events. These now have the suffix `Event` to distinguish between them. The new file names are below:

```
src/components/views/messages/
├── Event.js
├── MEmoteMessage.js
├── Message.js
├── MFileMessage.js
├── MImageMessage.js
├── MNoticeMessage.js
├── MRoomMemberEvent.js
├── MTextMessage.js
├── MVideoMessage.js
├── TextualEvent.js
└── UnknownMessage.js

```

There are glaring problems which need addressing in future PRs currently. Mostly this is due to the fact that we now have these components pulling in other components (from `getComponent()` which exist only in Vector). Future PRs will fix this.

See https://github.com/vector-im/vector-web/pull/425 for the rest.

### CODE REVIEW

**Comment by dbkr** [comment]
lgtm

**Comment by ara4n** [comment]
Finally getting a chance to look at these PRs.  Generally look great, but I don't get why we are mixing Event tiles together with the Message bodies in this messages/ directory.

The timeline is built up of three layers here EventTiles generate the timeline entry; they then wrap a EventTileType (Textual or Message); and then the Message type wraps different types of MessageBodies.  These layers have been mixed up together (complete with MessageComposer?!) into the same messages/ directory and I think it's quite confusing.

I would expect 'Event' to be in the rooms/ directory, and probably still called EventTile (like MemberTile and RoomTile) as it's a repeating list item.  I'd expect MessageComposer to be there too, as it's not a type of message.

I would expect MRoomMemberEvent to have died entirely, as i thought it had been replaced by TextualEvent.

I would expect TextualEvent and Message to have the same naming convention as they are at the same level of abstraction - e.g. MessageEvent and TextualEvent.

The MFooMessage names would probably be clearer if they were MFooBody or MFooMsgBody to make it clear that they are literally rendering the body (nothing else!) of a message, although I'm not too fussed.

I'm also scared that the CSS is getting completely out of sync with the component names here...

Can you face changing this?

**Comment by ara4n** [comment]
I've just complicated this further by combining M{Text,Notice,Emote}Message into a single TextualMessage, as they were 98% code duplication (and getting worse, as I add in more text processing stuff like search result highlighting).  I've stuck with the current naming scheme, but I still think this should be a TextualBody component.

**Comment by Kegsay** [comment]
I'm happy to move things *after* the heart transplant :)

 - I definitely agree with `MessageComposer` being in the wrong place; I would put it in `rooms/` as you say.
 - I don't feel that the layers within `messages/` is confusing. It's all to do with the same thing (rendering messages) but I don't feel strongly if you want to move it elsewhere. Moving `Event` to `rooms/EventTile` WFM.
 - The whole idea of "textual" events vs "$type" events is an interesting one. We have a bit of both atm (`m.call.*` rendering is done in `TextualEvent` whereas room member stuff is done in `MRoomMemberEvent`). I would prefer if we did this based on the $type. We should *not* be assuming that these event types are only ever going to be displaying a random string. The rest of the app shouldn't give a damn about how this is rendered. If we change it from rendering text to rendering gold unicorns then we'll need to rip out the code from `TextualEvent` and make a new class (`GoldUnicornEvent` if we're wanting to be consistent and naming the event after how it is rendered...).  We can share code without resorting to this. I feel moderately strongly on this.
 - `s/Message/MessageEvent/` WFM - though if we're being pedantic perhaps `MRoomMessageEvent` :)
 - As for `s/MFooMessage/MFooMsgBody/` - The accepted input props to these events are the complete `MatrixEvent` (`this.props.mxEvent`). If we're just making these things responsible for rendering the `content` then we should make this explicit in the prop interface (e.g. `this.props.content`), then WFM.

**Comment by ara4n** [comment]
I think we're aligned everywhere above, other than "The whole idea of 'textual' events" - i think we're crosswired somehow; will come discuss IRL.  Can you confirm that MRoomMemberEvent isn't actually being used anywhere in practice?  (it's just rendered as a generic TextualEvent).

I'm not convinced that just because MFooMessage takes an event object as a prop, we should call it an Event or a Message - instead the class name should surely reflect what it displays... which is the 'body' of an event, for purposes of embedding the body inside the general EventTile component within the timeline.

**Comment by Kegsay** [comment]
> Can you confirm that MRoomMemberEvent isn't actually being used anywhere in practice?

I can confirm this. We use `TextualEvent` (`Event.js:41`).

> I'm not convinced that just because MFooMessage takes an event object as a prop, we should call it an Event or a Message

I'm not trying to say that. I am trying to say that if we're just rendering a body and nothing else, why are we passing in the entire event.

**Comment by Kegsay** [comment]
As per RL:
 - I don't like it but we're sticking with `TextualEvent` and will make type-specific classes as and when we need them. If people are trying to find how some events are rendered they just need to "know" where to look.
 - `s/MEmoteMessage/MEmoteBody/g`
 - `s/Event/EventTile/g` (back to how it was originally)
 - `s/Message/MessageEvent/g`
 - We also now have `TextualBody` for `msgtypes` which render just plain text (`m.emote`, `m.notice`, `m.text`).

**Pull request merged**
