### PR TITLE
Fix waste of space of collapsed left panel

### PR DESCRIPTION
**Pull request by azuenko**
Hello,

I've made a fix to make left panel look more pleasant in collapsed mode. I've tuned some CSS and removed chevron in collapsed mode.

### Before
image

### After

image

### CODE REVIEW

**Comment by jryans** [comment]
@azuenko Thanks for making this contribution a while back!

It looks quite nice to me, and it may have slipped through the cracks in our review process. 😭 To move forward, I think we'll need to:

* [ ] Update the PR or each commit with your sign off as described in [CONTRIBUTING.rst](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst)
* [ ] Fix merge conflicts
* [ ] Code review
* [ ] Design review

If that sounds good, please take a look a updating the PR to fix conflicts, and then we can move forward from there.

**Comment by azuenko** [comment]
Hello @jryans 

I've updated the PR: resolved merge conflicts and added signed-off-by tag. Could you please proceed?

Thanks!

**Comment by jryans** [comment]
Great, thanks for continuing with this effort! Next step is a design review. @nadonomy, could you provide design feedback on this?

**Comment by nadonomy** [comment]
> Great, thanks for continuing with this effort! Next step is a design review. @nadonomy, could you provide design feedback on this?

This looks great! (And checked the design review in your comment above).

**Comment by nadonomy** [comment]
@jryans I held off from formally approving the PR via GitHub as the code review is outstanding, but just lmk if you'd prefer me to sign it off via GitHub here.

**Comment by turt2live** [comment]
(a green light in the comments is not much different from a green checkmark tbh)

**Pull request merged**
