### PR TITLE
Redesign: Add a form field component

### PR DESCRIPTION
**Pull request by jryans**
The label moves into the border on focus and after being filled. A valid color
is applied to the label and input border. Other states like invalid can be added
later as needed.

Adapted from @ara4n's experiment into a React component with a CSS only
approach.

form-fields

### CODE REVIEW

**Comment by jryans** [comment]
> Some variables might need to be added to riot-web's status theme as well (errors might not crop up until someone uses the component, though)

These days, such errors seem to appear at build time. (Perhaps that's new as of the content hashed image work, unsure...) In any case, the Status theme root [imports](https://github.com/vector-im/riot-web/blob/0802aaae914ac72ad9e19ac04ffb88098d595d1c/res/themes/status/css/status.scss#L3) the light theme's `_base.scss`, so it should be okay.

**Comment by turt2live** [comment]
so it does... I wonder why I've never had luck with that...

I guess it's fine though - it seems to build fine

**Comment by ara4n** [comment]
woo, awesome :) thank you! i don’t believe we need to worry about keeping the status theme working with Experimental.

the demo gif here highlights that we need to distinguish “focused” from “valid” somehow; need input from @nadonomy here

**Comment by ara4n** [comment]
@nadonomy okay - so how do we distinguish between unfocused-and-valid and focused-and-valid? as the current zeplin implies they should both be green atm...

**Comment by nadonomy** [comment]
@ara4n just updated the comp in Zeplin to show what I'm thinking: https://zpl.io/VDqejkr

**Comment by jryans** [comment]
Opened https://github.com/matrix-org/matrix-react-sdk/pull/2468 for the label alignment and new focused color.

**Pull request merged**
