### PR TITLE
Move react-addons-test-utils to react-dom/test-utils

### PR DESCRIPTION
**Pull request by akihikodaki**
See https://github.com/facebook/react/commit/3a7eef2bcfdc215192f8c33e8f7ab5fb9b9eb87b. This is a preparation for https://github.com/vector-im/riot-web/issues/6410.

### CODE REVIEW

**Comment by dbkr** [comment]
Can you do the DCO signoff please: https://github.com/matrix-org/matrix-react-sdk/blob/master/CONTRIBUTING.rst

**Comment by akihikodaki** [comment]
34f5fb91599adcc17e35824f149b11290f84fba3 added Signed-off-by. I also added Signed-off-by to my other pull requests.

**Comment by jryans** [comment]
Thanks for making this contribution a while back. It looks like this needs a rebase to resolve some conflicts since we have switched to Yarn. Do you still want move forward with this?

I will do my best to re-review it quickly after you update it.

**Comment by jryans** [comment]
Since there's been no reply, I'll assume this has been abandoned.

**Pull request closed without merging**
