### PR TITLE
Fix: Move "Leave Space" option to the bottom of space context menu

### PR DESCRIPTION
**Pull request by hanadi92**
Fixes an opened issue in element-web here: https://github.com/vector-im/element-web/issues/23627 

Note: fix move "leave space" to the bottom of space context menu.

Before: 
Screenshot 2022-11-02 at 10 38 41 PM

After:
Screenshot 2022-11-02 at 10 39 00 PM

Before the fix, this order applies:
-> settings
-> leave space
-> dev tools

After the fix, this order applies:
-> devtools
-> settings
-> leave space

type: enhancement

---
Here's what your changelog entry will look like:

## ✨ Features
 * Fix: Move "Leave Space" option to the bottom of space context menu ([\#9535](https://github.com/matrix-org/matrix-react-sdk/pull/9535)). Contributed by @hanadi92.

### CODE REVIEW

**Review by florianduros — COMMENTED** [review]
First of all thank you for your PR.

The change seems to be correct, I'll test it

**Comment by florianduros** [comment]
@hanadi92 some tests are in failure. I'm afraid that the branch is outdated from develop and this the reason why  the tests are failing regarding to your PR changes.

**Comment by hanadi92** [comment]
> @hanadi92 some tests are in failure. I'm afraid that the branch is outdated from develop and this the reason why the tests are failing regarding to your PR changes.

Weird. I double checked that the branches are synced and the exact test passes locally. There was an "update branch" button here, so I give it a go...

**Review by florianduros — APPROVED** [review]
All good!

**Pull request merged**
