### PR TITLE
Clarify a DM channel is immediately ready for messages

### PR DESCRIPTION
**Pull request by raboof**
Fixes https://github.com/vector-im/element-web/issues/21353

---
Here's what your changelog entry will look like:

## ✨ Features
 * Clarify a DM channel is immediately ready for messages ([\#7998](https://github.com/matrix-org/matrix-react-sdk/pull/7998)). Fixes vector-im/element-web#21353. Contributed by @raboof.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Code looks good, but will need to undergo a product review

**Comment by raboof** [comment]
> Code looks good, but will need to undergo a product review

Thanks! I'd appreciate that - I also realize I haven't followed all the steps from `CONTRIBUTING.md` yet, which is why I had left the PR on 'Draft' for now. Any feedback welcome!

**Comment by raboof** [comment]
> Hello! Product here :wave:

:wave: 
 
> Could you link the issue that you're working from so that we can have the context and solution that you're proposing and what that would look like to the user?
> 
> Thanks for your contribution - excited to hear/see more about it.

It was a UX snag that I [encountered myself](https://merveilles.town/web/statuses/107915569473669945) and didn't create an issue for yet. Would you like me to retroactively create one?

**Comment by daniellekirkwood** [comment]
> It was a UX snag that I [encountered myself](https://merveilles.town/web/statuses/107915569473669945) and didn't create an issue for yet. Would you like me to retroactively create one?

That would be amazing - thank you. It might be easier for us to keep track and answer questions in an issue over a PR. We can also use the issue as "acceptance criteria" and as a starting point if there's further work needed to improve the DM experience (which I'm sure there is!)

**Comment by raboof** [comment]
> > It was a UX snag that I [encountered myself](https://merveilles.town/web/statuses/107915569473669945) and didn't create an issue for yet. Would you like me to retroactively create one?
> 
> That would be amazing - thank you. It might be easier for us to keep track and answer questions in an issue over a PR.

I'm not sure I see how that would be easier in this case, but I'm happy to oblige ;). Would you prefer to see this issue in https://github.com/matrix-org/matrix-js-sdk or in https://github.com/vector-im/element-web/ or in https://github.com/vector-im/element-desktop/ ?

**Comment by daniellekirkwood** [comment]
Thank you - I guess easier for internal processes... 

Let's go for: https://github.com/vector-im/element-web/ if your changes impact the web client and desktop product. 

I appreciate it :)

**Comment by raboof** [comment]
> Let's go for: https://github.com/vector-im/element-web/ if your changes impact the web client and desktop product.

:+1: - added https://github.com/vector-im/element-web/issues/21353!

**Comment by t3chguy** [comment]
This is superseded by the new DM experience which doesn't create the room until you send your first message and has updated copy

**Pull request closed without merging**
