### PR TITLE
Fix inserting trailing colon after mention/pill

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes [#15794](https://github.com/vector-im/element-web/issues/15794)

Peek 2021-04-07 11-54

This removes the handling of trailing characters from `createMentionParts()` as we need to determine whether or not to insert the trailing character differently in different situations

I have to admit that my understanding of how the composer works is highly limited but this seems to work and make sense :sweat_smile:

### CODE REVIEW

**Comment by SimonBrandner** [comment]
Hmm, still not completely ideal... I'll try to fix the small problem that this has but it's probably close enough

**Comment by t3chguy** [comment]
Wonder if it'd be worth looking into https://github.com/vector-im/element-web/issues/4883 at the same time as that will likely overhaul this area

**Comment by SimonBrandner** [comment]
Hmm, maybe later. First, I'd fix the current behaviour and then I'd think about that and also [#16682](https://github.com/vector-im/element-web/issues/16682)

**Comment by t3chguy** [comment]
Well #16682 is to abolish this behaviour entirely which has pretty much been all but rejected by M

**Comment by jryans** [comment]
@bwindels, perhaps you have thoughts on this with your composer hat on?

**Review by turt2live — APPROVED** [review]
This seems relatively straightforward, thanks!

**Pull request merged**
