### PR TITLE
Add a badge to the favicon/tray icon for unread chats

### PR DESCRIPTION
**Pull request by hjri**
This mimics the discord's tray icon which has small dot when there's no notifications/mentions but are some unread messages in non-muted chats.

### CODE REVIEW

**Comment by lukebarnard1** [comment]
If I understand correctly, this would cause "+" to be shown whenever any room is unread. Typical usage involves many rooms that go unread without them requiring attention, so this might be a bit noisy.

I wonder what @lampholder thinks

**Comment by hjri** [comment]
the intention is to show a badge when any non-muted room is unread, though i don't remember if that's the case with this PR already. For rooms that don't require attention for unread messages one could just mute the room all together. At least that's the way discord works.

**Comment by lukebarnard1** [comment]
Muting the room also mutes mentions of the current user. So if the user mutes all the rooms they're not interested in (for the proposed unread badge), they wouldn't get notified for mentions.

**Comment by jryans** [comment]
Thanks for making this contribution a while back. Since the code base has changed since this was opened, it no longer applies cleanly, and I don't think there's a need to keep it open in this state, as we can always find the code here again if needed. If you are still interested in pursuing this feature, please discuss with us in #riot-dev:matrix.org to find a good approach forward.

**Pull request closed without merging**
