### PR TITLE
Improve spotlight accessibility by adding context menus

### PR DESCRIPTION
**Pull request by justjanne**
Type: Enhancement
Related: https://github.com/vector-im/element-web/issues/22361
Closes: https://github.com/vector-im/element-web/issues/20875
Closes: https://github.com/vector-im/element-web/issues/22675

---
Here's what your changelog entry will look like:

## ✨ Features
 * Improve spotlight accessibility by adding context menus ([\#8907](https://github.com/matrix-org/matrix-react-sdk/pull/8907)). Fixes vector-im/element-web#20875 and vector-im/element-web#22675. Contributed by @justjanne.

### CODE REVIEW

**Comment by DoM1niC** [comment]
Alternative right-click Context Menu will be nice to have ....

**Comment by niquewoodhouse** [comment]
Early design review:

- Use Tertiary content for menu icons in this context.  
- When hovering, change to Secondary content

**Review by andybalaam — APPROVED** [review]
Looks good, thanks!

**Comment by niquewoodhouse** [comment]
I'm not opening it with my keyboard.

- When I open the search I can keyboard up and down.
- When I then interact with an icon in the context menu, and leave the menu, I can no longer keyboard up and down.
- I can't then keyboard left and right between the menus either.

If this is how accessibility works, that's fine, I just want to share in case there's an easy way to let people still go up and down.

https://user-images.githubusercontent.com/1587166/177999199-99cc422d-bdef-4053-8869-1c461d23b6f8.mov

**Review by t3chguy — APPROVED** [review]
This is a functional review rather than a code one, +10000

You could probably get away with handling up/down arrows from the alternate tab indexes too instead of trapping the user until they shift-tab but that's tangential

**Pull request merged**
