### PR TITLE
Make the "Voice message" button in the message composer configurable

### PR DESCRIPTION
**Pull request by grantm**
* With this change the user can choose to hide the "Voice message" button in the message composer menu.

* The site administrator may also choose to hide the button by including this in the site config:

  "setting_defaults": { ... "MessageComposerInput.showVoiceRecordingButton": false, ... },

* Note: the button label reads "Voice Message" but the code refers to it as the voiceRecordingButton.

## Checklist

-   [X] Tests written for new code (and old code if feasible)
-   [X] Linter and other CI checks pass
-   [X] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Type: enhancement

---
Here's what your changelog entry will look like:

## ✨ Features
 * Make the "Voice message" button in the message composer configurable ([\#11603](https://github.com/matrix-org/matrix-react-sdk/pull/11603)). Contributed by @grantm.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
Looks sane to me

**Comment by robintown** [comment]
@grantm You have a failing snapshot test that needs updating before this can be merged

**Comment by grantm** [comment]
> @grantm You have a failing snapshot test that needs updating before this can be merged

I've just pushed a commit to fix that snapshot test.

The next issue will likely be a merge failure due to other changes in `src/i18n/strings/en_EN.json`. What's the preferred way to deal with rebasing a patch? Can I rebase, resolve and force push to my PR?

**Comment by t3chguy** [comment]
force pushing will discard review so please avoid it. We squash merge so don't worry about it.

**Comment by grantm** [comment]
Is there anything further I need to do on this one?

I seem to recall there was quite a spate of flakey tests blocking it.  I now have a set up where I can run the Cypress tests and I see the following three test failing consistently as of today:

- `crypto/crypto.spec.ts`
- `presence/presence.spec.ts`
- `read-receipts/redactions.spec.ts`

The failures don't seem to be related my change and the same tests fail in the same way on develop without my changes.

**Comment by t3chguy** [comment]
It looks like the code coverage for the change is not sufficient for it to pass the gate

**Comment by grantm** [comment]
OK, thanks. I'll take a look.

**Comment by t3chguy** [comment]
@grantm hey any update on this?

**Comment by grantm** [comment]
I haven't forgotten about this, but it's a "work thing" and I've had other work priorities. Since so much has changed with the tests since I originally did this, I wondered if starting fresh might be easiest.

**Comment by MidhunSureshR** [comment]
Closing because of the reasons mentioned in https://github.com/matrix-org/matrix-react-sdk/pull/11603#issuecomment-2257085885

**Pull request closed without merging**
