### PR TITLE
Track actual window location origin and hash

### PR DESCRIPTION
**Pull request by lukebarnard1**

### CODE REVIEW

**Comment by lukebarnard1** [comment]
I think the decision was indeed to report origins even though they might not be ours. Piwik is a configuration option anyway.

But you're absolutely right that this neglects the path, I shall fix that.

**Comment by dbkr** [comment]
Ftr, if we do report origins, we should add it to https://github.com/matrix-org/matrix-react-sdk/blob/master/src/Analytics.js#L200

**Comment by lukebarnard1** [comment]
OK, having spoken with @lampholder on this, we're going to go for:
 - Opt-in analytics, i.e. not reporting to piwik.riot.im by default
 - Reporting the true origin

This way we can configure the deploys we care about (like riot.im) to send analytics whilst not upsetting deployers about leaking their domains.

If other riot deploys want to share their analytics with us, they can but we will also filter on the piwik side using a segment restricted to the domain we care about.

**Comment by dbkr** [comment]
OK, but you'll need to update the list of info we send as per above.

**Comment by lukebarnard1** [comment]
oh right, yep

**Comment by dbkr** [comment]
Giving back to you in case you need to coordinate merging with piwik things

**Comment by lukebarnard1** [comment]
Turns out we do care about `/user/` vs. `/user/<redacted>` enough for us to want to change it. It would be confusing otherwise. The fix will be to special case paths that have variables in them (i.e. `/user/...`, `/group/...` and `/room/...`).

**Comment by dbkr** [comment]
re-lgtm, although also I've just noticed: did you mean PII rather than PPI? Or is there a meaning of PPI other than Payment Protection Insurance I'm unaware of?

**Comment by lukebarnard1** [comment]
*sigh*...

definitely meant to type PII

**Pull request merged**
