### PR TITLE
Use Own Profile Store for the Profile Settings

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/13093
Fixes https://github.com/vector-im/element-web/issues/9551

image

^ is the Synapse default displayname

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
can you also file an issue/PR for whatever went wrong with the placeholder avatar in your screenshot?

**Comment by t3chguy** [comment]
I have no idea what its meant to look like so looks fine to me 🙃

**Comment by turt2live** [comment]
a circle

**Comment by turt2live** [comment]
you also reviewed the PR, so I'm not buying your excuse :p  https://github.com/matrix-org/matrix-react-sdk/pull/5243

**Comment by t3chguy** [comment]
You are ignoring the fact that my memory is shorter than a fictitious length of string of any physically possible length

**Comment by t3chguy** [comment]
It was small enough that I just slid it into this one

**Review by turt2live — APPROVED** [review]

**Pull request merged**
