### PR TITLE
Indicate unread messages in tab title

### PR DESCRIPTION
**Pull request by tnt7864**
Adds an asterisk to the tab title when there are unread messages.

I find this really helpful for following conversations in the background without notifications.

|before|after|
|---|---|
|there are unread messages, and the tab title is "Element \| another room"|the tab title is "Element * \| another room"|

## Checklist

-   [x] Tests written for new code (and old code if feasible) ([I asked on #element-dev](https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$cE-N7agkatysysk7FfwnIi5XWB8DBqQpbWYcfIikYzw?via=matrix.org&via=element.io&via=envs.net))
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Indicate unread messages in tab title ([\#10096](https://github.com/matrix-org/matrix-react-sdk/pull/10096)). Contributed by @tnt7864.

### CODE REVIEW

**Review by daniellekirkwood — APPROVED** [review]

**Review by florianduros — APPROVED** [review]
Looks good to me! Thanks for you contribution!

**Comment by guilhermepiccoli** [comment]
Hi, thanks for the feature!

I'd like to ask, if possible, to have an option to opt-out from this new behavior. For me, it's been very distracting - I'd like to be able to see (any form of) notification only when I'm mentioned/highlighted, but at same time, when I open the client I can check updates by seeing the bold font on channel names.

This asterisk on tile seems like a notification that I cannot disable...

Thanks in advance!

**Comment by robintown** [comment]
@guilhermepiccoli I would encourage you to copy those thoughts into an issue in the [element-web](https://github.com/vector-im/element-web/issues) repository, where they're more likely to be noticed.

**Comment by guilhermepiccoli** [comment]
> @guilhermepiccoli I would encourage you to copy those thoughts into an issue in the [element-web](https://github.com/vector-im/element-web/issues) repository, where they're more likely to be noticed.

Thanks, it makes sense! Seems issue https://github.com/vector-im/element-web/issues/24554 took care of it heh

**Comment by kevinboulain** [comment]
Would you be open to a revert of this patch? I'm kinda new to Matrix and I was confused by the behavior introduced here. There are some examples at https://github.com/element-hq/element-web/issues/24554 but allow me to summarize the problem here to get a little bit more visibility.

I've configured the notification options of a busy room with 'Mentions & keywords' and I pin the Element tab in Firefox. It appears this patch ignores the notification options and is only concerned about unread messages, which comes in very frequently. Because it updates the tab's title, I get a semi-permanent blue-dot (https://support.mozilla.org/en-US/questions/1270061) indicating activity. So now, I don't really have a way to know whether there's activity in a room I care about (standard notification options) or whether it's background noise that I would prefer to skim through later.
To draw a comparison, I feel like the blue dot in Firefox would be like getting an Android notification on every new message (which I thankfully don't, thanks to the notification options).
So, to me, it breaks user expectations about how notifications are supposed to work.

I'm not familiar with the code but to make sure the nagging blue dot was introduced by this PR I patched my instance of Element Web:
```patch
--- i/node_modules/matrix-react-sdk/src/components/structures/MatrixChat.tsx
+++ w/node_modules/matrix-react-sdk/src/components/structures/MatrixChat.tsx
@@ -1941,8 +1941,6 @@ export default class MatrixChat extends React.PureComponent<IProps, IState> {
         }
         if (numUnreadRooms > 0) {
             this.subTitleStatus += `[${numUnreadRooms}]`;
-        } else if (notificationState.level >= NotificationLevel.Activity) {
-            this.subTitleStatus += `*`;
         }
 
         this.setPageSubtitle();
```

**Pull request merged**
