### PR TITLE
Add UI for hold functionality

### PR DESCRIPTION
**Pull request by dbkr**
UI for hold functionality

Hold video call, with avatar:
Screenshot 2020-11-26 at 14 39 33

Hold video call, no avatar:
Screenshot 2020-11-26 at 14 37 44

Hold voice call, with avatar:
Screenshot 2020-11-26 at 14 38 53

Hold voice call, no avatar:
Screenshot 2020-11-26 at 14 37 03

Call hold in PiP view:
Screenshot 2020-11-26 at 14 40 05

<del>Test build: https://dbkr.me/holdui/</del> See 'deploy preview' in the checks section at the bottom
Requires https://github.com/matrix-org/matrix-js-sdk/pull/1549

### CODE REVIEW

**Comment by t3chguy** [comment]
The square corners don't match Jitsi etc or the rest of the app IMO

**Comment by nadonomy** [comment]
@dbkr @simonkeane I have some visual requests on this:

- The pause icon looks tiny, would it benefit from being larger?
- Would benefit from more spacing/padding between elements
- Inconsistency in font weights between video/voice cals
- Inconsistency in line breaks between video/voice cals
- Is there a better CTA treatment (e.g. button with fill) which would have better legibility than text links?

Easier to jump on a call?

**Comment by dbkr** [comment]
Yeah, the pause icons did come out a bit tiny. I also worry about the visibility of that and the text if you have a very light avatar.

**Review by jryans — APPROVED** [review]

**Comment by dbkr** [comment]
Have tweaked the visuals a bit, although not sure what to do about the legibility of the text link.

Screenshot 2020-12-01 at 13 47 34

Screenshot 2020-12-01 at 13 42 03

**Comment by dbkr** [comment]
And now with 60% opacity black, rounded corners and smaller avatar:

Screenshot 2020-12-07 at 16 32 45

**Comment by dbkr** [comment]
Margins & header font size tweaked, and font bolding changed in hold text:
Screenshot 2020-12-08 at 19 29 19

**Comment by simonkeane** [comment]
This looks good to me! Thanks for all the iteration.

**Pull request merged**
