### PR TITLE
Fix forced lowercase username in login/registration flows

### PR DESCRIPTION
**Pull request by vrifox**
Lowercase doesn't make sense here (at least in German). I suggest removing it or creating a new translatable string.

Fixes https://github.com/vector-im/element-web/issues/22813
And partially even https://github.com/vector-im/element-web/issues/21820 (even thought this needs obviously more work)

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Type: defect
Signed-off-by: Vri <vrifox@vrifox.cc>

### Before
before
### After
after

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix forced lowercase username in login/registration flows ([\#9329](https://github.com/matrix-org/matrix-react-sdk/pull/9329)). Fixes vector-im/element-web#22813. Contributed by @vrifox.

### CODE REVIEW

**Review by SimonBrandner — APPROVED** [review]
LGTM, codewise though this is going to need a design review. Thank you!

**Comment by vrifox** [comment]
> LGTM, codewise though this is going to need a design review. Thank you!

Do you mean my changes/proposal or this flow in general? :)

**Comment by SimonBrandner** [comment]
> > LGTM, codewise though this is going to need a design review. Thank you!
> 
> **Never mind, I now get what you mean. ^_^**
> 
> Do you mean my changes/proposal or this flow in general? :) Or in other words: Can I do anything to assure the merging of this PR?

I mean just your changes - the design team needs to confirm that this is the behaviour we want (which I think we do). No, I don't think you can do anything atm. In case there is no activity from the design team here for a while, feel free to ping me and I can try to push the PR forward

**Comment by rufuskahler** [comment]
I agree with the proposal. I believe it's a pretty standard pattern to sentence-case Prompt Text for all input fields, even if desired values are typically not case sensitive (e.g usernames/email addresses). CC @pmaier1 in case there are particular system constraints for Log In/Reg we should be aware of here?

**Comment by pmaier1** [comment]
I agree with this as well. The input should still always be lower case then (or at least not conflict with API restrictions). I think I've seen errors during account creation caused by defaulting to upper case (but I think that was on iOS). And cross-platform consistency is also desired, of course.

**Comment by t3chguy** [comment]
> The input should still always be lower case then (or at least not conflict with API restrictions).

This will cause legacy users with mixed case usernames to be entirely unable to log in. Modern servers forbid mixed case but existing accounts are out there.

**Comment by dbkr** [comment]
To clarify, this is referring only to if we force-lowercased everything in the username field. This PR is just changing the placeholders so our conclusion is to just merge it.

**Review by dbkr — APPROVED** [review]

**Pull request merged**
