### PR TITLE
Correctly specify types for modern React contexts

### PR DESCRIPTION
**Pull request by t3chguy**
For https://github.com/vector-im/wat-internal/issues/65
Requires https://github.com/vector-im/element-web/pull/24764

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
👏  Looks great!

**Comment by t3chguy** [comment]
https://github.com/babel/babel/issues/13779 and https://github.com/microsoft/TypeScript/issues/45995 are inherently blocking this if we want to use the `declare` syntax without disabling class properties and/or constructor property shorthand.

**Comment by Johennes** [comment]
> [babel/babel#13779](https://github.com/babel/babel/issues/13779) and [microsoft/TypeScript#45995](https://github.com/microsoft/TypeScript/issues/45995) are inherently blocking this if we want to use the `declare` syntax without disabling class properties and/or constructor property shorthand.

It looks like these issues haven't seen meaningful updates since 2021. 😕

Possibly a stupid question but is there any alternative that would not make us block the React 18 update on them?

**Comment by t3chguy** [comment]
@Johennes we would either need to ditch property initialisation or typescript constructor properties as they do not play well together once you enable support for the `declare` syntax.

**Comment by Johennes** [comment]
> @Johennes we would either need to ditch class property initialization or typescript constructor properties as they do not play well together once you enable support for the `declare` syntax.

Hm, sounds like we couldn't realistically do either since both appear to be widely used? Is there a way in which we could avoid the `declare` syntax, assuming that's what's triggering the issue?

**Comment by Johennes** [comment]
> [babel/babel#13779](https://github.com/babel/babel/issues/13779) and [microsoft/TypeScript#45995](https://github.com/microsoft/TypeScript/issues/45995) are inherently blocking this if we want to use the `declare` syntax without disabling class properties and/or constructor property shorthand.

As mentioned in the chapter sync today, https://github.com/vector-im/element-web/pull/26079 may or may not help unblock this. I haven't done any explorations into that direction so far though.

**Comment by dzienisz** [comment]
Can I help somehow with this? React 18 is a must today.

**Comment by t3chguy** [comment]
@dzienisz sure if you know of a way around https://github.com/babel/babel/issues/13779 & https://github.com/microsoft/TypeScript/issues/45995 whilst allowing the use of the `declare` syntax to enable use of React 18 contexts in class components

**Comment by dzienisz** [comment]
My quick advice would be to ts-ignore it and write a comment with a link to this issue. Typescript is just a superset of JavaScript that, in my option it is to help you write a bug free code. In this case, Typescript has a bug, and it should not block you from upgrading this app.

**Comment by t3chguy** [comment]
@dzienisz even if you do that, you end with ~60+ broken tests due to changes in React & RTL. If you want to help you are more than welcome to fix the remaining ~30. https://github.com/matrix-org/matrix-react-sdk/pull/10314

**Comment by dzienisz** [comment]
Sure, I will try to run the project and jump into it, or we can meet one, and you could make me a quick into. What do you think?

**Pull request closed without merging**
