### PR TITLE
Color de-duplication #3

### PR DESCRIPTION
**Pull request by SimonBrandner**
Type: task

<hr>

Should be reviewable commit-by-commit

<hr>

This is the first of the colour de-duplication PRs that does some visible changes. They can be split into three categories:

+ Removing colours from legacy and custom themes - these changes remove colours that use some other color that should already be customizable
+ Color changes based on design - these changes change a colour to a different one because the design says so
+ Color changes based on my judgement - these changes change a colour because we have a very similar one and the color is used only in a few places and so shouldn't have a big effect and shouldn't require a design review

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

Preview: https://61574fba0c5b5013b293f0f7--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by Palid** [comment]
>     * Color changes based on my judgement - these changes change a colour because we have a very similar one and the color is used only in a few places and so shouldn't have a big effect and shouldn't require a design review

I don't really think that's a great idea without having screenshots to compare each and every case, as in some cases that may be a slight difference of the color for additional visibility, or border purposes. Going through the commits I couldn't figure out which changes are based upon your judgment, and which ones were just about normalizing things. Could you maybe help me out with this?

**Comment by SimonBrandner** [comment]
[`86d4a49` (#6674)](https://github.com/matrix-org/matrix-react-sdk/pull/6674/commits/86d4a49e10ec657393f3b325720ee7a6c8d4c1ed) still needs a check

WIP comment

ZOld1
ZNew1

<hr>

ZNew2
ZOld2

<hr>

ZOld3
ZNew3

<hr>

ZOld4
ZNew4

<hr>

ZOld5
ZNew5

**Comment by Palid** [comment]
@turt2live Can you have a quick look if we're not breaking any custom-themes related things here? Don't spend too much time on it, already figuring the general changes with Simon, but want to double-check if we won't break any of your stuff.

**Comment by turt2live** [comment]
Custom theme breakage is checked simply on whether or not the variables change from their original colours or sources.

**Comment by SimonBrandner** [comment]
Closing as some of the changes from here were cherry-picked to other PRs and the rest will follow

**Pull request closed without merging**
