### PR TITLE
Fix Incorrect message scaling for verification request

### PR DESCRIPTION
**Pull request by capGoblin**
Fixes https://github.com/vector-im/element-web/issues/24304

This pull request addresses the issue verification request message scaled vertically when information side panel is opened.

Changes Made:
- added `min-inline-size` property to `.mx_EventTileBubble_title, .mx_EventTileBubble_subtitle` classes.

Let me know any changes to be made.

Before:
214179700-30975d30-96f7-4af4-9e35-b64f0a9c31c3

After:

https://github.com/matrix-org/matrix-react-sdk/assets/78524377/eecafb1c-eb1f-4e3e-9071-d3078625e5b1

Signed-off-by: dharshan [dharshan2457@gmail.com](mailto:dharshan2457@gmail.com)

## Checklist
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

<br>
Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix Incorrect message scaling for verification request ([\#11793](https://github.com/matrix-org/matrix-react-sdk/pull/11793)). Fixes vector-im/element-web#24304. Contributed by @capGoblin.

### CODE REVIEW

**Review by weeman1337 — CHANGES_REQUESTED** [review]
Thank you for working on this @capGoblin 

I don't know if it is a solution to limit the min width of only the verification text and let the rest of the timeline scale like before :neutral_face: Also I can see in the preview that the verification text does now overflow the background of the message. If you limit the message with can you do this on the surrounding element, so that the text has the background?

**Comment by nadonomy** [comment]
> I don't know if it is a solution to limit the min width of only the verification text and let the rest of the timeline scale like before 😐

It'll feel arbitrary that one component is behaving differently, but we can polish the rest when we do broader component housekeeping.

**Comment by capGoblin** [comment]
Here's how it looks now:


https://github.com/matrix-org/matrix-react-sdk/assets/78524377/3dc8f562-d574-4c3a-8018-cec41ea921da

**Review by weeman1337 — APPROVED** [review]
Thanks !

**Pull request merged**
