### PR TITLE
Revert " make click to insert nick work on join/parts, /me's etc"

### PR DESCRIPTION
**Pull request by t3chguy**
Reverts matrix-org/matrix-react-sdk#1945

Fixes https://github.com/vector-im/riot-web/issues/6967

### CODE REVIEW

**Comment by t3chguy** [comment]
This issue requires a refactor of the code to be able to generate both Textual and Richer (Element) representations of events.

**Comment by dbkr** [comment]
Would be good to understand what's gone wrong here and how this has ended up changing the events that get generated.

**Comment by lukebarnard1** [comment]
This also reverts a lot of translations that were done for the PR. Losing those would be a pain for translators as they'd have to re-translate. Can we keep them in?

**Comment by dbkr** [comment]
oops, sorry luke. I Think all the translation changes were michael's script though.

**Comment by t3chguy** [comment]
@lukebarnard1 the only i18n changes I see are the ones I made using my script (replacing `%(...)s` with `<...>`)

**Comment by t3chguy** [comment]
> Would be good to understand what's gone wrong here and how this has ended up changing the events that get generated.

things using TextForEvent rightly assume it returns strings, but by throwing JSX in there it ended up spitting back React Elements so now things started printing it as `[Object object]` instead

**Comment by dbkr** [comment]
ah right

**Comment by t3chguy** [comment]
this'll need more thought and a way of either getting a Textual Representation or a richer React Element one

**Pull request merged**
