### PR TITLE
Ignore media actions

### PR DESCRIPTION
**Pull request by dbkr**
Hopefully the comment explains all

Fixes https://github.com/vector-im/riot-web/issues/11118

### CODE REVIEW

**Comment by turt2live** [comment]
can we not just opt to do nothing? It would be weird to me if I'm trying to change songs in $music_player but instead the key is trapped by Riot.

**Comment by dbkr** [comment]
Yeah, I would think that would be better, but I can't see any way to say, "I am not interested in these events".

**Comment by turt2live** [comment]
not sure if it'll actually do anything, but the html spec supports `controls="false"` on the `<audio>` element. It might just hide the controls rather than disable them though.

**Comment by dbkr** [comment]
This definitely works without `controls` since spotify etc. don't use the native audio element controls but work with the media keys.

**Pull request merged**
