### PR TITLE
Release message right-click context menu out of labs

### PR DESCRIPTION
**Pull request by SimonBrandner**
To merge with https://github.com/vector-im/element-web/pull/22228

---
Here's what your changelog entry will look like:

## ✨ Features
 * Release message right-click context menu out of labs ([\#8613](https://github.com/matrix-org/matrix-react-sdk/pull/8613)).

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
code lgtm

**Comment by kittykat** [comment]
@SimonBrandner do you know what testing has happened for this feature? I've asked @frakic to include it in our community testing for this week

**Comment by SimonBrandner** [comment]
> @SimonBrandner do you know what testing has happened for this feature? 

There hasn't been any testing yet

> I've asked @frakic to include it in our community testing for this week

Thank you!

**Comment by frakic** [comment]
Two issues were found during the Community session. I'll post them here for history:
https://github.com/vector-im/element-web/issues/22279
https://github.com/vector-im/element-web/issues/22282

**Comment by SimonBrandner** [comment]
> Two issues were found during the Community session. I'll post them here for history: [vector-im/element-web#22279](https://github.com/vector-im/element-web/issues/22279) [vector-im/element-web#22282](https://github.com/vector-im/element-web/issues/22282)

Both are fixed now

**Review by kittykat — APPROVED** [review]
Happy for this to be merged after #9200

**Pull request merged**
