### PR TITLE
Warn when you attempt to leave room that you are the only member of

### PR DESCRIPTION
**Pull request by aaronraimist**

### CODE REVIEW

**Comment by nadonomy** [comment]
@aaronraimist what's the rationale for this warning? If my goal is to leave a room I just want to leave with little friction.

Are there any github issues indicating it's been a high impacting issue? As we haven't had much feedback through other channels on this.

**Comment by aaronraimist** [comment]
@nadonomy I agree that less friction is better but the problem is if you are the last member to leave then the room becomes unusable, you can never rejoin it. This is a bit of a wart of Matrix that people coming from other platforms do not expect.

This issue of people fat fingering the leave button and then getting stuck outside of a room and losing their alias is a fairly common problem in the support rooms. Eventually Synapse should delete rooms when the last member leaves but that hasn't happened yet. Even once that is implemented I think it would be a good idea to keep this warning and just change the wording to indicate the room will be deleted.

This problem is related to issues like:

https://github.com/vector-im/element-web/issues/2855 
https://github.com/vector-im/element-web/issues/3194
https://github.com/vector-im/element-web/issues/13613
https://github.com/vector-im/element-web/issues/722#issuecomment-630953050

but doesn't exactly fix any of them.

**Comment by aaronraimist** [comment]
Also just to note, this doesn't add an extra dialog box or anything. The dialog box already exists.

All it does it change it from looking like:


to:

**Review by jryans — APPROVED** [review]
Thanks, code wise I believe this looks good. 😄 I'll nudge Design as well to take another look.

**Comment by niquewoodhouse** [comment]
Reviewing on behalf of design team, apologise for the delay @aaronraimist 

Just a couple of small things detailed below.  I think this is a really smart iteration that just gives users a bit more information to help them decide what to do.

- The copy could be simplified to be more easily understandable and room agnostic: 
   -  `You are the only person here.  If you leave, no one will be able to join in the future, including you.` ~You are the only member of this room. This room will become unjoinable if you leave~. Removing 'the room' means we could potentially use this copy, once it's translated, in various areas where leaving a thing isn't just room specific.
- The leave button should be green instead of red 
   - the contrast will make some users question if they're doing the right thing, which I understand is part of the point, but it will lead to more double-guessing by users, and ultimately more people being in rooms they don't want to be in anymore, leading to a worse experience for them.
   - it will be consistent with other leave room dialogs that don't have a red button (eg leaving a private room)

image


Thank you for this improvement.

**Comment by aaronraimist** [comment]
No problem. Thanks for the review, I think that all makes sense. I have made those changes.

Screenshot of updated dialog

**Review by niquewoodhouse — APPROVED** [review]

**Comment by t3chguy** [comment]
Already has code & design review, I just sorted the lint

**Pull request merged**
