### PR TITLE
Rename PostCSS files to `.pcss`

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/22730
Fixes https://github.com/vector-im/element-web/issues/16429

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by gsouquet — COMMENTED** [review]
I don't think I've ever encountered a `pcss` file extension. 
I can see the [PostCSS team advocating for this](https://twitter.com/postcss/status/661645290622083073) in a tweet, but that really does not sit well with me as PostCSS is supposed to ingest CSS.

The broad majority of the defined mixins we have could instead be another CSS class. I would much rather see use move to use a `.css` extension and start using vanilla CSS. 

There are currently 3 features we use that are non vanilla (mixins, nested selectors and variables). We can achieve those in vanilla CSS and get PostCSS to transpile that to an output that will work with our target browsers.

**Comment by t3chguy** [comment]
> I can see the [PostCSS team advocating for this](https://twitter.com/postcss/status/661645290622083073) in a tweet, but that really does not sit well with me as PostCSS is supposed to ingest CSS.

It is also the extension many tools use to identify PostCSS syntax files, including Jetbrains IDEs and seemingly SonarQube.

> The broad majority of the defined mixins we have could instead be another CSS class. I would much rather see use move to use a .css extension and start using vanilla CSS.

That is an entirely separate issue, it also requires us to rework entirely how our themes work, into css runtime vars, which don't support adding a transparency using utility commands like rgba

> There are currently 3 features we use that are non vanilla (mixins, nested selectors and variables). We can achieve those in vanilla CSS and get PostCSS to transpile that to an output that will work with our target browsers.

Yup, separate issue.

This PR just fixes us lying to things saying we write SASS when we in fact don't.

**Comment by t3chguy** [comment]
image

^ is the full list of postcss plugins we use ftr

**Comment by gsouquet** [comment]
Sure I understand that this is quite a much larger change, but if the issue is really just to write new mixins, then I would like to challenge their usefulness in the first place.
I have not yet encountered a place in our codebase where they brought significant value in my opinion.

I'd much rather stay in the current situation, not write new mixins (and start to remove the ones that exist in the platform) to start the transition to a more vanilla CSS codebase... where we align over time the things we use with the CSS feature set.

**Comment by t3chguy** [comment]
@gsouquet this is also a prerequisite for https://github.com/vector-im/element-web/issues/10544 which whilst only talking about mixins is actually of wider scope of our linter having holes due to it not matching the actual configuration we build the styles with.

**Comment by t3chguy** [comment]
Its also important for contributors who may be confused by the scss extension and then look up sass docs and expect the utilities and syntaxes there to work verbatim.

**Comment by t3chguy** [comment]
> not write new mixins 

This is also not agreed to as I understand it, the code style doc says to make use of PostCSS mixins - https://github.com/vector-im/element-meta/pull/216/files#r852734110

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/21656

**Comment by gsouquet** [comment]
I have commented on the code style PR.

I also agree with the `scss` argument, but the same applies to the `pcss` extension that is very very uncommon in the front-end realm. I'm not going to block this moving forward, but I'm not sure this solves more problems than it will create

**Comment by gsouquet** [comment]
> We should take the discussion about not using PostCSS elsewhere. I Have strong opinions about the minimums for what a CSS system does for us, but am generally not concerned with the finer details within.

I'm not advocating to remove PostCSS. This is a very useful tool, just like babel is for JavaScript, and we should keep using it. However we should remove all plugins that use non standards CSS syntax (mixins, inline comments, ...) as they conflict with the linter and forces us to do very unconventional things in a codebase like what is happening here

**Pull request merged**
