### PR TITLE
Circular MessageActionBar buttons

### PR DESCRIPTION
**Pull request by resynth1943**
As discussed (and proposed) in the [Element Design](https://matrix.to/#/!zzGPdcyFqxIOJEijoI:matrix.org?via=matrix.org&via=privacytools.io&via=mozilla.org) room, I have made the action bar buttons circular!

I have also *slightly* increased the border of the action buttons, so it's a little easier to differentiate between them and the background.

I think this design looks a little more modern.
See screenshots below.

## Light Mode

image

image

## Dark Mode

image

image

### CODE REVIEW

**Comment by resynth1943** [comment]
(I fixed the background behind the buttons in dark mode.) Anything else I've missed?

**Comment by aaronraimist** [comment]
Personally I prefer the existing buttons but that could just be me. If it was going to switch to these circular buttons I think it would look better if the bottom lip of the circle didn't go on top of images. It looks misaligned.

**Comment by resynth1943** [comment]
Hmm, so that would mean *slightly* more space for the circular buttons. I'll implement it and see what it looks like.

**Comment by resynth1943** [comment]
## Before

image

## After

image

**Comment by resynth1943** [comment]
I honestly prefer no spacing.

**Comment by resynth1943** [comment]
image

image

My one issue with the buttons is that they're a little big. Working on reducing them a little.

**Comment by resynth1943** [comment]
# Smaller Buttons; Standoff Padding

image

**Comment by resynth1943** [comment]
# Embed Into Messages

image

As proposed by @aaronraimist. Thoughts?

**Comment by resynth1943** [comment]
# Current Design

image

image

**Review by nadonomy — CHANGES_REQUESTED** [review]
Hi @resynth1943— thanks for the contribution, but we won't merge this in to master as the changes aren't cohesive with the rest of the visual language of the app. Obviously feel free to use these as custom CSS on your side though!

**Comment by turt2live** [comment]
(closing due to Nad's comment)

**Pull request closed without merging**
