### PR TITLE
Add greentext command

### PR DESCRIPTION
**Pull request by dali99**
A command to create imageboardlike greentexts

2021-04-08-135145_162x88_scrot
2021-04-08-135154_166x78_scrot

### CODE REVIEW

**Comment by turt2live** [comment]
We have [previously rejected](https://github.com/matrix-org/matrix-react-sdk/pull/4561) this change and will not be considering it for inclusion. More details are here: https://github.com/matrix-org/matrix-react-sdk/pull/4561#issuecomment-638219805

**Comment by dali99** [comment]
ah, thanks no worries, I'll just maintain it in a custom fork in that case

**Comment by TheStranjer** [comment]
Just noticed this. The good thing about FOSS is that you can just edit your version however you like. I still use my greentext branch on my instance of Element and it works with everybody else's clients, so I can't complain.

**Comment by tatsumoto-ren** [comment]
There is really nothing that prevents this PR from being merged considering that we already have rainbow text and other slash-commands that aren't used very often (if used at all). So you can't really say, "we don't want this because it's too niche."

screenshot-2022-01-18-15-18-48

I really only see people use rainbow text when they find out about it the first time. They test it once and never try it again.

#4561 was rejected because of "Overriding the commonmark spec". However, this PR doesn't have the problem.

Nad also mentioned, "you can always run your own fork of Riot." If this isn't merged, it would be really nice to at least have instructions on how to build `element-web` yourself. Currently such instructions don't exist (I spent two days trying to find them before posting this comment).

**Comment by t3chguy** [comment]
> I really only see people use rainbow text when they find out about it the first time. They test it once and never try it again.

I use it fairly frequently in DMs, so you won't be seeing me use it

**Comment by TheStranjer** [comment]
@tatsumoto-ren If you're interested in building greentext locally, you can use my branch: https://github.com/TheStranjer/matrix-react-sdk/tree/greentext

Interestingly, because the HTML is processed locally, even if nobody else has my branch when you use it, it will come out as greentext -- with the right shade of green -- for everybody else in the channel.

**Pull request closed without merging**
