### PR TITLE
Redirect paste to composer when event target can't receive input

### PR DESCRIPTION
**Pull request by bwindels**
To match shifting focus when starting to type from https://github.com/matrix-org/matrix-react-sdk/pull/3224

### CODE REVIEW

**Comment by bwindels** [comment]
> Is the magic here passing `true` to the dispatch so that the focusing happens synchronously and therefore the newly focused composer catches the same paste event as it bubbles down? Either way it could use a comment as it's not obvious why for keyboard input we need to catch keydown specifically to get the event before whereas here we can catchup the same paste event and it's fine.

Yeah, the synchronous dispatch is essential. Will add a comment.

**Comment by bwindels** [comment]
> Is the magic here passing `true` to the dispatch so that the focusing happens synchronously and therefore the newly focused composer catches the same paste event as it bubbles down?

Oh, you mean if the handler listens during the capture phase? No, we listen during the bubble phase at the highest DOM node (`<div className="mx_MatrixChat_wrapper">`). So handling the event at the right moment is not what makes this work. It's just that empirically I found that refocusing during a paste event will paste in the newly focused element.

**Comment by bwindels** [comment]
Added comments trying to clarify how this works.

**Comment by dbkr** [comment]
ah, gotcha. lgtm.

**Pull request merged**
