### PR TITLE
Redirect from /#/welcome to /#/home if already logged in

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/element-web/issues/18990

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Redirect from /#/welcome to /#/home if already logged in ([\#6786](https://github.com/matrix-org/matrix-react-sdk/pull/6786)). Fixes vector-im/element-web#18990. Contributed by [aaronraimist](https://github.com/aaronraimist).

Preview: https://613cd1c2973b72aa1f1b5709--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by novocaine** [comment]
Added design as a reviewer as this is a behaviour change

**Review by t3chguy — APPROVED** [review]
LGTM code-wise

**Review by janogarcia — COMMENTED** [review]
Agree, this should be the expected behavior for those users that already signed in, as long as we don't add support for signing in to multiple accounts with the same client, which is not the case as far as I'm aware. 👍 I'd approve it myself right away, but would like to double check with @nadonomy first in case such a feature is in the works (as part of the Spaces release).

**Review by janogarcia — APPROVED** [review]
In any case, this should be the behavior for the current implementation / feature set. I'm approving it.

**Pull request merged**
