### PR TITLE
Use the room avatar as a placeholder in calls

### PR DESCRIPTION
**Pull request by dbkr**
Rather than the image for the user we're in a call with. This makes it work correctly with virtual rooms easily since we'll get the avatar for the correct room.

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Use the room avatar as a placeholder in calls ([\#10231](https://github.com/matrix-org/matrix-react-sdk/pull/10231)).

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]
Looks good!

**Comment by dbkr** [comment]
Are folks happy for me to bypass the codecov on this one? I've added a unit test for VideoFeed, but its complaints are now that there are changes in LegacyCallView which doesn't have tests and one uncovered nullish coalese condition I had to add to fix Typescript errors.

**Comment by t3chguy** [comment]
@dbkr looks like Sonar is having issues right now, no time better to take advantage of that and bypass it :P

**Comment by dbkr** [comment]
Thanks :)

**Pull request merged**
