### PR TITLE
Added TextInputWithCheckbox dialog

### PR DESCRIPTION
**Pull request by psaavedra**
This change allows change the default value for `m.federate` value during the create action. Useful for enviroments where you prefer `m.federate = False` as `default` choice for the created rooms (see related PR).

~This PR is embraces the following SPEC: https://docs.google.com/document/d/14zqsbwl5KKil-bB8w2HMhidBVmFkP9Q7EQKFwKIIfZc/edit#heading=h.eipip5qhqo0d~

~Other PR in synapse and matrix-js-sdk and riot-web are envolved~

Signed-off-by: Pablo Saavedra <psaavedra@igalia.com>

Related PR: 
* https://github.com/vector-im/riot-web/pull/3849

Edited by Michael to match what the PR actually entails rather than the entire movement that it began as

### CODE REVIEW

**Comment by aperezdc** [comment]
It's going to be great for people running their own home servers to have this setting available in the UI :muscle: 

One suggestion/idea: Probably it would make sense to also add an element in the room settings panel which shows the status of the `m.federate` flag as part of this set of PRs (I am not sure whether that would go here or as part of vector-im/riot-web#3849 though). Without something like that there is no way of knowing whether a room was created as federatable or not without checking with the HTTP API manually, right?

**Comment by psaavedra** [comment]
Yes,  you are right. In fact both PR are part of the same feature.

**Comment by t3chguy** [comment]
would fix https://github.com/vector-im/riot-web/issues/1669

**Comment by t3chguy** [comment]
@aperezdc riot-web Room Settings already shows a message if `m.federate=false`

**Comment by t3chguy** [comment]
From conversation in riot-dev, needs  an `Advanced Settings` accordion/spoiler thing

**Comment by t3chguy** [comment]
I'm thinking that the **advanced** option should mention m.federate explicitly as its wording is somewhat ambiguous

**Comment by ara4n** [comment]
sorry that this has been stuck for so long, and huge thanks for submitting it (and @t3chguy for pushing it through).  part of the stuckness has been due to confusion on whether this actually means to check the synapse API or not (and whether that API shape is okay).  However, given it just goes off the riot config for now, the concern was confused.

However, the tests are failing due to:
```
/home/travis/build/matrix-org/matrix-react-sdk/src/components/views/dialogs/CreateRoomDialog.js
  51:53   error  A space is required after '{'               react/jsx-curly-spacing
  51:80   error  A space is required before '}'              react/jsx-curly-spacing
  54:154  error  A space is required before closing bracket  react/jsx-tag-spacing
  56:24   error  A space is required before closing bracket  react/jsx-tag-spacing
  61:120  error  A space is required before closing bracket  react/jsx-tag-spacing
  63:33   error  A space is required after '{'               react/jsx-curly-spacing
  63:102  error  A space is required before '}'              react/jsx-curly-spacing
  64:36   error  A space is required before closing bracket  react/jsx-tag-spacing
  65:34   error  A space is required after '{'               react/jsx-curly-spacing
  65:78   error  A space is required before '}'              react/jsx-curly-spacing
```
If fixed, i'll merge. thanks again.

**Comment by aperezdc** [comment]
One more data point supporting the merge of this PR: Our self hosted Riot instance has had this patch set since applied to it by @psaavedra to all Riot releases since last May, and it has been working well. That is a few months of testing :wink:

**Comment by t3chguy** [comment]
@ara4n PTAL

**Comment by lukebarnard1** [comment]
LGTM

**Pull request merged**
