### PR TITLE
Comply with new member-delimiter-style rule

### PR DESCRIPTION
**Pull request by dbkr**
Just `eslint --fix` with rule from
https://github.com/matrix-org/eslint-plugin-matrix-org/pull/9 in place

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
This PR might want to hold off on https://github.com/matrix-org/eslint-plugin-matrix-org/pull/9 and also include the update in yarn.lock

**Comment by dbkr** [comment]
Problem is if we merge the new rule first, everything will start failing CI. We can merge & the worst that will happen is the rule won't be enforced - we can bump yarn.lock separately if we want to.

**Comment by t3chguy** [comment]
> Problem is if we merge the new rule first, everything will start failing CI.

It ought not to given the presence of `yarn.lock`

**Comment by dbkr** [comment]
Hmm - in theory I guess yes - we could try & see if it explodes...

**Pull request merged**
