### PR TITLE
Improve tooltip positioning

### PR DESCRIPTION
**Pull request by weeman1337**
I actually wanted to fix the tooltip of the „decryption issue“ message.  
After spending some time on this I found that tooltips can be improved in other places as well.

This PR partially refactors tooltips. Worth mentioning:
- Left/right tooltips are now vertically centre aligned to their parent
- Removed `yOffset`

❗Notes
- I've tested all tooltips I can find. If you know a hidden or special one just leave a comment.
- Like mentioned above the left/right tooltips changed (top vs centre aligned).
This is just a suggestion. But so far in my opinion this improves the tooltips.

The changes are improving the tooltip positioning in many places, for example:

| Where | Before | After |
| --- | --- | --- |
| call buttons | image <br> (tooltip appears above another button) | image |
| search button | image <br>(unaligned) | image |
| „decryption issue“ | image <br> (cut off) | image |
| spaces buttons | image <br> (tooltip appears above another button) | image |

Notes: Tooltip positioning has been improved

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Tooltip positioning has been improved ([\#8219](https://github.com/matrix-org/matrix-react-sdk/pull/8219)). Contributed by @weeman1337.

Preview: https://pr8219--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — COMMENTED** [review]
I think this requires design review before code review is a reasonable course of action, to verify the tooltip behaviour and expectations for at least the sample cases in the PR description.

**Review by gaelledel — APPROVED** [review]
lgtm!

**Comment by t3chguy** [comment]
@weeman1337 can you fix the merge conflicts so that it can be reviewed, thanks!

**Review by robintown — COMMENTED** [review]
No questions otherwise, this is a great improvement!

**Review by robintown — APPROVED** [review]
Looks good now, but for future reference, please avoid force pushing after review since it makes it more difficult to determine what's changed

**Pull request merged**
