### PR TITLE
Make `CallHandler` more `EventEmitter`y

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/18812
Type: task

<hr>

For the reviewer: please review carefully as this could lead to regressions. Also, this should be reviewable commit-by-commit

<hr>

This is more TypeScript friendly since it's easier to type than the dispatcher actions. It's easier to read, imo and quite a bit shorter. It should also theoretically be better for performance but it's not like that would be noticeable :D 

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

Preview: https://61a0f0ec203e4619c6da8a42--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
This looks fine, though I believe there's some hidden requirements for stuff in this area so going to ask for a second opinion review. 

Thanks for taking a look at this! Down with the dispatcher!

**Comment by SimonBrandner** [comment]
@turt2live, let me know if there is someone I can talk to about this, in case there are some internal requirements

**Review by turt2live — APPROVED** [review]

**Comment by dbkr** [comment]
While I'm not necessarily saying the dispatcher is the best thing, it's still nominally our way of handling actions from the user, so is there a reason to call the methods directly for thing like placing / answering / hanging up calls rather than go via the dispatcher?

alsoa cc @robertlong as this is probably going to cause conflicts with your stuff

**Comment by SimonBrandner** [comment]
> While I'm not necessarily saying the dispatcher is the best thing, it's still nominally our way of handling actions from the user, so is there a reason to call the methods directly for thing like placing / answering / hanging up calls rather than go via the dispatcher?

As I said in the description:

> This is more TypeScript friendly since it's easier to type than the dispatcher actions. It's easier to read, imo and quite a bit shorter. It should also theoretically be better for performance but it's not like that would be noticeable :D

I generally find this much easier to work with, navigating the dispatches just feels much harder and this feels much cleaner. It also cuts down the number of lines

**Comment by SimonBrandner** [comment]
I see this a bit from the other perspective, why would you want to use the dispatcher for this :p

**Comment by dbkr** [comment]
OK, but I think this is something we need to coordinate on across the app. I'm not really a fan of the dispatcher either, but if we're going to stop using it we should decide to do so in general rather than have some bits of the app using it and some not.

**Comment by SimonBrandner** [comment]
> OK, but I think this is something we need to coordinate on across the app. I'm not really a fan of the dispatcher either, but if we're going to stop using it we should decide to do so in general rather than have some bits of the app using it and some not.

I definitely agree though I would say we already are in a state where parts of the app use and other parts don't...

Is there anything I can do to help this..?

**Comment by dbkr** [comment]
I'll ask around & see what people think

**Comment by SimonBrandner** [comment]
> I'll ask around & see what people think

Thank you!

**Comment by dbkr** [comment]
Well, nobody seemed to object to going this way so let's do it. Let's merge this post RC.

**Pull request merged**
