### PR TITLE
Expose apps/widgets

### PR DESCRIPTION
**Pull request by charlynguyen**
This PR exposes the apps/widgets of a room via `ProxiedModuleApi`. It allows to:

- `getApps` – Gets the apps for a given room.
- `getAppAvatarUrl` – Gets the avatar URL for an app.
- `isAppInContainer` – Checks if an app is in a container for a given room.
- `moveAppToContainer` – Moves apps to containers for a given room.

~~Is blocked by https://github.com/matrix-org/matrix-react-sdk-module-api/pull/30.~~

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Expose apps/widgets ([\#12071](https://github.com/matrix-org/matrix-react-sdk/pull/12071)). Contributed by @charlynguyen.

### CODE REVIEW

**Comment by charlynguyen** [comment]
@t3chguy @robintown friendly reminder 🤗

**Comment by t3chguy** [comment]
@charlynguyen it isn't passing CI.

**Comment by charlynguyen** [comment]
@t3chguy I merge develop into this branch and the CI for E2E Tests fail with `yarn playwright install`. What do I miss?

**Comment by t3chguy** [comment]
@charlynguyen its a caching issue with github actions, I purged the cache, now it is fine

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
