### PR TITLE
Use minimist instead of optimist as it is deprecated

### PR DESCRIPTION
**Pull request by t3chguy**
react-sdk exposes the `reskindex` script as a "bin" so its available to any projects which depend on it and thus its dependencies should be in `dependencies` which they are not (optimist), instead of adding it, use minimist which we already depend on and use for all our other scripts.

Smells like it could resolve https://github.com/vector-im/riot-web/issues/11851#issuecomment-579228605

### CODE REVIEW

**Comment by turt2live** [comment]
Why are we spending time maintaining a script we plan to `rm`?

**Comment by t3chguy** [comment]
> Hmm, shouldn't there be some package.json / yarn.lock changes as well...?

package.json already lists minimist, we never relied on optimist, it is a transitive dev-dep from jest though

**Comment by t3chguy** [comment]
> Why are we spending time maintaining a script we plan to rm?

in case we don't get around to `rm`'ing it in time for next release

**Comment by jryans** [comment]
Hmm, wouldn't anything that's used by our `bin` scripts need to be direct, regular dep (not a dev dep, and not transitive) to do things by the book?

**Comment by t3chguy** [comment]
> Hmm, wouldn't anything that's used by our bin scripts need to be direct, regular dep (not a dev dep, and not transitive) to do things by the book?

Exactly, minimist is a direct, regular dep
optimist (what the script used) was not a dep at all, it was a transitive dep of our dev-dep

**Comment by jryans** [comment]
> Exactly, minimist is a direct, regular dep

But it should be listed in package.json then...? I don't see it, but maybe I am being daft or looking at the wrong thing...

**Comment by t3chguy** [comment]
Dammit, my bad, I was looking in the wrong package.json, its in riot-web's dependencies

**Pull request merged**
