### PR TITLE
Change wording of debug log submission

### PR DESCRIPTION
**Pull request by lukebarnard1**
Fixes https://github.com/vector-im/riot-web/issues/5985

### CODE REVIEW

**Comment by lukebarnard1** [comment]
2018-02-08-181300_236x153_scrot

2018-02-08-181215_267x153_scrot

Thoughts on ^ appreciated.

**Comment by uhoreg** [comment]
Instead of just "Want to send logs?", it should say something about what logs are, and why someone would want to send logs.  Maybe something along the lines of: "If you've found a bug, debug logs can help us track down the problem.  Debug logs do not contain any of your messages, but will include your username, ..."

**Comment by lukebarnard1** [comment]
I think we should focus on the original remit, which was to encourage people to submit an issue on GitHub if they want to report a bug, so I would opt for something more like (building on @uhoreg's proposal): 

>If you've [submitted a bug via GitHub](link), debug logs can help us track down the problem. Debug logs contain your username, the IDs or aliases of the rooms or groups you visit, usernames of other users and other information. They do not contain messages.

**Comment by lampholder** [comment]
@lukebarnard1 - I like that wording.

Will we still give users a box to type additional comments when they click 'submit debug logs'? What about an optional field to include a reference to the github issue they've (hopefully) filed?

**Comment by turt2live** [comment]
wrt the url field, it might be worth it to make it appear required (ie no text saying "required" or "optional") but treat it as optional behind the scenes.

**Comment by lukebarnard1** [comment]
@lampholder I think for those who don't use GH or who'd prefer not to, it's still useful to have the comment box. I like the idea of optional GH URL inserting - under the hood we can append it to the description.

We should also consider adjusting the wording in the dialog box itself, as it is geared towards sending a bug report:
2018-02-15-112133_793x492_scrot

**Comment by lampholder** [comment]
I'd like to refine the wording to read:
```
If you've submitted a bug via GitHub, debug logs can help us track down the problem.
Debug logs contain application usage data including your username, the IDs or aliases 
of the rooms or groups you have visited and the usernames of other users. They do not
contain messages.
```

How about the modal looking something like:

```
# Submit debug logs

Debug logs contain application usage data including your username, the IDs or aliases
of the rooms or groups you have visited and the usernames of other users. They do not 
contain messages.

Github issue link: [_https://github.com/vector-im/riot-web/issues/1337____]
            Notes: [______________________________________________________]
                   [______________________________________________________]

[Send Logs]   [Cancel]
```

As @turt2live says, the additional fields can be optional. Styling the issue link field with a placeholder URL should encourage people to fill it in, and hopefully the 'notes' field is sufficiently vague that people who've filed a github issue will ignore it (and only the desperate will fill it in).

I've repeated the 'debug logs contain...' segment because I think it's important people know exactly what they're doing :) 

I think this whole section could be further improved by making reference to where and how the logs are stored, who will have access to them, and how long they will be kept, but I'd suggest we just get version out and then iterate.

**Comment by lukebarnard1** [comment]
FTR, I'll push changes to the dialog in another PR because it's in vector-web.

**Pull request merged**
