### PR TITLE
Include non-matching DMs in Spotlight recent conversations when the DM's userId is part of the search API results

### PR DESCRIPTION
**Pull request by mgcm**
This PR continues the work started in #9556 and #11290 and fixes a couple of issues associated with how search results are filtered and handled in the Spotlight search dialog.

Specifically, it handles the situation when there is no match in the search term query to existing DMs but the user search directory results includes a userId that does have an existing DM with the user. With this change, the DM rooms will appear as items in the "Recent Conversations" section at the top of the results.

The PR also changes how users are sorted in the "Suggestions" section when there is no significant activity between them. This assumes that the server is already sorting users by some relevant property, as per [the spec](https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3user_directorysearch) which states "results: Ordered by rank and then whether or not profile info is available".

## Checklist

-   [X] Tests written for new code (and old code if feasible)
-   [X] Linter and other CI checks pass
-   [X] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Signed-off-by: Milton Moura <miltonmoura@gmail.com>

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Include non-matching DMs in Spotlight recent conversations when the DM's userId is part of the search API results ([\#11374](https://github.com/matrix-org/matrix-react-sdk/pull/11374)). Contributed by @mgcm.

### CODE REVIEW

**Review by dbkr — COMMENTED** [review]
I'm not sure I understand this. You're talking about the user directory but I don't see that being used here? It's just referring to the list of DMs. Also, I can't reproduce the bug I think you're implying, in that if I search for a someone's user ID (where their user ID is different from their display name), the DM room with them appears in my spotlight search results.

**Comment by mgcm** [comment]
> I'm not sure I understand this. You're talking about the user directory but I don't see that being used here? It's just referring to the list of DMs.

The Spotlight People results are built from the list of users that you have a DM with, the list of users that are in other rooms with you and the list of users returned from the user directory search API, filtered by the search terms that are used.

The proposed change affects the final results list by not excluding DM users that might not match the terms but are included in the possible result list.

> Also, I can't reproduce the bug I think you're implying, in that if I search for a someone's user ID (where their user ID is different from their display name), the DM room with them appears in my spotlight search results.

I can point you to the test case I added (https://github.com/matrix-org/matrix-react-sdk/blob/4b11fa3dd03c16f3aaf199abfe55878ec9daf7af/test/components/views/dialogs/SpotlightDialog-test.tsx#L403) - where searching for terms that are not the user's MXID or the user's Display Name should not exclude a DM result if and only if the user ID is part of the possible result list (most likely retrieved from the API).

If that test case, the existing implementation will give results for "Wonder" but no results for "Something Wonder" because that doesn't match any MXID, room name or user's display name.

My proposed change modifies that, by checking if there is a search result MXID that matches an existing DM, it will not discard it.

This is difficult to replicate in a standard homeserver deployment but let's you have user metadata, like office location, job title, organization or department, and your user directory search implementation is aware of that and can use it as search terms, then they can be used as search terms as well.

Another example - You (David) and me (Milton) have a DM. We have a custom search API implementation that will match location metadata. Currently, if you search for "Milton Moura Azores", you will get no results because it's not part of the display name or MXID. With this patch, a search API implementation that can handle those terms will return my MXID as part of the result list and the DM with me will appear in the "Recent Conversations" section.

Hope this clears up things a bit.

**Review by dbkr — COMMENTED** [review]
Ah, thanks for the explanation! I entirely did not get that `users` was the results from the user directory search (wish we'd used a clearer variable name...).

Could we possibly expand the comment to something like, "If the room is a DM with a user that was included in the user directory search results, we can assume the user is a relevant result, so include the DM with them too."?

Also if you felt like renaming the `users` variable to `userDirectorySearchResults` or something, I certainly wouldn't complain.

Other than that, I think this looks sensible.

**Comment by dbkr** [comment]
Oh, also you have some eslint failures which look relevant (and it's a required check).

**Comment by mgcm** [comment]
I've updated the PR taking @dbkr 's comments into consideration.

**Review by dbkr — APPROVED** [review]
Thanks, this feels a lot easier to understand now.

**Pull request merged**
