### PR TITLE
Handle well-known data in the login response

### PR DESCRIPTION
**Pull request by richvdh**
... as per [MSC1730](https://github.com/matrix-org/matrix-doc/pull/1730).

### CODE REVIEW

**Comment by richvdh** [comment]
clues as to why the CI is broken are welcome.

**Comment by turt2live** [comment]
It's complaining about electron, which changed very recently. Should be able to rebase the branch on a modern develop and it'll pick up the appropriate riot-web changes and magically work.

**Comment by turt2live** [comment]
Tests would be fixed by https://github.com/matrix-org/matrix-react-end-to-end-tests/pull/43

**Comment by richvdh** [comment]
ok, I'm going to assume that the test failures here are unrelated.

**Pull request merged**
