### PR TITLE
Adding description for Clear Cache and Reload Button in Settings

### PR DESCRIPTION
**Pull request by tawfiek**
Fixes vector-im/element-web#5800
Screenshot from 2021-03-26 18-54-23

---
This PR currently has none of the required changelog labels.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

### CODE REVIEW

**Comment by tawfiek** [comment]
I can provide Arabic translation for the new added description, should I do this into the same PR ?!

**Comment by t3chguy** [comment]
> should I do this into the same PR

No as it'll cause conflicts in Weblate, all translations must be done from Weblate only

**Comment by SimonBrandner** [comment]
> I can provide Arabic translation for the new added description, should I do this into the same PR ?!

No, the translations are done through [Webplate](https://translate.element.io/engage/element-web/?utm_source=widget)

**Comment by tawfiek** [comment]
so should I delete what I added for en_US ?!

**Comment by SimonBrandner** [comment]
> so should I delete what I added for en_US ?!

That should have been autogenerated using `yarn i18n`

**Comment by tawfiek** [comment]
Okay my bad I'll revert the changes

**Comment by t3chguy** [comment]
>  and automatically log you in.

This is misleading, as logging you in would make you expect the `New sign in` toasts on other devices which will not happen here. Your device ID (unique to each login) will not change

**Comment by ShadowJonathan** [comment]
"No key backups will be deleted" is hard to understand for those not in the know, I'd say "Your end-to-end-encryption keys will be untouched" would work better

**Comment by niquewoodhouse** [comment]
> "No key backups will be deleted" is hard to understand for those not in the know, I'd say "Your end-to-end-encryption keys will not be affected" would work better

That's definitely easier for me to understand (and I'm not in the know) but do we refer to them as end-to-end-encryption keys anywhere else?  I just wonder if you'd then be looking for that exact phrase in other areas of Element, and so it further complicates all the names we have/use.  Eg "I'm looking for my e2e keys" Would rather use the exact same phrases or something so generic it doesn't sound potentially specific e.g:

"Your encryption settings will not be deleted or affected in anyway."  But I don't know much about this area of Element.

**Comment by MadLittleMods** [comment]
@tawfiek Please update the PR with the copy suggestions above. This one looks almost good to go 😊

Bundling all of the points above, perhaps:

 - Clear cache and reload Element
 - This will delete all cached data and reload Element (you will still be signed in). Your encryption settings and keys will not be deleted or affected in anyway.

**Comment by tawfiek** [comment]
Yes, this much cleaner and very obvious, I'll add this to my schedule for the next week.
I think that I'll need to go through all the building and configuration stuff to run Matrix, it's been a long time since I contributed here.
But it'll be my pleasure to finish what I started with you guys 😇

**Comment by ShadowJonathan** [comment]
> No login required

I just noticed this, maybe it should be "No re-login required" or something along the lines?

Maybe "You'll stay logged in" is better.

**Comment by andybalaam** [comment]
@tawfiek any chance you could update this as requested? Thanks!

**Comment by andybalaam** [comment]
Feel free to pick this up when you get to it, but I'll mark it as draft for now so that it drops off our radar since it's not ready.

**Comment by andybalaam** [comment]
Please mark it as non-draft if you get this ready for another review. Thanks!

**Comment by tawfiek** [comment]
Hello, I need small assistance to get back into the community,
How to join Element channels?

**Comment by dbkr** [comment]
It's been 2 years since we heard anything here I believe it's probably deprecated by new settings UI design, so I'm going to close this again. It's also in a rather broken state (github doesn't think there is a diff).

**Pull request closed without merging**
