### PR TITLE
Add menu for legacy and element call in 1:1 rooms

### PR DESCRIPTION
**Pull request by toger5**
This allows to also initiate element call calls in 1:1 rooms.

Signed-off-by: Timo K <toger5@hotmail.de>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Add menu for legacy and element call in 1:1 rooms ([\#11910](https://github.com/matrix-org/matrix-react-sdk/pull/11910)). Contributed by @toger5.

### CODE REVIEW

**Review by t3chguy — COMMENTED** [review]
This legacy room header is about to be thrown out, are you sure you wish to contribute to it?

**Comment by toger5** [comment]
Good question. I should also port it to the new one.
(will the right panel chat button be added to the new header before dropping the old one? Otherwise video rooms would be broken)

**Comment by t3chguy** [comment]
@kerryarchibald are you able to answer @toger5 - for I have no idea

**Comment by kerryarchibald** [comment]
@toger5 https://github.com/vector-im/element-web/issues/26181 will be fixed before the legacy room header is removed.

> Uh the new room header also drops jitsi support right? (choosing between jisti or ec. It just makes the choice based on flags)

Right, the new room header chooses according to flags and `element_call` config.

I'm not sure this should be merged; if this is a feature we want it should be discussed with product and added to the new room header.

**Comment by toger5** [comment]
Since this exclusivly touches legacy files and is a fairly lightweight change I dont see why we would not merging it. 
I am fine with it getting removed in the next weeks in favor of the new header. It provides a working solution until design has decided if we want EC 1:1 calls to be a feature flag or if it can be selected on the fly via a menu and we can implement the final decision in the new header.

**Comment by t3chguy** [comment]
@toger5 because the legacy header is still used in most production deployments today

**Comment by toger5** [comment]
What if we add: use element call in 1:1 calls and make the menu conditional?

**Comment by toger5** [comment]
I just was about to add this behind a feature flag. It turns out it already is:
Its all behing a big if bracket: `else if (groupCallsEnabled) { ... /*changes from this pr are here*/ }`

So for users not having the feature flag enabled this would change nothing.

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
