### PR TITLE
Perform a local rejection for failed invite rejections,

### PR DESCRIPTION
**Pull request by t3chguy**
which synapse does not send its own local-rejection down sync

Fixes https://github.com/vector-im/riot-web/issues/3743

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
Scrap that, further testing shows that refreshing just brings the room back because js-sdk processes the sync response once again

**Comment by t3chguy** [comment]
I'm going to expand on this by implementing a method in the various js-sdk stores to "locallyRejectInvite" so that there's 0 chance of a race condition with nextBatch

**Comment by Ezwen** [comment]
Any news on this? Thanks for looking into it :)

**Comment by t3chguy** [comment]
I wrote some code but it had a lot of edge cases where it would come back. I think implementing it more as an ignore invites from room X would be clearer in behaviour.

**Comment by Ezwen** [comment]
ah I see, but then one would want to cancel ignores somehow I suppose?

**Comment by t3chguy** [comment]
Synapse fixed the stuck invite bug 🎉

**Pull request closed without merging**
