### PR TITLE
Emoji does not align properly with text on chats

### PR DESCRIPTION
**Pull request by yaya-usman**
Fixes:  [vector-im/element-web#21655](https://github.com/vector-im/element-web/issues/21655)

Issue reported by @yaya-usman 

Signed-off-by: Yaya Usman [yaya-usman@users.noreply.github.com](mailto:yaya-usman@users.noreply.github.com) 

**Before:**
issue1

**After:** 
issue2

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Emoji does not align properly with text on chats ([\#8216](https://github.com/matrix-org/matrix-react-sdk/pull/8216)). Contributed by @yaya-usman.

Preview: https://pr8216--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by yaya-usman** [comment]
@t3chguy @andybalaam can you help review my PR.

**Comment by robintown** [comment]
I can't reproduce the original issue, and I don't think we should be making emoji any smaller than they currently are, since 1.8rem was a value deliberately chosen to improve their readability.

Here's what emoji look like on my system, before this change:
Screenshot 2022-04-03 at 10-20-19 Element Test room
After this change:
Screenshot 2022-04-03 at 10-20-38 Element Test room

I think it would be better to investigate what's causing your browser to not display emoji correctly. Could you update the issue with information about the browser you're using, and what version it's on?

**Comment by yaya-usman** [comment]
> I can't reproduce the original issue, and I don't think we should be making emoji any smaller than they currently are, since 1.8rem was a value deliberately chosen to improve their readability.
> 
> Here's what emoji look like on my system, before this change: Screenshot 2022-04-03 at 10-20-19 Element Test room After this change: Screenshot 2022-04-03 at 10-20-38 Element Test room
> 
> I think it would be better to investigate what's causing your browser to not display emoji correctly. Could you update the issue with information about the browser you're using, and what version it's on?

it's probably my browser btwn i am using Brave Browser with a version of Chromium: 100.0.4896.60. after your response now i tried it on firefox and it seems to be fine but not as centered as it should be. about the size, i personally just thought the emoji seems too big for that small text, that was why i decreased it a bit.  I guess i should close this issue then. Thanks

**Comment by ShadowJonathan** [comment]
(I'd appreciate if someone could check this change with custom emoji, considering they more-or-less have the same problem.)

**Comment by robintown** [comment]
Custom emoji aren't supported yet, so that should be left to separate PRs.

**Pull request closed without merging**
