### PR TITLE
Enable options to favourite and low priority rooms

### PR DESCRIPTION
**Pull request by JorikSchellekens**
fixes: https://github.com/vector-im/riot-web/issues/14283

relates to:  https://github.com/vector-im/riot-web/issues/13635

image

image

### CODE REVIEW

**Comment by turt2live** [comment]
For https://github.com/vector-im/riot-web/issues/13635

**Comment by turt2live** [comment]
this also doesn't need design review - it's pre-approved design.

**Comment by JorikSchellekens** [comment]
@t3chguy it's not? 
image

**Comment by JorikSchellekens** [comment]
image
image

**Comment by t3chguy** [comment]
It was though https://github.com/matrix-org/matrix-react-sdk/pull/4920/commits/53bdddfcdd95ff908e143d695c18004426d9e07c#diff-c59d17ad818d75495c5f7d5310efc62fL228 ?

**Comment by JorikSchellekens** [comment]
That lint is a lie but I'll fix it.

**Comment by JorikSchellekens** [comment]
I don't think so. But anyway. Is it ok to land?

**Comment by turt2live** [comment]
lgtm - merging so it ends up in the secret build

**Pull request merged**
