### PR TITLE
Device manager - design tweaks

### PR DESCRIPTION
**Pull request by kerryarchibald**
**Behavior and component normalization**

- Hide the ".mx_DeviceSecurityCard" when the details for the Current Session are uncollapsed.
- ".mx_FilterDropdown .mx_Dropdown_input" should only show the background color on hover or active (e.g., see current implementation for the Threads panel, ".mx_ThreadPanel_dropdown"). [↗ Figma](https://www.figma.com/file/jI0ZdCeKKa51BDORmXdnRU/Settings%3A-UI-Refresh?node-id=1390%3A82261&t=RSlUlsl3z0f6jTkm-0)
- "#device-list-filter_listbox" doesn't look or behave as the identical menu used for the Threads panel (e.g. missing top and bottom padding, last hovered item remains highlighted).

**Colors**

- ".mx_DeviceTypeIcon_verificationIcon" border should be Compound "quinary" color (#E3E8F0).
- When hovering ".mx_DeviceExpandDetailsButton" make the background Compound "Quinary" (#E3E8F0). Should work with equivalent shades for the dark theme.

**Spacing**

- ".mx_SettingsSubsection_description" margin-bottom should be 24px.
- ".mx_DeviceDetails" padding should be 24px.
- ".mx_DeviceDetails_section" grid-gap should be 24px
- ".mx_DeviceDetails_section" padding-bottom and margin-bottom should be 20px.
- Gap between ".mx_DeviceDetails_sectionHeading" and ".mx_DeviceDetails_sectionSubheading" should be a 4px.

**Typography**

- ".mx_DeviceDetailHeading .mx_Heading_h3" font-size should be 15px.

**Icons**

- ".mx_DeviceExpandDetailsButton_icon" use Compound "Chevron" icon at 16px size. [↗ Figm](https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1373%3A13&t=uTjnTm15Gpv3R8cN-0)a
Updated the size to 16

**Copy**

- Missing trailing full stop for "Improve your account security by following these recommendations."
- Missing trailing full stop for "Consider signing out from old sessions (90 days or older) you don’t use anymore."
- "1 sessions selected" should be singular "1 session selected"

|Before|After|
|---|----|
| Screenshot 2022-12-19 at 11 35 52| Screenshot 2022-12-19 at 11 36 11|
|Screenshot 2022-12-19 at 11 35 29|Screenshot 2022-12-19 at 11 35 34|
|Screenshot 2022-12-19 at 11 35 22|Screenshot 2022-12-19 at 11 35 12|

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Device manager - design tweaks ([\#9768](https://github.com/matrix-org/matrix-react-sdk/pull/9768)). Contributed by @kerryarchibald.

### CODE REVIEW

**Review by turt2live — COMMENTED** [review]
this seems fine as a change - would we be able to get screenshots please?

**Comment by kerryarchibald** [comment]
@turt2live screenshots added

**Review by dbkr — APPROVED** [review]
Looks fine - I assume Travis's code signoff means he doesn't need to see it again, it now has screenshots.

**Review by turt2live — APPROVED** [review]
what Dave said :)

(thank you - figma links are not as permanent as would be ideal)

**Pull request merged**
