### PR TITLE
Update membership reason handling, including leave reason displaying

### PR DESCRIPTION
**Pull request by turt2live**
Incorporates ideas from https://github.com/matrix-org/matrix-react-sdk/pull/6198

image

Proof that MELS is fine:
image

### CODE REVIEW

**Comment by nadonomy** [comment]
@turt2live is it trivial to apply a distinct style to the reason text?

**Comment by turt2live** [comment]
far from trivial, unfortunately.

**Comment by nadonomy** [comment]
Ok, that's a shame. So the current implementation is a little clunky and inelegant. Relatedly, there's also a bunch of unnecessary periods/punctuation on these messages.

A couple of requests: 

1. For the messages specifically for this PR, please can you restyle as: `User left the room: reason` & `User left the room`
2. If trivial, would be great to remove the extraneous periods from the other events styled in this way (invited, joined, etc) to match

**Comment by turt2live** [comment]
@nadonomy screenshot/build updated - let me know if I've misinterpreted that somehow 😅

**Review by nadonomy — APPROVED** [review]
Looks perfect, thanks!

**Comment by t3chguy** [comment]
@turt2live https://github.com/matrix-org/matrix-react-sdk/pull/6257 paves a path to making it possible for TextToEvent to be able to enrich its output with JSX

**Review by gsouquet — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
