### PR TITLE
Fix position of PiP overlay for calls

### PR DESCRIPTION
**Pull request by tulir**
Fixes vector-im/element-web#16116

Preview: https://mau.photos/2Iu7s.png (new on the left, old on the right)

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
code seems fine, though design would need to sign off on this

**Review by gaelledel — CHANGES_REQUESTED** [review]
Ok for placing the PIP at the top right-hand corner by default but could it be placed so it is placed 4px under the navbar and the same padding we have on the last icon in the nav? 
Example
Screenshot 2021-04-23 at 12 52 16

Also, we're aiming to have the PIP window movable throughout the UI. I wonder if this is something that could also be done?

**Comment by SimonBrandner** [comment]
> Also, we're aiming to have the PIP window movable throughout the UI. I wonder if this is something that could also be done?

As far as I can tell, this aims to be a quick fix. A draggable PIP will require a bit more work. I've created [#17130](https://github.com/vector-im/element-web/issues/17130) to track that. For now, I have assigned it to myself as I am happy to look into it but if @tulir wants to do it I have no problem with that. Let me know what you prefer

**Comment by tulir** [comment]
Yeah, this was just a quick fix since blocking view of the latest messages was very annoying.

Adjusted the pixels now:

image

**Comment by chagai95** [comment]
This now blocks stuff when open the room info...

image

**Comment by SimonBrandner** [comment]
> This now blocks stuff when open the room info...
> 
> image

https://github.com/matrix-org/matrix-react-sdk/pull/5952 will fix this

**Comment by SimonBrandner** [comment]
The design team has decided that they'd prefer the PiP to stay in the bottom-right corner. Though they'd like it to be movable - https://github.com/matrix-org/matrix-react-sdk/pull/5952

**Comment by gsouquet** [comment]
Closing following @SimonBrandner 's comment

**Pull request closed without merging**
