### PR TITLE
Hide Remove button in message editing history if you don't have permission to redact

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/riot-web/issues/10366
Fixes https://github.com/vector-im/riot-web/issues/10292

### CODE REVIEW

**Comment by turt2live** [comment]
we actually probably want to figure out a greyed state for this because hiding UI is something we're trying to avoid.

**Comment by aaronraimist** [comment]
Why are there so many different kinds of AccessibileButton with the same opacity for the disabled state?

https://github.com/matrix-org/matrix-react-sdk/blob/e7f292794c55dff1fd2a77eba5ec7eb249ca5f58/res/css/views/elements/_AccessibleButton.scss#L44-L46
https://github.com/matrix-org/matrix-react-sdk/blob/e7f292794c55dff1fd2a77eba5ec7eb249ca5f58/res/css/views/elements/_AccessibleButton.scss#L54-L56
https://github.com/matrix-org/matrix-react-sdk/blob/e7f292794c55dff1fd2a77eba5ec7eb249ca5f58/res/css/views/elements/_AccessibleButton.scss#L84-L86
https://github.com/matrix-org/matrix-react-sdk/blob/e7f292794c55dff1fd2a77eba5ec7eb249ca5f58/res/css/views/elements/_AccessibleButton.scss#L94-L96

Can't all of those be replaced with:
```
mx_AccessibleButton_disabled {
    opacity: 0.4;
}
```

**Comment by turt2live** [comment]
probably, though I'm sure there's a button somewhere in the depths of the app that needs the rules to be as specific as possible :/

**Comment by nadonomy** [comment]
I took a closer look at this, also consulting some old school HCI research on context menus, and came to the conclusion that it's a better user experience to not display the remove button when the action isn't available.

**Pull request merged**
