### PR TITLE
Add a link in room settings to get at the tombstoned room if it exists

### PR DESCRIPTION
**Pull request by turt2live**
Fixes https://github.com/vector-im/riot-web/issues/8542

image

### CODE REVIEW

**Comment by turt2live** [comment]
went with just saying "View older messages in *room name*" because we don't really have a concept of generations for rooms, and saying "version 3" could be confusing.

**Comment by turt2live** [comment]
went with just saying "View older messages in *room name*" because we don't really have a concept of generations for rooms, and saying "version 3" could be confusing.

**Comment by turt2live** [comment]
The concern would be when someone sees "room version: 4" in the future and the messaging says "previous version 3 room", which was actually the second generation room. It's just a bunch of numbers to confuse the user, and if they really want to know the version of the old room they can go look imo

**Comment by bwindels** [comment]
> The concern would be when someone sees "room version: 4" in the future and the messaging says "previous version 3 room", which was actually the second generation room. It's just a bunch of numbers to confuse the user, and if they really want to know the version of the old room they can go look imo

Right, makes sense. I was just thinking that with "View older messages" users might wonder what the difference is with scrolling up in the timeline, but I guess they have the context of being in the room version section in the settings, so fine.

**Pull request merged**
