### PR TITLE
Reinstate Posthog analytics PR fixing type definitions via installing dev dependencies

### PR DESCRIPTION
**Pull request by novocaine**
Part of the previous PR for posthog https://github.com/matrix-org/matrix-react-sdk/pull/6495 included overriding posthog's type definitions to remove references to transitive dependencies which we don't use and don't want to install. This was done via a `paths` entry in `tsconfig.json`.

This caused element-web linting to fail as EW's type linting descends into matrix-react-sdk but the override didn't apply to EW as no changes were made to its respective `tsconfig.json`. So I reverted the PR in https://github.com/matrix-org/matrix-react-sdk/pull/6531.

It wouldn't be great for every Typescript user of `matrix-react-sdk` to have to do that. 

In this PR, I initially took a different approach suggested by @Palid - use `patch-package` to autopatch the library on postinstall. Unfortunately, as noted in the comments, we disable the postinstall hook in CI, and it would be awkward to work around that.

I considered forking the library, but we don't currently maintain any forked dependencies and it seems silly to start doing that now for this one.

So for the time being, we are just going to install the libraries referred to as dev dependencies. We will be using Sentry shortly anyway. Flagged with posthog maintainers at https://github.com/PostHog/posthog-js/issues/252

### CODE REVIEW

**Comment by novocaine** [comment]
(looks like branch is a bit confused due to rebasing, resolving)

**Review by Palid — APPROVED** [review]

**Comment by Palid** [comment]
@novocaine it seems that for some reason the CI does not patch the packages properly, or it's using a cached version.

**Comment by novocaine** [comment]
It seems that because we run `yarn install --ignore-scripts`, the `postinstall` hook is not run. I think this is kind of intentional - we don't want third party packages executing scripts inside the CI.

https://github.com/yarnpkg/yarn/issues/7338

**Comment by Palid** [comment]
@novocaine I guess we can just run it manually then?

**Comment by novocaine** [comment]
We could, but then we're trusting `patch-package` itself to run inside our CI which I'm not quite sure about.

I considered just running `patch -p1 < patches/posthog-js+1.12.2.patch` which is all that's needed but I guess that will not work on windows.

**Comment by novocaine** [comment]
Giving up and adding them as dev dependencies in the interests of pragmatism. 

As noted in the commit we will shortly be using sentry anyway, and I'm chasing up the posthog maintainers at https://github.com/PostHog/posthog-js/issues/252

**Pull request merged**
