### PR TITLE
ignore e2e tests node_modules during linting

### PR DESCRIPTION
**Pull request by bwindels**
Not sure if this happens for other people, but I get this on my machine otherwise:

```
Error: Cannot find module '@ljharb/eslint-config'
Referenced from: /home/bwindels/dev/riot/matrix-react-sdk/test/end-to-end-tests/node_modules/extend/.eslintrc
```

### CODE REVIEW

**Comment by t3chguy** [comment]
> Not sure if this happens for other people

I think you're the only to run the e2e tests locally :D

**Comment by bwindels** [comment]
> > Not sure if this happens for other people
> 
> I think you're the only to run the e2e tests locally :D

:smiley: possibly, but this is when running lint locally though.

**Comment by t3chguy** [comment]
but only after setting up e2e tests

**Comment by bwindels** [comment]
> but only after setting up e2e tests

Ah, true :) Want to review now that you're here?

**Pull request merged**
