### PR TITLE
Stop sending reply and edit fallbacks (MSC2781)

### LINKED ISSUE #7014: Redacting an event doesn't redact the fallback in replies
This is probably impossible without aggregations, but it is something that should happen

### LINKED ISSUE #7874: Replying to a message containing a ping causes the intended recipient(s) of the ping to be pinged again
This happens for both room pings and user pings. Examples:

image
(As seen by users other than Ruff_Wizard. User Ruff_Wizard does not get themself pinged by their reply, but the rest of the room does.)

image
(As seen by user Ruff_Wizard. User Ruff_Wizard gets pinged by a message replying to one containing their name.)

It shouldn't work like this; this system assumes that someone necessarily wants/needs to get pinged just because another person is replying to a message which contains their name/a room ping. If someone wants to ping the person or the room again, they can simply insert another ping in the text of their reply. The system shouldn't ping every time the intial ping is replied to.

### LINKED ISSUE #20334: Replying to Notify Everyone (@room) Triggers Another Notification
### Steps to reproduce

An a user with notify all permissions pings the room, any user (even if they do not have the permissions to notify all) 
is able to ping the room by replying to the @ room notification.

image

#### What did you expect?
If a user responds to a room notification, it does not ping the whole room again if the user does not have permissions to do so.

#### What happened instead?
The room was pinged

### Operating system

MacOS

### Browser information

Chrome 96.0.4664.93

### URL for webapp

Private (version: 1.9.7 Olm version: 3.2.8)

### Application version

Element version: 1.9.7 Olm version: 3.2.8

### Homeserver

Private

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/element-web/issues/20334
Fixes https://github.com/vector-im/element-web/issues/7874
Fixes https://github.com/vector-im/element-web/issues/7014

Implementation of MSC2781 https://github.com/matrix-org/matrix-doc/pull/2781

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

Preview: https://616fbd209150a3addcee4a49--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — COMMENTED** [review]
While the code looks fine, there's ecosystem compatibility to consider on this, including with bots, bridges, other clients, etc. 

This PR serves functionally fine for an implementation of the removal, but for the spec side we'd need reassurance that bridges and bots won't break (clients are easier to fix).

**Comment by HarHarLinks** [comment]
while I agree the ecosystem needs to adapt, I think it's much easier to support events without than with fallbacks also for bots just as it is for client( sdk)s. What's the plan to push towards it? Labs flag for this and test around how it goes? Announce to everyone to implement this MSC before it gets merged while retaining compatibility with fallbacks with a deadline?

**Comment by turt2live** [comment]
See also: MSC2781

**Review by turt2live — CHANGES_REQUESTED** [review]
This PR will probably take a while to merge, as it would require us to have suitable support on mobile (android at least doesn't currently render replies properly). The MSC also appears to be stalled, which isn't good :( 

For now I think we can keep this PR open because it's not that old, though if the Android/mobile support or MSC take too long then we may revisit this at a later date. 

Code-wise this looks fine. Just marking requested changes for the mobile support (and MSC, though to a lesser degree).

**Comment by weeman1337** [comment]
Conversion to a draft, as we are still waiting for mobile. We should reopen it if there is a chance to move it forward.

**Pull request closed without merging**
