### PR TITLE
Implement erasure option upon deactivation

### PR DESCRIPTION
**Pull request by lukebarnard1**
Requires https://github.com/matrix-org/matrix-js-sdk/pull/649

### CODE REVIEW

**Comment by lukebarnard1** [comment]
Blocked on merging js-sdk so that we don't break `riot.im/develop`...

**Comment by ara4n** [comment]
@lukebarnard1 heads up that the wording on the googledoc for this has evolved slightly since implementation - if you can resync it (i think it's just the first paragraph) it would be appreciated.

**Comment by lukebarnard1** [comment]
No worries, I think I'll open a new PR for that :+1:

**Comment by lukebarnard1** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/649 Merged :ballot_box_with_check:

**Pull request merged**
