### PR TITLE
Switch to updating presence via /sync calls instead of PUT /presence

### PR DESCRIPTION
**Pull request by t3chguy**
2nd attempt of https://github.com/matrix-org/matrix-react-sdk/pull/11223
Fixes https://github.com/vector-im/element-web/issues/20809
Fixes https://github.com/vector-im/element-web/issues/13877
Fixes https://github.com/vector-im/element-web/issues/4813
Closes https://github.com/matrix-org/matrix-react-sdk/pull/10184

Also stops multiple running sessions clobbering each other's presence

image
image

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Switch to updating presence via /sync calls instead of PUT /presence ([\#11824](https://github.com/matrix-org/matrix-react-sdk/pull/11824)). Fixes vector-im/element-web#20809 vector-im/element-web#13877 and vector-im/element-web#4813.

### CODE REVIEW

**Comment by andybalaam** [comment]
Do we have a way of warning people running old Synapse versions that this will cause them problems?

**Comment by t3chguy** [comment]
No, there is no Matrix Client-Server API which gives you the Server software name & version, only a Federation endpoint for it.

**Review by andybalaam — APPROVED** [review]
Looks good, thanks!

**Comment by andybalaam** [comment]
> No, there is no Matrix Client-Server API which gives you the Server software name & version, only a Federation endpoint for it.

I mean in real life. I guess we just add it to the release announcement.

**Comment by andybalaam** [comment]
Note to whoever does the release announcement (probably me?) - the first Synapse release with the fix is https://github.com/matrix-org/synapse/releases/tag/v1.93.0

**Pull request merged**
