### PR TITLE
Prevent Element appearing in system media controls 

### PR DESCRIPTION
**Pull request by SuperKenVery**
Use WebAudio API to play notification sound, so that it won't appear in system media control.

For now, if I leave element web in the background, it would have an `<audio>` element for playing notification sound, and there will be an entry in system media controls, making it impossible to control other music with media keys on the keyboard. This pr aims to fix that. 

Before:
image

After:
image

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Signed-off-by: 许煜恒 <xyhken@icloud.com>

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Prevent Element appearing in system media controls  ([\#10995](https://github.com/matrix-org/matrix-react-sdk/pull/10995)). Contributed by @SuperKenVery.

### CODE REVIEW

**Comment by SuperKenVery** [comment]
Corresponding element-web pr: https://github.com/vector-im/element-web/pull/25477

**Comment by SuperKenVery** [comment]
Why does Jest complain that `AudioContext` is undefined? It woks on my machine...

**Review by germain-gg — CHANGES_REQUESTED** [review]
As a result of no WebAudio API being present, we should most probably mock out `_playAudioNotifcation` and assert it being call.

But as discussed in https://github.com/vector-im/element-web/pull/25477, the issue it claims solving is not fully solved until ALL sound gets routed through the WebAudio API (call ringtones, messages, ...).

**Comment by SuperKenVery** [comment]
Phew, now I've got (almost, see below) all `<audio>` tags removed and use WebAudioAPI, and the sounds work normally. 

However, as I'm not familiar with the project, there's probably more to be cleaned up or even my code can be organized better... Tell me if any!

There's still one `<audio id="remoteAudio"></audio>`. I'm not sure what it does, and it seems that it's only used in tests, so I don't know what to do with it. However it's never played so I think even leaving it there wouldn't be a problem.

**Comment by t3chguy** [comment]
Does this also fix https://github.com/vector-im/element-web/issues/18643?

**Comment by SuperKenVery** [comment]
> Does this also fix [vector-im/element-web#18643](https://github.com/vector-im/element-web/issues/18643)?

I believe so, it should also fix that issue. Actually I'm doing this because of that issue 🤣

**Comment by t3chguy** [comment]
This looks sane but needs some mocks created to pass tests, are you interested in getting this over the line?

**Comment by SuperKenVery** [comment]
I have zero experience in writing UI tests and mocks, and unfortunately I’m quite busy recently so :( No quite interested, sorry😮‍💨在 2024年6月21日，上午12:28，Michael Telatynski ***@***.***> 写道：﻿
This looks sane but needs some mocks created to pass tests, are you interested in getting this over the line?

**Comment by dbkr** [comment]
I think we'll close this for now as it will need to pass the testing bar to get merged. If someone else wants to pick it up, they can always open a fresh PR. Ideally it would convert the various uses of audio separately to make smaller PRs. It will obviously need serious testing.

**Comment by t3chguy** [comment]
This is on my plate to get over the line

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
