### PR TITLE
Push name to the end, near text, in IRC layout

### PR DESCRIPTION
**Pull request by Glandos**
Currently, the name (and aux message) are align to the start, leaving a blank space between the end of the name and the message.

In a lot of IRC themes, names (and actions) are aligned to the end, next to the message, for a better readability.

### CODE REVIEW

**Comment by jryans** [comment]
@Glandos Could you add a screenshot here for easier review?

**Comment by Glandos** [comment]
Before:
Screenshot_2020-09-28 Element  1  #element-dev matrix org

After:
Screenshot_2020-09-28 Element  1  #element-dev matrix org(1)

**Review by jryans — APPROVED** [review]
Thanks, seems good code-wise to me.

**Review by nadonomy — APPROVED** [review]
LGTM, with the caveat that some opinionated users may feel otherwise so may need to rollback.

**Comment by Glandos** [comment]
Yes of course… In this case, I'll try to add an option, but it is far less easy :)

Anyway, I know that I can't speak for everyone, but it makes more sense to me to have it right aligned (in LTR) because text could be far away from the nickname otherwise.

**Comment by blattersturm** [comment]
I find this visually painful to use. Moving the avatar to be inline with the name might be a better choice, though an option might ultimately make more sense?

**Comment by Glandos** [comment]
I have to admit that, even if I really like this new placement, having the avatar far from the name can be a bit weird. It's clearly visible on the screenshot above.

What about having the avatar at the end of the name when `text-align: end`, and at the start with `text-align: start`?

**Comment by jryans** [comment]
> I have to admit that, even if I really like this new placement, having the avatar far from the name can be a bit weird. It's clearly visible on the screenshot above.
> 
> What about having the avatar at the end of the name when `text-align: end`, and at the start with `text-align: start`?

I'd suggest new issues / PRs for such ideas, as we don't really follow closed PRs on the core team.

**Pull request merged**
