### PR TITLE
Fixed custom emotes background color #27745

### PR DESCRIPTION
**Pull request by asimdelvi**
## Checklist

-   [x] Tests written for new code (and old code if feasible).
-   [x] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [x] Linter and other CI checks pass.
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

fixes element-hq/element-web#27745

in [github-markdown-css](https://github.com/sindresorhus/github-markdown-css#readme), img background is set to #fff for light theme and #000 for dark theme. So had to override the styling.

### CODE REVIEW

**Review by t3chguy — CHANGES_REQUESTED** [review]
Looks sane to me, could you add a comment to the style so its clear to future readers why this override exists

**Comment by t3chguy** [comment]
The reason the tests are failing is due to your fork of https://github.com/asimdelvi/element-web being out of date, could you sync that up so the branch matching doesn't fail :)

**Comment by asimdelvi** [comment]
yep, updated the branch. 
Thanks

**Comment by t3chguy** [comment]
You checked `Sign-off given on the changes` but I don't see a sign off from you, that should be all that is missing to get this landed

**Comment by asimdelvi** [comment]
Signed-off-by: Asim Mohammed Delvi [asimdelvi30@gmail.com](mailto:asimdelvi30@gmail.com)

**Comment by asimdelvi** [comment]
thanks for the guidance @t3chguy

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
