### PR TITLE
 #22233issue: Update textualBody.tsx

### PR DESCRIPTION
**Pull request by adityakishor1**
## Checklist

-  
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This PR currently has none of the required changelog labels.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

### CODE REVIEW

**Comment by adityakishor1** [comment]
t

**Comment by adityakishor1** [comment]
Very interesting while doing this.

**Comment by adityakishor1** [comment]
very interested to do this.
And while this i learn many things.

**Comment by luixxiul** [comment]
https://github.com/vector-im/element-web/issues/22233 has been fixed already.

**Comment by gsouquet** [comment]
Thank you for opening your first pull request! As @luixxiul pointed out, this issue as already been fixed.

But I'd encourage you to look for other [good first issues](https://github.com/vector-im/element-web/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sort%3Aupdated-desc) that do not have pull requests associated with them

**Pull request closed without merging**
