### PR TITLE
Adds 'display_name' param when user is registered via Module API

### PR DESCRIPTION
**Pull request by maheichyk**
Type: Enhancement
Related: https://github.com/matrix-org/matrix-react-sdk-module-api/

Suggests to pass `'display_name'` parameter when user is registered via Module API. 

This will allow to validate and override if needed the display name of the user inside of `/register` request using synapse API: [get_displayname_for_registration](https://github.com/matrix-org/synapse/blob/develop/docs/modules/password_auth_provider_callbacks.md#get_displayname_for_registration)

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Adds 'display_name' param when user is registered via Module API ([\#10250](https://github.com/matrix-org/matrix-react-sdk/pull/10250)). Contributed by @maheichyk.

### CODE REVIEW

**Comment by maheichyk** [comment]
Signed-off-by: Mikhail Aheichyk <mikhail.aheichyk@nordeck.net>

**Review by SimonBrandner — COMMENTED** [review]
I don't see `display_name` in the spec being allowed on `/register` - what am I missing?

**Comment by maheichyk** [comment]
yes, `/register` has no `display_name` parameter in the spec, the idea was still to pass it to be used by synapse custom module.

But we have found another solution for our case and don't need this change anymore. I will close PR, thanks for you feedback.

**Comment by t3chguy** [comment]
@maheichyk in future custom extension need to be namespaced as per notes in the spec

**Comment by maheichyk** [comment]
@t3chguy could you please provide a link to these notes? I was checking https://spec.matrix.org/v1.6/client-server-api/#post_matrixclientv3register and seems no namespace notes here... It could be useful if we/someone will need to use modules and could know how to follow the spec in this case.

**Comment by t3chguy** [comment]
@maheichyk the spec doesn't explicitly allow it on that API but in theory any JSON object is allowed to be extended using 

> may include additional keys, which MUST follow the Java package naming convention

It'd be better if the spec was more explicit about it

**Pull request closed without merging**
