### PR TITLE
Fix button width and align 絵文字 (emoji) on the user panel

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/vector-im/element-web/issues/22142

Before: See https://github.com/vector-im/element-web/issues/22142

After:
after
after1

type: defect

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix button width and align 絵文字 (emoji) on the user panel ([\#8562](https://github.com/matrix-org/matrix-react-sdk/pull/8562)). Fixes vector-im/element-web#22142. Contributed by @luixxiul.

### CODE REVIEW

**Comment by t3chguy** [comment]
image
image

These states still look broken I think

As does this one but probably needs design input
image

**Comment by luixxiul** [comment]
I would compare with a previous version to see how they should be aligned.

**Comment by luixxiul** [comment]
I confirmed that the layout on the last picture was not regression of recent commits. It has been reproduced already since `1.10.5` of Element Desktop.

**Comment by luixxiul** [comment]
Indent to `Unable to load session list`:
after

The spinner is displayed on the center:
after1

**Review by t3chguy — APPROVED** [review]
This is much much better, thank you

**Pull request merged**
