### PR TITLE
Only set title when it changes

### PR DESCRIPTION
**Pull request by resynth1943**
I've seen Chromium constantly refresh the title in the developer tools,
when the title hasn't actually changed.
To be honest, I'm not sure if this means Chromium wastes CPU
time changing a title, but this may introduce better performance.

Signed-off-by: Resynth <resynth1943@tutanota.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
Needs DCO Sign-off as per contributing doc

https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst#sign-off

**Comment by resynth1943** [comment]
How do I keep forgetting this

**Comment by t3chguy** [comment]
The sign-off can go into the PR description too, for future reference to save you having to force-push

**Review by t3chguy — APPROVED** [review]
No idea if will gain any performance but can't hurt, thanks!

**Comment by resynth1943** [comment]
> No idea if will gain any performance but can't hurt, thanks!

Same here. That being said, when I've looked in the Developer Tools, the `<title>` element keeps flashing when the title "changes" to the same value, so I figured we might as well cover all bases :-)

**Pull request merged**
