### PR TITLE
Show invite reasons

### PR DESCRIPTION
**Pull request by robintown**
Displays the reason for invitation in the invitation dialog, requiring a click to reveal the message. I based it on [this mockup](https://user-images.githubusercontent.com/1922197/88951009-56ff1200-d28d-11ea-905c-1695ce838a80.png), which I assume still needs a design review.

Screenshot_2021-02-26 Element  1  test room
Screenshot_2021-02-26 Element  1  test room(1)

Closes vector-im/element-web#14832.

### CODE REVIEW

**Comment by turt2live** [comment]
I haven't looked at the code, but the screenshots look great - thank you! A designer will be able to review it a bit better than I.

Something to consider is abusive invite reasons: we might need to hide these behind disclosures or blurs or something.

**Review by turt2live — APPROVED** [review]
Code seems generally fine - thanks for taking a look!

**Comment by robintown** [comment]
Ummm why are the tests failing? It looks unrelated to these changes

**Comment by jryans** [comment]
Seems to have been an intermittent failure.

**Comment by jryans** [comment]
Oh no, I forgot about the Design review... 😓

**Comment by jryans** [comment]
I guess I'll revert it and open a new PR. 😭

**Comment by jryans** [comment]
I'll try to rustle up some Design feedback before the RC, and perhaps we can tweak as needed from there.

**Comment by jryans** [comment]
I created https://github.com/vector-im/element-web/issues/16869 to track any design feedback.

**Pull request merged**
