### PR TITLE
Hopefully make cancel dialog a bit less weird

### PR DESCRIPTION
**Pull request by dbkr**
There's no design on how to fix this so I've switched the buttons
and made the primary not a danger button. We could also try some
different wording, eg. 'abort' rather than 'cancel' because with
'cancel' it's not clear if you're cancelling whatever you were trying
to do or the dialog asking you if you want to cancel...

Ideal might be to make the cancel button red but that means making
it a separate button or adding support for doing so to DialogButtons,
so not going to do that unless we're sure that's what we want.

Also the 'your operation' here is because this is fetching the master key,
as we enter the security key on logging in (to get your secrets out of SSSS)
and this is a case that's not covered: all we have is what type of key we're trying
to get so it's a little harder to guess in this case.

Screenshot 2020-06-25 at 14 51 23

Fixes https://github.com/vector-im/riot-web/issues/14140

### CODE REVIEW

**Comment by nadonomy** [comment]
@dbkr can you expand on the user context before we show this modal?

**Comment by dbkr** [comment]
This is shown specifically when the user cancels a prompt for their security passphrase by clicking on the background of the dialog (ie. not if they click the 'cancel' button). It was added because some people were clicking on the background accidentally which would dismiss the passphrase prompt, then being left in a state without secret storage set up.

**Comment by nadonomy** [comment]
Got it. In that case, then, to address:

> We could also try some
different wording, eg. 'abort' rather than 'cancel' because with
'cancel' it's not clear if you're cancelling whatever you were trying
to do or the dialog asking you if you want to cancel...

Can we lose the body copy and instead use:

#### Are you sure you want to cancel entering passphrase?
[Cancel] **[Go Back]**

**Comment by dbkr** [comment]
Done:

Screenshot 2020-07-06 at 15 24 46

**Pull request merged**
