### PR TITLE
Fix padding and border-radius issue of the right panel for chat aka mx_ThreadPanel

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes https://github.com/vector-im/element-web/issues/21745

This PR fixes the lost border issue without introducing another `:not()` to `.mx_ThreadPanel:not(.mx_ThreadView).mx_BaseCard`.

It is out of scope of this PR to address the issue which seems to be more fundamental that the `.mx_ThreadPanel` is added to the chat timeline on the right panel as well. I think threads and chats on the right panel should be distinguished clearly in order to avoid confusion and misunderstanding.

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

**Steps to confirm the fix**
1. Create a room
2. Add a widget such as Jitsi
3. Maximize the widget
4. Check that the chat on the side panel has the right border whose width is same as the left border
5. Check that the border-radius is applied to the chat timeline

(Color of the border changed temporarily for clarification)
after

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

Preview: https://pr8307--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by robintown — CHANGES_REQUESTED** [review]
Looks like this removes the border radius from thread timelines

Screenshot 2022-04-13 at 09-10-59 Element #element-dev matrix org

**Comment by robintown** [comment]
Hm, on my side I see:

- on develop: no border radius on the threads list, but a border radius on the threads timeline
- on this PR: the opposite, border radius on the threads list but not on the threads timeline

**Comment by luixxiul** [comment]
Here is the cropped screenshot of my environment (develop branch, dark theme, Firefox 99 on Debian).

dark

I am akso wondering why the color combination is different from yours :thinking:

**Review by robintown — APPROVED** [review]
Oh, I looked again, and you're right? Not sure what happened there, but this PR looks fine, thanks!

**Comment by luixxiul** [comment]
Thanks for checking again! Maybe due to cache or something?

The style rules around that area are very complex and complicated :sweat_smile: I will try to simplify them by solving puzzles hidden inside the codebase..

**Pull request merged**
