### PR TITLE
Better rendering for autocomplete in narrow spaces

### PR DESCRIPTION
**Pull request by gsouquet**
Fixes https://github.com/vector-im/element-web/issues/21393

Screen Shot 2022-03-17 at 12 19 54

@janogarcia what do you reckon a good minimum width would be for the autocomplete wrapper here? It's currently using `450px` which I'm afraid would be quite wide

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Better rendering for autocomplete in narrow spaces ([\#8073](https://github.com/matrix-org/matrix-react-sdk/pull/8073)). Fixes vector-im/element-web#21393.

Preview: https://pr8073--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]

**Comment by janogarcia** [comment]
@gsouquet That command palette is such a terrible mess that I couldn't help making a proper mockup to illustrate it better... 

- Ideally, it should line up with the composer, matching its width.
- The right sidebar should have a wider minimum width, at least for those views that include a composer (Threads, Timeline for maximized widgets), to avoid the composers and contents getting unusable small.

Composer commands

**Comment by gsouquet** [comment]
@janogarcia I'm fine making the autocomplete always match the width of the composer. So what should be the minimum width of the the right panel? 

I'd be more comfortable doing this as a two step process, where we first patch the fact that the autocomplete is nearly unusable on narrow screens, and then we plan for a redesign of it, and maybe updating some rules regarding the sizing of elements.

**Comment by janogarcia** [comment]
@gsouquet Yeah, the mockup was just for illustration purposes, as previously stated. For now I'm just suggesting those two points in the list I shared:

- Match the composer width.
- As discussed internally, let's update the minimum panel width to 400px.

**Review by janogarcia — CHANGES_REQUESTED** [review]
@gsouquet Requested changes in [previous comment](https://github.com/matrix-org/matrix-react-sdk/pull/8073#issuecomment-1072526736).

**Comment by gsouquet** [comment]
@janogarcia so we've decided not to update the width of the right panel in the end... where does that live us in regards to this pull request?

**Comment by janogarcia** [comment]
Recommended design tweaks: https://github.com/vector-im/element-web/issues/21393#issuecomment-1114618653

**Review by janogarcia — COMMENTED** [review]
Comments in previous message: https://github.com/matrix-org/matrix-react-sdk/pull/8073#issuecomment-1114621913

**Comment by t3chguy** [comment]
image

The given box-shadow is pretty much invisible in Dark mode
`box-shadow: 0px -16px 32px rgb(0 0 0 / 4%), 0px -2px 4px -2px rgb(0 0 0 / 12%); // improved foreground-background separation`

**Review by turt2live — APPROVED** [review]

**Comment by gsouquet** [comment]
This has gone stale, closing

**Pull request closed without merging**
