### PR TITLE
Delabs Spaces, iterate some copy and move communities/space toggle to preferences

### PR DESCRIPTION
**Pull request by t3chguy**
Requires https://github.com/vector-im/element-web/pull/18490
Fixes vector-im/element-web#18088
Fixes https://github.com/vector-im/element-web/issues/18524

image
image
image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Delabs Spaces, iterate some copy and move communities/space toggle to preferences ([\#6594](https://github.com/matrix-org/matrix-react-sdk/pull/6594)). Fixes vector-im/element-web#18088 and vector-im/element-web#18088.

---
Here's what your changelog entry will look like:

## ✨ Features
 * Delabs Spaces, iterate some copy and move communities/space toggle to preferences ([\#6594](https://github.com/matrix-org/matrix-react-sdk/pull/6594)). Fixes vector-im/element-web#18088 vector-im/element-web#18524 and vector-im/element-web#18088.

Preview: https://61430a9a315b83cf4fac102d--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
This seems fine, though I'm curious as to why this is a breaking change? We regularly delete/modify components in patch releases given our skinning is terrible.

**Comment by turt2live** [comment]
also conflicts, already.

**Comment by t3chguy** [comment]
(hopefully stray commits will go away once the stacked PR lands)

**Comment by turt2live** [comment]
might need to do one more round of develop -> this

**Comment by turt2live** [comment]
on the breaking change front: it got moved to element-web after some oob discussion. Just want to make sure we release a new 1.x Element version rather than a react-sdk version specifically.

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
Almost everything looks good to me, just minor things.

- [x] Change copy on settings page from `Temporarily show communities instead of Spaces. Support for this will be removed in the near future. This will reload Element ` to `Temporarily show communities instead of Spaces for this session. Support for this will be removed in the near future. This will reload Element.`

So adding a full stop at the very end, and adding _for this session_ to the first sentence.

- [x] Can 'show my Communities' have a pointer cursor, so its more obviously clickable
- [ ] Can 'show my Communities' and its arrow be in primary-fg please?  Just in practice, they're hard to see.

Just to ask the question, do we know if a person has 0 Spaces?  If they have 0 spaces, the pulsing dot feels appropriate, but if they have Spaces it feels a bit out of place in testing (for me).

**Comment by niquewoodhouse** [comment]
@nadonomy I think you should review this too - as this will turn on Spaces for everyone, and hide communities.

**Comment by t3chguy** [comment]
> Just to ask the question, do we know if a person has 0 Spaces? If they have 0 spaces, the pulsing dot feels appropriate, but if they have Spaces it feels a bit out of place in testing (for me).

Sure, will do so.

**Review by niquewoodhouse — APPROVED** [review]

**Comment by t3chguy** [comment]
The e2e tests are passing locally :(

image

**Review by nadonomy — APPROVED** [review]
I think some users will be jarred by existing communities being absent when logging in, but the blue beacon in the space panel to discover enabling communities in settings is discoverable enough, so LGTM!

**Comment by niquewoodhouse** [comment]
> I think some users will be jarred by existing communities being absent when logging in, but the blue beacon in the space panel to discover enabling communities in settings is discoverable enough, so LGTM!

Just to say out loud I requested a change that would remove the blue beacon if you have more than 0 Spaces as it felt a bit strange to have that CTA promoted when I'd already used it successfully.  So if someone has communities and more than 0 Spaces they won't see a beacon.

**Comment by t3chguy** [comment]
Type check failure unrelated and fixed in https://github.com/matrix-org/matrix-react-sdk/commit/6fcd930d0b49e565c506f556b12e0f5d5d04c79b

**Pull request merged**
