### PR TITLE
Added very basic audio notifications.

### PR DESCRIPTION
**Pull request by ajohnson23**
This plays the same message.ogg/message.mp3 regardless of event type.
It also does not check the user's event settings (LOUD/OFF/etc), instead
playing a sound upon every single notification.
Clearly, it still needs some work.

### CODE REVIEW

**Comment by ajohnson23** [comment]
Also see https://github.com/vector-im/vector-web/pull/1078

**Comment by ajohnson23** [comment]
This is a start toward fixing https://github.com/vector-im/vector-web/issues/167

**Comment by ara4n** [comment]
dave: do you have a quick solution for hooking this up to the notif sound tweak?

**Comment by dbkr** [comment]
I can take a look at hooking this in.

@ajohnson23 normally you'd base pull requests off `develop`, but since I'll be adding support for the sound tweak, could you re-open the PR against https://github.com/matrix-org/matrix-react-sdk/tree/audio_notifications please? And also sign off the code (https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst).

Thanks!

**Comment by dbkr** [comment]
Hooking into the sound tweak is fairly trivial actually: you would just pass the `actions` into `displayNotification`, then use `if (actions.sound)`.

**Comment by ajohnson23** [comment]
Closing / reopening under audio_notifications

**Pull request closed without merging**
