### PR TITLE
Use forms to wrap password fields so Chrome doesn't go wild

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/12127

Chrome can't understand our password fields...

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by jryans** [comment]
So what's the result after this change? Maybe a quick video would make it clear...

**Comment by t3chguy** [comment]
I'm going to manually verify each of these prompts just to triple check nothing goes awry as this is a pretty big change

**Comment by jryans** [comment]
Taking out of review until you've verified it's safe, as we're quite close to the deadline. Please re-add once verified.

**Comment by t3chguy** [comment]
Behaviourally all the password fields function the same with the following exceptions:

+ fields which were for inputting a new password were set to `autoComplete="new-password"` to tell password managers what was going on.
+ password fields got wrapped in forms and had their explicit Enter handling moved to Form onSubmit handling to clean up the code
+ some buttons (which defaulted to submits) got swapped out to AccessibleButtons to prevent submission ambiguity

The biggest effect of this change is now upon a password autofill, the e-mail/username won't get filled into some random field like the Room Filter or Member Filter box.

https://riot.ovh/_matrix/media/r0/download/riot.ovh/KdwobkyYEpObvaySAVnWhqhY

previously the act of using Chrome's password fill on that field would have put `webdevguru` into the Room Filter field.

**Pull request merged**
