### PR TITLE
made signin appear on the login page and fixed the padding issue 

### PR DESCRIPTION
**Pull request by aryabyte21**
fixed this issue https://github.com/vector-im/element-web/issues/21545

 Arya Bhosale <arya2001bhosale@gmail.com>

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * made signin appear on the login page and fixed the padding issue  ([\#8163](https://github.com/matrix-org/matrix-react-sdk/pull/8163)). Contributed by @aryabyte21.

Preview: https://pr8163--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by andybalaam** [comment]
@AryaArunB the issue that you linked to is a pull request, not a bug so I'm not sure what this is fixing?

**Comment by gsouquet** [comment]
This issue was already claimed by someone else, and a PR was already open https://github.com/matrix-org/matrix-react-sdk/pull/8143
I will unfortunately have to decline this pull request

**Comment by andybalaam** [comment]
@AryaArunB you can still list this work under your contributions for Outreachy. Please look for issues where there is not already a pull request attempting to fix them.

**Comment by luixxiul** [comment]
I think this should be reopened as I've closed that PR of mine in favor of this. See: https://github.com/matrix-org/matrix-react-sdk/pull/8143#issuecomment-1096612558

**Comment by andybalaam** [comment]
@AryaArunB are you interested in improving this to do what @janogarcia said [in #8143](https://github.com/matrix-org/matrix-react-sdk/pull/8143#issuecomment-1096612558)?:

> The correct way to handle it would be to use a busy state for the button (disabled button, loading spinner inside), so there are no UI reflows / layout shifts involved

**Comment by AryaArunB** [comment]
Sure @andybalaam

**Review by germain-gg — COMMENTED** [review]
Marking this issue as draft, can you let me or Andy know when this is ready to be reviewed and we'll add this back to the queue

**Pull request closed without merging**
