### PR TITLE
Update the avatar mask so it doesn’t cut off spaces’ avatars anymore

### PR DESCRIPTION
**Pull request by justjanne**
Type: Defect
Related: https://github.com/vector-im/element-web/issues/22589

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Update the avatar mask so it doesn’t cut off spaces’ avatars anymore ([\#8849](https://github.com/matrix-org/matrix-react-sdk/pull/8849)). Contributed by @justjanne.

### CODE REVIEW

**Comment by justjanne** [comment]
We already use border-radius to ensure rounded edges for space, user and room avatars everywhere, so the mask shouldn’t have them hardcoded (especially as different avatars use different border radii)

**Comment by t3chguy** [comment]
`dnd-avatar-mask` can be deleted and `.mx_UserMenu_cutout` deleted, it is no longer used

**Comment by t3chguy** [comment]
Any chance of a screenshot how a Space with the cutout & dot looks?

**Comment by justjanne** [comment]
## In Action

New search experience dialog showing room and space results with the new mask

**Comment by weeman1337** [comment]
Just checked the user avatars on the Netlify deployment. Looks good!

image

**Pull request merged**
