### PR TITLE
New User Onboarding Task List

### PR DESCRIPTION
**Pull request by justjanne**
Type: Enhancement
Related: https://github.com/vector-im/element-web/issues/22463
Related: https://github.com/vector-im/element-web/issues/21947
Related: https://github.com/vector-im/element-web/issues/22880
Closes https://github.com/vector-im/element-web/issues/22919

---
Here's what your changelog entry will look like:

## ✨ Features
 * New User Onboarding Task List ([\#9083](https://github.com/matrix-org/matrix-react-sdk/pull/9083)). Fixes vector-im/element-web#22919. Contributed by @justjanne.

### CODE REVIEW

**Review by gsouquet — COMMENTED** [review]
Looks quite sensible overall!
There's probably a few thing that would benefit from being tested in there, what's your plan on that front?

**Review by gsouquet — COMMENTED** [review]
I believe `res/img/user-onboarding/CommunityMessaging.png` would benefit from being compressed. I think it's the original file size and it's rather large compared to the other assets

**Review by gsouquet — APPROVED** [review]

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
**Non-task list UI**

These are changes not specific to the list, but as part of optimising the experience for new users.

- [ ] Remove the skeleton ui when no rooms and no people in the relevant lists.  This could distract people from the list, make them think there's more things loading.  We've had feedback from users that they felt something was loading, but nothing was of course.

**Task list**

- [x] Alignment of text and elements.

In Figma, the text in the hero section and the list line up like so

image

- [x] Animation of progress

Can we have the green progress bar grow in width or from left to right - so its hopefully more clear that it means progress.  Example:

https://user-images.githubusercontent.com/1587166/181592567-00e5ddb9-8dca-4fff-86ac-656825466c7a.mov

I would bring the grey bar in at the same time as "only X steps to go" and then, have the green progress bar grow in width.

- [ ]  More responsive?

In general, unfortunately, I don't think we ever put much focus into making much of the app responsive but I wonder if, this being early in someone's experience, its worthwhile it being slightly more responsive.  If we have some specific widths we target, or you have suggested widths, I'm happy to generate some designs if it helps.  But things could just be tidied up a tiny bit.

image

- [x] Max-width

Adding a max width will help keep the content readable, in designs I'm using 900px but I'm happy to use something else too - somewhere around there.

- [x] Hero Title - make green full stop at end green.
- [x] Hero paragraph - remove margin top and bottom

- [ ] Revealing content slowly

 I think we should reduce the amount of content shown at first, and reveal the hero section followed by the task list.  Something like this for the top section (please feel free to ignore the rest of it).

ezgif-1-38005a7cf9


At the moment, you see the list animate which distracts you from the top section.

**Comment by justjanne** [comment]
Regarding the skeleton UI, that’s already a separate issue: https://github.com/vector-im/element-web/issues/15797

**Review by niquewoodhouse — APPROVED** [review]

**Pull request merged**
