### PR TITLE
Fix minimized left panel avatar alignment

### PR DESCRIPTION
**Pull request by SimonBrandner**
I've fixed the alignment of the avatar icon in the left panel while it's minimized.

Before:

Screenshot_20201215_144046

After:

Screenshot_20201215_144025

### CODE REVIEW

**Review by jryans — APPROVED** [review]
Code wise it looks fine to me, thanks!

**Comment by jryans** [comment]
@matrix-org/design: It's not immediately clear to me what's intended here design-wise, so the main question to resolve whether the above change matches your expectations when the left panel is minimised.

**Comment by turt2live** [comment]
@jryans this is just an implementation bug. It's supposed to be aligned. Not sure if this qualifies as not needing design review though.

**Comment by jryans** [comment]
> @jryans this is just an implementation bug. It's supposed to be aligned. Not sure if this qualifies as not needing design review though.

Aha, thanks, then let's just go with it. 😄

**Pull request merged**
