### PR TITLE
Implement tab-complete for slash commands

### PR DESCRIPTION
**Pull request by Kegsay**
This needed a new interface function `getOverrideSuffix()` so we didn't suffix
commands at the start with ": ". All seems to work.

Fixes https://github.com/vector-im/vector-web/issues/417

### CODE REVIEW

**Comment by ara4n** [comment]
Looking at the behaviour rather than the code: this is almost excellent - thanks!  From a UX perspective i think the utility is very limited however unless the tabcomplete entries actually give us a hint of the command's arguments.  Can we just put basic BNF-style syntax in the prompt for now?  So:

```
/nick <new display name>
/tint <primary color> [<secondary color>]
/me <action>
/encrypt <on|off>
/topic <new topic>
/invite <user id>
/join <room alias>
/part [<room alias>]
/kick <user id> [<reason>]
/ban <user id> [<reason>]
/unban <user id>
/op <user id> [<power>]
/deop <user id>
```

I'll then go fix the CSS to make these nice pretty lozenges.

**Comment by dbkr** [comment]
lgtm

**Comment by Kegsay** [comment]
@ara4n PTAL

**Comment by ara4n** [comment]
Looks good, but can you add in `/me` please? :)

**Comment by Kegsay** [comment]
Eugh, but it isn't actually a proper command as such... will have to fudge it in.

**Pull request merged**
