### PR TITLE
Apply new design to highlighted tags and add toggle mechanic

### PR DESCRIPTION
**Pull request by t3chguy**
Based on top-left corner of
image

image

### CODE REVIEW

**Comment by t3chguy** [comment]
Nad wants more design applied to this, taking it off review for now

**Comment by t3chguy** [comment]
- [ ] Margins between the tiles need adjusting
- [ ] Colouring of the `+` Communities button needs adjusting

image

**Comment by t3chguy** [comment]
Colours matching the + buttons on room sublist

image

**Comment by t3chguy** [comment]
image

**Comment by nadonomy** [comment]
@t3chguy visually LGTM, with the caveat that we should be on guard for feedback on /develop to reduce some of the whitespace.

Thanks for doing this!

**Comment by t3chguy** [comment]
# We should watch for people on /develop complaining about the spacing here as it is still up for shrinking

**Pull request merged**
