### PR TITLE
Improved ringtone sound

### PR DESCRIPTION
**Pull request by itay-grudev**
Ringtone provided by **Baptiste Gelez** (@elegaanz) who has graciously agreed to distribute his ringtone under the terms of the Apache License.

Replaces the high-pitch, widely disliked original ringtone. I would like to apologise in advance to the original ringtone artist for the somewhat harsh words and I would like to thank them as their work has been the sound of Riot for years. I also believe it is time for change and I quite like this one.

Here is a link to the proposed new sound: [:play_or_pause_button: `Ringtone by Baptiste Gelez`](https://raw.githubusercontent.com/matrix-org/matrix-react-sdk/f81db65e82873d38ce8fb0a56f7e92b1dd23c7b5/res/media/ring.ogg)

Current ringtone (for comparison): [:play_or_pause_button: `Current ringtone`](https://raw.githubusercontent.com/matrix-org/matrix-react-sdk/8371774d1301e8648c998b552081a360264c9598/res/media/ring.ogg)

Fixes https://github.com/vector-im/riot-web/issues/5031

@YoanaGrudeva

### CODE REVIEW

**Comment by turt2live** [comment]
@itay-grudev Please sign off on these changes per the contributing guidelines, then we'll be able to take a look. Thanks!

**Comment by itay-grudev** [comment]
@turt2live Commit amended to include Sign off.

**Comment by turt2live** [comment]
Thanks!

**Comment by itay-grudev** [comment]
# [:play_or_pause_button:](https://raw.githubusercontent.com/matrix-org/matrix-react-sdk/f81db65e82873d38ce8fb0a56f7e92b1dd23c7b5/res/media/ring.ogg)

**Comment by itay-grudev** [comment]
@turt2live I can't see what code needs to be changed, though that seems unlikely as I just replaced the old sound files - same filename.

**Comment by turt2live** [comment]
The extension changed.
image

**Comment by turt2live** [comment]
oh github is awful and doesn't show this well at all. I see what happened now.

**Comment by itay-grudev** [comment]
@turt2live The extension wasn't changed. I replaced both files. One was reduced in size while the other increased slightly.

**Comment by itay-grudev** [comment]
Look very carefully at the numbers.

image

**Comment by nadonomy** [comment]
Hey @itay-grudev & @elegaanz thanks for this contribution!

While this may be a marked improvement, we wouldn't like to merge this into the project as is. This clashes with some notification work we're (@matrix-org/design) doing internally and any updates to the sounds would have to be part of a pack with variations for multiple contexts, rather than just one sound being changed arbitrarily. 

We're actually slightly along with choosing some sound packs, but if you'd be interested to talk more feel free to DM me on Matrix: [https://matrix.to/#/@nadonomy:matrix.org](https://matrix.to/#/@nadonomy:matrix.org)

Also @turt2live (& @jryans) for future & posterity— I noticed there were no attributions as a part of this PR, if we're accepting assets as a part of community PRs should they have some kind of license/attribution? Should they be listed under Credits in Settings/Help & About? Should this be documented in our contributing docs?

**Comment by turt2live** [comment]
> I noticed there were no attributions as a part of this PR, if we're accepting assets as a part of community PRs should they have some kind of license/attribution?

@nadonomy this is typically going to be a legal department question (meaning Matthew and friends at the moment). From my understanding, it depends entirely on the license and the license granted to us. If it's creative commons for instance, we'd need to acknowledge it in settings I think, and probably somewhere else within the repo itself. Historically we have not had to worry about this from a contributor perspective as we the team have made and managed the changes going through.

The next steps, if approved from design, were to be figuring out the licensing side and make changes as needed.

**Comment by itay-grudev** [comment]
@nadonomy 
1. The current sound set is not very consistent from a style perspective and I don't believe this one is so different and inconsistent.
2. The author agreed to release it under the same license as the whole project making the legal issue extremely simple as for attribution, since this project doesn't have an `AUTHORS` file I made sure the sound files have the correct headers.
3. I am a Lead Software Developer. I know how redesign projects work. It could take ages to get them done and in the mean time we might as well use this improvement. When you update the whole set you can replace this one as well.

**Comment by nadonomy** [comment]
> @nadonomy
> 
> 1. The current sound set is not very consistent from a style perspective and I don't believe this one is so different and inconsistent.
> 2. The author agreed to release it under the same license as the whole project making the legal issue extremely simple as for attribution, since this project doesn't have an `AUTHORS` file I made sure the sound files have the correct headers.
> 3. I am a Lead Software Developer. I know how redesign projects work. It could take ages to get them done and in the mean time we might as well use this improvement. When you update the whole set you can replace this one as well. I didn't do any drastic changes.
> 
> I was just really pissed at my family refusing to use Riot because of this and that... And the really annoying ringing sound...

@itay-grudev I respect those points, but the core basis of [my original reply](https://github.com/matrix-org/matrix-react-sdk/pull/4500#issuecomment-620942203) still holds  true. It doesn't make sense to arbitrarily change one sound on one platform while we've already started work on audio notifications.

We'd rather [measure twice & cut once](https://en.wiktionary.org/wiki/measure_twice_and_cut_once) (well, thrice when counting iOS, the web & Android) than merge in this piecemeal.  

But again, if there are more sounds available and you/your friend would like them to be a part of that conversation please [DM me on matrix](https://matrix.to/#/@nadonomy:matrix.org).

**Comment by jryans** [comment]
Thanks for working on this a few months back. As the Design team mentioned above that they'd like to handle this as part of reworking notifications more generally, I don't think it makes sense to keep this open for the moment. We'll keep the sound in mind as we work on notifications.

**Comment by itay-grudev** [comment]
@nadonomy I would like to remind you how this clashed with the design work you planned to release shortly. It's been two years where people have expressed strong irritance towards the original ringtone. @jryans Maybe it's worth revisiting this, after no progress has been made in such a long timeline.

**Comment by GarthPS** [comment]
I could not agree more !!

**Comment by claell** [comment]
> We'd rather [measure twice & cut once](https://en.wiktionary.org/wiki/measure_twice_and_cut_once)

Seems like the saw broke over time of "measurement" 😢

Also, this reasoning is not making sense. The phrase is used in cases where it can be helpful to measure twice to avoid unnecessary work in the future (effort of measurement is much less high than effort of breaking a product by cutting wrong). Here, already done good work is just abolished. That is not saving any effort and just frustrates everybody 🥲. The phrase applicable is "Don't let perfect be the enemy of good".

Can't we just show some love and do something good together as a community in the spirit of open source? ❤️ This is also very important from a psychological POV (self-efficacy).

@kongo09 another one to get feedback from product on. 😉

**Comment by claell** [comment]
@ara4n @turt2live: Your request (https://github.com/vector-im/element-web/issues/16927) was apparently heard (about one year! before you even made it 😉). But your own team didn't see this to be the correct route to go.

You requested:
> Please can we swap it for anything which sounds better.

This is done here (I guess).

But this wasn't accepted. How to proceed?

**Comment by turt2live** [comment]
From the backlog here, this wasn't accepted due to planned work in the area, but obviously plans changed. Discussion on the new issue is preferred rather than posting on an ancient PR: https://github.com/vector-im/element-web/issues/5891

Please also avoid pinging people arbitrarily - notifications are sent to those interested when you leave a comment, and pinging people implies that literally no one else can help you, which is false.

**Comment by claell** [comment]
Thanks for your reply. I specifically pinged some people as they were contributing in corresponding issues. Also, there seems to have been different statements on how to proceed with this in the team, so I wanted to bring the relevant parties on board. Not as an implication that I need help from them specifically, but to notify the relevant people about issues relevant to them. Sorry, probably you were only involved with triaging, so that was not really a relevant ping.

Regarding the issue: https://github.com/vector-im/element-web/issues/5891 is the wrong one 😉. It is talking about customizing the sounds.

The right one is https://github.com/vector-im/element-web/issues/5031 (talking about replacing the defaults).

But in general, sure, we can continue that discussion on that issue. I basically just want to know whether this PR can be merged now, or whether the team is wanting to work on their own solution (with unknown ETA).

**Pull request closed without merging**
