### PR TITLE
hide the rightpanel by default

### PR DESCRIPTION
**Pull request by ara4n**

### CODE REVIEW

**Comment by ara4n** [comment]
actually, i want to tweak the CSS a bit so MiddlePanel doesn't change position when you hide/show the RightPanel

**Comment by ara4n** [comment]
bleurgh, this is a mess - the CSS is fixed now, but the UX still sucks, as you lose all the 3 RightPanel buttons when it's collapsed, and the UX for expanding it again has been broken forever.

It feels like the 3 RightPanel buttons should be visible all the time... but then they're going to jump nastily when the RightPanel is toggled.  At this point I almost feel like jumping ahead and implementing the new design :/

**Comment by lukebarnard1** [comment]
> I almost feel like jumping ahead and implementing the new design :/

So let's close this in favour of redesign?

**Comment by lukebarnard1** [comment]
Closing this pending redesign

**Pull request closed without merging**
