### PR TITLE
Watch `RoomList.backgroundImage`

### PR DESCRIPTION
**Pull request by SimonBrandner**
Type: task

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

Preview: https://611fb5824a407b831ca385bd--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by Palid** [comment]
@SimonBrandner are you sure it won't get overriden by `OwnProfileStore.instance.on(UPDATE_EVENT, this.refreshBackgroundImage);` ?

**Comment by SimonBrandner** [comment]
> @SimonBrandner are you sure it won't get overriden by `OwnProfileStore.instance.on(UPDATE_EVENT, this.refreshBackgroundImage);` ?

What exactly do you mean by overridden?

**Comment by SimonBrandner** [comment]
Oh, you mean that when the user changes their avatar, it will be overridden by the avatar? That is intentional, the fact that you can change this is an easter egg

**Comment by Palid** [comment]
> Oh, you mean that when the user changes their avatar, it will be overridden by the avatar? That is intentional, the fact that you can change this is an easter egg

Hmm, sounds good.  I'll refrain from accepting though, I'll make someone with more experience in this project click the merge button. 😄

**Review by turt2live — APPROVED** [review]

**Pull request merged**
