### PR TITLE
Fixed 1px jump upwards

### PR DESCRIPTION
**Pull request by nigelrudolf**
Fixes https://github.com/vector-im/element-web/issues/15048

### CODE REVIEW

**Comment by t3chguy** [comment]
The design has this being a 16x16 so really we can't change that, plus wouldn't that break the centering?

**Comment by nigelrudolf** [comment]
Ok I see, how about setting the input element to a height of 16px?

**Comment by t3chguy** [comment]
That sounds sensible :)

**Review by turt2live — CHANGES_REQUESTED** [review]
I'm flagging this as needing changes so it's not in my review queue forever

**Review by t3chguy — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
