### PR TITLE
Trim spurious whitespace of nicknames

### PR DESCRIPTION
**Pull request by Transfusion**
Fixes vector-im/element-web#15374.

Signed-off-by: Bryan Kok <bryan.wyern1@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
Needs DCO sign-off as per https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst#sign-off

**Comment by t3chguy** [comment]
There are other ways of setting your displayname, such as Slash Commands, might be sane to cover those too, maybe also room names and such.

**Comment by Transfusion** [comment]
> There are other ways of setting your displayname, such as Slash Commands, might be sane to cover those too,
https://github.com/matrix-org/matrix-react-sdk/blob/d5e9d5306a638f217a29cbf3e6467e1e2d262ebf/src/SlashCommands.tsx#L1063-L1080

It appears that Slash Commands already trim the space in between the base command (like `/roomname`, `/nick`, and `/myroomnick`), and any trailling whitespace.
image

**Review by t3chguy — APPROVED** [review]
Looks sane to me, thanks. Sorry this fell through a crack

**Pull request merged**
