### PR TITLE
Add jump to related event context menu item

### PR DESCRIPTION
**Pull request by gsouquet**
Fixes https://github.com/vector-im/element-web/issues/19883

Done with my community hat on

I have the "show hidden events" labs flag on. I sometimes wish to see the related event an annotation is linked to. There are no easy way of achieving that. For that reason I thought of adding a link in message context menu to jump to the related event

Screen Shot 2021-09-09 at 19 57 02

Keen to hear feedback and see whether it'd help anyone else

---
Here's what your changelog entry will look like:

## ✨ Features
 * Add jump to related event context menu item ([\#6775](https://github.com/matrix-org/matrix-react-sdk/pull/6775)). Fixes vector-im/element-web#19883.

Preview: https://613a5ae84b89dd00d8f8a880--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
We might want to put this behind a labs flag (or behind the `show hidden events` flag that already exists) as it will show up for things like replies. Generally, we want these things to show up only to developers.

**Comment by SimonBrandner** [comment]
IMO, we should rename the `Show hidden events` to `Developer mode`, move it out of labs and also move `View source` there

**Comment by gsouquet** [comment]
> We might want to put this behind a labs flag (or behind the `show hidden events` flag that already exists) as it will show up for things like replies. Generally, we want these things to show up only to developers.

I don't think it would be a bad things for it to show up for replies. I guess it's an alternative way to jump to the original event. There's often a couple of different paths to reach the same destination. 
Let's wait on the design review and see what they believe would be the best way to approach this for Element

**Comment by JokerGermany** [comment]
> IMO, we should rename the `Show hidden events` to `Developer mode`, move it out of labs and also move `View source` there

I don't think that `Show hidden events` is only for Developers.
Yes i think it can be moved out of Labs, but i don't think it should be in developer mode.

I helps me see what messages are changed, if there are new reactions and so on.

**Comment by JokerGermany** [comment]
But yeah it's not nice, that it appear for thinks like replies, too...
Perhaps linking the event Text (like a reply) on the related event is better?

**Review by janogarcia — COMMENTED** [review]
@gsouquet, I'd suggest, for now, enabling it **only for hidden events** when in developer mode.

Also, as we may end up using the link icon for other purposes (e.g. a single click action for copying the link to an event, as we did for threads) I'd suggest using the back arrow icon for this purpose, and maybe updating the copy to `View related event`.

Compound – Figma

**Comment by janogarcia** [comment]
@gsouquet Dropping the icon here. 
[child-icon.zip](https://github.com/matrix-org/matrix-react-sdk/files/8732351/child-icon.zip)

**Comment by t3chguy** [comment]
Hmm this seemed to land without design review ✅ 
It is also not hidden behind labs and is using the wrong icon, it either needs someone to fast-follow a fix or it will need reverting. The author is unavailable to do so.

**Comment by turt2live** [comment]
> Also, if "View parent event" makes more sense than "related" and applies to all possible cases, please update the copy.

As a developer tool, "related" is the more accurate phrasing for this case. "Parent" isn't necessarily accurate, but is truthful in lots of cases.

**Comment by JokerGermany** [comment]
Thanks this is a big Feature for me.

[The Jump is a Bit Flickering](https://www.youtube.com/watch?v=avZCfZeUi7A) sometimes, but i really like it. =)

**Pull request merged**
