### PR TITLE
Specify spacing around EventTileBubble for each layout

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes https://github.com/vector-im/element-web/issues/22758

This PR removes the default margin declaration from `_EventTileBubble.scss` to specify the value for each layout. It also aligns the bubble with normal event tiles on IRC layout.

|Before|After|
|---------|------|
|before1|after1|

https://user-images.githubusercontent.com/3362943/177711769-b963efc5-db81-4266-b5ce-b1a3f5ba74d5.mp4

type: defect
Notes: Align verification bubble with normal event tiles on IRC layout

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Align verification bubble with normal event tiles on IRC layout ([\#9001](https://github.com/matrix-org/matrix-react-sdk/pull/9001)). Fixes vector-im/element-web#22758. Contributed by @luixxiul.

### CODE REVIEW

**Comment by weeman1337** [comment]
Maybe I am a bit picky :laughing: But can you make the space around the tiles equal:

image

The call / verification tile have different spacing.

**Comment by luixxiul** [comment]
@weeman1337 Which layout is it? Is it bubble layout?

**Review by weeman1337 — COMMENTED** [review]
Tested an looks good. Can you check the alignment detail?

**Comment by weeman1337** [comment]
> @weeman1337 Which layout is it? Is it bubble layout?

Yes, bubble layout

**Comment by luixxiul** [comment]
It should be fine now.

I am not really satisfied with the fact that inline spacing of tiles are not normalized (between call event tiles and verification request tiles on your screenshot for example), but it is out of scope.

**Review by weeman1337 — APPROVED** [review]
LGTM now :+1:

**Comment by luixxiul** [comment]
@weeman1337 Thanks for reviewing.

**Pull request merged**
