### PR TITLE
Collect decryption failure translations together

### PR DESCRIPTION
**Pull request by richvdh**
They are not specific to threads.

### CODE REVIEW

**Comment by t3chguy** [comment]
Only changing the en file, the rest of the updates would need to be done via Localazy which owns those files.

**Comment by richvdh** [comment]
I thought I asked you about this and you told me I had to change it. And I spent two hours writing a script to do so :angry:

**Comment by richvdh** [comment]
> Only changing the en file

Done.

**Comment by t3chguy** [comment]
> I thought I asked you about this and you told me I had to change it. And I spent two hours writing a script to do so 😠

All I recall is you asking if we had such a script and I answered you that we did: https://github.com/matrix-org/matrix-web-i18n/blob/main/scripts/rekey.ts

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
