### PR TITLE
Set margin between "Forgot passwords?" and SSO buttons

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes vector-im/element-web#21545

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

https://user-images.githubusercontent.com/3362943/159900189-885d2aa7-cdc2-400f-88b3-4fba684b6925.mp4

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Set margin between "Forgot passwords?" and SSO buttons ([\#8143](https://github.com/matrix-org/matrix-react-sdk/pull/8143)). Fixes vector-im/element-web#21545. Contributed by @luixxiul.

Preview: https://pr8143--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — COMMENTED** [review]
hmm, maintaining either the button itself or moving the spinner above the SSO buttons would probably be best - both before and after this bug it's far too easy to double click and end up in a bad spot.

Passing off to design before code review.

**Comment by luixxiul** [comment]
This case https://github.com/matrix-org/matrix-react-sdk/pull/8163 should just be reopened to fix the issue.

**Comment by janogarcia** [comment]
Thanks @luixxiul, but I agree with @turt2live remarks. The correct way to handle it would be to use a busy state for the button (disabled button, loading spinner inside), so there are no UI reflows / layout shifts involved.

Two questions for @turt2live:

- Do we have such a busy state already that we can reuse?
- This shouldn't be on the contributor's plate if not interested / can't contribute it. In that case, should we just close this PR without merging?

**Comment by luixxiul** [comment]
> The correct way to handle it would be to use a busy state for the button (disabled button, loading spinner inside), so there are no UI reflows / layout shifts involved.

I would totally agree :+1:

**Comment by turt2live** [comment]
> - Do we have such a busy state already that we can reuse?

We have a disabled state, yea. Should be easy to copy.

> - This shouldn't be on the contributor's plate if not interested / can't contribute it. In that case, should we just close this PR without merging?

Yup, though they've done so from the looks of it ;)

**Comment by luixxiul** [comment]
#8163 was closed in favor of this. That should be reopened. It should realize https://github.com/vector-im/element-web/issues/21545#issuecomment-1079617500

**Pull request closed without merging**
