### PR TITLE
Remove more unused strings

### PR DESCRIPTION
**Pull request by pafcu**
Signed-off-by: Stefan Parviainen <pafcu@iki.fi>

Remove the following unused strings:

demote
favourite
tag direct chat
restore
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
Never send encrypted messages to unverified devices in this room
to browse the directory
to start a chat with someone
You're not in any rooms yet! Press
to make a room or
joined and left
times
joined
left
and
or
left and rejoined
Set
rejected
Failed to register as guest:
had
%(weekDayName)s, %(monthName)s %(day)s %(fullYear)s
%(weekDayName)s, %(monthName)s %(day)s

After this PR, all the keys found in the current translations can be automatically extracted from the source code.

### CODE REVIEW

**Comment by lukebarnard1** [comment]
OK, after a quick sanity check, I think this is fine. But there are some conflicts to resolve first (due to us taking too long to actually review this, sorry @pafcu)

**Comment by pafcu** [comment]
I suspect it's just easier to regenerate the list rather than sorting out the conflicts.

**Comment by lukebarnard1** [comment]
Oh! There are more conflicts than there were yesterday apparently... @pafcu if you could do that, it'd be much appreciated!

**Comment by pafcu** [comment]
Yep, I think I'll just wait for things to calm down a bit string-wise. I suspect with all the activity going on right now any PR will get old quite fast.

**Comment by lukebarnard1** [comment]
>I'll just wait for things to calm down a bit string-wise

**Pull request closed without merging**
