### PR TITLE
Improve bubble layout colors

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/18081

<hr>

Screenshot_20210804_083210
Screenshot_20210804_083236

### CODE REVIEW

**Comment by gsouquet** [comment]
That looks good on the code side of things.

There's probably a few more colours we'll want to update and I know that @amshakal is currently looking into that. Will hold off merging this PR until they are decided

**Review by gsouquet — APPROVED** [review]

**Comment by amshakal** [comment]
The internal design review for these bubbles took a while. Here are the colours we reached at:

Light theme
Sender bubble colour: Accent with 6% opacity (#F0FBF8)
Receiever bubble colour: System Light (#F4F6FA)
Hover: (#FAFBFD)

Dark theme
Sender bubble colour: Accent with 15% opacity (#14322E)
Receiever bubble colour: System Light (#21262C)
Hover: (#1C2026)

**Comment by SimonBrandner** [comment]
@amshakal, thanks! Will have a look into updating the PR tomorrow

**Comment by SimonBrandner** [comment]
@amshakal, I've updated the colours (and the images in the description). Does this look the way it should?

@gsouquet, I've also re-requested your review as I've made some more changes. (also some unrelated ones to shut up stylelint)

**Review by gsouquet — APPROVED** [review]
Looks good to me! Thank you for working on that 🙌

**Pull request merged**
