### PR TITLE
Implement some parts of new cross signing bootstrap UI

### PR DESCRIPTION
**Pull request by dbkr**
Screenshot 2020-01-22 at 10 34 13

Screenshot 2020-01-22 at 11 44 26

Implements:
 * Password prompt on upgrade from key backup (if HS supports just password auth)
 * New copy on success screen
 * Icons

Not included in the PR:
 * New designs for setting up cross-signing from scratch
 * Remembering password from registration / login
 * Encryption upgrade nag toast

Fixes https://github.com/vector-im/riot-web/issues/11903

### CODE REVIEW

**Comment by jryans** [comment]
@dbkr, could you please add screenshots of what's implemented?

**Comment by dbkr** [comment]
Oops, I even took the screenshots and then forgot to upload them. Both dialogs do actually have the shield, I just took the screenshot before adding it, but it looks the same as the other one obviously.

**Comment by jryans** [comment]
For the remaining pieces, let's ensure we have issues filed for all of them:

> * New designs for setting up cross-signing from scratch

Is that same as what's tracked by https://github.com/vector-im/riot-web/issues/11902?

>     * Remembering password from registration / login

Can you file an issue for this bit, @dbkr?

>     * Encryption upgrade nag toast

I believe this is tracked by https://github.com/vector-im/riot-web/issues/11906.

**Comment by dbkr** [comment]
> > Remembering password from registration / login

> Can you file an issue for this bit, @dbkr?

I can do, although I've been assuming it was covered as part of https://github.com/vector-im/riot-web/issues/11902 (was just calling those things out as things I hadn't included in the PR rather than meaning to imply they were in the scope of #11903).

> so I believe we want to hook into the point in MatrixChat where we're showing the "Complete Security" screen and instead launch this modal.

Yeah, that sounds about right: I'm mostly worrying about getting the flow right in the modal first and was then going to hook that in to happen after registration / login.

**Comment by jryans** [comment]
> > > Remembering password from registration / login
> 
> > Can you file an issue for this bit, @dbkr?
> 
> I can do, although I've been assuming it was covered as part of [vector-im/riot-web#11902](https://github.com/vector-im/riot-web/issues/11902) (was just calling those things out as things I hadn't included in the PR rather than meaning to imply they were in the scope of #11903).

Ah okay, seems fine for this one then, thanks.

> > so I believe we want to hook into the point in MatrixChat where we're showing the "Complete Security" screen and instead launch this modal.
> 
> Yeah, that sounds about right: I'm mostly worrying about getting the flow right in the modal first and was then going to hook that in to happen after registration / login.

Okay great, we're on the same page. If it won't be done as part of the existing issues, please make sure to file a new one for this part.

**Comment by dbkr** [comment]
yep, will do!

**Pull request merged**
