### PR TITLE
Poll history - remove active development labs flag

### PR DESCRIPTION
**Pull request by kerryarchibald**
Polls history is feature complete and has been reviewed by design ([internal ticket here](https://element-io.atlassian.net/browse/PSG-1179))

This PR removes the labs flag used to hide poll history during active development.

Poll history is now accessible through the room info panel and the room settings:
Screenshot 2023-03-14 at 10 40 33

Screenshot 2023-03-14 at 14 08 00

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by florianduros — APPROVED** [review]
LGFM

**Comment by t3chguy** [comment]
@kerryarchibald releasing features from labs needs explicit sign off from product, please acquire posthumously or it'll need reverting

**Comment by kittykat** [comment]
It should ideally have a [review from QA](https://github.com/vector-im/internal-planning/issues/new?assignees=&labels=Team%3A+QA%2CT-Request&template=request-qa.yml&title=%5BQA%5D+%3Ctitle%3E) as well ;)

**Comment by Johennes** [comment]
There is some context missing here. This is a former PS project and, as such, has been managed in Jira. Design review has been completed in https://element-io.atlassian.net/browse/PSG-1179 and cross-platform testing was covered in https://element-io.atlassian.net/browse/PSG-1054.

@jakewb-b would you mind giving us formal product approval for the delabsing?

**Comment by t3chguy** [comment]
@jakewb-b can we have a checkmark please

image

**Comment by jakewb-b** [comment]
@t3chguy - as far as I can see, I don't have the ability to add a review anymore, presumably because this is already merged. Or am I missing something?

**Pull request merged**
