### PR TITLE
Change Rich Quoting HTML Format over the wire

### PR DESCRIPTION
**Pull request by t3chguy**
To something a little richer that will look better on clients that do not yet support this feature whilst still keeping it as easy to parse

Fixes https://github.com/vector-im/riot-web/issues/5967
Fixes https://github.com/vector-im/riot-web/issues/5982

### CODE REVIEW

**Comment by t3chguy** [comment]
TravisCI Chrome is still broken

**Comment by dbkr** [comment]
I think we'll have to do the due diligence here as this is basically spec stuff (even if the actual `blockquote` / `cite` is going into `org.matrix.custom.html`). My main concern here is that the reply metadata is only in the HTML body, so clients that don't render HTML now have to parse the HTML body to support rich quoting. It feels like we ought to have the quoting metadata outside of the body, but then this is starting to intersect with @ara4n 's message typing stuff too.

Shall we get some suggestions on a google doc and try to get some feedback?

**Comment by t3chguy** [comment]
So I'm all for instead throwing `quotedEvent: ".../..."` into the content of the `m.room.message`, it'd mean that there can only be one, but I consider that a good thing
so that an event could not be sent with 100s of the damn things

**Comment by dbkr** [comment]
True, but in the context of a forum post, only being able to cite one message and in no particular point in your message feels quite limiting. I guess this is essentially the same argument as Pills where we eventually put everything into the HTML, so perhaps it's better to be consistent, although I still have the same concern there.

Anyway, arguing myself back & forth aside, unassigning myself to let others chime in.

**Comment by t3chguy** [comment]
Because of https://github.com/vector-im/riot-web/issues/5967#issuecomment-357931310 the semantics are entirely different IMO.
Its more a linear reply to a single precursor. So a `replyingToEvent` field on `m.room.message` events makes most sense for this to me. Though would mean that "dumb" clients would simply render nothing.

**Comment by t3chguy** [comment]
The above would also fix (and seems to be the sanest/only sane way to fix) things like: https://github.com/vector-im/riot-web/issues/6061

**Comment by t3chguy** [comment]
Could also fix node replacing nastiness/race conditions such as https://github.com/vector-im/riot-web/issues/6059#issuecomment-361357885

**Comment by t3chguy** [comment]
Replaced by #1741

**Pull request closed without merging**
