### PR TITLE
Recreate SMIL SVG spinner using CSS Animations

### PR DESCRIPTION
**Pull request by t3chguy**
So that it runs on compositor and is simply more efficient
It also fixes the size to be like the non-Labs one
spinner.svg had a HUGE padding baked in

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by jryans** [comment]
Let's ensure that Design review this as well, to double-check they are the same. Could we have an testing / ad-hoc build to try it out somewhere?

**Comment by t3chguy** [comment]
Its behind Labs, wouldn't it be simpler to just chuck it on develop?

**Comment by jryans** [comment]
Ah right, I forgot the feature flag... Okay, perhaps it's fine then.

**Comment by t3chguy** [comment]
Side-by-side: https://riot.ovh/_matrix/media/r0/download/riot.ovh/ocoyVjYPJbYudkJRUkLrkwjJ

**Comment by jryans** [comment]
Hmm, which is SVG SMIL and which is CSS anim?

Looking in Flow briefly, it appears there's more going on here than just rotation, as it also appears to grow then shrink slightly as well.

@ara4n suggests we may revise this to a different design, so it might be best to park it for now...?

**Comment by t3chguy** [comment]
Left is SVG SMIL

Alright, drafting for now, got a call planned with Nad later on in the week to revisit

**Pull request closed without merging**
