### PR TITLE
Add link to next file in the export

### PR DESCRIPTION
**Pull request by grimhilt**
Fixes https://github.com/vector-im/element-web/issues/20272

There are two links allowing you to move from one file to another. I don't know if the design is great. The links are fixed on the page (visible all time). It may be supposed to be on the content, I don't know.

I also removed the room introduction when it is not the first file as it is not the start of the conversation.

image

Signed-off-by: [grimhilt@users.noreply.github.com](mailto:grimhilt@users.noreply.github.com)

type: Defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Add link to next file in the export ([\#10190](https://github.com/matrix-org/matrix-react-sdk/pull/10190)). Fixes vector-im/element-web#20272. Contributed by @grimhilt.

### CODE REVIEW

**Review by florianduros — CHANGES_REQUESTED** [review]
Hi ! First of all, thanks for your contribution !

I tested the fix and I noticed one issue:

- Exported the current timeline of a room
- One `message.html` is created
- The `next group of messages` link is available at the end of the message
- Since there is only one message, the link is going anywhere

**Comment by grimhilt** [comment]
Yes indeed, I thought I tested that with the snapshot but I updated it with this error.
This is now fixed. Sorry

**Review by florianduros — APPROVED** [review]
Thanks for the fix, it works perfectly !

**Comment by grimhilt** [comment]
Thank you for reviewing and for the great work you do!

**Pull request merged**
