### PR TITLE
Display room name in pills instead of address

### PR DESCRIPTION
**Pull request by SimonBrandner**
A bit of context: I was chatting with someone this morning and they got confused by the fact that the text of the room's pill wasn't the same as the room's name.

Before:
Screenshot_20210212_142644
Screenshot_20210212_082103

After:
Screenshot_20210212_142557
Screenshot_20210212_130441
image

### CODE REVIEW

**Comment by jryans** [comment]
@SimonBrandner I think get the idea, but a screenshot would make it even easier!

The code side is easy to review, but we'll need to check with Product as well.

**Review by jryans — APPROVED** [review]
This seems fine code wise, but we'll need Product approval as well, as I am not sure how we prefer pills to work in such a case.

**Comment by nadonomy** [comment]
@SimonBrandner this looks great!

One thing to consider is we might want this to also be more defensive against phishing attacks, so it would be good to also display the room id prominently with a secondary action. Would you mind adding the room id, in an element web tooltip on hover? I'd prefer this over using native HTML tooltips as native ones can take a while to appear.

@jryans I'm away next week so will leave this in your hands while absent, no need to block merging on me if we can resolve the above!

**Comment by SimonBrandner** [comment]
@nadonomy, thanks for the review! I can surely add a tooltip. I am not sure I understand you. By room id do you mean something like this: `!vJDDwAdAxpkieXYWEp:envs.net`? Or do you mean the address, something like this: `#element-dev:matrix.org
`?

**Comment by nadonomy** [comment]
@SimonBrandner great! I misspoke— you're right, the main address/alias would be ideal when it exists.

There might be some precedent on the critical thinking side for what to show if the main address doesn't exist. @jryans do you know of any? Can you think of anything pragmatic?

**Comment by SimonBrandner** [comment]
Screenshot_20210212_082103

Should I change this as well?

**Comment by jryans** [comment]
> There might be some precedent on the critical thinking side for what to show if the main address doesn't exist. @jryans do you know of any? Can you think of anything pragmatic?

Hmm, I suppose if there's no main address, we could just show the first address (if any exist). I don't know that we have any way to know which address to prefer (when there's no main one)... Perhaps preferring any addresses that match the user's own server would make sense, if any exist.

**Review by jryans — APPROVED** [review]
Thanks, this looks good code wise! @SimonBrandner, is there anything left to do here before this merges?

**Comment by SimonBrandner** [comment]
@jryans, thanks! I think this is ready

**Pull request merged**
