### PR TITLE
Fix translucent `TextualEvent` on search results panel

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes https://github.com/vector-im/element-web/issues/25292

This PR intends to reset a opacity setting for `TextualEvent` on search results panel, making it opaque.

Currently, `EventTile`s with `mx_EventTile_contextual` class name are translucent ([`0.4`](https://github.com/matrix-org/matrix-react-sdk/blob/de16d347e9294f9f4771ca4bc950fcf1e8c1acb4/res/css/views/rooms/_EventTile.pcss#L135)). Applying that value to contextual `TextualEvent`s (which are applied with [`0.5`](https://github.com/matrix-org/matrix-react-sdk/blob/de16d347e9294f9f4771ca4bc950fcf1e8c1acb4/res/css/views/messages/_TextualEvent.pcss#L18) opacity by default) makes them even more transparent (0.4 x 0.5 = 0.2), which is problematic for a11y.

There are several possibilities here;

- a) display found `TextualEvent`s in full opaqueness, in the same way as other normal `EventTile`s on the search panel
- b) apply the same opacity to both contextual `TextualEvent`s and found `TextualEvent`s, not making the latter fully opaque
- c) hide `TextualEvent`s on the search result panel altogether

I'm not quite sure which one has been intended here, but I *believe* a) is a plausible solution here, since `TextualEvent` itself is searchable and the default opacity setting of `TextualEvent` seems to be intended to be applied to ones inside GELS (`mx_GenericEventListSummary`) on the main timeline only.

Design input is appreciated.

| |Before|After|
|-|--------|-------|
|Search `Element` on<br />#element-web-announcements:matrix.org|<br />Contextual `TextualEvent`s lack contrast and hard to read|<br/>`TextualEvent` about topic change becomes fully opaque|
|Cypress| ||

type: defect

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix translucent `TextualEvent` on search results panel ([\#10810](https://github.com/matrix-org/matrix-react-sdk/pull/10810)). Fixes vector-im/element-web#25292. Contributed by @luixxiul.

### CODE REVIEW

**Comment by luixxiul** [comment]
There are actually several possibilities here;

- a) display found `TextualEvent`s in fully opacity
- b) apply the same opacity to both contextual `TextualEvent` and found `TextualEvent`s, not making them fully opaque
- c) hide `TextualEvent` on the search result panel altogether

I thought a) was a plausible solution here, but I'm not quite sure what is the intended result here.

**Comment by t3chguy** [comment]
The opacity was added intentionally by some old designs, I think this needs a design pass rather than simply being improved, hopefully Compound's new colour ranges will fix this, no? 

cc @gsouquet

**Comment by luixxiul** [comment]
So should this be this one?

> b) apply the same opacity to both contextual TextualEvents and found TextualEvents, not making the latter fully opaque

I do not think `0.2` opacity was intended.

**Review by t3chguy — APPROVED** [review]
This is a quantifiable improvement either way, and Compound has plans for a contrast colour and typography pass which will align it

Thanks

**Comment by luixxiul** [comment]
The conflict was fixed.

**Comment by luixxiul** [comment]
The snapshot was taken here: https://percy.io/dfde73bd/matrix-react-sdk/builds/28088183/search/preview/1562071752

**Pull request merged**
