### PR TITLE
Spaces quick settings

### PR DESCRIPTION
**Pull request by t3chguy**
Part of https://github.com/vector-im/element-web/issues/19529

Behind metaspaces labs flag

image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Spaces quick settings ([\#7196](https://github.com/matrix-org/matrix-react-sdk/pull/7196)).

Preview: https://61a0fdd86ee8412a39e23980--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by dbkr — APPROVED** [review]

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
Small things:

**Button**
- [ ] On hover, can the icon colour change to primary-content

**Menu**
- The theme dropdown gets a blue border on focus - is that our component?  I'm just wondering if we have scope to change that across the product, maybe you can point me to where there's one already and I can give it a go?
- I had a close button in the wireframes, but prefer it without, thanks.
- [ ] The pin icon is missing, can it be aligned to the right of the "Pin..." title

**Comment by Palid** [comment]
> * The theme dropdown gets a blue border on focus - is that our component?  I'm just wondering if we have scope to change that across the product, maybe you can point me to where there's one already and I can give it a go?

@niquewoodhouse this is probably the default a11y thing that browsers do, I would be very much against removing it.

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
@t3chguy Seeing it in practice, I'm sorry, I think the pin feels more awkward on the right, so could we please position left?

**Comment by t3chguy** [comment]
image

@niquewoodhouse Done

**Review by niquewoodhouse — APPROVED** [review]

**Pull request merged**
