### PR TITLE
Prevent Invite and DevTools dialogs from being cut off

### PR DESCRIPTION
**Pull request by justjanne**
Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/20911
Closes: #8165

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Prevent Invite and DevTools dialogs from being cut off ([\#8646](https://github.com/matrix-org/matrix-react-sdk/pull/8646)). Fixes vector-im/element-web#20911 and undefined/matrix-react-sdk#8165. Contributed by @justjanne.

### CODE REVIEW

**Comment by luixxiul** [comment]
FWIW: https://github.com/matrix-org/matrix-react-sdk/pull/8165#pullrequestreview-937076918

> I'm still generally concerned that the change is wider spread than the two dialogs. I'm very mindful that we have half a dozen ways to construct a dialog, but finding the commit/change which caused the regression in the first place would be ideal to help identify all of the affected dialogs.
>
> I don't think we need to introduce flexboxes in the dialogs to fix this.

**Comment by justjanne** [comment]
> FWIW: [#8165 (review)](https://github.com/matrix-org/matrix-react-sdk/pull/8165#pullrequestreview-937076918)

Yeah, I’d have preferred if we could have done it without that as well. Sadly, after reviewing all dialog code, it turns out that’s not really possible, as it’s not as simple of an regression as expected.

**Comment by luixxiul** [comment]
@justjanne yeah, I would totally agree with you.

**Comment by justjanne** [comment]
Note that (for some reason) my browser ignores the overflow setting on one element, so in these screenshots you’ll just see elements move around, but not being cut off (neither before nor after).

## DM Dialog

* Before: Before
g
* After: After

## Invite Dialog

* Before: Before
* After: After

## Call Transfer (to user)

* Before: Before
* After: After

## Call Transfer (to number)
* Before: Before
* After: After

These are all variants of the invite dialog, they are the only dialogs affected by this change besides the devtools dialog.

I haven’t taken screenshots of the devtools dialog yet, if that’s requested I can take those as well

**Review by gsouquet — APPROVED** [review]
That looks good to me 👍

**Pull request merged**
