### PR TITLE
Fix condition of logging possible room list corruption

### PR DESCRIPTION
**Pull request by weeman1337**
Reverts the logging condition [changed here](https://github.com/matrix-org/matrix-react-sdk/commit/9aef1874db09f0eb0eefca83d42e98b6afac7f40#diff-58fb34f963968c49c6e28c428d27861c6e078a05b7a86afe4ba9a814145617beR296)

fixes https://github.com/vector-im/element-web/issues/25099

PSF-1999

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by weeman1337** [comment]
We can probably add a test once https://github.com/matrix-org/matrix-react-sdk/pull/10682 is merged

**Review by dbkr — COMMENTED** [review]
I'm struggling to understand why this is correct. Is it a bad thing for the variables to be undefined or are we saying that's okay? Would a comment explaining the logic help clarify this?

**Comment by weeman1337** [comment]
> I'm struggling to understand why this is correct. Is it a bad thing for the variables to be undefined or are we saying that's okay? Would a comment explaining the logic help clarify this?

To be hones I don't know the logic behind that. [Before](https://github.com/matrix-org/matrix-react-sdk/commit/9aef1874db09f0eb0eefca83d42e98b6afac7f40#diff-58fb34f963968c49c6e28c428d27861c6e078a05b7a86afe4ba9a814145617beR296), the variables were compared without any pre-condition. Comparing a number with `undefined` is always `false` → this PR here should revert the change introduced during TypeScript strictification.

**Comment by dbkr** [comment]
I guess my concern here is if the initial strict fix made the warning fire when it was always supposed to fire and we'd be suppressing it again. If we're not sure whether things are supposed to be undefined here or not, we could be silencing a warning that'd trying to tell us something.

**Comment by weeman1337** [comment]
> I guess my concern here is if the initial strict fix made the warning fire when it was always supposed to fire and we'd be suppressing it again. If we're not sure whether things are supposed to be undefined here or not, we could be silencing a warning that'd trying to tell us something.

One issue may be that the last loop iteration always ends with `undefined`. I've changed to loop condition [here](https://github.com/matrix-org/matrix-react-sdk/pull/10685/files#diff-58fb34f963968c49c6e28c428d27861c6e078a05b7a86afe4ba9a814145617beR290). Logging should be more reasonable now.

**Pull request merged**
