### PR TITLE
fix issue 24419: paragraph display in timeline

### PR DESCRIPTION
**Pull request by alunturner**
This PR addresses the regression raised in [element web  issue 24419](https://github.com/vector-im/element-web/issues/24419).

I didn't realise that including markdown in messages in the current composer resulted in message content being wrapped in p tags, so I didn't realise this would clash with the output from the rich text editor (which almost always wraps paragraphs in p tags).

This gives us a styling issue due to the output from the rich text editor containing empty p tags representing new lines. This is shown in the screenshot. I think that fixing this issue probably warrants a separate piece of work due to it potentially impacting on Android and iOS implementations of the rich text editor.

Element___Alun_Turner

## Checklist

-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * fix issue 24419: paragraph display in timeline ([\#10071](https://github.com/matrix-org/matrix-react-sdk/pull/10071)). Contributed by @alunturner.

### CODE REVIEW

**Comment by alunturner** [comment]
Although this fixes the regression, which is the main aim, I'm not really a fan of the solution breaking the rich text editor implementation as it stands.

Ultimately the problem comes down to how do we differentiate messages composed in different composers to style them as required. I am currently wondering if a message sent from the rich text editor is given a different `content.format`, which is currently set to `matrix.org.custom.html`, but I need to look deeper into the knock on effects of changing the format type.

**Review by dbkr — APPROVED** [review]
Yeah, seems like a reasonable fix for now.

**Comment by t3chguy** [comment]
@alunturner please update the PR title, right now it is quite messy for a changelog entry.

image

Please also use github magic keywords `Fixes vector-im/element-web#24419` for appropriate cross-linking, this would have automatically closed the issue.

**Comment by alunturner** [comment]
Will make that change in another PR

**Comment by Johennes** [comment]
Thanks for the quick fix @alunturner. Given that this regressed, I was wondering if there'd be a reasonable way to cover it with a test to prevent it regressing again in future?

**Comment by t3chguy** [comment]
> Will make that change in another PR

Sorry what do you mean? The title of this PR needs updating as that is what the allchange tooling will see over the github API.

**Comment by alunturner** [comment]
I didn't realise you could change a title after merging, so I thought something would have to be reopened and then was going to amend the changelog manually.

**Comment by t3chguy** [comment]
The changelog is generated at release time rather than at merge time, based on the titles of PRs and/or their `Notes: ` in the PR body

**Pull request merged**
