### PR TITLE
Fix handlebar interaction

### PR DESCRIPTION
**Pull request by JorikSchellekens**
https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$0ARJ2K9VHXkoa7YRVb30dtgh16elucsYGy_554fDJIM?via=matrix.org&via=mozilla.org&via=vector.modular.im

### CODE REVIEW

**Comment by JorikSchellekens** [comment]
@nadonomy

**Comment by jryans** [comment]
I reverted the original styles in https://github.com/matrix-org/matrix-react-sdk/commit/9b13ef1446dbc1fde6251868de1f14ac7cb79e68, which normally I would not do, but it will greatly simplify today's patch release, as I can take everything else form develop.

Please re-add the base commit to this PR, and let's work with Design to find out might be remaining to do here.

**Comment by JorikSchellekens** [comment]
I really have no idea how to do this without a force push so please forgive me

**Comment by JorikSchellekens** [comment]
Well, that didn't work

**Comment by JorikSchellekens** [comment]
image

I think these might be too small

**Comment by t3chguy** [comment]
They were exactly what Nad asked for, they're identical to the room list ones just rotated

**Comment by JorikSchellekens** [comment]
I got the ok for this from Nique. Merging

**Pull request merged**
