### PR TITLE
Don't hide room header buttons in video rooms and rooms with a call

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/23900

<hr>

Hiding the buttons reduces functionality - there is no way to access the threads list, pinned messages and the notifications panel

<hr>

Video rooms:

Huddles:

---
Here's what your changelog entry will look like:

## ✨ Features
 * Don't hide room header buttons in video rooms and rooms with a call ([\#9712](https://github.com/matrix-org/matrix-react-sdk/pull/9712)). Fixes vector-im/element-web#23900.

### CODE REVIEW

**Review by robintown — APPROVED** [review]
Code looks fine. I'll discuss this with Gaëlle tomorrow, but I suspect she'll at least want to keep the header buttons in non-video-room calls hidden

**Comment by germain-gg** [comment]
@SimonBrandner it seems like a valuable thing to merge. Should we get to merge this?

**Comment by SimonBrandner** [comment]
I was waiting for Gaelle's review... Could we get someone from design to review this since Gaelle's not available atm?

**Comment by germain-gg** [comment]
I'm inclined to accept this, not entirely sure this warrants a design review. Can't really think of a reason why we would want to keep the threads button hidden.

If we get this in a ready state I'd be happy to move this forward and merge it

**Comment by SimonBrandner** [comment]
I think there was a concern of too many buttons being there...

I am happy to resolve the merge conflicts over the weekedn

**Comment by germain-gg** [comment]
This area will be changed soon as part of the rebuild of the room header/sidebar, see this figma doc https://www.figma.com/file/wqgXVb7RVaIybfRsXdWEiL/Trust-%26-Decoration?type=design&node-id=130-28837&mode=design

So also happy to close this off and tackle it as part of the UI refactor. Whichever avenue you prefer

**Comment by SimonBrandner** [comment]
Ah, I see, /me will update the PR then and merge (during the weekend
)

**Comment by SimonBrandner** [comment]
(argh, I don't have time to fix the test rn...)

**Pull request merged**
