### PR TITLE
Default intentional mentions

### PR DESCRIPTION
**Pull request by Johennes**
As discussed with @clokep it should be safe for us to include the `m.mentions` field regardless of whether the home server supports it or not as servers that don't support it should simply ignore it.

This is as far as I could get in-between other things. It will still require more work as there are three remaining test failures.

```
 FAIL  test/components/views/rooms/EditMessageComposer-test.tsx
  <EditMessageComposer/>
    ✓ should edit a simple message (105 ms)
    ✓ should throw when room for message is not found (40 ms)
    createEditContent
      ✓ sends plaintext messages correctly (1 ms)
      ✓ sends markdown messages correctly (10 ms)
      ✓ strips /me from messages and marks them as m.emote accordingly (2 ms)
      ✓ allows emoting with non-text parts (1 ms)
      ✓ allows sending double-slash escaped slash commands correctly (1 ms)
    when message is not a reply
      ✓ should attach an empty mentions object for a message with no mentions (48 ms)
      ✓ should retain mentions in the original message that are not removed by the edit (45 ms)
      ✓ should remove mentions that are removed by the edit (85 ms)
      ✕ should add mentions that were added in the edit (51 ms)
      ✕ should add and remove mentions from the edit (54 ms)
    when message is replying
      ✓ should retain parent event sender in mentions when editing with plain text (37 ms)
      ✕ should retain parent event sender in mentions when adding a mention (47 ms)
      ✓ should retain parent event sender in mentions when removing all mentions from content (55 ms)
      ✓ should retain parent event sender in mentions when removing mention of said user (54 ms)

  ● <EditMessageComposer/> › when message is not a reply › should add mentions that were added in the edit

    expect(received).toEqual(expected) // deep equality

    - Expected  - 5
    + Received  + 1

    - Object {
    -   "user_ids": Array [
    -     "@dan:server.org",
    -   ],
    - }
    + Object {}

      354 |
      355 |             // new mention in the edit
    > 356 |             expect(messageContent["m.mentions"]).toEqual({
          |                                                  ^
      357 |                 user_ids: ["@dan:server.org"],
      358 |             });
      359 |             expect(messageContent["m.new_content"]["m.mentions"]).toEqual({

      at Object.<anonymous> (test/components/views/rooms/EditMessageComposer-test.tsx:356:50)

  ● <EditMessageComposer/> › when message is not a reply › should add and remove mentions from the edit

    expect(received).toEqual(expected) // deep equality

    - Expected  - 5
    + Received  + 1

    - Object {
    -   "user_ids": Array [
    -     "@dan:server.org",
    -   ],
    - }
    + Object {}

      377 |
      378 |             // new mention in the edit
    > 379 |             expect(messageContent["m.mentions"]).toEqual({
          |                                                  ^
      380 |                 user_ids: ["@dan:server.org"],
      381 |             });
      382 |             // all mentions in the edited version of the event

      at Object.<anonymous> (test/components/views/rooms/EditMessageComposer-test.tsx:379:50)

  ● <EditMessageComposer/> › when message is replying › should retain parent event sender in mentions when adding a mention

    expect(received).toEqual(expected) // deep equality

    - Expected  - 5
    + Received  + 1

    - Object {
    -   "user_ids": Array [
    -     "@dan:server.org",
    -   ],
    - }
    + Object {}

      473 |
      474 |             // new mention in edit
    > 475 |             expect(messageContent["m.mentions"]).toEqual({
          |                                                  ^
      476 |                 user_ids: ["@dan:server.org"],
      477 |             });
      478 |             // edited reply still mentions the parent event sender

      at Object.<anonymous> (test/components/views/rooms/EditMessageComposer-test.tsx:475:50)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 13 passed, 16 total
Snapshots:   0 total
Time:        2.574 s, estimated 4 s
```

I'm probably just too dense to quickly understand what's happening here. I suspect something is wrong with the completion setup but I didn't have time yet to look into it further.

```
  console.error
    Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
        at BasicMessageEditor (/Users/jm/Code/matrix-react-sdk/src/components/views/rooms/BasicMessageComposer.tsx:144:9)
        at div
        at EditMessageComposer (/Users/jm/Code/matrix-react-sdk/src/components/views/rooms/EditMessageComposer.tsx:135:9)
        at /Users/jm/Code/matrix-react-sdk/src/contexts/MatrixClientContext.tsx:56:34
        at wrapper (/Users/jm/Code/matrix-react-sdk/test/components/views/rooms/EditMessageComposer-test.tsx:87:25)

      685 |     private onAutoCompleteSelectionChange = (completionIndex: number): void => {
      686 |         this.modifiedFlag = true;
    > 687 |         this.setState({ completionIndex });
          |              ^
      688 |     };
      689 |
      690 |     private configureUseMarkdown = (): void => {
``

<!-- CHANGELOG_PREVIEW_START -->
---
Here's what your changelog entry will look like:

## ✨ Features
 * Default intentional mentions ([\#11602](https://github.com/matrix-org/matrix-react-sdk/pull/11602)).<!-- CHANGELOG_PREVIEW_END -->

### CODE REVIEW

**Comment by Johennes** [comment]
Thanks @kerryarchibald for working your magic to fix the composer tests! 🙏

The remaining failures appear unrelated to the change here to me. Might be flakes? 🤔

```
FAIL test/components/views/settings/JoinRuleSettings-test.tsx (7548 ms)
FAIL test/components/views/right_panel/VerificationPanel-test.tsx (6.095 s)
```

**Comment by weeman1337** [comment]
> Thanks @kerryarchibald for working your magic to fix the composer tests! 🙏
> 
> The remaining failures appear unrelated to the change here to me. Might be flakes? 🤔
> 
> ```
> FAIL test/components/views/settings/JoinRuleSettings-test.tsx (7548 ms)
> FAIL test/components/views/right_panel/VerificationPanel-test.tsx (6.095 s)
> ```

An issue for `JoinRuleSettings-test` does already exist: https://github.com/vector-im/element-web/issues/25625

Can you create one for the `VerificationPanel-test` ?

**Review by weeman1337 — APPROVED** [review]
Looks good :+1:

**Comment by Johennes** [comment]
> Can you create one for the `VerificationPanel-test` ?

Thanks, have opened https://github.com/vector-im/element-web/issues/26166. I didn't manage to find the failed test result anymore though. They don't appear to show up in https://github.com/matrix-org/matrix-react-sdk/actions/workflows/tests.yml?query=branch%3Ajohannes%2Fdefault-intentional-mentions. 🤔

**Comment by Johennes** [comment]
Nothing compared to the groundworks you and Kerry did. 😉

**Pull request merged**
