### PR TITLE
Improve room directory UX for mobile devices

### PR DESCRIPTION
**Pull request by 2580ayush2580**
Fixes https://github.com/vector-im/element-web/issues/16063

Before:-

element2

After pull request:-

resolve3

Please Review My PR
Signed-off-by: Ayush Kumar [2580ayush2580@gmail.com]()

### CODE REVIEW

**Comment by jryans** [comment]
Please use PR titles that explain the change from a user's perspective. I'll update this one as an example. (At the moment, we use the PR titles directly in our changelogs.)

**Comment by 2580ayush2580** [comment]
> Please use PR titles that explain the change from a user's perspective. I'll update this one as an example. (At the moment, we use the PR titles directly in our changelogs.)

Okay, I will remember for next time.

**Review by jryans — CHANGES_REQUESTED** [review]
Thanks for working on this, these seem like reasonable tweaks to the mobile view. 😄 

One thing is still needed though: Please update the PR or each commit with your sign off as described in [CONTRIBUTING.rst](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.rst).

**Comment by jryans** [comment]
Since the mobile view is experimental and these seems like safe changes to me, I think we can skip Design review here.

**Comment by jryans** [comment]
Once you've added sign off, please make sure to click the re-request review wheel at the top so I know to take another look.

**Comment by 2580ayush2580** [comment]
@jryans sir, please review changes.

**Review by jryans — CHANGES_REQUESTED** [review]
Hmm, something seems a bit wrong with the PR now, perhaps a bad rebase...? You seem to have rewritten various commits from other unrelated changes, so we'll need to get that fixed first.

**Comment by 2580ayush2580** [comment]
may I create new PR?

**Pull request closed without merging**
