### PR TITLE
Remove duplicate translated string

### PR DESCRIPTION
**Pull request by luixxiul**
Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

This PR changes a letter in uppercase after `Warning: ` to lowercase letter, in order to remove a duplicate translation source.

type: defect
element-web notes: none

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by gsouquet — CHANGES_REQUESTED** [review]
This seems to be a rule only for american english. In british english, according to various sources, only proper nouns and acronyms will see a capital letter after a colon

https://www.grammarly.com/blog/capitalization-after-colons/

`en_EN` is british english, whereas `en_US` should receive the change you've contributed

**Comment by luixxiul** [comment]
Removing the duplicate of translation source is the motive of this PR, which is still relevant.

**Comment by luixxiul** [comment]
Sorry, found a couple more to be changed.

**Comment by luixxiul** [comment]
ahh sorry, I've pushed other changes just now!

**Pull request merged**
