### PR TITLE
Appease webpack

### PR DESCRIPTION
**Pull request by luixxiul**
Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

This change stops webpack from issuing warnings related to `justify-content: start`. See: https://github.com/vector-im/element-web/issues/23595

type: task

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by gsouquet — CHANGES_REQUESTED** [review]
What are those warning and why does PostCSS spit them out?
I'm not convinced this is the right fix. I have a hunch this happens because of outdated packages
Using `justify-content: start` is completely valid in this instance and I would not want to change our code to satisfy this tool's incorrect expectations

**Comment by luixxiul** [comment]
````
2023-02-15 00:14:44.855 [element-js] (53:9) start value has mixed support, consider using flex-start instead
2023-02-15 00:14:44.856 [element-js] ℹ ｢wdm｣: Compiled with warnings.
2023-02-15 00:15:03.352 [element-js] ℹ ｢wdm｣: Compiling...
2023-02-15 00:15:07.710 [element-js] ⚠ ｢wdm｣:    2648 modules
2023-02-15 00:15:07.710 [element-js]
2023-02-15 00:15:07.710 [element-js] WARNING in ../matrix-react-sdk/res/themes/light/css/light.pcss (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/postcss-loader/src??postcss!../matrix-react-sdk/res/themes/light/css/light.pcss)
2023-02-15 00:15:07.710 [element-js] Module Warning (from ./node_modules/postcss-loader/src/index.js):
2023-02-15 00:15:07.710 [element-js] Warning
2023-02-15 00:15:07.710 [element-js]
2023-02-15 00:15:07.710 [element-js] (53:9) start value has mixed support, consider using flex-start instead
2023-02-15 00:15:07.710 [element-js]
2023-02-15 00:15:07.710 [element-js] WARNING in ../matrix-react-sdk/res/themes/dark/css/dark.pcss (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/postcss-loader/src??postcss!../matrix-react-sdk/res/themes/dark/css/dark.pcss)
2023-02-15 00:15:07.710 [element-js] Module Warning (from ./node_modules/postcss-loader/src/index.js):
2023-02-15 00:15:07.710 [element-js] Warning
2023-02-15 00:15:07.710 [element-js]
2023-02-15 00:15:07.710 [element-js] (53:9) start value has mixed support, consider using flex-start instead
2023-02-15 00:15:07.711 [element-js] ℹ ｢wdm｣: Compiled with warnings.
````

Essentially the same PR as https://github.com/matrix-org/matrix-react-sdk/pull/9500.

As I myself am not annoyed with these warnings, it's ok for me to close this.

What do you think?

**Comment by gsouquet** [comment]
I understand what you're getting at, I'm just not sure this is how we should approach it.
We're changing our codebase to satisfy a tool that has a wrong assumption, I'll bring that up with a few other folks as it does not seem we have consensus on the matter

**Comment by luixxiul** [comment]
Might be reopened after https://github.com/vector-im/element-web/issues/23597 is resolved.

**Pull request closed without merging**
