### PR TITLE
Move call buttons to the room header

### PR DESCRIPTION
**Pull request by turt2live**
This is to make some room in the composer for voice messages. The hangup behaviour is intentionally lost by this change as the VOIP UX is intended to rely on dedicated hangup buttons instead.

New look:
image
image

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
I dislike it but code looks sane :(

**Review by dbkr — APPROVED** [review]

**Comment by t3chguy** [comment]
DOUBLY APPROVED

**Comment by turt2live** [comment]
let's hope the CI agrees

**Comment by turt2live** [comment]
oh wow, it does. 

/me merges before it changes its mind

**Pull request merged**
