### PR TITLE
Enable RoomViewLifecycle.ViewRoom to be responsive to widget layout changes

### PR DESCRIPTION
**Pull request by charlynguyen**
This PR introduces `Action.WidgetLayoutChanged` in a room view to enable `RoomViewLifecycle.ViewRoom` to be responsive to widget layout changes.

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Enable RoomViewLifecycle.ViewRoom to be responsive to widget layout changes ([\#11897](https://github.com/matrix-org/matrix-react-sdk/pull/11897)). Contributed by @charlynguyen.

### CODE REVIEW

**Comment by charlynguyen** [comment]
@richvdh @kerryarchibald friendly reminder 🙂 (in case you missed it somehow)

**Review by weeman1337 — COMMENTED** [review]
Hi @charlynguyen I have another question before I can review this in detail:

Do you address any particular issue with this?

Is the goal maybe that `ModuleRunner.instance.invoke(RoomViewLifecycle.ViewRoom, viewRoomOpts, this.getRoomId());` gets called after a layout change?

We should probably not dispatch `ViewRoom` again. Some kind of update event would fit better here.

**Comment by charlynguyen** [comment]
> Hi @charlynguyen I have another question before I can review this in detail:
> 
> Do you address any particular issue with this?
> 
> Is the goal maybe that `ModuleRunner.instance.invoke(RoomViewLifecycle.ViewRoom, viewRoomOpts, this.getRoomId());` gets called after a layout change?
> 
> We should probably not dispatch `ViewRoom` again. Some kind of update event would fit better here.

@weeman1337 Thanks a lot for the feedback. Sorry to be unclear regarding the intention of the PR. You are right, it is mainly about to call `ModuleRunner.instance.invoke(RoomViewLifecycle.ViewRoom, viewRoomOpts, this.getRoomId());` to let the UI provided by the `viewRoomOpts` notice widget layout changes.

Thanks for the advice/proposal to handle it with a different update event. I will wrap my head around and get back to you asap.

**Comment by weeman1337** [comment]
> Thanks for the advice/proposal to handle it with a different update event. I will wrap my head around it and get back to you asap.

I am going to set this PR to draft-state until then. If you have questions feel free to ask here in comments. Once you think it is ready for a review again un-draft the PR (and eventually leave a comment).

**Comment by charlynguyen** [comment]
It turns out that the new room header is sufficient for our needs. Thanks 🙏

**Pull request closed without merging**
