### PR TITLE
Fix call crashing because `element` was undefined

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/18270

### CODE REVIEW

**Comment by t3chguy** [comment]
Does this affect the RC @SimonBrandner ?

**Comment by SimonBrandner** [comment]
> Does this affect the RC @SimonBrandner ?

Nope

**Comment by SimonBrandner** [comment]
(though it would be great to review this as soon as possible as it completely breaks call on develop)

**Review by t3chguy — APPROVED** [review]
:shipit:

**Comment by SimonBrandner** [comment]
(thanks!)

**Pull request merged**
