### PR TITLE
Allow bubble layout in Thread View

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/20419

image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Allow bubble layout in Thread View ([\#7478](https://github.com/matrix-org/matrix-react-sdk/pull/7478)). Fixes vector-im/element-web#20419.

Preview: https://61ddbd47d7c1205068c2dba1--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]
Looks good!

**Comment by SimonBrandner** [comment]
I don't like the padding, it seems too big, tbh

**Review by daniellekirkwood — APPROVED** [review]

**Comment by amshakal** [comment]
I agree with Simon, would it be possile to reduce the padding on left and right? For threads without bubbles, the padding is 12px on both sides. We could keep it the same.

**Comment by t3chguy** [comment]
image

Done

**Comment by amshakal** [comment]
Looks great! Thank you. :)

**Review by amshakal — APPROVED** [review]

**Comment by toger5** [comment]
This does not work for the right panel chat yet. (As the title of the PR implies)
There is some work done, to improve on the code sharing between timeline and thread. 
https://github.com/matrix-org/matrix-react-sdk/pull/7262

The plan was for this to simplify the transition to shared settings like custom styles. Sorry for joining the discussion so late. Is it still planned to have message bubbles for the right panel timeline as well? If so it might be worth to transition the thread view to use the timeline card class.

**Comment by t3chguy** [comment]
> Is it still planned to have message bubbles for the right panel timeline as well?

@daniellekirkwood / @amshakal ^

**Comment by daniellekirkwood** [comment]
Yes, if the user has Bubbles turned on, all chat messages will need bubbles (threads, timelines, etc)

**Comment by amshakal** [comment]
+1

**Pull request merged**
