### PR TITLE
Pass device id to widgets

### PR DESCRIPTION
**Pull request by Fox32**
Implement the [comment in MSC 3819](https://github.com/matrix-org/matrix-spec-proposals/pull/3819#discussion_r1099833846) which requests passing a device id to a widget.

This is based on the previous work in the matrix-widget-api: https://github.com/matrix-org/matrix-widget-api/pull/78

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Pass device id to widgets ([\#10209](https://github.com/matrix-org/matrix-react-sdk/pull/10209)). Contributed by @Fox32.

Type: enhancement

### CODE REVIEW

**Comment by dhenneke** [comment]
The related PR in the matrix-widget-api was merged and released so we can move on here.

**Review by richvdh — APPROVED** [review]
looks good, thank you!

**Comment by dhenneke** [comment]
I updated the branch to resolve the merge conflict. I think auto-merge didn't merge it after the approval.

**Comment by richvdh** [comment]
Thanks; looks like github had some fail.

It's now failing for an unrelated reason, which #10963 fixes.

**Comment by dhenneke** [comment]
Now there is one last error but I don't know how that is related to the change.

**Review by richvdh — APPROVED** [review]

**Comment by richvdh** [comment]
> Now there is one last error but I don't know how that is related to the change.

It's not, and it's not a required check, so can be ignored.

this neeeds a review from @matrix-org/element-web-app-team though due to the change to package.json

**Pull request merged**
