### PR TITLE
Support Podman style of accessing the host network in Cypress tests

### PR DESCRIPTION
**Pull request by andybalaam**
---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by t3chguy — CHANGES_REQUESTED** [review]
Don't you also need to do this in email.spec.ts which uses host.docker.internal?

**Comment by andybalaam** [comment]
> Don't you also need to do this in email.spec.ts which uses host.docker.internal?

Yes, thanks - I've added a commit covering that.

**Review by t3chguy — APPROVED** [review]

**Review by t3chguy — CHANGES_REQUESTED** [review]
CI looks unhappy...

**Review by t3chguy — APPROVED** [review]
Looks sane

**Pull request merged**
