### PR TITLE
Style 'your settings' in error message as link

### PR DESCRIPTION
**Pull request by ttheshreeyasingh**
"your settings" in the error message is styled as a link. That link opens the user setting jumps to the "Security & Privacy" tab and scrolls down to the "Message search" section.

Fixes issue https://github.com/vector-im/element-web/issues/18164 

Signed-off-by: Shreeya [shreeya.singh@students.iiit.ac.in](mailto:shreeya.singh@students.iiit.ac.in)

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Style 'your settings' in error message as link ([\#8277](https://github.com/matrix-org/matrix-react-sdk/pull/8277)). Contributed by @ttheshreeyasingh.

### CODE REVIEW

**Review by dbkr — CHANGES_REQUESTED** [review]
Do we know why `link_inline` wasn't working? It looks like it's being used successfully in other places, so I'm not sure swapping it out is necessarily the right answer. Adding the `mx_DesktopBuildsNotice` isn't as this is the class for the another component.

Also I think you may need to merge develop to get the CI to pass.

I'm also going to make a minor change to the title so it's in the right tense for a change (this is what will appear in the changelog)

**Comment by luixxiul** [comment]
I guess there should be an issue of CSS style inheritance. Fixing it looks straightforward.

**Comment by kittykat** [comment]
@ttheshreeyasingh I wanted to check in if you're intending to update your PR with the requested changes? If not, we'd like to unassign the issue in case anyone else would like to pick it up :+1:

**Comment by andybalaam** [comment]
Abandoned - reopen if you are working on it.

**Pull request closed without merging**
