### PR TITLE
Show 3PID invites in the invite part of the membership list

### PR DESCRIPTION
**Pull request by Kegsay**
Fixes https://github.com/vector-im/vector-web/issues/613

**Requires latest `develop` on JS SDK**

Not overly happy with how this turned out but it'd require a complete re-jig of the passing of room members throughout the app to reasonably do this. The fix basically allows `MemberTile` and `MemberAvatar` to work *without a `RoomMember`*, allowing a new prop `customDisplayName` which is displayed instead. The `MemberList` then maps `m.room.third_party_invites` to these kinds of `MemberTiles` and ta-daaah! I opted for this rather than duplicating all the code for `MemberTile` and `MemberAvatar` given we want them to look and feel much the same and Vector's form is still extremely fluid. The cost to doing this means lots of conditional checks in these 2 components.

Overall, I'm not happy with this PR because it doesn't fix the underlying problem which is that:
 - We can't represent 3PID invited people as `RoomMembers` (we have no `m.room.member` event, no user ID, etc). Throughout the app we assume `member.userId` exists and that it has the form `@foo:bar` which is just not true here, and I think it'd be horrible to contort the entire app for this.
 - We have no interface for "displaying a member". Instead, we just say "here's a `RoomMember`, have fun!" even though we don't use most of the functions most of the time. If we separated these concepts this would've been a lot easier since I'd just need to meet an interface which had a display name, a power level, a presence state, etc. As a result of passing `RoomMembers` all over the shop, many components look for data in the same shape as the `RoomMember` object (e.g. `member.user.presence` rather than just `member.presence`) which further hinders converting things over.

This PR has the following shortcomings:
 - It displays `onhover` stuff correctly but clicking on it does nothing (the dispatch expects a `RoomMember` which I cannot satisfy).

We'll need to tweak this in the future to match Zeplin designs (which have a little email icon at the top-right of the member avatar for 3PID invites).

### CODE REVIEW

**Comment by ara4n** [comment]
surely we need to be able to interact with these invites somehow, if only to cancel them if they're stale/ignored?

**Comment by Kegsay** [comment]
There is no API to cancel 3PID invites AFAIK.

**Comment by dbkr** [comment]
lgtm. Agreed some bits could be better but yay for factoring out PresenceLabel.

**Comment by ara4n** [comment]
okay, will file new bugs for ability to cancel 3PIDs

**Pull request merged**
