### PR TITLE
Add warm fuzzy dialog for inviting users to a group

### PR DESCRIPTION
**Pull request by lukebarnard1**

### CODE REVIEW

**Comment by lukebarnard1** [comment]
>Would this be necessary if we showed invited group users in the member list?

No, but in the short-term this seemed trivial enough to do for the bare minimum feedback.

>Otherwise, it would make more sense to me if the Address Picker stayed on screen while the invites were sent, showing a spinner, then changed to confirm the invites have been sent

I would _love_ to do a generic addition to `BaseDialog` to indicate some work being done, and then showing success/error. This would be hugely useful for not reinventing the wheel every time a dialog shows this kind of UX. 

If we apply surgery to `AddressPicker`, it will be yet another UX concept to add to the mix.

**Comment by dbkr** [comment]
fair enough if it's temporary then, although I'd expect showing invited group users to be very simple.

**Comment by lukebarnard1** [comment]
>although I'd expect showing invited group users to be very simple.

It is, but for the fact that it requires server-side changes. 

TBH it still feels confusing because the dialog says one thing and the list says another.

**Comment by lukebarnard1** [comment]
@lampholder thoughts?

**Comment by lukebarnard1** [comment]
Merging for now as this is slightly better than what we have, but we still might decide that this is not good enough for a first cut because it's awful that:
 - The user has to remember who they've sent an invite to,
 - The user gets no persisted feedback that an invite has happened

**Pull request merged**
