### PR TITLE
Add padding for close button in settings dialog

### PR DESCRIPTION
**Pull request by gefgu**
Add padding for close button in settings dialog. It maintains the alignment with the heading, maintains the original size of the "X" mark and follows Apple's human interface guidelines of 44x44 points for touch targets.

Fixes https://github.com/vector-im/element-web/issues/22915

Signed-off-by: gefgu <gefgu@hotmail.com>

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [X] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Type: [enhancement/defect/task]

Before:
before
After:
after

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Add padding for close button in settings dialog ([\#9202](https://github.com/matrix-org/matrix-react-sdk/pull/9202)). Fixes vector-im/element-web#22915. Contributed by @gefgu.

### CODE REVIEW

**Review by SimonBrandner — CHANGES_REQUESTED** [review]
It doesn't seem right the button is not in the middle of the clickable area...

**Comment by gefgu** [comment]
I didn't let the button in the center of the clickable area because it would lose the alignment with the heading, but if you prefer it to the center, I will work on it.

**Comment by SimonBrandner** [comment]
I've requested a review from the design team to figure out how this should actually look/behave

**Comment by gefgu** [comment]
Thanks for the quick feedback! When they figure out, I'm happy to help.

**Comment by janogarcia** [comment]
I'd suggest using a target area of 32x32px for the desktop context.

- It's a nice trade off between not taking way too much space and complying with [upcoming WCAG 2.2 recommendation](https://www.w3.org/TR/WCAG22/#target-size-minimum) for AA level (24x24px).
- I'd only recommend using 44x44px when in a touch context (mobile viewport, webview, touch input...), or trying to comply with WCAG 2.2 AAA.

**Review by janogarcia — CHANGES_REQUESTED** [review]
Please refer to my [previous comment](https://github.com/matrix-org/matrix-react-sdk/pull/9202#issuecomment-1236761611).

**Comment by janogarcia** [comment]
As for the icon alignment and placement I'd suggest, for now:

- Keep the close icon centered within the 32x32px target area.
- Place the 32x32px target area at 24px from the the modal window edges.

SCR-20220905-gzz-2

**Comment by gefgu** [comment]
I've updated the code following @janogarcia suggestion.


The close icon is centered within the 32x32 target area: 
button

And the target area is at 24px from the the modal window edges:
outer_padding

I hope this solve the issue. What do you think @SimonBrandner?

**Review by SimonBrandner — COMMENTED** [review]
LGTM codewise

**Review by janogarcia — COMMENTED** [review]
It seems this PR is introducing (maybe reintroducing an old one?) a different close icon than the one we currently use for modal windows.

**Comment by MidhunSureshR** [comment]
The playwright tests are failing due to a difference in the size of the close icons - https://e2e-9202--matrix-react-sdk.netlify.app/#?testId=e020cd10d103304ed79f-bd3d48af8331ff4cee52038c2392796d4a22.
I don't think this PR intended to change the size of the close button in the first place.

**Review by MidhunSureshR — CHANGES_REQUESTED** [review]
Sorry for letting this get stale, please see https://github.com/matrix-org/matrix-react-sdk/pull/9202#issuecomment-1909487938

**Comment by MidhunSureshR** [comment]
Closing this for now, feel free to reopen if you want to make the changes.

**Pull request closed without merging**
