### PR TITLE
[WIP] Textarea based composer input

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/4861
Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by ara4n** [comment]
I'm worried that the maintenance burden of the overlapping functionality between the draft & textarea-based composer is going to be a pain - I was expecting more to be factored out between the two, particularly: typing notifs, history management, clipboard pasting, processing slash commands.  Otherwise the two are just going to spend their lives drifting out of sync with one another.

It otherwise looks good though :)

**Comment by dbkr** [comment]
Echoing what @ara4n says about code duplication - I think this will be too much of a burden without factoring out the common functionality.

**Comment by lukebarnard1** [comment]
@t3chguy are you likely to have another crack at doing this in a way that factors out functionality between both composers?

**Comment by lukebarnard1** [comment]
FTR this looks like it will be usurped by [move to Slate from Draft.js](https://github.com/matrix-org/matrix-react-sdk/pull/1890) anyway.

**Comment by t3chguy** [comment]
I don't think this is superseded but will definitely be broken by;
Draft.js and Slate both use a contenteditable div which doesn't play very well with extensions which people like to use in their browsers to improve their editing experience, and other fun stuff like pop-out editors, which is why this PR was even a thing.

**Comment by lukebarnard1** [comment]
Fair enough, @t3chguy. "Usurped" was probably the wrong word, my bad.

I can see us definitely wanting to support an "insert your favourite editor here" functionality, even with Slate.

**Pull request closed without merging**
