### PR TITLE
Move session manager out of beta

### PR DESCRIPTION
**Pull request by kerryarchibald**
For https://github.com/vector-im/element-web/issues/25422

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by t3chguy** [comment]
@odelcroi we are very unlikely to keep old code around once we have new code to replace it, the maintenance burden is just too high. I'd suggest forking if you need to maintain old code.

**Comment by daniellekirkwood** [comment]
We had a discussion about this in the PM room. @jakewb-b who has previously worked on the feature as PM is in favour of de-labsing. @pmaier1 has some questions about the state of the experimental back-end features. 

Do we have line of sight to when these things won't be experimental anymore? I'm not close enough on this to know - otherwise happy to approve :)

Screenshot 2023-05-25 at 09 28 41

**Comment by Johennes** [comment]
> Do we have line of sight to when these things won't be experimental anymore?

The experimental features (MSC3852 & MSC3881) are plug-in and cover functionality that the old session manager did not have. These shouldn't block us from landing the new session manager IMO.

**Review by pmaier1 — APPROVED** [review]
:+1:

**Review by t3chguy — APPROVED** [review]
:shipit:

**Pull request merged**
