### PR TITLE
Allow voice messages to be scrubbed in the timeline

### PR DESCRIPTION
**Pull request by turt2live**
Fixes https://github.com/vector-im/element-web/issues/18713

**Reviewer: This has internal context - see backreferenced issues**

----

Ignoring the fact that I've uploaded a file called a voice message that isn't a voice message:
image

Sizing (should be the same):
| Before | After |
|-|-|
| image | image |

Evidence of composer still working for playback with waveforms:
image

Evidence that the file panel and such still work:
image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Allow voice messages to be scrubbed in the timeline ([\#8079](https://github.com/matrix-org/matrix-react-sdk/pull/8079)). Fixes vector-im/element-web#18713.

Preview: https://pr8079--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by SimonBrandner** [comment]
To be perfectly honest, I don't like losing the waveform in the timeline and still not being able to scrub in the composer :/

**Comment by turt2live** [comment]
For accessibility we can't keep the waveform in the timeline, unfortunately. At least while it's at odds with the seeking support.

**Review by kerryarchibald — APPROVED** [review]
LGTM

**Review by gaelledel — APPROVED** [review]

**Comment by turt2live** [comment]
@SimonBrandner @DoM1nic we're going to go ahead and land this as-is for now, but if you feel strongly otherwise then please open an issue on element-web for the team to take a closer look. 

fwiw, it's been through internal review for the last couple weeks after the concern was raised, but we still believe this is the best approach for the time being.

**Pull request merged**
