### PR TITLE
Task - replace img icons with svg components

### PR DESCRIPTION
**Pull request by kerryarchibald**
Work on fixing extant `jsx-a11y/alt-text` violations so we can enable that rule

| Before | After |
| -------|-------|
| Screenshot 2022-07-01 at 16 42 25| Screenshot 2022-07-01 at 16 53 37|
|Screenshot 2022-07-01 at 16 55 22|Screenshot 2022-07-01 at 16 56 02|
|Screenshot 2022-07-01 at 17 01 18|Screenshot 2022-07-01 at 17 04 00|
|Screenshot 2022-07-01 at 17 45 11|Screenshot 2022-07-01 at 17 44 15|

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by turt2live** [comment]
@kerryarchibald can this get a changelog-friendly title please?

**Comment by t3chguy** [comment]
@turt2live it is a task so won't be included in changelog

**Comment by turt2live** [comment]
arguably this could be a proper changelog entry though (as a feature), though also our commit history being clear would be nice.

**Review by justjanne — COMMENTED** [review]
Code looks fine, works as expected, just one minor comment

**Review by justjanne — APPROVED** [review]

**Pull request merged**
