### PR TITLE
Simplify UserMenu for Guests as they can't use most of the options

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/15700

image

### CODE REVIEW

**Review by jryans — APPROVED** [review]

**Comment by nadonomy** [comment]
Blocking this on design for now— need to figure out a more elegant layout for it.

**Comment by niquewoodhouse** [comment]
FTR design is my bad - I just did a 30 second mockup for @t3chguy that was essentially this, just so it was fixed in _some_ way.

**Review by nadonomy — APPROVED** [review]

**Comment by nadonomy** [comment]
LGTM— after some discussion with @niquewoodhouse arrived at this being good to merge as a quick solution. Looking good!

**Comment by t3chguy** [comment]
Though in coming back to it `Not you?` to a Guest makes 0 sense

**Comment by niquewoodhouse** [comment]
> Though in coming back to it `Not you?` to a Guest makes 0 sense

Got an account? Sign in, maybe makes more sense

**Comment by t3chguy** [comment]
image

**Pull request merged**
