### PR TITLE
Remove obsolete style rules - mx_SpaceRoomView_inviteTeammates_betaDisclaimer

### PR DESCRIPTION
**Pull request by luixxiul**
This PR intends to remove `mx_SpaceRoomView_inviteTeammates_betaDisclaimer` style rules as the Space has left beta. This also suggests to add a Percy snapshot test as there has  not been one for dialogs related to Space. The snapshot should also help us to detect a regression if any, when we replace the invite mask-image with a SVG icon next to `Invite by username`.

|Before|After|
|---------|-------|
|before|after|

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by luixxiul** [comment]
…But is this still used? 

https://github.com/matrix-org/matrix-react-sdk/blob/3bba816b105b00c11cffbbd76fe0e41af97da34d/src/components/structures/SpaceRoomView.tsx#L506-L632

This seems to have been used to render `Invite your teammates` dialog which was initially implemented by https://github.com/matrix-org/matrix-react-sdk/pull/5933.

>

**Review by kerryarchibald — CHANGES_REQUESTED** [review]
This style is still in use.
It's safe to remove the [beta disclaimer](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/structures/SpaceRoomView.tsx#L589-L603) along with the styles as spaces is out of beta, and the warning about the link is no longer relevant.

**Comment by luixxiul** [comment]
yeah right, thanks for confirmation.

**Comment by kerryarchibald** [comment]
@luixxiul Can you please add a screenshot of the invite dialog with the beta card removed?

**Comment by kerryarchibald** [comment]
And update the PR title to better describe the change please!

**Review by kerryarchibald — COMMENTED** [review]
Looks good, thank you. Just a couple of small requests about the PR title and screenshot, then should be good to go 🚀

**Review by kerryarchibald — APPROVED** [review]

**Comment by luixxiul** [comment]
The percy snapshot was not correctly specified to take "invite your teammates" dialog. I am going to submit a fix.

Currently it takes a dialog after clicking the primary button just before the invitation dialog: https://percy.io/dfde73bd/matrix-react-sdk/builds/27785922/changed/1545562064

**Pull request merged**
