### PR TITLE
Further improve replies

### PR DESCRIPTION
**Pull request by SimonBrandner**
Main issue which this fixes https://github.com/vector-im/element-web/issues/19074
Fixes https://github.com/vector-im/element-web/issues/18194
Fixes https://github.com/vector-im/element-web/issues/18027
Fixes https://github.com/vector-im/element-web/issues/19179

<hr>

https://user-images.githubusercontent.com/25768714/137592147-190d4136-ded7-4ea7-9307-8a3831ebf445.mp4

---
Here's what your changelog entry will look like:

## ✨ Features
 * Further improve replies ([\#6396](https://github.com/matrix-org/matrix-react-sdk/pull/6396)). Fixes vector-im/element-web#19074, vector-im/element-web#18194 vector-im/element-web#18027 and vector-im/element-web#19179.

Preview: https://pr6396--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by robintown** [comment]
They're looking even better! :heart_eyes: Some thoughts:

The avatar is slightly off-center:
Screenshot 2021-07-17 at 13-01-32 Element general

"In reply to themselves" overall sounds fine, but it feels weird when the message is coming from *you*. Maybe it should say "In reply to yourself" for that special case?
Screenshot 2021-07-17 at 13-16-23 Element Robin's test account

And while this does significantly improve the style of the "In reply to" bit to make it feel more clickable, I don't feel that it totally resolves https://github.com/vector-im/element-web/issues/7159, since the overall layout is still a bit confusing to read. Perhaps it would be better to just replace the "In reply to" text with "Expand thread"?

**Comment by SimonBrandner** [comment]
> And while this does significantly improve the style of the "In reply to" bit to make it feel more clickable, I don't feel that it totally resolves vector-im/element-web#7159, since the overall layout is still confusing to read. Perhaps it would be clearer if the "In reply to" text were just replaced with "Expand thread"?

Yeah, "Expand thread" sounds so much better!

**Comment by robintown** [comment]
For some reason avatar alignment is still broken for people without avatars:
Screenshot 2021-07-18 at 10-48-27 Element general

**Comment by robintown** [comment]
Also closes https://github.com/vector-im/element-web/issues/18194

**Comment by robintown** [comment]
The display names not being in bold looks a little strange to me IMO

**Comment by robintown** [comment]
Some more design comments:

The hover effect doesn't look great in light mode, and I wonder if there's something other than a brightness change that might look better in general. I feel like the hover effect, if any, should be some kind of background color change, but I get that that's tricky since there's already a hover effect on the overall event tile, sooo idk :woman_shrugging:

Screenshot 2021-07-25 at 21-25-50 Element general

Also, the quoted messages appear to have sliiightly more padding on the bottom than on the top, even though they technically are symmetrical just going by the CSS, so that might benefit from some tuning

**Comment by SimonBrandner** [comment]
> The hover effect doesn't look great in light mode, and I wonder if there's something other than a brightness change that might look better in general. I feel like the hover effect, if any, should be some kind of background color change, but I get that that's tricky since there's already a hover effect on the overall event tile, sooo idk

Yeah, it's not perfect, but I don't know how to solve it either. Let's if design has any ideas

> Also, the quoted messages appear to have sliiightly more padding on the bottom than on the top, even though they technically are symmetrical just going by the CSS, so that might benefit from some tuning

Hopefully, that's better now

**Comment by robintown** [comment]
Padding looks good now, though the line height should be loosened up a little bit since descenders on certain letters get cut off now:

Screenshot 2021-07-27 at 21-52-40 Element  1  general

(something like `line-height: $font-18px` looks reasonable to me)

**Comment by robintown** [comment]
Also I had some inspiration for the hover effect: since the quoted message now has blockquote coloring, what if the effect of hovering over it was to remove that blockquote coloring, and return it back to the normal text color? I also tried out replacing the `brightness(1.5)` on the "Expand text" button with `opacity(0.65)`. These hover effects are of course a bit more subtle than the current brightness change you have, but I personally think the subtlety works out really well:

Unhovered
Screenshot 2021-07-27 at 22-23-34 Element #element-dev matrix org

"Expand thread" hovered
Screenshot 2021-07-27 at 22-24-00 Element #element-dev matrix org

Quoted message hovered
Screenshot 2021-07-27 at 22-24-21 Element #element-dev matrix org

**Comment by robintown** [comment]
I also wonder if replies to images could be improved while we're here, as they currently look a bit weird.

Screenshot 2021-07-27 at 22-47-50 Element projects

My initial thoughts are, since the filename and filesize labels were removed recently when the download button for images got moved, could we just get rid of the "unknown.png (x KB)" text entirely and unify this with the rest of the reply layouts?

Screenshot 2021-07-27 at 22-55-49 Element projects

**Review by turt2live — APPROVED** [review]
I think this is probably fine, though and worried that the word "thread" will send the wrong message while threads are still in progress.

**Comment by robintown** [comment]
Recently I've been thinking that the "Expand thread" text should just be removed, given that they add a lot of noise to the timeline, and because once actual threads are a thing, jumping through long reply chains is probably going to be a less common interaction. Not really sure :/

**Comment by Palid** [comment]
Maybe "Expand replies" instead of "Expand thread" will be good enough?

**Comment by SimonBrandner** [comment]
> Maybe "Expand replies" instead of "Expand thread" will be good enough?

@robintown. how does that sound to you?

**Comment by robintown** [comment]
Maybe? It's a small enough thing though that I think we should just wait for design to provide a more conclusove opinion

**Comment by MadLittleMods** [comment]
What's stopping this from shipping? This seems like an nice iterative improvement and the expand/collapse stuff is being handled in https://github.com/vector-im/element-web/issues/18884 and https://github.com/matrix-org/matrix-react-sdk/pull/6701 while the text itself in this PR, if there is a more conclusive opinion, is an easy follow-up to change.

**Comment by robintown** [comment]
It's just waiting for design review currently

**Comment by MadLittleMods** [comment]
Added to the design inbox (doesn't show up cross-org here in the PR) -> https://github.com/matrix-org/design/projects/2

**Comment by novocaine** [comment]
Hi @SimonBrandner 

Whilst the video is great, for the purposes of us reviewing this PR it would be great to get a more formal text description of the problems you are aiming to solve and how you have solved them

Can you please create a new issue in the form we now [propose for enhancements](https://github.com/vector-im/element-web/issues/new?assignees=&labels=T-Enhancement&template=enhancement.yml) - listing each change you have made and why. 

This will help the design team to more rapidly engage with what you're proposing, understand the context of your changes, and suggest any improvements or decline any changes.

Thanks!

**Comment by SimonBrandner** [comment]
@novocaine, I've made https://github.com/vector-im/element-web/issues/19074

**Comment by graue70** [comment]
I find the two lines on top of each other at the same level of indentation confusing. Why not use nested lines as in the following example?

> > [Expand replies](#)
> 
> **Username**
> Text I am replying to

My own reply

**Comment by robintown** [comment]
Also fixes https://github.com/vector-im/element-web/issues/19179

**Review by janogarcia — CHANGES_REQUESTED** [review]
I'll refer to the issues listed on [#19074](https://github.com/vector-im/element-web/issues/19074) for easier reference:

> The copy is a bit weird when replying to oneself (In reply to <my name>) - we can use Expand replies
> The In reply to <someone> copy is super confusing - we can use Expand replies
> Reply threads look confusing - change the copy as mentioned above and add a hover effect to Expand replies

I would suggest not changing the rendering of the reply chain label in this PR. Let's keep it following the `In reply to {name}` format for now, as it's more consistent with other platforms (iOS, Android), offers a bit more context than "Expand replies", and doesn't get into conflict with the label for the "Expand replies/quotes" contextual action.

> New-style reply design can be harder to grok - make the messages being replied to a bit light/grayer

Use Compound's secondary color (#737D8C) instead of lower-contrast tertiary color.

> We should indicate replied-to messages are clickable in new reply UI - add a hover effect

Keep the hover effect for text, but add a really short transition to text color: `color ease 0.15s`

> Replies don't have an avatar - add a small avatar

- Change avatar size to 16px.
- Change `.mx_ReplyTile > a` gap from 4px to 2px.

> The Edited sign doesn't seem to be necessary in replies - we can remove it

I don't think we're rendering it anymore. Let me know otherwise! 👍

**Comment by robintown** [comment]
@janogarcia Here's what it looks like now:

Modern layout|Bubble layout
-|-
Screenshot 2022-11-17 at 15-37-47 Element 14 #element-dev matrix org|Screenshot 2022-11-17 at 15-38-09 Element 14 #element-dev matrix org

**Review by janogarcia — CHANGES_REQUESTED** [review]
@robintown Some further tweaks after testing it across more contexts:

Let's give "In reply to" (`.mx_ReplyChain_show`) the same color and hover treatment as the quotes.

That is, secondary text color by default, that transitions to primary color on hover. This way the actual message always stands out against the quoted message in the visual hierarchy.

**Comment by robintown** [comment]
@janogarcia Done, please take another look when you get the chance

**Review by janogarcia — APPROVED** [review]
@robintown Thanks for updating it!

**Pull request merged**
