### PR TITLE
Fix per-room RightPanel should not remember Notifications card

### PR DESCRIPTION
**Pull request by ShivraniAJ**
Fix: https://github.com/vector-im/element-web/issues/21529
Now when we are switching the room the right panel is not showing.

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix per-room RightPanel should not remember Notifications card ([\#8273](https://github.com/matrix-org/matrix-react-sdk/pull/8273)). Fixes vector-im/element-web#21529. Contributed by @ShivraniAJ.

Preview: https://pr8273--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by t3chguy — CHANGES_REQUESTED** [review]
This PR seems to do the opposite of what it claims to do. 

It looks to set the history to the notifications panel on every room change. The tests passing confirm this is not intended behaviour.

**Comment by t3chguy** [comment]
Needs DCO sign-off as per https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md#sign-off

**Comment by ShivraniAJ** [comment]
> This PR seems to do the opposite of what it claims to do.
> 
> It looks to set the history to the notifications panel on every room change. The tests passing confirm this is not intended behaviour.

I am trying to fix it, I will do the required changes.

**Comment by andybalaam** [comment]
@ShivraniAJ are you still working on this?

**Comment by ShivraniAJ** [comment]
> @ShivraniAJ are you still working on this?
yes I am still working on this

**Comment by ShivraniAJ** [comment]
I have tried to fix this issue, but I could not find a way to fix it, I am no more working on it.

**Pull request closed without merging**
