### PR TITLE
Fix ugly scrollbars in TabbedView (settings), emojipicker and widgets

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/12906
Fixes https://github.com/vector-im/riot-web/issues/12907
Fixes https://github.com/vector-im/riot-web/issues/12910

### CODE REVIEW

**Comment by bwindels** [comment]
actually, need to double check but we might be able to get rid of the autohidescrollbar component completely as it doesn't require js anymore, or does it?

**Comment by bwindels** [comment]
Yeah, we could apply to behaviour to any scrolling area by applying the css class (`mx_AutoHideScrollbar`). I wonder if we should rename it for that purpose though?

**Comment by t3chguy** [comment]
> Yeah, we could apply the behaviour to any scrolling area by applying the css class (mx_AutoHideScrollbar). I wonder if we should rename it for that purpose though?

Yes but I think maybe we should just apply it globally to all scrollbars, very few scrollbars are always-visible and where they are it seems inconsistent.
image

**Comment by bwindels** [comment]
So, as discussed in the standup, we keep the component to isolate the css class. So we just merge this and then I have a look why code blocks reverted to ugly scrollbars?

**Comment by t3chguy** [comment]
sgtm

**Pull request merged**
