### PR TITLE
Fix replies on the bubble layout

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/18184

<hr>

Screenshot_20210722_181852

<hr>

element-web notes: none

### CODE REVIEW

**Comment by robintown** [comment]
While you're on this it would be nice to fix the replied-to-username being 2px out of alignment with the replied-to-message

**Comment by SimonBrandner** [comment]
> While you're on this it would be nice to fix the replied-to-username being 2px out of alignment with the replied-to-message

/me is blind and doesn't notice these things

**Review by gsouquet — APPROVED** [review]

**Comment by amshakal** [comment]
This is looking great! :)

Just making sure that the reply line is 2px in width?

**Comment by SimonBrandner** [comment]
> Just making sure that the reply line is 2px in width?

Yep, 2px :)

**Pull request merged**
