### PR TITLE
Standardise on top margin for settings tabs

### PR DESCRIPTION
**Pull request by sahilsaini110**
Fixes vector-im/element-web#20767

Signed-off-by: Sahil saini <sohil170246@gmail.com.example.org>

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * changes top margin in settings tab. ([\#7727](https://github.com/matrix-org/matrix-react-sdk/pull/7727)). Fixes vector-im/element-web#20767. Contributed by @sahilsaini110.

### CODE REVIEW

**Comment by SimonBrandner** [comment]
Could you please add the following to the description 

```
Fixes https://github.com/vector-im/element-web/issues/20767
```

and change the PR's name to something more descriptive as it will be a part of the changelog?

**Review by SimonBrandner — CHANGES_REQUESTED** [review]
Could this be somehow applied more globally instead of adding the code to each file? Some tabs also seem to have other than 10px padding or no padding, does this PR somehow fix those?

**Comment by sahilsaini110** [comment]
> Could this be somehow applied more globally instead of adding the code to each file? Some tabs also seem to have other than 10px padding or no padding, does this PR somehow fix those?

okay i will check that and get back to you.

**Comment by sahilsaini110** [comment]
> Could this be somehow applied more globally instead of adding the code to each file? Some tabs also seem to have other than 10px padding or no padding, does this PR somehow fix those?

may you please brief me which tabs are you talking about?

**Comment by SimonBrandner** [comment]
> > Could this be somehow applied more globally instead of adding the code to each file? Some tabs also seem to have other than 10px padding or no padding, does this PR somehow fix those?
> 
> may you please brief me which tabs are you talking about?

Some tabs (e.g. notifications) have margin other than 10 px (e.g. 24 px), how does setting the margin to 10 px fix this? Does it override some other CSS?

It's not clear to me how setting the margin to 10 px in some tabs fixes the problem, perhaps I am missing something?

**Comment by sahilsaini110** [comment]
> Add

okay i will try to apply css globally. and also provide you the screenshots

**Pull request closed without merging**
