### PR TITLE
Make the text filter search all spaces instead of just the selected one

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/16998

@niquewoodhouse do you have any quick wins in terms of better explaining to the user that the text filter field will search across all your spaces rather than the selected one?

### CODE REVIEW

**Review by jryans — APPROVED** [review]

**Comment by niquewoodhouse** [comment]
@t3chguy what constraints do we have?

- Would it be feasible to amend the room tile in someway (eg say which space the result will take them to)?
- Would it be feasible to put them in a new section (eg 'rooms in other spaces)?
- Would it be feasible to amend the filter hint to say 'filter all spaces'?
- Would it be feasible to amend the results to say '13 results in all spaces' instead of '13 results'?

**Comment by t3chguy** [comment]
> Would it be feasible to amend the room tile in someway

Possibly, depending on the exact design you have in mind, keep in mind a room may be in many spaces so this behaviour might feel faulty if the space chosen is not the one you expected.

> Would it be feasible to put them in a new section

Not in a sane amount of time (would require a lot of modifications to the room list store which I'd like to avoid until we are certain this is a solution we are going to keep)

> Would it be feasible to amend the filter hint to say 'filter all spaces'

Sure

> Would it be feasible to amend the results to say '13 results in all spaces' instead of '13 results'

Sure

**Comment by niquewoodhouse** [comment]
@t3chguy thanks for explaining the above.  Given this, and the timeline, I just want to focus on the ones that are confirmed as feasible, it's a beta, and it just needs to work alright enough.

> Would it be feasible to amend the results to say '13 results in all spaces' instead of '13 results'

If we do this, can we have it as:

- If you're in no spaces: 13 results
-  If you're in 1 or more spaces: 13 results in all spaces

> Would it be feasible to amend the filter hint to say 'filter all spaces'

If we do this, can we have it as:

- If you're in no spaces: Filter
- If you're in 1 or more spaces: Filter all spaces

I'm more sold on the first idea above than the second, but think both might work ok enough together.

**Comment by t3chguy** [comment]
will do both together and let you know when you can try out the Netlify build

**Comment by t3chguy** [comment]
image
image

**Review by niquewoodhouse — APPROVED** [review]

**Review by jryans — APPROVED** [review]

**Pull request merged**
