### PR TITLE
Show room create icon if "UIComponent.roomCreation" is enabled

### PR DESCRIPTION
**Pull request by maheichyk**
Type: Enhancement

`"UIComponent.roomCreation"` is already used in several places to show/hide room creation functionality.

This PR suggest to use it in `RoomSublist` to show/hide room creation icon here as well.

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Show room create icon if "UIComponent.roomCreation" is enabled ([\#10364](https://github.com/matrix-org/matrix-react-sdk/pull/10364)). Contributed by @maheichyk.

### CODE REVIEW

**Review by kerryarchibald — CHANGES_REQUESTED** [review]
Display of the room creation option is already controlled in `RoomList` [here](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/RoomList.tsx#L124) and [here](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/RoomList.tsx#L215)

With `UIComponent.CreateRooms` disabled the `+` button only has the option to explore public rooms:
Screenshot 2023-03-15 at 10 17 05

There is another customisation point `UIComponent.ExploreRooms` that *should* be used in the display of the explore rooms button in the `RoomList` code.
If both create and explore rooms are disabled then it would be appropriate to hide the whole `+` button in `RoomSublist`

**Comment by maheichyk** [comment]
@kerryarchibald  many thanks for these explanations. `RoomList` is modified to use `UIComponent.ExploreRooms` to enable/disable "Explore rooms" ("Explore public rooms") menu options. The `+` button is hidden when both features `UIComponent.CreateRooms` and `UIComponent.ExploreRooms` are disabled.

**Review by kerryarchibald — CHANGES_REQUESTED** [review]
Sorry for the delay on the review - I was out of office.

**Review by kerryarchibald — APPROVED** [review]
LGTM

**Pull request merged**
