### PR TITLE
[FIX #3015] Add drag drop urls room view

### PR DESCRIPTION
**Pull request by oivoodoo**
Hi everyone!

As part of this issue(https://github.com/vector-im/riot-web/issues/3015) I were working on resolve api(https://github.com/matrix-org/synapse/pull/2751/) in synapse project and now it would require to integrate together.

By using resolve api as part of media api of synapse project it will solve CORS requests issue.

pull requests:

- https://github.com/matrix-org/matrix-js-sdk/pull/652
- https://github.com/matrix-org/synapse/pull/3308

Signed-off-by: Alexandr Korsak <alex.korsak@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
Since this adds API endpoints it should get specced, for now at least in a Google Doc with the request format, response format and a bunch of design decisions/choices

**Comment by dbkr** [comment]
Trying to fix the same thing as https://github.com/matrix-org/matrix-react-sdk/pull/1643 and https://github.com/matrix-org/matrix-react-sdk/pull/1688

**Comment by oivoodoo** [comment]
@dbkr yes. but it's using media repository to resolve the url and upload it instead of trying to use fetch method despite on CORS.

**Comment by oivoodoo** [comment]
@dbkr @t3chguy going to finish on the weekend.

**Comment by lukebarnard1** [comment]
@oivoodoo did you get any further with this? Looks like the synapse side of things stalled?

**Comment by oivoodoo** [comment]
@lukebarnard1 really sorry, but I am busy in my work for now. I will come back as soon as possible. I stuck on writing the test case coverage for new endpoint `/resolve_url` as the last local change.

**Comment by BloodyIron** [comment]
Looking forward to this! :D

**Comment by oivoodoo** [comment]
@BloodyIron @lukebarnard1 could you take a look for the recent changes when you have time? backend requires to get approve on spec, but the client side is probably good enough for review. 
thank you!

**Comment by BloodyIron** [comment]
Perhaps @t3chguy might be more suited to eyeballing what you've done @oivoodoo ?

**Comment by jryans** [comment]
Thanks for making this contribution a while back. Since the code base has changed since this was opened, it no longer applies cleanly, and I don't think there's a need to keep it open in this state, as we can always find the code here again if needed. If you are still interested in pursuing this feature, please discuss with us in #riot-dev:matrix.org to find a good approach forward.

**Pull request closed without merging**
