### PR TITLE
Migrate remaining crypto tests from Cypress to Playwright

### PR DESCRIPTION
**Pull request by t3chguy**
For https://github.com/vector-im/wat-internal/issues/37

Changing from `@alice` to `@user` caused Rust Crypto to fail with https://github.com/vector-im/element-web/issues/26723 - worked around by changing `@bot_XXXX` to `@zzz_XXXX`

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by florianduros — APPROVED** [review]

**Comment by MidhunSureshR** [comment]
> Changing from `@alice` to `@user` caused Rust Crypto to fail with https://github.com/vector-im/element-web/issues/26723 - worked around by changing @bot_XXXX to @zzz_XXXX

Ideally we would have conditionally expected the test to fail when we're running element with rust crypto:
```js
test.fail(testInfo.project.name === 'Rust Crypto', 'See https://github.com/vector-im/element-web/issues/26723');
```

**Comment by t3chguy** [comment]
@MidhunSureshR that wouldn't catch a regression in the rust crypto stack which made it fail outside of the edge case though.

**Comment by MidhunSureshR** [comment]
Sorry, I don't think I understand?

**Comment by t3chguy** [comment]
@MidhunSureshR if we allowed the test to fail, and rust crypto broke verification outside of the edge case I isolated, then we wouldn't know as the test was expected to fail.

**Pull request merged**
