### PR TITLE
Standardise the margin for settings tabs

### PR DESCRIPTION
**Pull request by yuktea**
Fixes https://github.com/vector-im/element-web/issues/20767
Modified the top margin for the settings tab to be 10px and made the space between the heading and the first subheading consistent at 22px.

### How it looked before:
image

### How it looks now:
image

Signed-off-by: Yukti Sharma <yukti.gh@outlook.com>

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Standardise the margin for settings tabs ([\#7963](https://github.com/matrix-org/matrix-react-sdk/pull/7963)). Fixes vector-im/element-web#20767. Contributed by @yuktea.

Preview: https://pr7963--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by yuktea** [comment]
> Tagging @janogarcia for design review. You might need to merge changes from develop to get the tests to pass, but you also have a stylelint warning (just an extra blank line). Thank you & congrats on your first PR!

Thank you, I've fixed the styling and rebased the commits. It's passing the checks now.

**Review by SimonBrandner — COMMENTED** [review]
It's not clear to me why it is necessary to set the margins in some files separately, why can't it all be done globally in `_SettingsTab.scss`? What am I not seeing?

**Comment by yuktea** [comment]
> It's not clear to me why it is necessary to set the margins in some files separately, why can't it all be done globally in `_SettingsTab.scss`? What am I not seeing?

The issue originally was standardizing just the top margin which is fixed by modifying _SettingsTab.scss globally with a` margin-top: 10px;`. 
Here, I've also tried to standardize the space between the Heading and the first Sub-Heading/Text to 22 pixels. I'll try to check this once more and look into if this could be performed in a better way.

**Review by turt2live — COMMENTED** [review]
code generally seems fine, though would like signoff from a designer before going much further.

**Review by janogarcia — APPROVED** [review]
Thanks for the contribution, @yuktea! We're already working on a major redesign of the settings panel, but these changes help improve the layout in the meantime. 👍

**Comment by andybalaam** [comment]
Thank you @janogarcia !  Thank you @yuktea for a nice improvement!

**Comment by yuktea** [comment]
Thank you!

**Pull request merged**
