### PR TITLE
Add custom audio player

### PR DESCRIPTION
**Pull request by turt2live**
----

**Reviewer**: This is marginally reviewable commit-by-commit (storytelling rather than practical review), and covers a lot of ground.

**This is not behind a labs flag (but is under the voice messages umbrella of work).** Also I have no idea how to test this, sorry. Possibly an end-to-end test, but that feels a bit overkill for a component that people rarely see, if ever (but that might also be a good reason to test it...)

----

`MAudioBody` has been outright deleted and replaced with a whole new body definition. This body definition includes genericising the body styles for file-looking events (raw files, audio, voice messages, etc). Images and video are notable excluded due to their difference in styles.

The voice message components have been downgraded in specificity, becoming general "audio message" components, given their shared state with the new audio event body handling.

image
image

*Note*: the download button bar is still present below the audio event despite not being allowed by the designs. This is because another issue (not public) will tackle the download states. 

Video for seeking (has audio, suggest unmute):

https://user-images.githubusercontent.com/1190097/123360792-266e3980-d52b-11eb-94da-8062b27f9fb5.mp4

Smallest width files panel:
image

Smallest width pinned panel:
image

### CODE REVIEW

**Review by SimonBrandner — CHANGES_REQUESTED** [review]
Screenshot_20210625_075438

This seems to break the audio recorder? Also, I find it quite hard to use seeking, the clickable area seems quite small

**Comment by SimonBrandner** [comment]
Also, this presumably fixes https://github.com/vector-im/element-web/issues/15945

**Comment by turt2live** [comment]
https://github.com/vector-im/element-web/issues/15945 feels like it's talking about more than a simple player. It seems to want an audio playing experience, which is not the goal here.

----

Turns out if you remove classes then the voice message stuff breaks. Who knew. (fixed)

----

Increasing the clickable area of the slider might be difficult if design wants to keep the 1px line: might have to apply more CSS tricks, or increase the line sizing.

**Comment by turt2live** [comment]
actually, increasing the click area was quite simple. Brought it up to match roughly the browser default sizing.

**Review by gaelledel — APPROVED** [review]

**Comment by DoM1niC** [comment]
#6240 Waveforms need be fixed again, since this commit are broken 
image

**Comment by turt2live** [comment]
@DoM1niC that should be fixed in this PR, I think.

**Review by dbkr — APPROVED** [review]
The `PlaybackClock` stuff looks terrifying but I guess that's already in. +1 for the splitting out into components though.

**Comment by turt2live** [comment]
> The PlaybackClock stuff looks terrifying 

This is the correct feeling. Turns out dealing with audio isn't as simple as "play".

**Pull request merged**
