### PR TITLE
Put low priority xor toggle back in the room list context menu

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/14440

image
image

# Pending design to confirm the exact svg & copy.

### CODE REVIEW

**Comment by niquewoodhouse** [comment]
Looks great @t3chguy.  Just to check, it's the same as it used to be?  Either way, very happy with the icon and copy use.   I do know @nadonomy wanted to move this out the menu so just want to double-check he's ok with low priority going back in?  If he's not said anything yet, I assume he's fine with it.


-


I know there was a plan to move the low priority out of the menu to reduce the amount of cognitive load in the menu for most users.  Just curious for your take on something like the below mockup (for the future) that would group more advanced actions like "low priority" and (when it comes) "archive" and whatever other features more experienced users might find useful at this level.   Does that sound like a good idea to help the menu scale and not add cognitive load to most users.  Would be interested in what you'd think, thanks.

Screenshot 2020-07-23 at 13 02 02

**Comment by t3chguy** [comment]
> Just to check, it's the same as it used to be? 

When? I have no easy way to check what something used to look like between releases

> I do know @nadonomy wanted to move this out the menu so just want to double-check he's ok with low priority going back in?

He was in the prioritization call when it was put back on the table

> Just curious for your take on something like the below mockup (for the future) that would group more advanced actions like "low priority" and (when it comes) "archive" and whatever other features more experienced users might find useful at this level.

I believe the long term plan for the Archive to hold Left rooms (Historical) and Low priority rooms so not sure what `Archiver oom` action would do here. Same for `Report`, it isn't an existing concept. Which would mean we end up with a `... More` menu which just ends up holding the `Low priority` action, no?

**Comment by niquewoodhouse** [comment]
> When? I have no easy way to check what something used to look like between releases

Before it was changed to not be there (so the previous room list prior to rebrand).  For checking what something used to look like, in the future we should have design files with history, but we unfortunately don't have this in an easy to refer way. I don't think this should block you - I doubt it was anything but "Low Priority" but was just suggesting we should check if easy.  It's not easy, so lets not.

> He was in the prioritization call when it was put back on the table

Great!  Thanks for confirming he knows about it.

> I believe the long term plan for the Archive view is to hold Left rooms (Historical) and Low priority rooms so not sure what Archive room action would do here. Same for Report, it isn't an existing concept. Which would mean we end up with a ... More menu which just ends up holding the Low priority action, no?

Yes, if that's the long term plan, exactly right, which makes the "more" pointless.  I didn't know that's the plan.  I'm not sure that it makes sense to mix Low Priority and left rooms into the Archive view, as they are now but I'm sure it's been thought through.    

Thanks for replying quickly to each point.

**Comment by t3chguy** [comment]
If you want to check what past releases of Riot/Element looked like you can use https://riots.im/

It looked like the following in the latest pre-Element release:

image

**Comment by niquewoodhouse** [comment]
That's an absolute genius, I didn't think of that at all - literally saved me hours 🙏 

Think this copy + icon is perfect then - all lgtm.

**Comment by t3chguy** [comment]
@niquewoodhouse have you changed your mind? In Figma it has been put below `Settings`

image

Also Figma has no active state, can you confirm the one I did is fine?

**Comment by niquewoodhouse** [comment]
> @niquewoodhouse have you changed your mind? In Figma it has been put below `Settings`

No, happy with its position above settings as per the fix suggested.  Figma is just a bit WIP generally atm.

> Also Figma has no active state, can you confirm the one I did is fine?

The one you did is fine to me, yes.  It's hard to be very confident if it's optimal without trying it out in practice (eg should it use the tick from notifications so there's some difference between on and off beyond colour) but hopefully the context is enough to make this not a problem.  If you're able to try it and feel it doesn't need it, I trust its absolutely fine.  Thanks for doing this sans design for it.

**Comment by valerio-bozzolan** [comment]
Stupid question:

Is this feature ("Low Priority") documented somewhere? At the moment, this commit is the most useful result using DuckDuckGo

**Comment by t3chguy** [comment]
@valerio-bozzolan https://spec.matrix.org/v1.7/client-server-api/#:~:text=m.lowpriority%3A%20These%20should%20be%20shown%20with%20lower%20precedence%20than%20others.

Nothing. It is just a visual category.

**Pull request merged**
