### PR TITLE
Hint at username format on login screen

### PR DESCRIPTION
**Pull request by aaronraimist**
Part of https://github.com/vector-im/riot-web/issues/9648, https://github.com/vector-im/riot-web/issues/11295, https://github.com/vector-im/riot-web/issues/12021#issuecomment-587976956

Feel free to close this PR and choose a different placeholder name or go about this in a different way, I just feel like the login screen needs to provide some kind of hint that you can (and should) enter your full username so you get all of the benefits of `.well-known/matrix/client`.

Screen Shot 2020-03-04 at 12 08 52 AM

See convo up from https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$8JutMfzMSMo8rOzNmnOyBHg2MSGf3d8mcKRIvHG5M68?via=matrix.org&via=privacytools.io&via=mozilla.org

### CODE REVIEW

**Comment by turt2live** [comment]
I imagine one of the concerns will be that this field also takes email addresses and pretty much anything else the server accepts, so have requested design review. Personally I think this is small enough that confident code reviewers could act as design review and solicit designer input post-merge.

**Comment by aaronraimist** [comment]
Right now the field just says Username so I don't think the current state of the login page makes it clear that you can enter anything other than a username.

https://github.com/vector-im/riot-web/issues/6826, https://github.com/vector-im/riot-web/issues/8311, and https://github.com/vector-im/riot-web/issues/8292 are related issues

**Comment by nadonomy** [comment]
> I imagine one of the concerns will be that this field also takes email addresses and pretty much anything else the server accepts, so have requested design review.

Is that true of this field? I would've thought you'd need to interact with the dropdown to change to email or phone.

Having looked at this, I'd block this PR as is on design. The content (random domain) and visual design doesn't support new users goals well. If we could modify the hint to defer itself in the visual hierarchy like so:

image

Then I'd be happy to go ahead to merge this. But otherwise, this is a surprisingly complex and multifactorial problem as the heart of the issue comes down to teaching new users mxid's and interactions to support that. 

Relatedly, the timing of this is great as we're actually kicking off design efforts on mapping out this problem properly in the next week (related PR https://github.com/vector-im/riotX-android/pull/1095).

With all of the above in mind, I'd suggest 1 of the following paths forward:

1. If we want to get this PR over the line, update as per the design above (need to make sure it behaves nicely when the selection is input, however I suspect we don't want the text to scale down proportionally when the field is focused, which leads me to think this might not be low hanging fruit).
2. Wait on actual designs for all platforms, which is happening soon™, and close this PR out to avoid bitrot.

**Comment by aaronraimist** [comment]
I'm wait to wait for real designs and close this, as long as they are coming soon :)

**Comment by turt2live** [comment]
Blocked on future designs then, thanks for the detailed explanation Nad!

**Comment by nadonomy** [comment]
> I'm wait to wait for real designs and close this, as long as they are coming soon :)

Yup, for context we just had a new designer start today, and it's on their list of first projects. Kick off is definitely happening in the next week.

**Comment by ottok** [comment]
Currently there is even no dialog to enter username and password:

image

image

image

l only have a username and password for my account and it is not registered via Github or other external provider. I have not clue howto login now..

**Comment by t3chguy** [comment]
Don't abuse old issues. Riot is too old to understand modern login mechanism so it only let's you use sso. You have to update to Element.

**Pull request closed without merging**
