### PR TITLE
Fix well-known lookup for sliding sync labs check

### PR DESCRIPTION
**Pull request by t3chguy**

### CODE REVIEW

**Review by richvdh — APPROVED** [review]
How was it broken?
When was it broken?
Shouldn't we have a test for this?

But ok I guess

**Comment by t3chguy** [comment]
Introduced by https://github.com/matrix-org/matrix-react-sdk/pull/12307

**Comment by EdGeraghty** [comment]
> Introduced by #12307

What was, exactly?

**Comment by t3chguy** [comment]
@EdGeraghty the code which caused the bug this fixes

**Comment by EdGeraghty** [comment]
@t3chguy that's what I'm asking. Which bug?

If it's respecting paths in the proxyurl, that's not a "bug" I introduced, it's the behaviour of the original check and the current behaviour in ElementX...

**Comment by t3chguy** [comment]
It was checking the base url not the server name domain. The well known is on the server name not the base url. The url constructor check is unrelated to the fix and the msc is unclear whether the path is absolute or relative, I'd argue the former given the specified path starts with a slash.

**Pull request merged**
