### PR TITLE
Fixed issue(#10261): Made id proptype not required in Field component

### PR DESCRIPTION
**Pull request by gate3**
Signed-off-by: Doyin Olarewaju <doyinolarewaju@gmail.org>

### CODE REVIEW

**Comment by turt2live** [comment]
it should be required though - why aren't we supplying an ID in the first place?

**Comment by gate3** [comment]
I don't feel it should be though. Please check [https://github.com/vector-im/riot-web/issues/10261](https://github.com/vector-im/riot-web/issues/10261). Thanks

**Comment by t3chguy** [comment]
Label would still need linking semantically for aria accessibility purposes. So if there's no id then a globally unique one must be generated.

**Comment by turt2live** [comment]
We should just give the field an ID in that dialog rather than make it optional

**Comment by jryans** [comment]
@gate3, are you interested in revising this PR to supply an ID in the dialog as suggested?

**Comment by gate3** [comment]
@jryans Yes sure. Will do that and revert. Thanks

**Comment by t3chguy** [comment]
Thank you for your contribution, ID is indeed important for aria relationship semantics and as this seems abandoned; this moves onto https://github.com/matrix-org/matrix-react-sdk/pull/4298

**Pull request closed without merging**
