### PR TITLE
Tweak branch matching to allow not applying outside of PRs for matrix-analytics-events

### PR DESCRIPTION
**Pull request by t3chguy**
Requires https://github.com/vector-im/element-web/pull/25712

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]

**Comment by richvdh** [comment]
> Tweak branch matching to allow not applying outside of PRs for matrix-analytics-events

I'm struggling to parse this. I think it means: we will no longer apply branch matching, except on PRs for https://github.com/matrix-org/matrix-analytics-events?

**Comment by t3chguy** [comment]
@richvdh yup. English hard

**Comment by richvdh** [comment]
If we're not doing branch matching any more, that seems like big news?

**Comment by t3chguy** [comment]
@richvdh sorry maybe its once again misunderstood.

We still branch match, this just uses the `@matrix-org/analytics-events` version from `yarn.lock` on `develop` (outside of PRs) rather than using the `main` branch there as it did before. Matching `develop` between EW + react-sdk + js-sdk is unchanged. Branch matching in PRs is unchanged

**Comment by richvdh** [comment]
"Disable branch matching of `@matrix-org/analytics-events`, except for PRs" ?

**Pull request merged**
