### PR TITLE
Move pin drop out of labs (PSG-664)

### PR DESCRIPTION
**Pull request by Johennes**
Sanctioned by @jakewb-b.

For: https://github.com/vector-im/element-web/pull/22993

Notes: Move pin drop out of labs

## Checklist

* [x] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Move pin drop out of labs ([\#9135](https://github.com/matrix-org/matrix-react-sdk/pull/9135)).

### CODE REVIEW

**Comment by Johennes** [comment]
> Can you please fix the changelog so that it doesn't contain things not useful to users `(PSG-664)`

Having the Jira ticket number in the release notes is actually helpful to us internally because it allows us to easily find out what release a ticket went into. I know this isn't really useful to external people but it's really just a short internal reference so maybe we could live with that?

**Comment by t3chguy** [comment]
> Having the Jira ticket number in the release notes is actually helpful to us internally because it allows us to easily find out what release a ticket went into.

That only works for enhancements & defects, if your Jira ticket relates to a Task then it wouldn't be in the changelog so is quite a brittle solution to begin with

**Comment by Johennes** [comment]
Ok, I added a `Notes:` section in the description.

**Comment by t3chguy** [comment]
Thanks!

**Comment by Johennes** [comment]
Is it possible to re-run the cypress tests? I'm not sure the failures are related to my changes. 🤔

**Review by jakewb-b — APPROVED** [review]
All good from my side. Thanks.

**Review by robintown — APPROVED** [review]

**Comment by Johennes** [comment]
So after merging in `develop` the timeline spec is green again but the spaces spec failed. I don't think any of this has something to do with moving pin drop out of labs.

**Comment by t3chguy** [comment]
@Johennes https://github.com/vector-im/element-web/issues/23005

**Comment by Johennes** [comment]
Ah thanks @t3chguy. 👍

**Comment by Johennes** [comment]
Tests are green now so I think this is ok to land (I don't have write access myself).

**Review by kerryarchibald — APPROVED** [review]

**Pull request merged**
