### PR TITLE
Use app url as key to ensure that widget is re-rendered on edit.

### PR DESCRIPTION
**Pull request by rxl881**

### CODE REVIEW

**Comment by lukebarnard1** [comment]
What if two app tiles share a URL?

**Comment by rxl881** [comment]
@lukebarnard1 - Yep, that's a good point. I think that it is rare that the widget URLs would be identical, but it's definitely possible. Concatenating the widget ID and URL should be a safer bet (as the widget ID encodes the time that the widget instance was created).

Good to go?

**Comment by rxl881** [comment]
Closing PR in favour of handling prop change updates properly.

**Comment by rxl881** [comment]
Closed in favour of https://github.com/matrix-org/matrix-react-sdk/pull/1548

**Pull request closed without merging**
