### PR TITLE
Rxl881/parallelshell

### PR DESCRIPTION
**Pull request by rxl881**
With recent versions of node / npm (node v8.4.0, npm v5.3.0), npm run start fails with the following error:

```
richard@MacBook-Pro:~/vector/matrix-react-sdk$npm run start

> matrix-react-sdk@0.10.2 start /Users/richard/vector/matrix-react-sdk
> parallelshell "npm run build:watch" "npm run reskindex:watch"

child_process.js:400
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:400:11)
    at exports.spawn (child_process.js:487:38)
    at /Users/richard/vector/matrix-react-sdk/node_modules/parallelshell/index.js:92:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/richard/vector/matrix-react-sdk/node_modules/parallelshell/index.js:91:6)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! matrix-react-sdk@0.10.2 start: `parallelshell "npm run build:watch" "npm run reskindex:watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the matrix-react-sdk@0.10.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richard/.npm/_logs/2017-08-25T08_57_00_027Z-debug.log
```

Updating parallelshell to v3.0.1 fixes this.

### CODE REVIEW

**Comment by t3chguy** [comment]
# Blocked on https://github.com/keithamus/parallelshell/pull/60

**Comment by rxl881** [comment]
@t3chguy, @dbkr - I've bumped the parallelshell dep. version to ^v3.0.2, to the match the corresponding riot-web PR.

**Comment by rxl881** [comment]
Travis build is (now) failing with spinner stuck error. @lukebarnard1 suggested that this is a known error and can probably be safely ignored.

**Comment by rxl881** [comment]
@dbkr - I think that the general guidance is that all package-lock.json files should be checked in? 

From - https://docs.npmjs.com/files/package-lock.json:
> This file is intended to be committed into source repositories, and serves various purposes:

**Comment by dbkr** [comment]
https://jpospisil.com/2017/06/02/understanding-lock-files-in-npm-5.html suggests just checking it in everywhere even though it's ignored for library packages, which I guess makes things easier to follow, so fine.

**Pull request merged**
