### PR TITLE
Make 24hr timestamps 15px shorter than 12hr

### PR DESCRIPTION
**Pull request by barrowsys**
Fixes vector-im/element-web#17871
Signed-off-by: Ezra Barrow <barrow@tilde.team>

### CODE REVIEW

**Review by t3chguy — CHANGES_REQUESTED** [review]
Thanks for this contribution, looks good on the surface but has some edge case issues

---

Hmm so this makes an existing issue worse

image
image

It also breaks down with a larger font set in Appearance

image

image


(and wastes more space than needed with a smaller font set but this is an issue today too)

**Comment by barrowsys** [comment]
that shouuuld fix both the font size change and the e2e badge. matrix encryption works too well on our server so i cant find examples of all the badges but it should work for all of them.

**Comment by t3chguy** [comment]
Unfortunately some of the linters are now failing, the stylelint looks to be legit, the eslint is failing due to the base branch being stale, please pull in latest develop

**Comment by turt2live** [comment]
Hey @barrowsys are you still interested in pursuing these changes?

**Comment by barrowsys** [comment]
no i dont think so

**Pull request closed without merging**
