### PR TITLE
Support setting username and avatar colors in custom themes

### PR DESCRIPTION
**Pull request by bwindels**
Partially overlaps with https://github.com/matrix-org/matrix-react-sdk/pull/4373, but introduces fewer new symbols in the custom theming JSON blob. Also supports avatar backgrounds.

Documentation updates at https://github.com/vector-im/riot-web/pull/13406

### CODE REVIEW

**Comment by turt2live** [comment]
@bwindels have we considered the security implications of this?

**Comment by bwindels** [comment]
> @bwindels have we considered the security implications of this?

Oooh, not at all :facepalm:

**Comment by turt2live** [comment]
It's more that allowing people to change them can lead to themes which remove/alter the disambiguation technique.

**Comment by bwindels** [comment]
> It's more that allowing people to change them can lead to themes which remove/alter the disambiguation technique.

Hmm, I see. People are in control though of the theme they choose?

**Comment by turt2live** [comment]
I guess so. This is the consideration part of the conversation :p

It's probably fine, assuming product is okay with it.

**Comment by bwindels** [comment]
> It's probably fine, assuming product is okay with it.

They are asking for it :)

**Comment by turt2live** [comment]
that needs to be captured somewhere public :(

**Comment by fooness** [comment]
Just tried using `"username-colors": ["#rrggbb", "#rrggbb", "#rrggbb", "#rrggbb", "#rrggbb", "#rrggbb", "#rrggbb", "#rrggbb"]` as well as `"avatar-background-colors": ["#rrggbb", "#rrggbb", "#rrggbb"]` in my `config.json` on a fresh build of 1.6.0-rc4, but unfortunately that didn’t work.

Using `"username-colors_1": "#rrggbb"` (and 2, 3, …) worked! Could not verify the same for single definitions of `avatar-background-colors`, though. Not sure if I did anything wrong, I bet it was tested before being merged … but I also don’t know what I might have done wrong in my `config.json` …

**Comment by t3chguy** [comment]
This isn't in 1.6.0-rc4. It is only in develop.

**Pull request merged**
