### PR TITLE
Another change from recovery passphrase to Security Phrase

### PR DESCRIPTION
**Pull request by aaronraimist**
Guess I missed this one in https://github.com/matrix-org/matrix-react-sdk/pull/5533

### CODE REVIEW

**Comment by aaronraimist** [comment]
A very similar but slightly different string is used in another file. If you want to pick one then it could be standardized and only translated once. https://github.com/matrix-org/matrix-react-sdk/blob/78b1f6c0b13efd57031a329a1ac62baba948dad3/src/async-components/views/dialogs/security/CreateKeyBackupDialog.js#L313

Enter your Security Phrase a second time to confirm it.
vs
Please enter your Security Phrase a second time to confirm.

**Comment by jryans** [comment]
> Enter your Security Phrase a second time to confirm it.
> vs
> Please enter your Security Phrase a second time to confirm.

The one in `CreateSecretStorageDialog.js` is what's shown to new accounts, so feel free to drop the "please" from key backup so they are shared.

**Review by jryans — APPROVED** [review]
Looks good, thanks! I guess you might intend to add one more change though?

**Review by jryans — APPROVED** [review]
Great, thanks! 😄

**Pull request merged**
