### PR TITLE
Make AppsDrawer resizable by dragging its bottom border

### PR DESCRIPTION
**Pull request by pv**
Make widgets resizable by dragging their bottom border with mouse. Implements https://github.com/vector-im/riot-web/issues/6785  (see especially https://github.com/vector-im/riot-web/issues/6785#issuecomment-604038713)

[Video](https://raw.githubusercontent.com/pv/matrix-react-sdk/resizable-appsdrawer-media/appsdrawer.webm)

Fixes https://github.com/vector-im/riot-web/issues/6785

### CODE REVIEW

**Comment by nadonomy** [comment]
@pv is it possible to make the target to drag more generous? From the video it looks like your cursor struggles to drag exactly, toggling between cursors rapidly.

**Comment by pv** [comment]
@nadonomy: thanks, the handle indeed was half hidden behind the apptile. Fixed it, now it should be the same size as the other handles: https://raw.githubusercontent.com/pv/matrix-react-sdk/resizable-appsdrawer-media/appsdrawer-2.webm

**Comment by nurjinjafar** [comment]
@pv is this video: https://raw.githubusercontent.com/pv/matrix-react-sdk/resizable-appsdrawer-media/appsdrawer-2.webm still available? i can't play it!

**Comment by t3chguy** [comment]
@nurjinjafar sounds like your browser doesn't support WebM. It plays fine in Firefox

**Comment by t3chguy** [comment]
Has been superceded by #5138, making use of the above commits as a foundation.

**Pull request closed without merging**
