### PR TITLE
Compound Typography pass regression fixes

### PR DESCRIPTION
**Pull request by germain-gg**
Worked on this with @nadonomy 
Introduced by https://github.com/matrix-org/matrix-react-sdk/pull/11103

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
Looks sane

**Review by nadonomy — CHANGES_REQUESTED** [review]
From DM discussion, for PR posterity:

- To revert usernames back from sm to md, as this introduces strain without materially improving the timeline legibility or hierarchy
- Nit: Text in room tiles with previews isn't vertically centred 
- Nit: Room name & text preview in room tiles would benefit from more negative space - 4px extra margin in browser dev tools helps, whatever implementation plays nice with font scaling works

**Comment by nadonomy** [comment]
@germain-gg looking much better, thx! one small issue - it looks like the descenders on message previews are clipping:

Screenshot 2023-07-04 at 16 56 39

**Review by nadonomy — APPROVED** [review]
@germain-gg LGTM now, thx for the tweaks!

If a message preview has no descenders the alignment can look off, but suggest we solve this when we're properly componentising the room list in due course.

**Pull request merged**
