### PR TITLE
De labs font-scaling

### PR DESCRIPTION
**Pull request by JorikSchellekens**
Just a quick fire pr to remove font-scaling from labs. No review requested yet as font-scaling needs to be reviewed after the new room list lands.

requires: https://github.com/vector-im/riot-web/pull/14355
requires: https://github.com/vector-im/riot-desktop/pull/112

### CODE REVIEW

**Comment by jryans** [comment]
What happens today with the new room list here? Does the scaling not apply or...?

**Comment by jryans** [comment]
@JorikSchellekens In order to make this available for the upcoming launch even while it may have some issues, could you move UI controls into the advanced section and request design review?

**Comment by JorikSchellekens** [comment]
It seems to work fine for the room list. Can we get design review and land it as is? @jryans

**Comment by JorikSchellekens** [comment]
@nadonomy could we get a quick look at this?

**Comment by nadonomy** [comment]
@JorikSchellekens @jryans having played around with this in more anger, would be great if we can adjust the sizes to:

- 13
- 14
- 15 (Default, middle)
- 16
- 18

Above 18 seems to clip some larger text in some places, which we can circle back to in future.

**Pull request merged**
