### PR TITLE
Improve room directory UX for mobile devices

### PR DESCRIPTION
**Pull request by 2580ayush2580**
Fixes https://github.com/vector-im/element-web/issues/16063

Before:-

element2

After pull request:-

resolve3

Please Review My PR
Signed-off-by: Ayush Kumar [2580ayush2580@gmail.com]()

### CODE REVIEW

**Comment by 2580ayush2580** [comment]
@jryans Please Review Changes

**Comment by weeman1337** [comment]
Hey @2580ayush2580 maybe we could merge this and #5551? Then the room list is improved on both: desktop and mobile.

**Comment by jryans** [comment]
Since the mobile view is experimental support only, I'll take a look at https://github.com/matrix-org/matrix-react-sdk/pull/5551 first. We may need to adjust this one if it merges soon.

**Comment by jryans** [comment]
@2580ayush2580 Can you merge develop into your branch here, so that we can see a preview site of this now that https://github.com/matrix-org/matrix-react-sdk/pull/5551 has merged?

**Comment by 2580ayush2580** [comment]
I will update my PR according to this PR #5551

**Review by jryans — CHANGES_REQUESTED** [review]
Thanks for merging! It seems like you'll need to make some more changes to adjust for the new grid style, as it's no longer moving to the next line as it was before:

Screen Shot 2021-02-16 at 14 26 51

**Review by jryans — CHANGES_REQUESTED** [review]
Hmm, the current means rows will create a horizontal scrollbar on mobile devices, isn't that confusing...?

Screen Shot 2021-03-09 at 16 25 55

I think it would better if we could change to a "column" style for low width devices, so that the user count and preview button for each room are shown below the room info (or something similar), so we can avoid needing a horizontal scrollbar here.

**Comment by 2580ayush2580** [comment]
ttt

**Review by jryans — APPROVED** [review]
Thanks for the continued work, it seems usable on mobile now, though the info is a bit spread out, and it's a bit hard to know where the rows start and end. I'd be happy to merge this as-is and, we could refine it further in a separate PR, or keep working in this one. @2580ayush2580, what would you prefer?

For example, it might look better if the left hanging avatar was still indicating where a row starts, but we've move the user count and action button below the details (unsure whether the user count and action should then be laid out horizontally or vertically):

image

**Comment by MadLittleMods** [comment]
> I'd be happy to merge this as-is and, we could refine it further in a separate PR, or keep working in this one.

@jryans Given no response, seems like we should just merge to get the iterative improvements ⏩

**Pull request merged**
