### PR TITLE
Inhibit clicking on sender avatar in threads list

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/23482

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Inhibit clicking on sender avatar in threads list ([\#9417](https://github.com/matrix-org/matrix-react-sdk/pull/9417)). Fixes vector-im/element-web#23482.

### CODE REVIEW

**Review by weeman1337 — APPROVED** [review]
LGTM :+1:

**Comment by weeman1337** [comment]
Is this flow something we should cover with cypress tests?

**Comment by t3chguy** [comment]
Threads are in Labs so do not require tests

**Comment by t3chguy** [comment]
Force merging due to wedged Cypress test

**Pull request merged**
