### PR TITLE
When joining, use a roomAlias if we have it

### PR DESCRIPTION
**Pull request by lukebarnard1**
And default to the current roomId otherwise

### CODE REVIEW

**Comment by richvdh** [comment]
except for all the build fails...

**Comment by lukebarnard1** [comment]
Requires https://github.com/vector-im/riot-web/pull/4252 for the tests to pass, so we'll land that first and then merge

**Comment by lukebarnard1** [comment]
I've re-triggered the builds, they should pass now now that vector-im/riot-web#4252 has landed

**Comment by lukebarnard1** [comment]
Fixes https://github.com/vector-im/riot-web/issues/4251

**Pull request merged**
