### PR TITLE
Reorganize preferences

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes [#16550](https://github.com/vector-im/element-web/issues/16550)

Screenshot_20210310_153229
Screenshot_20210310_153250

### CODE REVIEW

**Comment by niquewoodhouse** [comment]
This feels so much easier to scan and digest.  In general, I wish the margins between each item could be improved to help people scan the list more, but this is a great step forwards for this section.  And thanks for including screenshots.  Just some small comments and questions.

- I didn't quite understand the distinction between the `hide on timeline` and `timeline` sections.  I get the want to break up the density of options, but the timeline list has a `show avatars in user and room mentions`, which feels like from the wording it should be in the `hide on timeline` section unless I misunderstood it?  `Enable big emoji.`..is that also defining something that is visible on the timeline?  Please let me know if I've misunderstood these.

- Are the `hide things on timeline` options set to on by default?  Or is that customizable by the server?   I just wonder if it's a confusing title, given the switches when `on` are showing things.  Maybe in practice, it doesn't matter but `Display things on timeline` might be clearer.
  
- I don't think keybindings is a very familiar term to most people.  I assume Keyboard shortcuts would be more immediately understandable to most users.  Is that what this is?  If so, I think Keyboard shortcuts makes the most sense, and I do believe there are other shortcuts, maybe in small text we should include a link to see them all underneath it?


- `Use Ctrl + F to search` could that be `Use Ctrl + F to search current room or conversation`?  I kind of expected it to open the filter/search room list.
 
I had some other comments, like room list possibly not being a known term, and the option in it talking about something above the room list, not actually the room list itself - but I see that's nothing to do with your changes, it's already in the product.

Thanks

**Comment by SimonBrandner** [comment]
> I didn't quite understand the distinction between the hide on timeline and timeline sections. I get the want to break up the density of options, but the timeline list has a show avatars in user and room mentions, which feels like from the wording it should be in the hide on timeline section unless I misunderstood it? Enable big emoji...is that also defining something that is visible on the timeline? Please let me know if I've misunderstood these.

Yeah, you're right - I was trying to decrease the density but it probably doesn't make much sense to put these apart

> Are the hide things on timeline options set to on by default? Or is that customizable by the server? I just wonder if it's a confusing title, given the switches when on are showing things. Maybe in practice, it doesn't matter but Display things on timeline might be clearer.

I'll merge them into just `Timeline`

> I don't think keybindings is a very familiar term to most people. I assume Keyboard shortcuts would be more immediately understandable to most users. Is that what this is? If so, I think Keyboard shortcuts makes the most sense. I do believe there are other shortcuts, so maybe we should include a link to see them all underneath it, but I don't actually know if that list exists/how to see it, so maybe we leave that for 

Yes, `Keybaord shortcuts` sounds nice. There is a list of all of them if you press `Ctrl+/`. I'll see if I can add a link to it.

> Use Ctrl + F to search could that be Use Ctrl + F to search current room or conversation? I kind of expected it to open the filter/search room list.

I'll change the name to make thing clearer

> I had some other comments, like room list possibly not being a known term, and the option in it talking about something above the room list, not actually the room list itself - but I see that's nothing to do with your changes, it's already in the product.

**Comment by SimonBrandner** [comment]
@niquewoodhouse, thanks for the suggestions!

Screenshot_20210430_111417

This is how the merged timeline section looks.

Screenshot_20210430_111453

I've tried using the `Keyboard shortcuts` button that is used in the `Help & about` user settings tab but it doesn't fit there at all... Do you have an idea of how it should look in mind?

**Comment by niquewoodhouse** [comment]
Hey @SimonBrandner thanks so much for your patience and the reminder!

Two small things:

- In Keyboard shortcuts, making all shortcuts accessible in some way

image

I used `mx_SettingsTab_subsectionText` to include some copy, which can be a link to open the shortcuts.   `Click here` can be the link bit.  I'm sure the copy could be better but this is alright for now.

- Use `Ctrl + F to search current room` could be `Use Ctrl + F to search timeline`

**Comment by SimonBrandner** [comment]
@niquewoodhouse, I've updated the PR, this is the updated look:

Screenshot_20210701_190244

**Review by t3chguy — APPROVED** [review]
Looks sane code-wise

**Review by niquewoodhouse — APPROVED** [review]

**Pull request merged**
