### PR TITLE
Revert "Use another login"

### PR DESCRIPTION
**Pull request by SimonBrandner**
### Description

As mentioned [here](https://github.com/vector-im/element-meta/issues/361), _Use another login_ and _Verify this login_ are regressions in many people's opinion. In the Czech translation, this resulted in something more like _Use another username_ which is not what the option is at all...

Screenshot_20210504_210433

### Notes

This currently does the change _only_ in this dialog, but I think we should globally stick to it. _Session_ is already used in most places, so I don't really see the reason to use _login_ which is actually probably more confusing, imo. 

Personally, I feel like _device_ is the best but that isn't ideal either because you can have multiple logged-in sessions on one physical device.

One thing I am almost sure about is that _login_ isn't good as it sounds more like a _username_ or something along those lines. These seem to support this: ["login" (dictionary.com)](https://www.dictionary.com/browse/login), ["login" (techterms.com)](https://techterms.com/definition/login), ["login" (wikipedia.org)](https://en.wikipedia.org/wiki/Login), ["login" (dictionary.cambridge.org)](https://dictionary.cambridge.org/dictionary/english/login)

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Revert "Use another login" ([\#5967](https://github.com/matrix-org/matrix-react-sdk/pull/5967)).

### CODE REVIEW

**Comment by jryans** [comment]
I suspect it may take a while to review this, as there's a lot of history in the naming to page back in.

**Comment by frlan** [comment]
I'd even extent it to include something like "with another session" -- but actually no real idea how to phrase it. But this version already improves it a lot IMHO

**Comment by weeman1337** [comment]
Hi @SimonBrandner can you check if this one is still valid?

After a quick test I found „other device“ everywhere.

image

**Comment by SimonBrandner** [comment]
You're right - thank you for letting me know!

**Pull request closed without merging**
