### PR TITLE
Expose at-room power level setting

### PR DESCRIPTION
**Pull request by turt2live**
Fixes https://github.com/vector-im/riot-web/issues/5835

### CODE REVIEW

**Comment by t3chguy** [comment]
testing this now :)

**Comment by t3chguy** [comment]
Looks GREAT except it breaks when you set it to `0` because js-sdk treats it as 50, so breaks notifications and autocomplete, blocking on https://github.com/matrix-org/matrix-js-sdk/pull/651

**Comment by turt2live** [comment]
Blocking this on the autocomplete not working correctly (even today) feels a bit weird, particularly given the unlikeliness of someone actually setting this to be 0.

**Comment by t3chguy** [comment]
It's not just autocomplete, if you set it to 0 then it won't get highlighted unless you're PL >=50

**Comment by t3chguy** [comment]
Though on the other hand to get around that this would need to block until the js sdk fix is in stable riot, which is a little obscene so...

**Comment by turt2live** [comment]
I was going to say something like "it's a bug either way independent of this change", and then github updated itself :p

**Pull request merged**
