### PR TITLE
Remove package-lock.json for now

### PR DESCRIPTION
**Pull request by dbkr**
As per https://github.com/vector-im/riot-web/issues/7083

The package-lock file is currently not bringing any of the benefits
it's supposed to bring because we don't do the neccessary things to
massage it during the release process. Remove it until we actually
manage it correctly.

### CODE REVIEW

**Comment by bwindels** [comment]
Cool. Perhaps also include it in `.gitignore`?

**Comment by dbkr** [comment]
Done

**Comment by bwindels** [comment]
The GroupView tests are broken, hmm. Doesn't seem like it's due to test flakiness as I restarted the build with exactly the same result.

**Comment by dbkr** [comment]
Eugh, presumably, having asserted npm isn't reading this file, presumably npm 6 on Travis *is* reading it and is preventing us from pulling in a new dependency which breaks the test. What a mess.

**Comment by bwindels** [comment]
Interesting. Strange that adding it to `.gitignore` would trigger this. Seems to be a TypeError in the client (or the peg), in one of the fetchers in `GroupView::_resourceFetcher`. Would be good to see the stack. Ughh.

**Comment by bwindels** [comment]
sanitize-html seems to be the offender. Adding it to `.gitignore` was probably not what caused the error but merging the PR in riot-web as it's in the manifest for both repos (with different versions)

**Comment by dbkr** [comment]
indeed it did seem to be the sanitize-html thing

**Pull request merged**
