### PR TITLE
Update WidgetUtils.js fix Jitsi path

### PR DESCRIPTION
**Pull request by t3chguy**

### CODE REVIEW

**Comment by t3chguy** [comment]
> its what caused me to get a riot embedded instead of a Jitsi so I entirely disagree.

http://riot.im/develop/index.html? is a valid (albeit bizarre) way to view Riot, if you add a trailing slash to that it won't work.
However if you try and go to https://riot.im/develop you will observe that the webserver adds the trailing slash for you because its a directory.

I don't think writing a heuristic to detect "indexy" things is sane.

**Comment by turt2live** [comment]
we also can't guarantee that `window.location` will have a slash...

**Comment by t3chguy** [comment]
> we also can't guarantee that window.location will have a slash...

the right thing to do, is to follow browser mechanisms and use relative paths which is what the above matches.

**Comment by turt2live** [comment]
No, it's not:
```
new URL("jitsi.html#stuff", "https://riot.im/develop")
URL {href: "https://riot.im/jitsi.html#stuff", origin: "https://riot.im", protocol: "https:", username: "", password: "", …}
```

**Comment by t3chguy** [comment]
Right. the above example is expected. but in this case it is not possible to write code which works for both

riot.im/develop
&
riot.im/develop/index.html

and we have no way of knowing if someone is just hosting their riot in a folder called index.html or if its a file so we should rely on relative URLs as other apps would break if they were misconfigured too as they wouldn't be able to find their assets without manual base url configuration.

**Pull request merged**
