### PR TITLE
Adds Option to Choose Light High Contrast Theme

### PR DESCRIPTION
**Pull request by tessgadwa**
Configuration file for option high contrast condensed light desktop theme.

I also had to manually add a lib file to get my local build to run -- please let me know if you encounter any difficulties.

Signed-off-by: Tess Gadwa <tess.gadwa@yesexactly.com>

### CODE REVIEW

**Comment by lukebarnard1** [comment]
This bit looks good, I'll make some comments on https://github.com/vector-im/riot-web/pull/3819

**Comment by dtygel** [comment]
How does it relate to https://github.com/matrix-org/matrix-react-sdk/pull/876 ?

**Comment by tessgadwa** [comment]
@dtygel The riot-web PR #3819 is still under review. Would be curious for your thoughts as to how it would integrate with your changes.

**Comment by lukebarnard1** [comment]
Closing as per https://github.com/vector-im/riot-web/pull/3819#issuecomment-399949216

**Pull request closed without merging**
