### PR TITLE
Improve the look of the spinner

### PR DESCRIPTION
**Pull request by SimonBrandner**
This replaces the current spinner icon with something a bit less outdated and more visually pleasing (at least in my opinion).

<hr>

Screenshot from 2021-10-30 09-35-45

Screenshot from 2021-10-30 09-36-03

---
Here's what your changelog entry will look like:

## ✨ Features
 * Improve the look of the spinner ([\#6083](https://github.com/matrix-org/matrix-react-sdk/pull/6083)). Contributed by @SimonBrandner.

Preview: https://6180096f25c04b89cdb6a304--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by robintown** [comment]
Huh, I had no idea there were so many spinner PRs. Make sure to update InlineSpinner's CSS as well.

**Comment by SimonBrandner** [comment]
> Make sure to update InlineSpinner's CSS as well.

As far as I can tell, there isn't anything I would need to change there. Am I missing something?

**Comment by robintown** [comment]
Oh nevermind, I forgot that InlineSpinner now reuses the Spinner class

**Review by t3chguy — APPROVED** [review]
LGTM code-wise

**Comment by niquewoodhouse** [comment]
@janogarcia 👋 I think this is in your area of focus - a community PR to improve the spinner on web.

**Review by niquewoodhouse — COMMENTED** [review]
Looks good thanks @SimonBrandner 

Just one thing

- On the sign-in page, it's in a strange position but I don't think that's anything to do with your files?  Would be great if possible to double check what's happened there.

image

**Comment by SimonBrandner** [comment]
> Looks good thanks @SimonBrandner

Thanks!

> Just one thing
> 
> On the sign-in page, it's in a strange position but I don't think that's anything to do with your files?  Would be great if possible to double check what's happened there.

Should be fixed now

**Review by niquewoodhouse — APPROVED** [review]
👌🏽

**Review by t3chguy — APPROVED** [review]
Looks sane to me! thanks

**Pull request merged**
