### PR TITLE
Remove weird padding on stickers

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/17787

Screenshot_20210626_081430

Preview: https://61cc1cc1c5975ed4d1717fb1--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
Code-wise LGTM

Not sure if this might want some design input,

image

(before^)

**Comment by Oha-you** [comment]
I hope this padding can be removed soon 😅
There's really no reason to add it IMO, a sticker should be treated in the same way as a normal message.
Also the case when a single person sends several stickers in a row is rather rare, I think. And messages from different people already have their own padding in `.mx_EventTile`.
Another idea: remove this padding only when "Modern/compact layout" is selected. Though I'd still lower it to 10px by default.

**Review by janogarcia — CHANGES_REQUESTED** [review]
The padding is probably there for two reasons:

- Make the sticker stand out in the timeline, rather than making them look like regular images.
- Account for stickers that may have little empty space and prevent them from collapsing with other contents.

In my opinion, the 0px padding proposed in this PR it's just a personal preference that it's not addressing any of the use cases above. That said, I have tested different padding values for `.mx_MStickerBody_wrapper` (0, 12px, 20px) for different sticker packs, and it seems 12px could be a better compromise between standing out in the timeline and not taking up too much space.

**Comment by janogarcia** [comment]
Worst case scenario for zero padding: sticker without inner padding.

Chatterbox – Figma

**Review by janogarcia — APPROVED** [review]

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
