### PR TITLE
Update muting in calls to work with the js-sdk call upgrade changes 

### PR DESCRIPTION
**Pull request by SimonBrandner**
Type: task
**Requires https://github.com/matrix-org/matrix-js-sdk/pull/1827**

<hr>

This is **not** call upgrade support

<hr>

Since design is busy with other stuff I've decided to land call upgrade support in the js-sdk without support in Element. Once this lands we can experiment with call upgrades in group calls and similar things

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

Preview: https://6146cf49d86da16b8d552342--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by robintown** [comment]
Closes https://github.com/vector-im/element-web/issues/12646?

**Comment by SimonBrandner** [comment]
> Closes [vector-im/element-web#12646](https://github.com/vector-im/element-web/issues/12646)?

Yeah, I mainly wanted to put the thing on GH and I didn't bother doing that :D

**Review by turt2live — APPROVED** [review]

**Comment by turt2live** [comment]
(thank you for the reminder - I honestly thought I'd be smart enough to merge based on the js-sdk PR, but apparently not)

**Comment by SimonBrandner** [comment]
> (thank you for the reminder - I honestly thought I'd be smart enough to merge based on the js-sdk PR, but apparently not)

We need some automatic way to do this anyway

**Pull request merged**
