### PR TITLE
Added the /html command

### PR DESCRIPTION
**Pull request by waylon531**
This command lets you send html messages through riot. This is
incredibly useful for doing advanced formatting not supported by
markdown and lets riot support even more html tags.

I ended up implementing this for my fork of riot that supports extra html tags and it seemed useful to upstream, so here it is. I think there might be something missing here with respect to translations but I'm not sure how i18 works so I didn't put anything in.

### CODE REVIEW

**Comment by t3chguy** [comment]
As per the CONTRIBUTING doc, this needs a DCO sign-off, for i18n you need to run the script `yarn i18n` and then make a new commit with the modified file.

**Comment by waylon531** [comment]
Alright, just ran that command. Let me know if everything checks out!

**Comment by turt2live** [comment]
@waylon531 looks like your rebase went bad as it now has commits from other branches in here.

Please avoid rebases where possible and instead prefer merge commits.

**Comment by waylon531** [comment]
Yeah, I usually prefer merges myself. I ended up rebasing and adding the DCO signoff to my commit messages, it went wrong a couple of times (for some reason it was including some commits from the official repository?) but everything should be good now.

The ability to send HTML messages is useful in a couple of circumstances. RiotX doesn't support html in the same way that riot-web does so it's useful to be able to test what tags work and what doesn't, and to test how tags get rendered. I also have a custom version of riot-web running that allows extra html tags and a feature like this is the only way to make use of them. Previously I was sending html messages through a script but this is so much easier.

**Pull request merged**
