### PR TITLE
Add border radius to uploaded images

### PR DESCRIPTION
**Pull request by Dragnucs**
This adds a nice little border radius to uploaded images in discussions.

[](https://postimg.cc/bSnKWMXR)

Signed-off-by: Touhami MAHDI <touhami@touha.me>

### CODE REVIEW

**Comment by t3chguy** [comment]
This needs DCO sign-off as per the CONTRIBUTING doc. Also a screenshot of the effect in the PR would help.

**Comment by turt2live** [comment]
hey @Dragnucs are you able to sign off on this as per above? Thanks!

**Comment by Dragnucs** [comment]
Hello,

I think I might do that, I just need some time.

Can this be done via GitHub web UI ?

On April 14, 2020 8:48:06 PM GMT+01:00, Travis Ralston <notifications@github.com> wrote:
>hey @Dragnucs are you able to sign off on this as per above? Thanks!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/matrix-org/matrix-react-sdk/pull/4393#issuecomment-613646070
Cordialement / Regards,
Touhami
https://touha.me

**Comment by t3chguy** [comment]
Yup. Just edit your PR description with it.

**Comment by Dragnucs** [comment]
I updated the PR description with sign-off and screenshot. I hope this is sufficient.

**Comment by turt2live** [comment]
Thanks! I've sent this off for review from our design and development teams.

**Comment by nadonomy** [comment]
Hey @Dragnucs thanks for the contribution. This is a nice bit of polish but unfortunately we're going to hold off from merging this with master.

The border-radius property chosen (0.5rem) is fairly arbitrary and we're behind the scenes we're working on cross-platform UI refreshes which will iterate on this kind of stuff as part of a more cohesive design language, so it doesn't make sense to merge as is.

Thanks again though!

**Pull request closed without merging**
