### PR TITLE
Slightly improve the look of the `Message edits` dialog

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/22410

<hr>

---
Here's what your changelog entry will look like:

## ✨ Features
 * Slightly improve the look of the `Message edits` dialog ([\#8763](https://github.com/matrix-org/matrix-react-sdk/pull/8763)). Fixes vector-im/element-web#22410.

### CODE REVIEW

**Comment by robintown** [comment]
IMO the title should be left-aligned, since the way it's off-center with the date separator doesn't look great, and no other dialog puts the title there

**Review by turt2live — APPROVED** [review]
I don't think this needs design as it's effectively fixing a bug, though it'd be good to add to their backlog that there's an Edit History dialog that hasn't seen attention in years.

**Comment by HarHarLinks** [comment]
@turt2live @SimonBrandner shouldn't this use the color (and maybe icons)?

image

**Comment by turt2live** [comment]
Possibly, but that's for a different redesign ticket. This PR got scoped to maintenance.

**Comment by HarHarLinks** [comment]
Does this ticket exist yet?

**Comment by SimonBrandner** [comment]
No, not yet

**Pull request merged**
