### PR TITLE
Add warning bar for guest users.

### PR DESCRIPTION
**Pull request by dbkr**
Fixes https://github.com/vector-im/vector-web/issues/770

### CODE REVIEW

**Comment by Kegsay** [comment]
Is there a vector-web PR to rename the class names in the CSS?

**Comment by dbkr** [comment]
There is now

**Comment by Kegsay** [comment]
I don't mean to throw a spanner in here, but when you login as a guest you get dumped to the room directory and not a room. Therefore,  people will never see this message until way too late. Would it not be better to clobber the desktop notification bar which appears on every screen?

**Comment by dbkr** [comment]
@AmandineLP ?

**Comment by AmandineLP** [comment]
Good point @Kegsay, yup let's do this with the message as described in https://github.com/vector-im/vector-web/issues/770:
"You're using Vector as a guest, register or login to unlock all accesses."
with links to the register/login form

**Comment by dbkr** [comment]
@AmandineLP - are you saying you'd like to use the text you provided? 'access' isn't a discrete quantity, so it's not something you would normally pluralise, which is why I went with, "**Register** or **log in** to access more rooms and features.". You could also say, "to unlock full access".

**Comment by AmandineLP** [comment]
@dbkr Ah sure, feel free to fix the english sorry :) I didn't go into the code to check what you wrote but "unlock full access" sounds even better yes

**Comment by dbkr** [comment]
Okay, will do that then with the notification bar. Although, will this presumably mean that guests won't have an obvious way to enable desktop notifs without registering - is that okay?

**Comment by AmandineLP** [comment]
I never realised desktop notifs were off by default... But I think that's ok, let's see if people think it's a blocker later
thanks!

**Comment by dbkr** [comment]
ptal

**Comment by Kegsay** [comment]
LGTM

**Pull request merged**
