### PR TITLE
Display the action buttons on the center of the modal window

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/vector-im/element-web/issues/21604

Please see the issue for the reasoning of this change.

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

after1

---
Here's what your changelog entry will look like:

## ✨ Features
 * Display the action buttons on the center of the modal window ([\#8196](https://github.com/matrix-org/matrix-react-sdk/pull/8196)). Fixes vector-im/element-web#21604. Contributed by @luixxiul.

Preview: https://pr8196--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by kerryarchibald — COMMENTED** [review]
This change needs input from our design team.

**Review by janogarcia — COMMENTED** [review]
PR comments in m y previous message. https://github.com/matrix-org/matrix-react-sdk/pull/8196#issuecomment-1122655226

I'd recommend waiting for @amshakal input, as she may be already working on a different solution.

**Comment by janogarcia** [comment]
@amshakal Related https://github.com/matrix-org/matrix-react-sdk/pull/8167

**Comment by luixxiul** [comment]
Closing as stale due to no response.

**Pull request closed without merging**
