### PR TITLE
Apply the same max-width to image tile on the thread timeline as message bubble

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes https://github.com/vector-im/element-web/issues/22313

|Before|After|
|---------|------|
|before|after|

This PR replaces the hard-coded width value with a variable in order to align the image on the thread timeline with message bubbles.

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Apply the same max-width to image tile on the thread timeline as message bubble ([\#8669](https://github.com/matrix-org/matrix-react-sdk/pull/8669)). Fixes vector-im/element-web#22313. Contributed by @luixxiul.

### CODE REVIEW

**Comment by SimonBrandner** [comment]
Hmm, I think they should be wider rather than smaller?

**Comment by luixxiul** [comment]
I would agree, still the width setting should be adjusted some way, otherwise you could get the image which covers the thread timeline as below...

before

**Review by t3chguy — APPROVED** [review]
Looks sane to me, thanks!!

**Comment by luixxiul** [comment]
Fixing the conflict...

**Review by SimonBrandner — APPROVED** [review]

**Pull request merged**
