### PR TITLE
Add composer option to autoformat selection as list

### PR DESCRIPTION
**Pull request by owi92**
This adds a button and a shortcut for the ability to format selected lines as either a bulleted or a numbered list in the composer. Similar to other common implementations of this feature, it also allows to format complete lines if they are only partially selected, or single lines at caret position without any selection. Pressing the button or shortcut again or while selecting already formatted sections will unformat the lines.

Please note that for now this is missing the correct icons for the formatting bar, as I wasn't sure what icons should or could be used here and what the procedure of adding new icons to matrix-react-sdk would be.

https://user-images.githubusercontent.com/94838646/196958718-c110dcd7-2d0d-4c0e-a7bd-a0ca53240e7e.mov

Singed-off-by: Ole Wieners olewieners@yahoo.com

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Add composer option to autoformat selection as list ([\#9473](https://github.com/matrix-org/matrix-react-sdk/pull/9473)). Contributed by @owi92.

### CODE REVIEW

**Comment by t3chguy** [comment]
To fix the i18n CI please run `yarn i18n` and commit the result

**Comment by dbkr** [comment]
I think the first step for this would be product signoff, so probably easiest to make an issue for it and then get a tick from product on that.

**Review by richvdh — COMMENTED** [review]
pending design review

**Comment by weeman1337** [comment]
Clearing reviewers while waiting for design…

**Comment by daniellekirkwood** [comment]
@jakewb-b I'm going to assign this to you as I believe you would have the most context in answering this PR. Let me know if this doesn't work for you :)

**Review by jakewb-b — COMMENTED** [review]
The end-state for the new composer / RTE is expected to deprecate this piece of UI altogether, as the composer  will operate either in 

- markup-only mode, in which these easy-format buttons won't be available 
- rich-text mode, in which the full selection of formatting options are present, including lists

@daniellekirkwood can I just confirm that Web does intend to fully implement the RTE in this way at some point in the future? If not that might change our assumptions. 

But assuming yes, this change is likely to be fairly quickly overtaken and unfortunately made irrelevant. So, @owi92 If this requires further changes based on engineering or design reviews, I'd probably caution against spending too much time on this.

That said, it is a useful update for as long as it does exist, so if it's acceptable in all other respects (in particular, from the design POV - and we'll need to figure out those icons) then from the product perspective I'd be happy to approve it.

**Comment by rufuskahler** [comment]
Assigning to @callumu for design review :)

**Comment by jakewb-b** [comment]
@rufuskahler - sorry, I should have updated this, but Danielle and I spoke offline and she confirmed that she's happy for it to be my decision on the future of the RTE. So, in that case, I can confirm we will want the RTE editor to land in Element Web as soon as we can get it out of labs, and that will deprecate this issue. So, I'm happy to merge it but only if it can be done without too much time spent by either us or the submitter.

**Comment by rufuskahler** [comment]
@callumu – With the above from @jakewb-b – Can you add your feedback here as a comment?

**Comment by callumu** [comment]
It seems that as we're deprecating this easy-format menu with the new composer, it won't be merged and therefore doesn't need a review. Is this correct?

**Comment by florianduros** [comment]
Hi!

We are moving to a new composer, the Rich text editor. Due to all the conflicts and the size of changes, we will close it in favor of the new composer.

**Pull request closed without merging**
