### PR TITLE
Supports Drag & Drop of images from other browser windows into RoomView

### PR DESCRIPTION
**Pull request by georgiemathews**
Implements vector-im/riot-web#3015
Added a method to get link from dataTarget in onDrop event.
Signed-off-by: Georgie Mathews <mathews.georgie@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
The issue with this is you can't fetch all image urls from Javascript because of CORS and other restrictions.

**Comment by georgiemathews** [comment]
how about just linking to the image when there is a cors issue else actually uploading them.

**Comment by t3chguy** [comment]
There's already an existing PR which does better: #1689

**Comment by georgiemathews** [comment]
ah okay, we can close this one then?

**Comment by aaronraimist** [comment]
Should this be closed? TIL there are like 4 or 5 open drag and drop related PRs

**Pull request closed without merging**
