### PR TITLE
fix zero length tab complete so it doesn't fire automatically on empty MessageComposer

### PR DESCRIPTION
**Pull request by ara4n**

### CODE REVIEW

**Comment by richvdh** [comment]
looks ok, but wouldn't it be clearer/easier to add `if (this.textArea.value !== "")` to the timer code at line 184 rather than chase `passive` through and bailing out halfway through?

(IIRC kegan's intention was that the passive and non-passive codepaths be as similar as possible; hence it is preferable to avoid entering the codepath at all)

**Comment by ara4n** [comment]
this doesn't work because we also want it to not autofire on strings like "foo ".

**Comment by richvdh** [comment]
right, I see.

I don't like the way `startTabCompleting` sets some fields, then if it decides it was all a terrible mistake, calls `stopTabCompleting` to undo its mess (which fires a callback in the process). Given `_calculateCompletions` is only called from `startTabCompleting`, how about inlining it, and only set `this.completing` once we know we aren't going to bail out early?

I think the `if (!res)` path at line 278 should do the same fwiw.

**Comment by richvdh** [comment]
lgtm

**Pull request merged**
