### PR TITLE
Show room is encrypted on the sidebar roomtile

### PR DESCRIPTION
**Pull request by t3chguy**
Initial implementation:
image

Fixes https://github.com/vector-im/riot-web/issues/10180

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by turt2live** [comment]
@nadonomy will need to take a look at this first

**Comment by t3chguy** [comment]
of course, this was just a quick mockup to get the ball rolling

**Comment by nadonomy** [comment]
Hey @t3chguy— I'm actually just about to embark on (as in, in the next few days) figuring out encryption decoration across all platforms, which this would be a part of. Broadly speaking, the constraints and considerations are:

- Encryption relates to security, so we want to spend more time getting these changes as correct as possible up front, to avoid any unnecessary changes which would confuse users and erode trust
- A lot of our users use multiple platforms, so it's important we solve decoration consistently across all platforms
- We have several related and outstanding issues regarding iconography; e.g. some users carry affordance from https so associate locks with that, other users carry affordance from platforms like Slack so associate locks with private rooms
- Relatedly, we need to figure out how to precisely visualise device trust

Given all that, I'm reluctant to merge this PR in as is, and think it's better we figure out how we want to decorate rooms holistically given considerations like the above.

Given the technical changes are minimal, I think the risk of bit rot is too. Does it sound good to you for us to leave this open, and in the near future we revisit the PR with some simple icon/logic changes in line with something we have more confidence in?

**Comment by t3chguy** [comment]
Sure, that was my entire point with this PR, I knew it wouldn't be ready as-is

**Comment by jryans** [comment]
@t3chguy Thank you for starting the conversation here! 😁 We'd prefer to not leave PRs hanging without resolution for a long time, so I'll go ahead and close this for now. We can certainly use this as reference once we have the design firmed up.

**Comment by t3chguy** [comment]
> (as in, in the next few days)

I don't think this is a long time

**Comment by jryans** [comment]
Ah okay, when we discussed this PR during a team standup, I am not sure we saw that detail from @nadonomy... 😅 It was discussed as though the icons would be coming "at some unknown future time".

Sorry for the extra confusion. Anyway, the next step is to get the icons. We can reopen this PR or start a new one as appropriate when the icons appear.

**Comment by nadonomy** [comment]
Fwiw, things are moving. :) I wrapped up an initial proposal today which will do the rounds with internal stakeholders and then move from there.

**Comment by t3chguy** [comment]
Hey @nadonomy any updates?

**Comment by nadonomy** [comment]
Hey @t3chguy— a lot of the stakeholders on the core team are currently tending to urgent (privacy or security related) things with priority or are currently on holiday, so I'd expect progress to be a little slow.

I'll continue to iterate though and nudge internally, and just added a note on my personal TODO to ping you with an update again this time next week.

**Pull request closed without merging**
