### PR TITLE
Make diff colors in codeblocks more pleasant

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/17939#issuecomment-878141061

<hr>

#### Before:

Screenshot_20210712_123422

#### After:

Screenshot_20210712_165936

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
Unrelated, but shouldn't there be any empty spaces inbetween the lines at all?

**Comment by SimonBrandner** [comment]
> Unrelated, but shouldn't there be any empty spaces inbetween the lines at all?

Better? :)

**Comment by ShadowJonathan** [comment]
Yeah, thanks!

**Review by turt2live — APPROVED** [review]
:shipit:

**Pull request merged**
