### PR TITLE
null-guard defaultAvatarUrlForString

### PR DESCRIPTION
**Pull request by t3chguy**
Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

Because a rageshake showed a soft-crash where one of the callers tried to call it with `null`

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
This PR needs a why.

**Comment by t3chguy** [comment]
@turt2live happy with the OP update?

**Comment by turt2live** [comment]
not really - why was it being passed null? is `null` something we really want to support here? why are we returning an empty string instead of the first colour in the array?

**Comment by turt2live** [comment]
(I'd accept some answer that deals with most of these questions tbh - just looking for evidence that we've at least identified that `null` is a valid thing to pass through, and that an empty string is an appropriate response)

**Comment by t3chguy** [comment]
Because it is an existing output of the function already, see https://github.com/matrix-org/matrix-react-sdk/pull/5270/files#diff-60b23d36fdb11dfc4f7e59cdaabb8d36L103 which already returns an empty string.

**Comment by turt2live** [comment]
right, but we shouldn't ever be supplying null to it?

Where is the null coming from?

**Comment by t3chguy** [comment]
That is unclear, the rageshake being obfuscated means I can't see even what React Component it was within, unfortunately, we ideally would never pass anything non-stringy to it, this is just a sanity check to make sure we don't.

**Comment by turt2live** [comment]
can we get an `// XXX: Should never happen, but does` on the statement then?

**Review by turt2live — APPROVED** [review]

**Comment by turt2live** [comment]
thanks for suffering through this review :D

**Pull request merged**
