### PR TITLE
Fuzzy search

### PR DESCRIPTION
**Pull request by weeman1337**
:information_source: ignore this PR for now

ToDo: Add a setting for fuzzy search (disabled by default).

fuzzy

- [FZF algorithm description](https://github.com/junegunn/fzf/blob/master/src/algo/algo.go)
- [FZF for JavaScript](https://github.com/ajitid/fzf-for-js)

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Fuzzy search ([\#10282](https://github.com/matrix-org/matrix-react-sdk/pull/10282)).

### CODE REVIEW

**Comment by leeoniya** [comment]
fzf is okay...but there are better options ;)

https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

**Comment by weeman1337** [comment]
> fzf is okay...but there are better options ;)
> 
> https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

There is always a better option ;)

**Comment by weeman1337** [comment]
Other work on search: https://github.com/matrix-org/matrix-react-sdk/pull/8275
Just to keep that in mind and to not break it.

**Comment by weeman1337** [comment]
There are still some things to do here:
- Refactoring of the spotlight search:
  - Pull out search logic from the UI component
  - Introduce some interfaces
  - It should be possible to switch between algorithms (such as the current one and fzf). The refactoring should be done in a separate PR before.
- Put the new search behind a setting or labs flag

There is a chance I can find some time end of August to work on this.

**Comment by t3chguy** [comment]
@weeman1337 oh definitely, and currently it re-regresses https://github.com/vector-im/element-web/issues/24422

**Comment by t3chguy** [comment]
Think it'd be good to highlight more than just the name also, maybe even go as far as to replace the 2nd-ary text with the most-matching field if it is a !visible one (e.g. topic)

image

**Pull request closed without merging**
