### PR TITLE
Tweak pill UI

### PR DESCRIPTION
**Pull request by weeman1337**
Changes:
- Avatars should always be displayed on the left side
- If a permalink target event in the same room cannot be loaded, the pill label will only be „Message“

| Before | After |
| --- | --- |
| image |image |

part of https://github.com/vector-im/element-meta/issues/1030

closes https://github.com/vector-im/element-web/issues/24855

PSF-1962

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Looks sane to me! Do you know how the component behaves when the text has to wrap over two lines?

**Comment by weeman1337** [comment]
> Looks sane to me! Do you know how the component behaves when the text has to wrap over two lines?

It will cut the text and add ellipsis

image

**Comment by weeman1337** [comment]
Percy diff looks unrelated. Can you approve @t3chguy ?

Also added https://github.com/vector-im/element-web/issues/24889 . It would make sense to write some e2e tests for the permalink pills.

**Comment by andybalaam** [comment]
> Percy diff looks unrelated. Can you approve @t3chguy ?
> 
> Also added [vector-im/element-web#24889](https://github.com/vector-im/element-web/issues/24889) . It would make sense to write some e2e tests for the permalink pills.

Approved.

**Pull request merged**
