### PR TITLE
Implement default room colors

### PR DESCRIPTION
**Pull request by turt2live**
## Required PRs / Related issues
* CSS PR: https://github.com/vector-im/riot-web/pull/5283
* Adds: https://github.com/vector-im/riot-web/issues/738
* Fixes: https://github.com/vector-im/riot-web/issues/1958

## What it looks like
riotdefaultcolors
Note: The red/white tint at the end was part of a test. It's not actually part of the PR.

### CODE REVIEW

**Comment by ara4n** [comment]
this looks awesome! but shouldn't the default room colour picker be in UserSettings rather than RoomSettings, given it impacts the whole app rather than just that specific room?

**Comment by turt2live** [comment]
The default room color is per-room, to implement https://github.com/vector-im/riot-web/issues/738 ("let room admins set default room color"). It's backed by a state event in the room, so individual users can set different colors from what the admins want.

Although this PR could be extended to add a 3rd color picker to UserSettings to blanket defaults for all rooms. Is that something that would be wanted?

**Comment by ara4n** [comment]
aaaaah, i see. hmm. i wonder how much we really want room admins setting their own weird white-on-white style colour schemes for rooms... (and yes, i know i asked for it in the first place).
 
I also wonder if this should be implemented using generic granular settings (i.e. the ability to specify settings arbitrarily per-user, per-room, globally - also useful for stuff like configuring hiding URL previews, join/parts and other cosmetics)

**Comment by turt2live** [comment]
It should be fine if room admins want to do that, as users can always override their choice. The room admin may also find themselves with an angry crowd of people or an empty room - which might be enough of a deterrent to going outside the color schemes Riot lets you define.

Granular settings sounds like something @t3chguy has promised for quite a while now :p 
It really should be a granular setting, but I don't have all the details to implement it myself. If the requirements are outlined somewhere (and maybe some implementation notes?) I could start working away on it if @t3chguy is okay with it.

**Comment by t3chguy** [comment]
Granular Settings are still on the horizon (distant distant horizon)
I need someone to give me an inspiration of how the UI/UX for them would look without drowning everyone with too much choice

**Comment by t3chguy** [comment]
as for notes on Granular Settings I will try to recite a conversation between Matthew, Toml and I,
***
Per-room per-device
Per-room account
Per-room room state default
***
Per device
Per account
Default

is the ordering of the possible sources of truth in Granular Settings as far as I am aware
the top half only applies to options which make sense to be room specific, such as url previews

**Comment by turt2live** [comment]
I'm blocking this on https://github.com/matrix-org/matrix-react-sdk/pull/1516 (Granular Settings).

**Comment by turt2live** [comment]
Closing this for now - it requires relatively drastic changes to work with granular settings and I'm completely out of spare time.

**Pull request closed without merging**
