### PR TITLE
add lenny face command

### PR DESCRIPTION
**Pull request by dkanada**

### CODE REVIEW

**Comment by t3chguy** [comment]
Requires sign-off as per https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.rst#sign-off

**Comment by dkanada** [comment]
Signed-off-by: Dillon Kanada dkanada@protonmail.com

**Comment by dkanada** [comment]
@t3chguy any other issues with the pull request itself?

**Comment by t3chguy** [comment]
It goes through product review before we code review it

**Review by nadonomy — APPROVED** [review]
LGTM.

**Review by t3chguy — APPROVED** [review]
Looks good to me

Thanks

**Pull request merged**
