### PR TITLE
Part 2 of 3: Merge develop->experimental minus #2336

### PR DESCRIPTION
**Pull request by turt2live**
**This intentionally backs out https://github.com/matrix-org/matrix-react-sdk/pull/2336 because is not compatible with experimental.** The remainder of this branch *should* be develop as it is today, as shown here: https://github.com/matrix-org/matrix-react-sdk/compare/develop...travis/develop-for-real

**Requires https://github.com/matrix-org/matrix-react-sdk/pull/2398**

### CODE REVIEW

**Comment by jryans** [comment]
(Waiting on conflicts.)

**Comment by jryans** [comment]
In your first comment, maybe you mean https://github.com/matrix-org/matrix-react-sdk/compare/experimental...travis/develop-for-real?

**Comment by turt2live** [comment]
> In your first comment, maybe you mean experimental...travis/develop-for-real?

Nope, trying to prove that this branch is current develop with only 1 added change. The way to do that is to show what it would look like if the branch were merged into develop instead.

**Comment by turt2live** [comment]
Okay, I've merged experimental into this branch so that it doesn't conflict. The only questionable merge conflict is how the custom status message stuff interacts with experimental, as it may break the layout.

In addition to merging experimental into this branch, I've regenerated the language file so it is consistent going forward. I also didn't want to figure out which strings were no longer used in the merge and just accepted both sides of the conflict, making regeneration a requirement. See https://github.com/matrix-org/matrix-react-sdk/pull/2399/commits/01eacfa26a019bd8918cb92d8dcfa3c82ceb63d4

**Pull request merged**
