### PR TITLE
Enable redirected media by default

### PR DESCRIPTION
**Pull request by turt2live**
**Requires https://github.com/matrix-org/matrix-js-sdk/pull/4007**

Tested with https://github.com/turt2live/matrix-media-repo/pull/543 locally, both in encrypted and unencrypted rooms.

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Enable redirected media by default ([\#12142](https://github.com/matrix-org/matrix-react-sdk/pull/12142)).

### CODE REVIEW

**Review by andybalaam — COMMENTED** [review]
The code looks OK, but I don't understand what approval this needs, as a change of policy of some kind. It feels like either I need more context, or we need someone from the Element Web core team e.g. @dbkr to approve.

**Comment by turt2live** [comment]
This is a feature of the spec which can help servers reduce direct traffic by using a CDN.

I'll defer the review requirements to the team, and happy to answer any questions.

**Comment by turt2live** [comment]
@andybalaam what is needed to move this forward?

**Comment by andybalaam** [comment]
> @andybalaam what is needed to move this forward?

It needs @MidhunSureshR as nominated reviewer, or someone else from the Element Web team, to look at it.

**Review by MidhunSureshR — APPROVED** [review]

**Pull request merged**
