### PR TITLE
Changing the color of highlights to avoid confusions

### PR DESCRIPTION
**Pull request by heIsThePirate**
(with the aim of resolving issues [#9070](https://github.com/vector-im/riot-web/issues/9070) and related)
From:
Old

to:

New

Signed-off-by: Mohit Singh <mohitsingh1997@gmail.com>

### CODE REVIEW

**Comment by bmarty** [comment]
FTR RiotX will send pills

**Comment by heIsThePirate** [comment]
Thanks for the approval @turt2live 
I have tested this in a dev environment set up on my PC for the 'riot-web' and the above screenshots in my original post are for the same. Now, as @bmarty has pointed out that 'RiotX' will send pills and according to the announcement, the codebase of 'riot-android' would be replaced with that of 'RiotX', I don't think that would be a problem anymore...In the meanwhile, I think the stylesheet is already overwritten for the mobile client as this is what I observe in the 'riot-android' for the same content: https://ibb.co/zmB6W5P
I am not much familiar with Android still, I would try to test it with the gradle and update if any issues are found.

**Comment by jryans** [comment]
Riot iOS does not appear to send pills at the moment.

**Comment by turt2live** [comment]
@heIsThePirate just checking in - are you able to take this on still? If not, we can add it to our backlog.

**Comment by heIsThePirate** [comment]
> @heIsThePirate just checking in - are you able to take this on still? If not, we can add it to our backlog.

I have tried several things but wasn't able to test properly due to the recent chaos, this will take some more time. I am busy with exams right now so I guess I would take this on again in a week. Until then, if required, it may be added to the backlog. Thanks!

**Comment by jryans** [comment]
Since we have some unresolved concerns (which I am not quite sure how we _would_ resolve at the moment), and also the author is busy for now, I think it's best to close this for now. Please feel free to open a new PR if it would address the concerns highlighted here. Thanks!

**Pull request closed without merging**
