### PR TITLE
Improve AUX panel behaviour

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/18787
Type: enhancement

<hr>

Screenshot_20210827_133505

<hr>

This still quite far away from ideal but feels better than the previous behaviour

---
Here's what your changelog entry will look like:

## ✨ Features
 * Improve AUX panel behaviour ([\#6699](https://github.com/matrix-org/matrix-react-sdk/pull/6699)). Fixes vector-im/element-web#18787. Contributed by [SimonBrandner](https://github.com/SimonBrandner).

Preview: https://6128d6774c51b81c0fd83a4b--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
I love how fixing the UI is basically deleting code.

**Comment by janogarcia** [comment]
@SimonBrandner Just tested this one out. 👍 The related issue #18787 doesn't give much context of what specific problems are being addressed with this PR, sorry if I'm missing something obvious.

Apparently this PR changes the stacking order for the search box when there are other panels present, like the voice/video call panel or a widget.

I think this behavior breaks the relationship between the search interface and the search result area, making it more difficult for users to discover the outcome of the search operation. I actually think the current behavior is preferable, where both elements are always kept close to each other. What do you think @nadonomy ?

**Comment by SimonBrandner** [comment]
@janogarcia, sorry about the delay, I managed to forget about this :sweat_smile: 

I've reverted the change in the stacking order, so I think this basically means there are no changes for design to review

Screenshot_20210927_092150

**Comment by janogarcia** [comment]
@SimonBrandner Thanks for the update! As long as there are no design/product changes involved then it doesn't need a review on my side, but I'm approving it anyway to prevent blocking it from being merged. 👍

**Review by janogarcia — APPROVED** [review]

**Pull request merged**
