### PR TITLE
Fix spelling and grammar in README

### PR DESCRIPTION
**Pull request by ps0305**

### CODE REVIEW

**Comment by ps0305** [comment]
@turt2live rebased and signed-off.

**Comment by t3chguy** [comment]
Looks like your rebase went wrong as my commits are in there now

**Comment by ps0305** [comment]
> Looks like your rebase went wrong as my commits are in there now

changes reverted for your files

**Comment by t3chguy** [comment]
They should not be in this PR's commits in thy first place...

**Pull request closed without merging**
