### PR TITLE
Allow changing servers on nonfatal errors

### PR DESCRIPTION
**Pull request by dbkr**
@turt2live: hopefully this is a sensible way to do this

Fixes https://github.com/vector-im/riot-web/issues/10016

### CODE REVIEW

**Comment by dbkr** [comment]
I thought we needed the return value from `validateServerConfigWithStaticUrls` to continue here though? Which we don't get if it throws.

**Comment by turt2live** [comment]
we do, but we can always call it again with `syntaxOnly=true`.

**Comment by dbkr** [comment]
In this case we need to do so immediately though because we need to pass it to `this.props.onServerConfigChange`? I guess actually this is equivalent to just specifying syntaxOnly in the first place though?

**Comment by dbkr** [comment]
oh - it's not equivalent because nonfatal error !== liveness check fail (ie. we still want to fail if the HS isn't reachable)

**Comment by turt2live** [comment]
ah, yes, it would be... so just a try/catch around a `syntaxOnly` call and you should be fine

**Comment by turt2live** [comment]
hmm... if non-fatal is != to liveliness then the code you have here is fine, because `syntaxOnly=true` disables liveliness

**Comment by dbkr** [comment]
ok yeah, I think this is right then, ie. it will let you continue with the change if the IS server is down but not if the HS is down.

**Pull request merged**
