### PR TITLE
Allow setting room join rule to knock

### PR DESCRIPTION
**Pull request by charlynguyen**
We @nordeck are currently implementing the knock rooms behind the feature flag `feature_ask_to_join` (introduced in https://github.com/matrix-org/matrix-react-sdk/pull/11182).

This pull request allows setting room join rule to knock.

#### Relates to
- https://github.com/matrix-org/matrix-react-sdk/pull/11182

### Room Upgrade
The behavior is the same as for restricted room upgrades. In case a room upgrade is necessary for the knock join rule the "upgrade required" **pill** will appear. The room upgrade **dialog** will help the user to do so. The **result** will be a new room (including possible parent spaces and members).
|Pill|Dialog|Result|
|-|-|-|
|settings-ask-to-join-upgrade-required-pill|settings-ask-to-join-upgrade-required-dialog|settings-ask-to-join-upgrade-result|

### Option
If the upgrade is done or not needed the user is free to select the join rule ask to join.
settings-ask-to-join-option

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Allow setting room join rule to knock ([\#11248](https://github.com/matrix-org/matrix-react-sdk/pull/11248)). Contributed by @charlynguyen.

### CODE REVIEW

**Comment by andybalaam** [comment]
The code looks good to me. Requesting review from design and product. Since this is an incremental addition after https://github.com/matrix-org/matrix-react-sdk/pull/11182 this should be fairly routine I think.

**Review by andybalaam — APPROVED** [review]

**Review by daniellekirkwood — APPROVED** [review]

**Comment by charlynguyen** [comment]
@nadonomy Please, can you have a look here? Friendly reminder! 😄

**Review by nadonomy — APPROVED** [review]
@charlynguyen Thanks - from a design perspective this looks good to merge, especially given it's behind a labs flag.

It did prompt some thoughts on further iteration, but rather than blocking this PR on it I've captured the thinking in this issue for future enhancement: https://github.com/vector-im/element-meta/issues/1899

**Comment by catfromplan9** [comment]
When enable_ask_to_join is enabled, I still don't see the "People" tab in room settings. How to fix?

**Pull request merged**
