### PR TITLE
#23838: 24-hours time format fixed

### PR DESCRIPTION
**Pull request by nawarajshah**
Fixing the issue from https://github.com/vector-im/element-web/issues/23838

While exporting the chat, it forces AM / PM output instead of 24-hour format, and it is easily fixed by making hour12: false for the toLocaleString function

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Signed-off-by: Nawaraj Shah <shah.nawaraj.ns@gmail.com>

---
This PR currently has none of the required changelog labels.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

### CODE REVIEW

**Comment by dbkr** [comment]
This looks like a visual change so I'd expect to see a linked issue where we the change is agreed upon, as well as the before and after screenshots mentioned in CONTRIBUTING.md. You've also checked to say you've done DCO signoff but there's no signoff here.

**Comment by nawarajshah** [comment]
i am new on contributing, so if I check something that I shouldn't check, please let me know.
before
Screenshot (25)

after
Screenshot (24)

**Review by gsouquet — CHANGES_REQUESTED** [review]
This code is used throughout the whole product and not only in the context of chat exports.

You will also need to write tests for this PR to be merged as per then contributing guidelines https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.mdA

**Comment by T-bond** [comment]
Wouldn't using the user's preference for the 12/24 hour format better than hard coding it? Also using user's locale.

**Comment by nawarajshah** [comment]
> Wouldn't using the user's preference for the 12/24 hour format better than hard coding it? Also using user's locale.

I use the available option, it is not hard-coding I think.

**Pull request closed without merging**
