### PR TITLE
Fix "react error on share dialog"

### PR DESCRIPTION
**Pull request by yaya-usman**
Fixes [vector-im/element-web#21475](https://github.com/vector-im/element-web/issues/21475)

This fixes the "react share dialog  console error" 

Signed-off-by: Yaya Usman [yaya-usman@users.noreply.github.com](mailto:yaya-usmanl@users.noreply.github.com)

Before:
beforefix

After:
afterfix

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix "react error on share dialog" ([\#8170](https://github.com/matrix-org/matrix-react-sdk/pull/8170)). Contributed by @yaya-usman.

Preview: https://pr8170--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by turt2live** [comment]
There's a lot of stylistic changes to the code which make it difficult to see where the fix actually is - reverting the unnecessary changes would be appreciated.

**Comment by yaya-usman** [comment]
> There's a lot of stylistic changes to the code which make it difficult to see where the fix actually is - reverting the unnecessary changes would be appreciated.

@turt2live Alright thanks, let me do that. also i realized it's failing the jest-tests, the failed tests are from the files i didn't touch, how do i get around this?

**Review by t3chguy — CHANGES_REQUESTED** [review]
Making all checkboxes readOnly is very much not the right solution, the issue is that ShareDialog L158 has a typo of `onClick` which should be `onChange`

**Comment by yaya-usman** [comment]
> Making all checkboxes readOnly is very much not the right solution, the issue is that ShareDialog L158 has a typo of `onClick` which should be `onChange`

ohh yes, Thanks. let me change that, so how about the failing tests of files i didn't touch, how do i go about that?

**Comment by t3chguy** [comment]
Make sure to keep your branch up to date otherwise it'll cause test failures

**Comment by yaya-usman** [comment]
> Make sure to keep your branch up to date otherwise it'll cause test failures

it's up to date

**Comment by t3chguy** [comment]
Please avoid force pushing, it discards all review and creates extra work to do. We squash merge anyway.

**Comment by yaya-usman** [comment]
> Please avoid force pushing, it discards all review and creates extra work to do. We squash merge anyway.

Noted, thanks

**Review by t3chguy — APPROVED** [review]
This is great, thanks!

**Pull request merged**
