### PR TITLE
Update to hinted version of Inter 3.19 font to improve legibility on Windows (blurry text)

### PR DESCRIPTION
**Pull request by novocaine**
Fixes https://github.com/vector-im/element-web/issues/15594

Inter bundles a hinted version of its fonts which we can use to improve rendering on Windows, see [here](https://rsms.me/inter/#faq-unhinted-vs-hinted).

The fonts are larger in size, so we need to understand the increase in download size for users.

Before

```
-rw-r--r--   1 jsalter  staff   140K 12 Jul  2021 Inter-Bold.woff
-rw-r--r--   1 jsalter  staff   103K 12 Jul  2021 Inter-Bold.woff2
-rw-r--r--   1 jsalter  staff   147K 12 Jul  2021 Inter-BoldItalic.woff
-rw-r--r--   1 jsalter  staff   109K 12 Jul  2021 Inter-BoldItalic.woff2
-rw-r--r--   1 jsalter  staff   141K 12 Jul  2021 Inter-Italic.woff
-rw-r--r--   1 jsalter  staff   104K 12 Jul  2021 Inter-Italic.woff2
-rw-r--r--   1 jsalter  staff   139K 12 Jul  2021 Inter-Medium.woff
-rw-r--r--   1 jsalter  staff   103K 12 Jul  2021 Inter-Medium.woff2
-rw-r--r--   1 jsalter  staff   147K 12 Jul  2021 Inter-MediumItalic.woff
-rw-r--r--   1 jsalter  staff   110K 12 Jul  2021 Inter-MediumItalic.woff2
-rw-r--r--   1 jsalter  staff   131K 12 Jul  2021 Inter-Regular.woff
-rw-r--r--   1 jsalter  staff    97K 12 Jul  2021 Inter-Regular.woff2
-rw-r--r--   1 jsalter  staff   139K 12 Jul  2021 Inter-SemiBold.woff
-rw-r--r--   1 jsalter  staff   103K 12 Jul  2021 Inter-SemiBold.woff2
-rw-r--r--   1 jsalter  staff   148K 12 Jul  2021 Inter-SemiBoldItalic.woff
-rw-r--r--   1 jsalter  staff   109K 12 Jul  2021 Inter-SemiBoldItalic.woff2
```

After 

```
-rw-r--r--@  1 jsalter  staff   255K 18 Jun  2021 Inter-Bold.woff
-rw-r--r--@  1 jsalter  staff   174K 18 Jun  2021 Inter-Bold.woff2
-rw-r--r--@  1 jsalter  staff   265K 18 Jun  2021 Inter-BoldItalic.woff
-rw-r--r--@  1 jsalter  staff   179K 18 Jun  2021 Inter-BoldItalic.woff2
-rw-r--r--@  1 jsalter  staff   253K 18 Jun  2021 Inter-Italic.woff
-rw-r--r--@  1 jsalter  staff   172K 18 Jun  2021 Inter-Italic.woff2
-rw-r--r--@  1 jsalter  staff   250K 18 Jun  2021 Inter-Medium.woff
-rw-r--r--@  1 jsalter  staff   171K 18 Jun  2021 Inter-Medium.woff2
-rw-r--r--@  1 jsalter  staff   262K 18 Jun  2021 Inter-MediumItalic.woff
-rw-r--r--@  1 jsalter  staff   178K 18 Jun  2021 Inter-MediumItalic.woff2
-rw-r--r--@  1 jsalter  staff   240K 18 Jun  2021 Inter-Regular.woff
-rw-r--r--@  1 jsalter  staff   164K 18 Jun  2021 Inter-Regular.woff2
-rw-r--r--@  1 jsalter  staff   253K 18 Jun  2021 Inter-SemiBold.woff
-rw-r--r--@  1 jsalter  staff   173K 18 Jun  2021 Inter-SemiBold.woff2
-rw-r--r--@  1 jsalter  staff   265K 18 Jun  2021 Inter-SemiBoldItalic.woff
-rw-r--r--@  1 jsalter  staff   180K 18 Jun  2021 Inter-SemiBoldItalic.woff2
```

---
Here's what your changelog entry will look like:

## ✨ Features
 * Update to hinted version of Inter 3.19 font to improve legibility on Windows (blurry text) ([\#8676](https://github.com/matrix-org/matrix-react-sdk/pull/8676)). Fixes vector-im/element-web#15594. Contributed by @novocaine.

### CODE REVIEW

**Comment by t3chguy** [comment]
They are significantly larger, nearly double the size in some cases :(

**Comment by novocaine** [comment]
> They are significantly larger, nearly double the size in some cases :(

yeah, but will calculate the proportion of the page payload that actually represents

**Comment by t3chguy** [comment]
Is it not possible to include both but load hinted only if we think the platform is Windows?

**Comment by t3chguy** [comment]
> On desktop that's easy, do it in packaging, but who cares about the payload size on desktop

Not exactly, because its part of the asar bundle of element-web that Desktop builds just opaquely pull in

**Comment by novocaine** [comment]
I guess if we are worried about payload on web we can include these in Desktop but not web.

**Comment by MadLittleMods** [comment]
Re: ["alright. well I'd like to send https://github.com/matrix-org/matrix-react-sdk/pull/8676 to the person bitterly loyal to their lodpi windows rig and see if it works for them"](https://matrix.to/#/!bEWtlqtDwCLFIAKAcv:matrix.org/$DmwQRtJxBPM8ii3jaGNJ1a1qyj4d9MAOSZYZ9bQO-p4?via=matrix.org&via=element.io&via=mozilla.org)

The screenshots probably won't do it justice for you but here they are for reference. I wish I could comment on the diff to create a thread but it's all file blobs which don't allow comments.

## Chrome

 - The before never stood out to me and looks as expected.
 - The after makes letters taller by pixel aliasing upwards into the pixel grid in most cases. I'm not used to so it feels wrong to me at the moment but also feels not aliased very much now (very bare feeling).

Before | After
--- | ---
Chrome before | Chrome after font hint changes


## Firefox

 - The before in Firefox is noticeably bad as https://github.com/vector-im/element-web/issues/15594 describes
 - The after seems like a good iterative change although it still doesn't feel right

Before | After
--- | ---
Firefox before | Firefox after font hint changes

**Comment by novocaine** [comment]
Note there are also screenshots of the before and after in the failed percy run.

**Review by t3chguy — COMMENTED** [review]
Clearing review due to me fat fingering the ready button

**Comment by MadLittleMods** [comment]
Closing as I don't think this will move forward without someone else picking this up to deep dive into the intricacies here.

**Pull request closed without merging**
