### PR TITLE
ChatCreateOrReuse show only rooms both you and the other party still in

### PR DESCRIPTION
**Pull request by t3chguy**
Before
image
After
image

Fixes https://github.com/vector-im/riot-web/issues/10218

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
> lgtm, and merging despite this dialog quickly disappearing.

Any more info on this for people outside of the inner circle @turt2live ?

Thanks

**Comment by bwindels** [comment]
> > lgtm, and merging despite this dialog quickly disappearing.
> 
> Any more info on this for people outside of the inner circle @turt2live ?
> 
> Thanks

We're working on only having a single room for DMs per contact.

**Comment by t3chguy** [comment]
How would that work with existing rooms, say I already have 4 rooms to chat with X, would it just randomly pick one or would this dialog stay around to handle existing cases or would Riot somehow force me to merge them

**Comment by bwindels** [comment]
> How would that work with existing rooms, say I already have 4 rooms to chat with X, would it just randomly pick one or would this dialog stay around to handle existing cases or would Riot somehow force me to merge them

Not sure, haven't been involved really. See https://github.com/vector-im/riot-web/issues/7315 if you want to weigh in.

**Comment by turt2live** [comment]
There'll be a MSC which explains it before riot actually gets code for it. Still working out the details.

**Pull request merged**
