### PR TITLE
on HTML Imgs copy alt to title if there is no title to provide tooltip

### PR DESCRIPTION
**Pull request by t3chguy**
Especially helpful when someone's using a client capable of custom emojis which may or may not be unclear:
image
which currently have no hover tooltip because they only provide an alt
so now they magically will show a tooltip

### Fixes https://github.com/vector-im/riot-web/issues/6917

### CODE REVIEW

**Comment by dbkr** [comment]
Hmm - I'm not really convinced it's Riot's place to go fixing up other clients' HTML.

Also, I'd suggest putting linting fixes in a separate PR, especially when the actual change ends up being 5% of the content of the PR - it makes it quite hard to review when you have to hunt for the actual change in amongst linting fixes.

**Comment by t3chguy** [comment]
> Hmm - I'm not really convinced it's Riot's place to go fixing up other clients' HTML.

sure but making Riot as useful as it can be given any input is my way of thinking about it

**Comment by lukebarnard1** [comment]
I'm not convinced this would be a plus for accessibility: https://silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/

I also think it's up to the sending client to send messages that are accessible. Sending an `alt` that is `:man_shrugging:` or whatever is probably fine for screen readers as they read the img `alt` by default (although with `orca`, it'll read "man underscore shrugging").

As for adding a tooltip to an inline img, I think that's down to the sending client again.

**Comment by jryans** [comment]
Thanks for making this contribution a while back. Since the code base has changed since this was opened, it no longer applies cleanly, and I don't think there's a need to keep it open in this state, as we can always find the code here again if needed. If you are still interested in pursuing this feature, please discuss with us in #riot-dev:matrix.org to find a good approach forward.

**Pull request closed without merging**
