### PR TITLE
Don't rely on room members to query power levels

### PR DESCRIPTION
**Pull request by bwindels**
Fixes https://github.com/vector-im/riot-web/issues/7264
Requires https://github.com/matrix-org/matrix-js-sdk/pull/717

### CODE REVIEW

**Comment by ara4n** [comment]
no, we've concluded that for LL the server is entitled not to send you your own membership event (which is after all redundant and a waste of bandwidth).

**Comment by bwindels** [comment]
Actually, we have all the information we need in the power levels state event. We just shouldn't rely on having a member object. My bad, I'll change it.

**Comment by bwindels** [comment]
ready for another look

**Comment by dbkr** [comment]
How do you know your own display name and avatar URL in that room if you don't have your own membership event?

**Comment by bwindels** [comment]
@dbkr With https://github.com/matrix-org/matrix-react-sdk/pull/2132 we're now waiting for the members to load before showing the own avatar in the composer. I'm unsure where we currently display the own display name. This isn't great as it is, as the layout of the composer without the avatar rendered is currently a bit broken (everything moves to the left). We could easily solve this though by reverting to `User`, or even keep track of our own a profile info.

I'll make a task to improve this experience, but is probably independent of this PR.

**Comment by bwindels** [comment]
https://github.com/vector-im/riot-web/issues/7282

**Comment by bwindels** [comment]
Right, as it stands this will fallback to a fake sentinel just containing the userid, like for any user ...

**Pull request merged**
