### PR TITLE
Add cachebuster for i18n

### PR DESCRIPTION
**Pull request by MTRNord**
This is fixing the i18n part of vector-im/riot-web#4136

### CODE REVIEW

**Comment by ara4n** [comment]
rather than redownloading i18n every time you launch the app, i'd rather we used the cachebusting webpack already provides by bundling into a directory named with a unique hash. @dbkr may need to comment on the right voodoo for this

**Comment by dbkr** [comment]
Using webpack's cachebusting is not entirely trivial because we'd have to get the bundle hash into the language handler and also the copy-res script (or write a webpack loader to copy the i18n files with webpack itself).

We don't do any of this for images, fonts or the config file. Another option would be to use the app version number as a cachebuster, ie. force re-download every app update?

**Comment by dbkr** [comment]
I think on account of how stale this is, I'm going to close this, since it may not be clear what the correct fix is but it does seem like it's probably not this one - sorry.

**Comment by lukebarnard1** [comment]
except he didn't close it... :thinking:

**Pull request closed without merging**
