### PR TITLE
Better RTL support

### PR DESCRIPTION
**Pull request by Bitim**
Add more elements to support RTL languages, by adding dir="auto" attribute.

Signed-off-by: Shuki Liber liber@tee.org

### CODE REVIEW

**Comment by ara4n** [comment]
i'm not sure this is going to work in all cases, as React components don't add their properties to the underlying DOM object by default.  Have you tested these?

**Comment by Bitim** [comment]
Yes, most of them have been tested, and working.

**Comment by ara4n** [comment]
The ones that i'm surprised work are: 
 * Rich text editor composer input
 * Room name editor
 * Room tool tip (although I'm not sure how that's used precisely)
 * Room topic editor

On these ones, i'd expect the `dir=auto` would need to put in the component's render method, rather than as a property on the component.

**Comment by ara4n** [comment]
i'm going to merge this anyway for now, although I suspect it's incomplete

**Pull request merged**
