### PR TITLE
Change icon from "R" to "X"

### PR DESCRIPTION
**Pull request by lukebarnard1**
Codep https://github.com/vector-im/riot-web/pull/6216

### CODE REVIEW

**Comment by turt2live** [comment]
Why not a globe?

**Comment by ara4n** [comment]
because @AmandineLP doesn't like globes.

@lukebarnard1 - you're missing an alt attribute on the img; otherwise lgtm.

**Comment by turt2live** [comment]
It feels a bit weird to have a close button at the top of the screen all the time. I'm willing to try it, but here's some preemptive feedback: It's not immediately clear as to what this accomplishes, particularly when it's visible without any filtering going on (it feels like I can close the LLP).

**Comment by ara4n** [comment]
it's not meant to be visible all the time; it's meant to be visible only when the list is filtered. which is probably an oversight on the PR in retrospect.

**Comment by ara4n** [comment]
lgtm ,thanks

**Pull request merged**
