### PR TITLE
Sort short/exact emoji matches before longer incomplete matches

### PR DESCRIPTION
**Pull request by grimhilt**
Fixes https://github.com/vector-im/element-web/issues/23210

-The emoji provider prioritize exact match and shorted emojis.
-Emoji picker sort the results with the same logic

Signed-off-by: [grimhilt@users.noreply.github.com](mailto:grimhilt@users.noreply.github.com)

type: Enhancement

---
Here's what your changelog entry will look like:

## ✨ Features
 * Sort short/exact emoji matches before longer incomplete matches ([\#10212](https://github.com/matrix-org/matrix-react-sdk/pull/10212)). Fixes vector-im/element-web#23210. Contributed by @grimhilt.

### CODE REVIEW

**Review by dbkr — APPROVED** [review]
This looks great, thanks!

**Comment by grimhilt** [comment]
Thank you for reviewing !!

**Comment by softmix** [comment]
this seems to have broken partial matches, for example `:imp` no longer shows `:smiling_imp:` at all, altho it does show `:shrimp:`. curiously `:shrimp` does show `:fried_shrimp:`

**Comment by grimhilt** [comment]
Hi @softmix.
It would appear this behaviour was already present before my changes.
The reason for the differences between the two cases is that the emojis are also sorted by tags. And where ``:smiling_imp:`` does not have the tag ``imp``, ``:fried_shrimp:`` does have ``shrimp``.
~Concerning the reason behind this bug, I am not sure but I think this is because the emojis are sorted and only some of them are kept (currently LIMIT=20). The next sort is then applied to the previous set of emojis~. It was not, changing the limit does not seem to fix it, maybe there is indeed something wrong with the partial matches.
I think the approach that makes more sense to fix your example would be to add the tag ``imp`` to ``:smiling_imp:`` as it would be consistent with ``:imp:`` that possesses this tag.
I think this deserves its own issue.

**Pull request merged**
