### PR TITLE
Line 1 / 2 Support

### PR DESCRIPTION
**Pull request by dbkr**
Support 1 active call & 1 call on hold

Also adds the call control buttons into the PiP view

This room's call on hold, call with tiger bunny ongoing:
Screenshot 2020-12-04 at 14 01 24

This room's call active, another on hold:
Screenshot 2020-12-04 at 14 03 02

In two calls but not looking at the room for either of them
(⚠️ warning: freestyle developer UI)
Screenshot 2020-12-04 at 20 35 49

Incoming call notifications haven't moved to the top-left yet, so if you get a call while viewing one in PiP, this happens...
Screenshot 2020-12-04 at 16 22 28
...which is probably tolerable for now.

Fixes https://github.com/vector-im/element-web/issues/15662
Fixes https://github.com/vector-im/element-web/issues/15874
Fixes vector-im/element-web#15886

Based on: https://github.com/matrix-org/matrix-react-sdk/pull/5446
Diff: https://github.com/matrix-org/matrix-react-sdk/compare/pull/5446/head...pull/5468/head

### CODE REVIEW

**Comment by jryans** [comment]
If you merge in the latest from develop, I think that will give a working preview site here. 😄

**Comment by dbkr** [comment]
...and done:

Screenshot 2020-12-07 at 18 28 19

**Review by jryans — APPROVED** [review]
Looks great code wise! 😄

**Comment by simonkeane** [comment]
Looks good to me!

**Pull request merged**
