### PR TITLE
Catch new invalid user name error

### PR DESCRIPTION
**Pull request by dbkr**
See also:
 * https://github.com/matrix-org/synapse/pull/499
 * https://github.com/matrix-org/matrix-doc/pull/263

### CODE REVIEW

**Comment by dbkr** [comment]
Helps with https://github.com/vector-im/vector-web/issues/512

**Comment by Kegsay** [comment]
Looking at those other PRs you've got an inconsistency. Whilst Synapse and this PR look for `M_INVALID_USER_NAME`, the spec sez it is `M_INVALID_USERNAME`.

**Comment by Kegsay** [comment]
LGTM aside from matrix-doc inconsistency.

**Comment by dbkr** [comment]
Yeah, it started out as M_INVALID_USER_NAME but then was changed. I updated all three branches and re-merged the doc one I'd merged.

**Comment by Kegsay** [comment]
ok LGTM!

**Pull request merged**
