### PR TITLE
Remove an obsolete style declaration of .mx_ReplyChain_show

### PR DESCRIPTION
**Pull request by luixxiul**
|Before|After|
|---------|------|
|before|after|

It was added with https://github.com/matrix-org/matrix-react-sdk/pull/6291/files#diff-11808ff6468e6efa5982f414119fcc8a3a3eea4090b1a4ebda8ed6eae732418aR163 (#6291). It has not been effective for unknown period, and since the layout of the area has changed from flexbox/grid for [order](https://developer.mozilla.org/en-US/docs/Web/CSS/order) property, it should be able to be safely removed.

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by weeman1337 — APPROVED** [review]
Thanks for your contribution!

Tested, works :+1:

**Comment by luixxiul** [comment]
Removing it also makes it possible to fix the large pill (with a long display name) alignment :smiley:

**Comment by weeman1337** [comment]
@luixxiul can you merge `develop` into this?

**Comment by luixxiul** [comment]
@weeman1337 Done!

**Pull request merged**
