### PR TITLE
Remove spaces beta feedback prompts except a couple more strategic ones

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/18096

This can land prior to leaving Beta to help break down the work

image
image
image

### CODE REVIEW

**Review by turt2live — APPROVED** [review]

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
- [ ] The feedback component in the "create space" dialog has changed design to be less attention-grabbing.

- From A
   


- To B
 


- [ ] When I create a space, the feedback badge is a bit wide/out of place
  
image

Compared to the design where it's aligned to the avatar and search bar

**Comment by t3chguy** [comment]
> Compared to the design where it's aligned to the avatar and search bar

Compared to my screenshot too, how the heck did that happen lol

**Comment by t3chguy** [comment]
image
image

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
One small design change please, can we add the border-top back on the Create Space dialog?

I'm just realising it will help separate out the information.

**Comment by t3chguy** [comment]
image

There, better?

**Review by niquewoodhouse — APPROVED** [review]

**Pull request merged**
