### PR TITLE
Update `sliding-sync.spec.ts` - use Cypress Testing Library

### PR DESCRIPTION
**Pull request by luixxiul**
For https://github.com/vector-im/element-web/issues/25033

This PR intends to update `sliding-sync.spec.ts` by:

- using Cypress Testing Library

- changing the test rooms name from `Join`, `Reject` and `Rescind` to `Room to Join`, `Room to Reject` and `Room to Rescind`, respectively, as `findByRole()` this PR is going to add is used to search buttons as well, whose label texts are same as the rooms name. This change intends to avoid confusion due to the similarity (to avoid something like this: "Invite" button to search the room "Invite", etc.)

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by dbkr** [comment]
I'm no ARIA expert, but it would seem more logical to me to just have one element with the appropriate aria label rather than the header explicitly having a label saying that it's the header?

**Comment by luixxiul** [comment]
I'm sorry, but I am not quite sure either... At first, I am going to update the test by not touching ARIA related stuff, leaving comments / creating an issue about it.

**Comment by luixxiul** [comment]
@dbkr The change on ARIA stuff has been reverted. Would you kindly review again?

**Review by dbkr — APPROVED** [review]
Looks great, thanks very much!

**Comment by luixxiul** [comment]
Thanks for the review!

**Pull request merged**
