### PR TITLE
Add fallback to group avatar in case thumbnail not found on server

### PR DESCRIPTION
**Pull request by agent3bood**

### CODE REVIEW

**Comment by agent3bood** [comment]
Fix https://github.com/vector-im/riot-web/issues/3563

**Comment by turt2live** [comment]
I would almost expect this to be fixed on the server side to be honest. The thumbnailer seems broken, but if it can't be fixed then this seems like a relatively okay solution to me. (Although I have no authority on this aspect and I haven't tested it myself).

**Comment by agent3bood** [comment]
Agree, fixing it on tbe server is the way to go, but this fix is adding a fallback incase thumbnail not found on the server.

**Comment by agent3bood** [comment]
Also this issue
https://github.com/vector-im/riot-web/issues/2581

**Comment by lukebarnard1** [comment]
So this allows the original SVG to show be shown as the room avatar? We shouldn't be showing any SVGs afaik.

**Comment by ara4n** [comment]
yeah, i see the intention here, but the fact that it displays the original SVG if a thumbnail is missing (resolving vector-im/riot-web#2581) is not really ideal - as Luke says, we go to pains to not currently show any user-generated SVGs, as it is trivial to sculpt malicious SVGs (e.g. billion lol attacks).  If anyone is wrangling thumbnailing of SVGs it should be the sender client (or possibly the server)'s responsibility.

Sorry for not being able to merge :(

**Comment by agent3bood** [comment]
Thanks all for your comments, so this issue is a backend problem not the client.

**Pull request closed without merging**
