### PR TITLE
Manage PL to manage pinned events in Room Settings Roles Tab

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/5396

image

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
Ah, I grepped through the code and couldn't find the labs setting for it so presumed it was released already

**Comment by turt2live** [comment]
It's under "feature_pinning"

**Comment by Half-Shot** [comment]
Wow the roles tab looks ugly these days. I guess that needs a design

**Comment by jryans** [comment]
Thanks for making this contribution a while back. Since the code base has changed since this was opened, it no longer applies cleanly, and I don't think there's a need to keep it open in this state, as we can always find the code here again if needed. If you are still interested in pursuing this feature, please discuss with us in #element-dev:matrix.org to find a good approach forward.

**Pull request closed without merging**
