### PR TITLE
Include a mark as read X under the scroll to unread button

### PR DESCRIPTION
**Pull request by mstriemer**
This adds a simple X button under the scroll to top button that will mark all as read.

Probably needs some tests or something, but I didn't want to invest too much into this if it wasn't the desired solution.

Looks like the functionality was nearly there but I might be missing something. Open to suggestions but mostly wanted to get something started here.

A screenshot
In use

Fixes vector-im/riot-web#8666.

### CODE REVIEW

**Comment by turt2live** [comment]
Awesome, thanks Nad! @mstriemer please sign off on the changes and we can merge it :)

**Comment by mstriemer** [comment]
@turt2live I don't see anything in the readmes about the sign-off. What's the purpose of it? Just want to know what I'm signing off on :)

**Comment by turt2live** [comment]
Through a series of clicking links, you'd eventually land on this: https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.rst#sign-off

It's essentially to say you're okay with us merging the code, and that you have the right to submit it in the first place (ie: not stealing code from some other project and PRing it under your own name).

**Comment by mstriemer** [comment]
Cool, thanks! I checked the [readme](https://github.com/matrix-org/matrix-react-sdk#developer-guide) for this repo which has a link to a contributing guide that 404s, I'm guessing it should link to that page instead?

```
Signed-off-by: Mark Striemer <mstriemer@gmail.com>
```

**Comment by turt2live** [comment]
> Cool, thanks! I checked the readme for this repo which has a link to a contributing guide that 404s, I'm guessing it should link to that page instead?

ah, yes, that should be a useful link and not a useless one. Will get that fixed.

Thanks!

**Pull request merged**
