### PR TITLE
Fix grid blowout on pinned event tiles

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes https://github.com/vector-im/element-web/issues/22543

|Before|After|
|---------|------|
|before|after|

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix grid blowout on pinned event tiles ([\#8816](https://github.com/matrix-org/matrix-react-sdk/pull/8816)). Fixes vector-im/element-web#22543. Contributed by @luixxiul.

### CODE REVIEW

**Review by weeman1337 — CHANGES_REQUESTED** [review]
Hi @luixxiul thank you for your contribution.

I think this issue should better be solved by setting the correct size for the map. And it seems like the map doesn't update if the container changes:

map

**Comment by luixxiul** [comment]
Though the issue that the map size is not responsive should be fixed, the issue this PR tries to fix is the grid blowout which not only is reproduced with the map tile but also can potentially happen with any kinds of tiles. The map tile is an example of the issues.

The issue that the map size is not responsive is reproduced globally, and I would like to ask another PR to fix the issue since it is beyond my capability.

**Comment by weeman1337** [comment]
> Though the issue that the map size is not responsive should be fixed, the issue this PR tries to fix is the grid blowout which not only is reproduced with the map tile but also can potentially happen with any kind of tiles. The map tile is an example.
> 
> The issue that the map size is not responsive is reproduced globally, and I would like to ask another PR to fix the issue since it is beyond my capability.

Ok. Does an issue for this exist? If not can you create one?

**Comment by luixxiul** [comment]
@weeman1337 sure, I'm going to check it.

**Pull request merged**
