### PR TITLE
UserSettings.js

### PR DESCRIPTION
**Pull request by tessgadwa**
This file contains the user settings for an option Light High Contrast Theme (value: 'contrastlight'), to be added separately to riot-web.

### CODE REVIEW

**Comment by tessgadwa** [comment]
Pls verify this patch, thanks.

**Comment by lukebarnard1** [comment]
It appears you've PR'd to create a new file `UserSettings.js` in the root directory. Could you please push a diff for `src/components/structures/UserSettings.js`

**Comment by tessgadwa** [comment]
What was the number for the PR?

**Comment by tessgadwa** [comment]
@lukebarnard1 Please forgive me being new at this. I've used Git before for work, but it's very different pushing to an open source project. When you say, "push a diff" do you mean resubmit the PR to the directory you have indicated? Please confirm, thank you!

**Comment by lukebarnard1** [comment]
I do indeed, and it looks like you have :)

**Pull request closed without merging**
