### PR TITLE
Fix VoIP event tile issues

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/18216

<hr>

Screenshot_20210725_091701
Screenshot_20210725_091651
Screenshot_20210725_091832
Screenshot_20210725_091821
Screenshot_20210725_102914
Screenshot_20210725_105731

<hr>

element-web notes: none

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Looks good to me code wise!
When message bubbles are enabled the tiles are collapsed, but that will be fixed by #6465 
Will make sure that a design review is fast tracked for this PR to unblock RC tomorrow

Thank you for your continuous contributions 💯

**Review by janogarcia — CHANGES_REQUESTED** [review]
Thank you, Šimon!

Just a couple details we'd need to update to get this PR ready for the next RC.

- **Iconography**: Update the missed-video.svg icon to the one I'm attaching (it follows the latest Design System specs)
- **Copy**: Update the i18n strings "The remote side declined this call" and "The remote side didn't pick up", by replacing "The remote side" part with just "They".


[missed-voice.svg.zip](https://github.com/matrix-org/matrix-react-sdk/files/6880531/missed-voice.svg.zip)

**Comment by SimonBrandner** [comment]
Thanks for the review!

> Iconography: Update the missed-video.svg icon to the one I'm attaching (it follows the latest Design System specs)

I am a little confused, sorry - should I used the missed voice call icon even for missed video calls?

> Copy: Update the i18n strings "The remote side declined this call" and "The remote side didn't pick up", by replacing "The remote side" part with just "They".

Yeah, sounds much better

**Comment by janogarcia** [comment]
Sorry for the confusion, Šimon! It actually was `missed-voice.svg`, not `missed-video.svg`. 🙃 Anyway, please ignore my comment on updating it, as there's some deviation there in place from the design system that seems to be intentional.

**Comment by SimonBrandner** [comment]
> Sorry for the confusion, Šimon! It actually was `missed-voice.svg`, not `missed-video.svg`. upside_down_face Anyway, please ignore my comment on updating it, as there's some deviation there in place from the design system that seems to be intentional.

Ah, no worries :smile: I'll revert the change

**Comment by SimonBrandner** [comment]
Do you need me to retake the screenshots?

**Comment by janogarcia** [comment]
Don't bother taking new screenshots. Thanks anyway!

**Pull request merged**
