### PR TITLE
Change avatar to use Compound implementation

### PR DESCRIPTION
**Pull request by germain-gg**
For https://github.com/vector-im/element-web/issues/25883
This pull request took over https://github.com/matrix-org/matrix-react-sdk/pull/11393, which became stale and difficult to update.

Changes the `BaseAvatar` implementation to use the [Compound Avatar](https://compound.element.io/?path=/story/compound-web_avatar--round)

Apologies for the slightly large diff, here are a couple of noteworthy things to know that will make review easier:
- `width` and `height` prop have been changed to the single `size` prop
- `size` takes a value with its unit (any CSS unit), hence why it's a string
- Most of the relevant changes are in `BaseAvatar.tsx` and the `.pcss` files. 

Here are a couple of examples of the UI update. Please use the deploy preview for a comprehensive overview, I will not list every scenarios here

Screenshot 2023-08-22 at 16 15 14
Screenshot 2023-08-22 at 16 14 32
Screenshot 2023-08-22 at 16 14 15

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Change avatar to use Compound implementation ([\#11448](https://github.com/matrix-org/matrix-react-sdk/pull/11448)).

### CODE REVIEW

**Review by kerryarchibald — COMMENTED** [review]
Changes look good. Played around on the deployment and found a couple of issues with the room list and right panel.

**Review by kerryarchibald — APPROVED** [review]

**Comment by kerryarchibald** [comment]
Percy looks ok, removing `X-Needs-Percy` so it can make it through the merge queue

**Comment by aceArt-GmbH** [comment]
The new avatars do not seem to respect the theme `avatar-background-colors` property.
Is this intentionally or just at the moment broken?

**Comment by t3chguy** [comment]
@aceArt-GmbH I believe it is intentional, avatars now follow displayname colours 1:1

**Comment by aceArt-GmbH** [comment]
> @aceArt-GmbH I believe it is intentional, avatars now follow displayname colours 1:1

Should I send a PR removing the documentation for the avatar theme setting then?
cc https://github.com/vector-im/compound/issues/218

**Comment by t3chguy** [comment]
I'm not on the compound team so best to wait for them to give an authoritative response

**Pull request merged**
