### PR TITLE
Rephrased inconsistent "ban" in the room space.

### PR DESCRIPTION
**Pull request by ankur12-1610**
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>

Fixes: [element-web/20578](https://github.com/vector-im/element-web/issues/20578)

Before:

149632519-40c216a5-6173-455d-bdc1-0e5d97a9c80f

After:

ban
unban

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Rephrased inconsistent "ban" in the room space. ([\#7576](https://github.com/matrix-org/matrix-react-sdk/pull/7576)). Contributed by @ankur12-1610.

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@HarHarLinks can you review the changes:sweat_smile:?

**Review by HarHarLinks — APPROVED** [review]

**Comment by HarHarLinks** [comment]
Since this touches i18n, this needs to interact with weblate, which I don't know how the workflow is. Might be automatic.

**Review by turt2live — APPROVED** [review]
The code is fine, but this needs design review.

**Review by t3chguy — CHANGES_REQUESTED** [review]
This will wrongly say `Ban from room` when looking at a User in the context of a Space.

**Comment by turt2live** [comment]
@t3chguy doesn't the other one say "Remove from room" for kicks?

**Comment by t3chguy** [comment]
Yup, its a bug, ideally not one we proliferate

**Comment by turt2live** [comment]
Hopefully design's review can cover both cases then.

**Comment by ankur12-1610** [comment]
> Hopefully design's review can cover both cases then.

Sorry to disturb but what is the review frequency of the design team:sweat_smile:?

**Review by gaelledel — CHANGES_REQUESTED** [review]
As stated in previous comments, there is an issue with the sentence "remove from room" as this does not work for Spaces. Could we use a more general term like "Remove user" so it can apply to both room and spaces scenarios?

**Comment by HarHarLinks** [comment]
> As stated in previous comments, there is an issue with the sentence "remove from room" as this does not work for Spaces. Could we use a more general term like "Remove user" so it can apply to both room and spaces scenarios?

No, since then it is unclear where it might remove the user from. Viewing the member list in a room that is accessible by space members, once might not be certain whether that means room or space. As a server admin, one might even think it deletes the account altogether.

**Comment by gaelledel** [comment]
> > As stated in previous comments, there is an issue with the sentence "remove from room" as this does not work for Spaces. Could we use a more general term like "Remove user" so it can apply to both room and spaces scenarios?
> 
> No, since then it is unclear where it might remove the user from. Viewing the member list in a room that is accessible by space members, once might not be certain whether that means room or space. As a server admin, one might even think it deletes the account altogether.

Can we programmatically differentiate between Rooms and Spaces? If yes, then I'd prefer options like: Remove from room / Remove from space

**Comment by t3chguy** [comment]
This was already done by https://github.com/matrix-org/matrix-react-sdk/pull/8281

**Pull request closed without merging**
