### PR TITLE
Pass language to Jitsi Widget

### PR DESCRIPTION
**Pull request by Fox32**
I'm about to implement translating the start screen of the Jitsi widget in https://github.com/vector-im/element-web/pull/23412, however till now the client language isn't passed to the widget at all.

## Checklist

* [x] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Type: enhancement

---
Here's what your changelog entry will look like:

## ✨ Features
 * Pass language to Jitsi Widget ([\#9346](https://github.com/matrix-org/matrix-react-sdk/pull/9346)). Contributed by @Fox32.

### CODE REVIEW

**Comment by SimonBrandner** [comment]
It doesn't make much sense to review this without the other PR being ready... I am going to convert this into a draft until then

**Comment by Fox32** [comment]
> It doesn't make much sense to review this without the other PR being ready... I am going to convert this into a draft until then

The other one is already ready for review, would be glad if you have a look.

**Review by turt2live — APPROVED** [review]
This is reasonable on its own, I think.

**Comment by turt2live** [comment]
apparently I put the automerge on the web side - oops

**Pull request merged**
