### PR TITLE
Full page spinner has no padding

### PR DESCRIPTION
**Pull request by twigleingrid**
**Description:**
Adds padding to full page spinner (e.g. when creating a room),
which otherwise looks awkward on the grey background.
Before:
spinner-before1

After:
spinner-after2

Fixes [element-web/issues/20001](https://github.com/vector-im/element-web/issues/20001)

Signed-off-by: Ingrid Budau inigiri@posteo.jp

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

Preview: https://61bb19682eb271343d43a1a1--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
Thanks!

**Review by niquewoodhouse — APPROVED** [review]

**Comment by t3chguy** [comment]
CI failure due to stale base branch
Ignoring due to how trivial the change is

**Comment by t3chguy** [comment]
(wrong button)

**Comment by twigleingrid** [comment]
Thank you for accepting and merging!

**Pull request merged**
