### PR TITLE
Update Slate (#7419)

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/riot-web/issues/7419

Issue was fixed by using a more recent version of Slate. https://github.com/ianstormtaylor/slate/issues/982

Tests pass and everything appears to work with the latest versions of slate and slate-react so I went ahead and just used the latest version.

------

Unrelated but I was somewhat confused as CONTRIBUTING.rst says matrix-react-sdk follows the same pattern as Synapse but there is no Towncrier in here as far as I can tell.

Also why is the webpack version in here so old? I had to install 4.0.0 manually.

### CODE REVIEW

**Comment by turt2live** [comment]
I'm starting to think these PRs are for Hacktoberfest ;) Thanks for the PR anyhow, and here's hoping you'll be one of the 50k to get a tshirt.

I'm a bit worried that an older version of slate was used for some other reason. The end-to-end testing appears to have also caught an issue with the composer itself: https://travis-ci.org/matrix-org/matrix-react-sdk/builds/435783790#L2355 (luckily most of the console spam will be fixed by #2188). 

As for the contributing.md: good spot, I've opened https://github.com/vector-im/riot-web/issues/7430 to hopefully get it addressed. I'm not sure if we should copy/paste it into this repo or maybe spin up a repo specifically for holding the generic document, but suggestions here are appreciated (what would be easier for you, as a contributor?)

The old webpack is an interesting one. I don't see anything in the package.json that would use it, so it might have been included in error. @ara4n or @dbkr - do either of you happen to know what's going on here?

**Comment by t3chguy** [comment]
Older slate was pinned due to a bug they had I have since fixed upstream

**Comment by aaronraimist** [comment]
> The end-to-end testing appears to have also caught an issue with the composer itself: https://travis-ci.org/matrix-org/matrix-react-sdk/builds/435783790#L2355

How should I go about debugging what is wrong with the composer?

----

> I'm starting to think these PRs are for Hacktoberfest ;) Thanks for the PR anyhow, and here's hoping you'll be one of the 50k to get a tshirt.

Hacktoberfest? Actually I think it's just a coincidence that I started working on these in October.

**Comment by turt2live** [comment]
I'm not sure where to start debugging them to be honest. Did you see the placeholder while testing? @bwindels might have ideas (although he's on holiday at the moment).

As for hacktoberfest: it's basically a thing where if you open 5 PRs in October you can get a t-shirt: https://hacktoberfest.digitalocean.com/ - it's to promote open source and have a more thriving community. Looks like your timing was just perfect given you got 5 PRs on the 1st of the month :p 
I'm sure if you sign up now it'll back-credit the PRs for you, if you're interested.

**Comment by aaronraimist** [comment]
No I didn't see "Send a message (unencrypted)" pop up at the wrong time when I was testing it but admittedly I didn't play with it for that long. Will test more tomorrow.

**Comment by dbkr** [comment]
Did you try autocomplete or emoji with this? Just tested with these versions and typing an emoji gives ``Node.assertDescendant` could not find node with path or key: null` and autocomplete just doesn't appear at all.

**Comment by bwindels** [comment]
Yeah, the e2e tests seem to break on [typing in the composer](https://github.com/matrix-org/matrix-react-end-to-end-tests/blob/master/src/usecases/send-message.js#L26). The way to start debugging them would be to [install](https://github.com/matrix-org/matrix-react-end-to-end-tests) them locally and run them in windowed mode and dev tools open. I'll try to have a look as well.

**Comment by dbkr** [comment]
I've done the necessary API changes in https://github.com/matrix-org/matrix-react-sdk/pull/2202 (turns out there were quite a few). Thanks for looking at this!

**Pull request closed without merging**
