### PR TITLE
Fix event text overflow on bubble message layout

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/vector-im/element-web/issues/21882

This PR fixes the event text overflow on **bubble message layout.**

**Current implementation:**
before

This PR overrides the width settings to preserve the padding setting. Input on the padding width from the design team would be appreciated.

after

This should work for a short event text as well.

after2

The placement of the message action bar button with the magic number is adjusted too.

after1

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix event text overflow on bubble message layout ([\#8391](https://github.com/matrix-org/matrix-react-sdk/pull/8391)). Fixes vector-im/element-web#21882. Contributed by @luixxiul.

### CODE REVIEW

**Review by kerryarchibald — COMMENTED** [review]
This also doesn't reproduce on latest develop.
Screenshot 2022-04-27 at 17 05 36
Screenshot 2022-04-27 at 17 04 19

**Comment by luixxiul** [comment]
@kerryarchibald It is the modern layout. Please change the layout to the bubble message layout and try again.

> This PR fixes the event text overflow on **bubble message layout**.

**Comment by luixxiul** [comment]
As E2E test failed, I merged the latest develop branch but the test is not triggered..

**Comment by t3chguy** [comment]
Test runs need maintainer approval for security reasons

**Comment by luixxiul** [comment]
> Test runs need maintainer approval for security reasons

I see. Actually the test runs were conducted a moment ago, but E2E test has failed.

**Pull request merged**
