### PR TITLE
Enable sent receipt for poll start events (PSG-962)

### PR DESCRIPTION
**Pull request by Johennes**
Needs: https://github.com/matrix-org/matrix-js-sdk/pull/3034

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Enable sent receipt for poll start events (PSG-962) ([\#9870](https://github.com/matrix-org/matrix-react-sdk/pull/9870)).

### CODE REVIEW

**Comment by Johennes** [comment]
I'm a little lost in the massive CI output but it doesn't look like any of the failures would relate to my changes here?

**Comment by andybalaam** [comment]
I updated the change hoping for cleaner CI.

**Comment by Johennes** [comment]
> I updated the change hoping for cleaner CI.

Looks like that did it. 🙂

**Review by andybalaam — APPROVED** [review]
Looks good!

**Pull request merged**
