### PR TITLE
Search for users on paste

### PR DESCRIPTION
**Pull request by peterscheu-aceart**
Search for term on paste in the invite dialog instead of showing error dialog.

Keep behaviour for usernames/email or lists of users

Fixes https://github.com/vector-im/element-web/issues/17523

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Search for users on paste ([\#11304](https://github.com/matrix-org/matrix-react-sdk/pull/11304)). Fixes vector-im/element-web#17523. Contributed by @peterscheu-aceart.

### CODE REVIEW

**Comment by t3chguy** [comment]
3 of the 4 issues you linked as this fixing are already closed?

**Comment by peterscheu-aceart** [comment]
> 3 of the 4 issues you linked as this fixing are already closed?

yes they are marked as duplicates

**Review by germain-gg — CHANGES_REQUESTED** [review]
Thank you for opening this pull request.

There's no need to list the duplicated issue in your original description, I have edited them out. 
I will convert this issue to draft as it's still pending some tests to validate the new behaviour you're introducing. Feel free to request another request when you've managed to add those tests

**Comment by peterscheu-aceart** [comment]
I added the Tests. Do they suit the requirements like that?

**Review by germain-gg — CHANGES_REQUESTED** [review]
Thank you for adding tests, it does look like it's erroring out. But if we manage to fix that one out we should be able to merge this.

feel free to request a review when you've got this passing!

Thank you

**Review by germain-gg — APPROVED** [review]
Thank you for the perseverance with the tests 🙏 
Looks good, merging now

**Pull request merged**
