### PR TITLE
SearchBar: search by author

### PR DESCRIPTION
**Pull request by Pestdoktor**
## Update 2020-09-16

**Preview:** https://element.fentker.eu

This PR replaces the SearchBar input field with a BasicMessageComposer, hooking up autocompleted user and room pills to search filters. Server-side search already implements these filters, seshat support may be found at matrix-org/seshat#71.

### UX consideration
The ability to filter is not obvious to the user, especially after removing the room filter buttons

Possible Solutions:
- Add new buttons ("in", "by") opening the autocompleter
- Autofill the pill of the current room on opening the SearchBar
- ... (Suggestions?)

### Screenshot
image

## Original

related to https://github.com/vector-im/riot-web/issues/4752

**Todo**
- [x] add styling
- [x] make filter removeable
- [x] local search support

**Status**

image

### CODE REVIEW

**Comment by Pestdoktor** [comment]
So this was much easier than I expected and is basically in a mergeable state already now AFAIC

**Status**

image

A follow-up would probably address accessibility, local search support and autocompleting members of all rooms instead of just the current one

**Comment by turt2live** [comment]
This also needs product and design review to make sure it's something we actually want, and behaves how we want.

**Comment by Pestdoktor** [comment]
I just saw that local search isn't implemented yet, so I just added a commit preparing the noop for eventual by-author-support. At this point I'm going to lock my branch and commit any of the improvements I mentioned earlier to a new one so this one can be reviewed properly.

**Comment by turt2live** [comment]
Taking this out of dev review so the design/product team can take a look at it

**Comment by nadonomy** [comment]
Is there somewhere we can review an ad hoc/development build of this?

**Comment by Pestdoktor** [comment]
https://riot.fentker.eu/

**Comment by nadonomy** [comment]
> https://riot.fentker.eu/

Thanks for providing this! Will review this soon. Relatedly, I've also opened up an issue here so we can better communicate the value of the ad hoc builds here: https://github.com/vector-im/riot-web/issues/12614.

**Comment by Pestdoktor** [comment]
I'm looking to work on expanding this this week. Any feedback I should take into account?

Also what's the process to update the filter specs (https://github.com/matrix-org/matrix-doc/issues/969)? Can it just be implemented into Synapse as unspecified behaviour until there's a spec for it?

**Comment by nadonomy** [comment]
> I'm looking to work on expanding this this week. Any feedback I should take into account?

For sure, apologies reviewing this in detail is stuck behind some other work which is on the critical path but I'll figure out a way to unblock this.

**Comment by Pestdoktor** [comment]
I added a commit removing the search_term requirement, which is nice for testing but requires https://github.com/Pestdoktor/synapse/commit/1584f7f915ded62793ddd9dd143dade0c411a579 and breaks spec-compliance so it should  eventually be removed.

**Comment by Pestdoktor** [comment]
I'm now using BasicMessageComposer instead of trying to replicate the autocomplete functionality.

I also updated again, hence the preview is now available at https://element.fentker.eu/ 😉

Next up would be to allow for specifying multiple senders (currently takes only first one) and also hook up the room filter the same way. After that I'd look into seshat to make it work with e2e search.

**Comment by nadonomy** [comment]
@Pestdoktor just checking if the ad hoc build link is up to date? If so can review again!

**Comment by Pestdoktor** [comment]
Thanks! I'm trying to keep the preview up and synced with the branch.

Rebased again for good measure and included i18n gen.

**Comment by Pestdoktor** [comment]
Some things I noticed while making the new screenshot for OP:

- Synapse filtered search seems buggy, will open an issue over there when I've tested some more
- Can't self-autocomplete
- Result rendering could use some work

**Comment by atomtm** [comment]
Great feature needed!

**Comment by kittykat** [comment]
Product input: we would be open to adding the filtering if it fits with the designs for filtering in the new search experience. @Pestdoktor would you be interested in opening an updated PR for this issue?

As the codebase has changed a lot in the last couple of years, I'll close this one for now.

**Pull request closed without merging**
