### PR TITLE
Support $riot: Templates for SSO/CAS urls in the welcome.html page

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/12883

~~Additionally, there are 4 ways to reach this view:~~

~~+ You click Login~~
~~+ You navigate to #/login~~
~~+ You were already in login for another server but entered an SSO HS URL manually~~
~~+ You were already in login for another server but entered your SSO-powered MXID and well-known found your SSO HS URL~~

~~in my current implementation I only auto-redirect for the first two cases, is this desirable?~~

### CODE REVIEW

**Comment by ara4n** [comment]
I think it's fine to autoredirect for the common cases of login and #/login.

Is this good to review?  Would be good to get it up for the

**Comment by t3chguy** [comment]
Needs spinner and design

**Comment by t3chguy** [comment]
https://github.com/vector-im/riot-web/issues/12883#issuecomment-604312104

**Comment by t3chguy** [comment]
Something very basic for a login view with a spinner and manual link

**Comment by t3chguy** [comment]
image

For example like the above ^

**Pull request merged**
