### PR TITLE
Fix crash on logging in

### PR DESCRIPTION
**Pull request by dbkr**
If you arrived at the page via a link to a room.

Fixes https://github.com/vector-im/vector-web/issues/2634

### CODE REVIEW

**Comment by richvdh** [comment]
I appreciate this is better than a crash, but shouldn't it be showing the room you followed a link to, rather than the directory?

**Comment by dbkr** [comment]
done

**Comment by richvdh** [comment]
hrm... should we be clearing the roomid/alias on logout? somewhat worried about us leaking state to a future user.

**Comment by dbkr** [comment]
Ah yes, probably should.

**Pull request merged**
