### PR TITLE
Improve message error states

### PR DESCRIPTION
**Pull request by turt2live**
Fixes https://github.com/vector-im/element-web/issues/16423

----

**Code reviewer**: I would love to add tests for this, but there's a ton of logic which makes that difficult. It mostly comes from the js-sdk's built-in retry mechanisms (so messages don't fail for *ages*), and the fact that echo is just not something we can test for. Sorry.

**Design reviewer**: Testing this manually is a bit painful, so hopefully the screenshots below help. They should cover every state.

----

image
image
image
image
image
image
image

Dark theme visuals (only changed areas):
image

### CODE REVIEW

**Review by jryans — APPROVED** [review]
Thanks, looks great code wise! 😄

**Comment by jryans** [comment]
Thanks also for thinking about tests, I agree it's currently hard to cover in this case.

**Review by gaelledel — COMMENTED** [review]
- [ ] Just as we have the button " Retry all " leading to the "sending" state with a spinner, Could we do the same for "deleting all"? So it'd be "deleting" + spinner. Once the command is accomplished, we can remove the toast entirely.
- [ ] On dark mode on the bottom toast, can the separator colour be darker? 
Screenshot 2021-04-23 at 12 23 19

Apart from that all good!

**Comment by turt2live** [comment]
@gaelledel do we need a state for deleting? It should happen almost instantaneously every time...

For the divider, how's this?
image

**Comment by gaelledel** [comment]
> @gaelledel do we need a state for deleting? It should happen almost instantaneously every time...
> 
> For the divider, how's this?
> image

If it happens straight away then no we don't

**Review by gaelledel — APPROVED** [review]

**Pull request merged**
