### PR TITLE
Make local echo work for threads

### PR DESCRIPTION
**Pull request by gsouquet**
Fixes vector-im/element-web#19616
To review alongside https://github.com/matrix-org/matrix-js-sdk/pull/2026

---
This PR currently has no changelog labels, so will not be included in changelogs.

Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.

Preview: https://619df9ece62343d977d18e73--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by dbkr** [comment]
How about putting everything in a new `sendCompleteEventOnThread()` then make `sendCompleteEvent` a wrapper that calls `sendCompleteEventOnThread` with threadId undefined?

**Comment by gsouquet** [comment]
So `sendCompleteEvent` is actually private. But the public ones to update are

- sendEvent
- sendMessage
- sendStickerMessage
- sendTextMessage
- sendNotice
- sendEmoteMessage
- sendImageMessage
- sendHtmlMessage
- sendHtmlNotice
- sendHtmlEmote

Some of the function signatures are ambiguous

**Comment by turt2live** [comment]
A function overload which takes a `Thread` object of some sort should be able to distinguish between call signatures, and get us a bit closer to a design where we rely on models.

For example: 
```typescript
sendEmoteMessage(roomId: string, body: string, txnId?: string, callback?: Callback);
sendEmoteMessage(roomId: string, body: string, thread?: Thread); // I would intentionally stop letting `callback` proliferate
```

Compound IDs get messy over time, unfortunately :(

**Comment by gsouquet** [comment]
Right that's what I ended up doing! But the overload get really messy so haven't finalised it.
Looking purely at the type of the arguments is not enough, so I will usually inspect the fact that it's a string and that it starts with a `$` as it seems to be a  good identifier that a string will contain a Matrix event ID

**Comment by turt2live** [comment]
I'm a bit confused - the proposal is to send an object through instead of a string so the types can be checked.

**Comment by gsouquet** [comment]
Ohh, sorry, I've misread that 👀  I'll look at it properly in the morning

**Comment by gsouquet** [comment]
Sorry, I did not read your comment properly and thought you mentioned adding a `threadId` parameter.
This is the solution that I ultimately decided to go with rather than getting developers to construct a thread object as it requires a bit more work than it is asked of them today. Check the JS-SDK layer for more info.

Definitely agree that compound ID are not something to aim for

**Comment by gsouquet** [comment]
The CI is failing due to branch matching.

**Review by turt2live — CHANGES_REQUESTED** [review]
usage seems generally fine, though marking review for the js-sdk side.

**Review by turt2live — APPROVED** [review]

**Pull request merged**
