### PR TITLE
Fixed shield alignment on message Input

### PR DESCRIPTION
**Pull request by manancodes**
## Checklist

- [x] Tests written for new code (and old code if feasible)
- [x] Linter and other CI checks pass
- [x] Sign-off given on the changes (see [CONTRIBUTING.md] (https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Fixes https://github.com/element-hq/element-web/issues/26851
Signed-off-by: Manan Sadana manancodes.dev@gmail.com

This was the behaviour before the fix:
Screenshot 2024-01-17 at 3 24 14 AM

And this is the behaviour after the fix:
Screenshot 2024-01-17 at 3 24 23 AM

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fixed shield alignment on message Input ([\#12149](https://github.com/matrix-org/matrix-react-sdk/pull/12149)). Fixes element-hq/element-web#26851. Contributed by @manancodes.

### CODE REVIEW

**Comment by manancodes** [comment]
Converted to a draft because it needs some more work. The alignment is not right in rooms without encryption. And test screenshots need to be updated.

**Comment by manancodes** [comment]
I am trying to update the snapshots for the tests.

I am using this command: 
`yarn run test:playwright playwright/e2e/timeline/timeline.spec.ts --update-snapshots`

It adds new screenshots with `-darwin.png` extension but does not update the existing `-linux.png` files. I'm not very familiar with Playwright. What an I doing wrong?

In the .gitignore file I see that only `-linux.png` files are allowed to be pushed. So I think it is expected from playwright to create different types of screenshots.

**Comment by dbkr** [comment]
Thanks for this PR, I've updated the branch. I think you asked in the Matrix room but for the record, the answer was that we supply a docker image for the purpose, so `yarn test:playwright:screenshots timeline.spec.ts` should work.

**Comment by manancodes** [comment]
Awesome. Thanks. I'll update the PR.

**Review by dbkr — APPROVED** [review]

**Pull request merged**
