### PR TITLE
Handle permalinks in room topic

### PR DESCRIPTION
**Pull request by Johennes**
Fixes: vector-im/element-web#23395

This appears to work for permalinks in the room header. Needs tests and possibly handling the same case for space home screens.

---
Here's what your changelog entry will look like:

## ✨ Features
 * Handle permalinks in room topic ([\#11115](https://github.com/matrix-org/matrix-react-sdk/pull/11115)). Fixes vector-im/element-web#23395.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
Looks sane

> possibly handling the same case for space home screens.

IIRC that should be using this RoomTopic component too

**Comment by Johennes** [comment]
> > possibly handling the same case for space home screens.
> 
> IIRC that should be using this RoomTopic component too

Oh, yes I think you're right. `RoomTopic` is already used in `SpaceRoomView`. Nice!

**Comment by Johennes** [comment]
Tested manually and this appears to work fine for both rooms and space homes, both with and without HTML topics enabled.

I've added automated tests but I think they're a bit crap. I didn't manage to properly mock `window.location`. Would appreciate some guidance on whether and how to improve this.

**Review by t3chguy — APPROVED** [review]
Looks sane other than insufficient coverage

**Pull request merged**
