### PR TITLE
Add call silencing

### PR DESCRIPTION
**Pull request by SimonBrandner**
According to [this design](https://www.figma.com/file/V6m2z0oAtUV1l8MdyIrAep/VoIP?node-id=3472%3A79272)

Screenshot_20210522_202720

Screenshot_20210522_202732

### CODE REVIEW

**Review by jryans — APPROVED** [review]
Looks good code wise, thanks!

**Comment by ajayyy** [comment]
Would this just silence it for this call, or permanently? I think #15591 is about permanent silencing

**Comment by SimonBrandner** [comment]
> Would this just silence it for this call, or permanently? I think #15591 is about permanent silencing

You're right, sorry. I'll look into that issue separately

**Review by gaelledel — CHANGES_REQUESTED** [review]
Is it possible to see it in action? And see the light theme?

**Comment by gsouquet** [comment]
> Is it possible to see it in action? And see the light theme?

@gaelledel you can see it in action through the Netlify deploy preview, https://deploy-preview-6082--matrix-react-sdk.netlify.app/
If you want to find the link next time you can scroll down at the bottom of the pull request and click on "details" next to `netlify/matrix-react-sdk/deploy-preview`

**Review by gaelledel — APPROVED** [review]
Checked with Simon

**Pull request merged**
