### PR TITLE
RTE and Autocomplete fixes

### PR DESCRIPTION
**Pull request by aviraldg**
This PR tracks fixes to RTE and autocomplete, so we can finally make them the default. Fixes vector-im/vector-web#1761, vector-im/vector-web#1763.
- [x] autocompleting displaynames which include disambiguated mxids in RTE results in spurious lozenges #2231
- [ ] Wrap/ellipsize autocomplete text correctly vector-im/vector-web#2230
- [x] Speed up autocomplete matching vector-im/vector-web#1976.  At the least, please let's just turn off fuzzy matching for now.  It can be added back in again when performant.  Fuzzy matching is not a merge blocker.
- [x] Autocomplete should order based on who was last speaking #98 (Which was working pre-RTE)
- [x] press `t<tab><tab><tab>` - tabcomplete through room aliases like #test:matrix.org - cool! hit escape to hide the tabcompletion UI - reverts - cool! start hitting tab again... autocomplete UI doesn't display :(
- [x] press aviral<tab> - correctly tab completes to "aviraldg: ". keep typing, but the autocompletion UI remains present, trying to autocomplete the next things you say even though they don't look like rooms, names, emoji, etc. (related to #2189?) - this one is incredibly annoying.
- [x] Tab complete on a room alias should probably append a space, similar to what we do for users.
- [x] Selecting the input (e.g. by ctrl or cmd-A) adds a bunch of additional autocompletion options to the list if it's open, which is quite disconcerting.  (e.g. aviral<tab><ctrl-A> -> what?).  We should autocomplete options purely based on the stem that the cursor is currently at the end of, rather than looking inside the selection range, if any
- [x] Pause before displaying the autocomplete dialog.  It's completely unnecessary to display it the second someone presses @ or # or :.  Instead there should be a pause of 250ms or so before the autocomplete UI appears, otherwise it's just distracting and slows things down when typing .
- [x] In retrospect, I think we should Interpret `letter<tab>` autocomplete as searching displaynames/usernames only; not room names.  If you want to refer to a room by linkable name, you will always start with #.  Whereas our convention is to autocomplete plain fragments (i.e. no sigil) as people.  E.g. the chances of me wanting to refer to #aviralrocks:matrix.org when I type `av<tab>` rather than just trying to autocomplete the name Aviral is negligible.
- [ ] Remove MessageComposerInputOld, make MessageComposerInput default and remove from labs.

### CODE REVIEW

**Comment by ara4n** [comment]
@aviraldg is this ready for review & merge, or is/was the intention to tick off more of the checkboxes first?

**Comment by aviraldg** [comment]
(not ready for merge yet -- still a lot of debugging code, but check for the issues you've mentioned)

**Comment by ara4n** [comment]
I had a good play with this when flying back to the UK the other night.  It's a **huge** improvement.  Here are my remaining concerns:

Bugs:
 * [ ] # complete is broken entirely for me - see https://matrix.org/_matrix/media/v1/download/matrix.org/xkalGHJqxevanKKxsfIdxSNb. interestingly this looks to be a regression over develop, which seems fairly okay, but it's both losing the #, as well as trying to complete everything to 'undefined'.  To reproduce, hit `#<tab><tab><tab>`
 * [ ] Underline doesn't work - it isn't rendered.
 * [ ] When in MD authoring mode (not RTE), hitting the `</>` button silently does nothing at all.
 * [ ] Bulletpoint button when in MD-authoring mode just inserts `"-\n"` which doesn't help anyone; presumably it should jut be `" -"`?
 * [ ] When in RTE mode, there is no way to do multiple bulletpoints in a list - shift-return adds a <br/>; return sends the message
 * [ ] Round-tripping between MD & RTE mode on bulletpoint lists introduces vertical linespaces at the top
 * [ ] Lots of console debug present still
 * [ ] `/op` and `/tint` (and others?) don't show in the / command completion options * 
 * [ ] Lots of `Lots of
rageshake.js:63 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method 'preventDefault' on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.` errors

Refinements:
 * [ ] Delayed autocomplete almost works nicely, but it'd be nice if it only appeared if the user stops typing for more than 200ms or whatever.  Currently it seems to appear 200ms after you first hit # or @ or : etc even if you keep on typing.  Whereas if you're still typing you clearly aren't wanting to autocomplete and have the display flickering up at you.  The idea should be to show the menu when you hit tab (to explicitly select something) or pause to see if you can get a helper from the app.  (I'm about 60% sure about this, so happy to debate/experiment :)
 * [ ] Pasting HTML into a quote fails.  For instance, if you copy some scrollback into the RTE in order to quote, it gets pasted as a `<li/>` (which is almost fair enough, in some ways), but obliterates the quote block...
 * [ ] code blocks, when in RTE mode, have a weird and rather ugly amount of whitespace padding put above them.
 * [ ] When the autocomplete grid is shown, i found myself repeatedly trying to use the cursor-keys to move around.  It feels very strange that up/down work as you'd expect, but left/right don't and instead change the cursor position in the input view.  I strongly suggest that instead, if the user is interacting with the grid (having hit tab to enter it), the cursor keys operate within the grid.  And then 
 * [ ] Trying to use emoji feels weird.  The fact that it defaults to a fairly random set of emoji feel strange; the fact you can't navigate through a grid of possible options feels stranger.  This can wait until later, but I strongly suspect we can provide a better grid for navigating emoji options (perhaps relegating the `:sequence:` labels to a hoverover etc), and ordering by default by group rather than by random(!) :)
 * [ ] Still no `:(` `:)` style shortcuts for :smile: style emoji (but isn't a blocker)
 * [ ]  It'd be even nicer if common emoticons like `;)` were recognised and prompted for conversion to emoji with an autocomplete that you could engage by hitting tab.

The bugs are showstoppers for merging; the refinements are nice-to-have :)

**Comment by aviraldg** [comment]
> Bulletpoint button when in MD-authoring mode just inserts "-\n" which doesn't help anyone; presumably it should jut be " -"?

@ara4n The intention is for you to select the text you want as a bullet point and _then_ press that button. Clarify what the behaviour should be here.

**Comment by aviraldg** [comment]
> When in RTE mode, there is no way to do multiple bulletpoints in a list - shift-return adds a 
; return sends the message

Not sure how to resolve this -- we want to reserve return for sending and shift return for a soft break, so there's nothing for a hard break (which would end the bullet point.) Quotes have the same issue. Do you have a solution in mind?

**Comment by ara4n** [comment]
Have been testing.  Performance for autocomplete feels better, but still weird results...

https://matrix.org/_matrix/media/v1/download/matrix.org/gdacQBFEtkRUhTOemdJaVkfR

...and i got the overlay stuck on after fiddling:

screen shot 2017-03-11 at 20 16 58

I've hit a particularly annoying problem that cursor keys don't work when you're in a multiline entry - prioritising changing history.  So if you have written a multiline message and hit up-arrow to edit the next line up, it loses your current message(!) and replaces it with the previous one from history.

I then got another bug where the delete key appears to do nothing... although if you lean on it, you end up seeing this:

screen shot 2017-03-11 at 21 30 49

It looks like the RTE control wasn't updating the contents when you hit delete, even though the underlying input data was being updated?

**Comment by ara4n** [comment]
there's also a race where the overlay hangs around if you hit return to send a message rapidly after triggering it.  so the next line you write starts off in autocomplete mode.

**Pull request merged**
