### PR TITLE
MemberPresenceAvatar: fix null references

### PR DESCRIPTION
**Pull request by richvdh**
avoid assuming that `member` has a `user`

### CODE REVIEW

**Comment by turt2live** [comment]
Although this fixes the error, I'm not convinced it fixes the issue. The `render` function also assumes it gets some kind of value for both of those. It should probably not show a presence indicator (or the option to change presence) if there's no presence information.

**Comment by turt2live** [comment]
@richvdh I've pulled in your changes to see what happens, and it appears as though it effectively disables the icon but leaves the context menu accessible. https://github.com/matrix-org/matrix-react-sdk/pull/1623 should make sure that the handler is also ignored. Feel free to reauthor or redirect the PR: I've targeted against this PR's branch.

**Comment by richvdh** [comment]
@turt2live : is there a way to enable this? under labs I only have 'Message Pinning'.

**Comment by turt2live** [comment]
@richvdh yes, but riot.im/develop has a configuration problem (still). The feature is `feature_presence_management` not `feature_presence`.

**Pull request merged**
