### PR TITLE
[WIP] Tabbed Settings

### PR DESCRIPTION
**Pull request by turt2live**
# Required PRs
* https://github.com/vector-im/riot-web/pull/5773

# Addressed Issues
* https://github.com/vector-im/riot-web/issues/5476

# Description
Tabbed settings are an improved way for users to manage parts of their account in a more friendly manner. Prior to this PR, users would be faced with the challange of scrolling through a lengthy wall of settings to find what they need. Tabbed settings aims to simplify the settings interfaces for groups, rooms, and users by providing logical tabs for groups of similar settings.

The tabbed view is generic and intended to be a full-page component which accepts `Tab` objects to represent the different pages. Scrolling and navigation between the tabs is handled automatically.

A demo of this PR is running on https://t2bot.io/react1644/ with the feature enabled by default.

# Work in progress
This is still very early in the development stage and requires a fair amount of work still. Some of the items are listed below. Users may opt-in to using the new interface through a labs setting, however **you cannot revert back to the old interface yet**.

* [ ] Render all panels for CTRL+F support
* [ ] Field commitments should have a loading state, and confirmation of save
* [ ] Flair settings
* [ ] Make inputs a bit prettier when in a well
* [ ] Fix field commitment not being attached to displayname/avatar change
* [ ] Account settings panel
* [ ] Advanced settings panel
* [ ] Crypto settings panel
* [ ] Interface settings panel
* [ ] Notifications settings panel
* [ ] Voip settings panel
* [ ] Group settings (panel layout pending)
* [ ] Room settings (panel layout pending)
* [ ] Animations
* [ ] Documentation on tabbed view

### CODE REVIEW

**Comment by pafcu** [comment]
I think one issue is that there is no visual indication that it is possible to switch view by scrolling. Perhaps at the bottom right add a "Go to {name of next section}" link with a downward pointing arrow? I think this might make keyboard navigation easier (it does not seem possible to scroll with the keyboard now?).

**Comment by pafcu** [comment]
Also, do we want to think more about "Advanced settings"? Currently it has things like "Clear cache" and access tokens which are not really settings. Also, what is the actual reason for autocomplete delay being advanced? If these things were moved elsewehere, what remains is actually just the labs settings.

**Comment by turt2live** [comment]
"Advanced Settings" are supposed to be things that *could* fit on the about page, but have higher risk to the user or are more technical than other settings. For instance, clearing cache and the autocomplete delay are highly technical compared to changing your display name, so they get pushed to a dedicated tab. The access token is also being moved here because it's a technical element and has significant risk with having it on the about page.

Although it's called "user settings", people still end up going here for lack of a dedicated "about" page. This is why non-settings are included.

**Comment by turt2live** [comment]
Just a bit of a status update to prove this isn't abandoned: I've been a bit busy recently (yay! holidays!). I've slotted in some time for the week of Christmas with the goal of having at least UserSettings ready for complete review by the end of the year.

**Comment by turt2live** [comment]
I'm completely out of spare time and cannot maintain this PR anymore - someone else is more than welcome to pick it up on their side.

**Pull request closed without merging**
