### PR TITLE
Fix: <detail> HTML elements clickable area too wide.

### PR DESCRIPTION
**Pull request by manancodes**
## Checklist

- [x] Tests written for new code (and old code if feasible)
- [x] Linter and other CI checks pass
- [x] Sign-off given on the changes (see [CONTRIBUTING.md] (https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Fixes https://github.com/vector-im/element-web/issues/25454
Signed-off-by: Manan Sadana manancodes.dev@gmail.com

I fixed it in some other places too, wherever I could test it. 
Also some code has been removed from ```res/css/views/settings/tabs/user/_HelpUserSettingsTab.pcss``` which was not being used.

This was the behaviour before the fix:
Clickable area is too wide
Screenshot 2023-09-25 at 11 55 29 PM

And this is the behaviour after the fix:
On the text area is clicakable. 
Screenshot 2023-09-25 at 11 51 24 PM

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix: <detail> HTML elements clickable area too wide. ([\#11666](https://github.com/matrix-org/matrix-react-sdk/pull/11666)). Fixes vector-im/element-web#25454. Contributed by @manancodes.

### CODE REVIEW

**Comment by manancodes** [comment]
All checks have passed. Do you want me to change anything in the code?

**Review by florianduros — CHANGES_REQUESTED** [review]
Hi!

First of all, thank you for your contribution. I am sorry for the review delay.

I tested, it works when the clickable element is not toggled but when it's toggled, the area is still too wide: 

image

**Comment by manancodes** [comment]
I have fixed the width for the open state as well along with adding similar fix at a few more places.

**Comment by manancodes** [comment]
Some tests were failing because somehow `"common|advanced"` was changed to `"common|Advanced"` . Most probably this happend during the merge. Fixed now

**Comment by florianduros** [comment]
Great thank you!

**Review by florianduros — APPROVED** [review]
Great thank you!

**Pull request merged**
