### PR TITLE
Disable the message composer if we don't have permission to post to the room

### PR DESCRIPTION
**Pull request by dbkr**
Fixes https://github.com/vector-im/vector-web/issues/386
Requires https://github.com/matrix-org/matrix-js-sdk/pull/118 and https://github.com/vector-im/vector-web/pull/1249

### CODE REVIEW

**Comment by richvdh** [comment]
Looks ok, but it would make me much happier if you factored out a separate component (maybe the `mx_MessageComposer_input` div?) so you didn't have to null-check refs.textarea everywhere.

**Comment by dbkr** [comment]
Yeah, this would make a lot of sense because all the command history stuff could be factored out too. I wouldn't want to mix that in with this PR though.

**Comment by richvdh** [comment]
Sure. So first factor it out, then make the change?

I think this looks fragile at the moment - it's very hard to be sure that you've got enough null guards in there, and it's going to be very easy to break it in future.

If you want to go ahead and merge it because time is short, I won't throw my toys out of the pram; but the only time the refactor is going to happen is when you need to do some work on the code in question. (In other words: there is never a good time to do refactoring.)

**Comment by richvdh** [comment]
I'm going to take this off dave's hands and do the refactor first.

**Pull request closed without merging**
