### PR TITLE
Fix "Continuing without email" dialog bug 

### PR DESCRIPTION
**Pull request by 2580ayush2580**
Fixes [https://github.com/vector-im/element-web/issues/16248](https://github.com/vector-im/element-web/issues/16248)

Signed-off-by: Ayush Kumar 2580ayush2580@gmail.com

### CODE REVIEW

**Comment by 2580ayush2580** [comment]
@t3chguy please review this PR

**Review by jryans — APPROVED** [review]
Looks good, thanks for working on this! 😄

**Comment by t3chguy** [comment]
Ryan stole my fun :(

**Comment by t3chguy** [comment]
Thanks @2580ayush2580!!

**Comment by 2580ayush2580** [comment]
It's my pleasure to work with you all

**Pull request merged**
