### PR TITLE
Specify community description img must be mxc urls

### PR DESCRIPTION
**Pull request by mkenigs**
Closes vector-im/element-web#7100

Signed-off-by: Matthew Kenigsberg <matthewkenigsberg@gmail.com>

Closes #2856

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
Looks fine code-wise, though we might not want to put much effort into this broken feature until it is replaced from a product perspective.

**Comment by mkenigs** [comment]
So worth merging or too much work on a broken feature? @turt2live

**Comment by turt2live** [comment]
it means that I can't make the call and require a deisgner/product person to look at this.

**Review by nadonomy — APPROVED** [review]
Although the current communities implementation is on the chopping block, seems harmless to merge this for legacy.

**Pull request merged**
