### PR TITLE
Don't prefer STIXGeneral over the default font

### PR DESCRIPTION
**Pull request by robintown**
STIXGeneral contains some glyphs for non-LGC scripts, but often doesn't implement these scripts fully. We should always try the browser's default fonts, which are likely to look nicer and have broader script support, before falling back to STIXGeneral.

Closes https://github.com/vector-im/element-web/issues/23899

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Don't prefer STIXGeneral over the default font ([\#9711](https://github.com/matrix-org/matrix-react-sdk/pull/9711)). Fixes vector-im/element-web#23899.

### CODE REVIEW

**Comment by robintown** [comment]
Not entirely, because I don't have a macOS machine to test with

**Review by dbkr — COMMENTED** [review]
My guess would be that it it would be fine, since the browser should prefer a combining diacritic from any font before rendering glyphs separately? I'm not sure though - we should probably test to make sure (would it be too cheeky to suggest adding in a screenshot test or something for this bug while we're changing it?)

Also if you could add to the comment explaining this particular edge case which make the ordering important, that'd be fab.

**Comment by robintown** [comment]
I've slipped a screenshot test into the Polls test suite that covers both the Japanese and math-y diacritics cases. I also figured out how to get the font setup on my system to match that of Matthew's in https://github.com/matrix-org/matrix-react-sdk/pull/8687, and from manual testing I can confirm that this does not regress https://github.com/matrix-org/matrix-react-sdk/pull/8687.

**Review by justjanne — APPROVED** [review]

**Review by andybalaam — APPROVED** [review]
Looks good, thanks!

**Comment by tsawada** [comment]
Has this been deployed to element.io?
vector-im/element-web#23899 is still the case on my env.
```
Element version: 1.11.31
Olm version: 3.2.14
```

**Pull request merged**
