### PR TITLE
Show progress when loading keys

### PR DESCRIPTION
**Pull request by foldleft**
Fixes: https://github.com/vector-im/riot-web/issues/13167
Land after: https://github.com/matrix-org/matrix-js-sdk/pull/1351

Here's how it looks: [In channel](https://matrix.to/#/!MgHKouJtXaqQhDFKHq:matrix.org/$5uVEkcYbd6x2m2wH1AioeWHZNq5dD68oAGtuOw2Iy3M?via=matrix.org)

[Video link](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/HxPLaOFseSClfvjjpvUtOfYT)

### CODE REVIEW

**Comment by Half-Shot** [comment]
By stander thoughts: could this be inlined somehow into the security settings page, rather than as a model?

**Comment by foldleft** [comment]
> By stander thoughts: could this be inlined somehow into the security settings page, rather than as a model?

in this instance it might make sense, but the whole thing is a modal because it's also a part of the logout flow

**Comment by nadonomy** [comment]
@foldleft the copy updates would be:

- [ ] Update title "Loading..." -> "Restoring keys from backup"
- [ ] Update copy "Requesting from server..." -> "Fetching keys from server..."
- [ ] Update copy "Downloading from server..." -> "Fetching keys from server..."
- [ ] Update copy "Loaded x of y" -> "x of y keys fetched"
- [ ] Update title "Backup restored" -> "Keys restored"
- [ ] Update copy "Restored n session keys" -> "Successfully restored n keys"

**Comment by foldleft** [comment]
Okay, but note that "x of y keys fetched" isn't quite accurate. They're all definitely on the client at that point.

**Pull request merged**
