### PR TITLE
Unified room context menus

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/19527

---
Here's what your changelog entry will look like:

## ✨ Features
 * Unified room context menus ([\#7072](https://github.com/matrix-org/matrix-react-sdk/pull/7072)). Fixes vector-im/element-web#19527.

Preview: https://619242fcac6c7717dbc14db4--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by DoM1niC** [comment]
Wow this works fine and the events if I set a room to favourite seems fixed for me... but the low priority / favourit Chats could get divider from the rest... But this is in the end your choice

**Review by niquewoodhouse — COMMENTED** [review]
I think these are mostly small changes but some might not be.  

- [x] mx_RoomHeader_name to be same colour and size as mx_RoomListHeader
- [x] Room header name and avatar to align with your avatar from milestone 1.1
- [x] Notifications icon to update based on selection (eg if room is muted, show muted icon)

- [x] I think the room name could do with a hover state to give more feedback.
eg 



I wasn't aware this would change the room list options too.  I knew we'd have to do this eventually if this worked out, just not maybe now.  We might need to move the options around, tweak the styling a bit more, as this becomes a bit of a bigger change.  E.g., inset borders between some options, and maybe consider if there's a need for each item in both DMs and Rooms (eg `People` in DM is potentially not so helpful) so we might to spend more time considering these details :(

**Comment by t3chguy** [comment]
> I wasn't aware this would change the room list options too. I knew we'd have to do this eventually if this worked out, just not maybe now. We might need to move the options around, tweak the styling a bit more, as this becomes a bit of a bigger change. E.g., inset borders between some options, and maybe consider if there's a need for each item in both DMs and Rooms (eg People in DM is potentially not so helpful) so we might to spend more time considering these details :(

Can revert them if needed

**Comment by t3chguy** [comment]
- [ ] I've noticed in the threads lab the dropdown has a rotating arrow. Would be nice to be consistent and use that here too, but open to not doing for now as we've not tested this yet

**Review by jryans — APPROVED** [review]

**Review by niquewoodhouse — APPROVED** [review]

**Pull request merged**
