### PR TITLE
Remove hard-coded whitespace characters from SpaceCreateMenu.tsx

### PR DESCRIPTION
**Pull request by luixxiul**
Whitespace characters should not be hard-coded as some languages do not
have the concept of whitespace in the first place.

Fixes https://github.com/vector-im/element-web/issues/21187

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

Notes: none
element-web notes: none

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

Preview: https://pr7885--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by SimonBrandner — APPROVED** [review]
LGTM codewise - thanks!

I wonder if design/product has something to add here?

**Comment by dbkr** [comment]
Yeah, I think the we do need to keep the space when in English. Usually the solution to whitespace in strings would be to keep the three parts as separate strings, although of course that by itself doesn't let you tune the whitespace so it's sensible for each language.

**Comment by luixxiul** [comment]
FWIW there are a lot of cases where sentences are concatenated like [here](https://github.com/matrix-org/matrix-react-sdk/blob/5e467b5d43968479ff1dd1f90697367996e6c053/src/i18n/strings/en_EN.json#L454), so I would not see the reason why this case should be treated differently.

**Review by turt2live — APPROVED** [review]
I think this is probably fine. From digging through historical designs and the [original PR](https://github.com/matrix-org/matrix-react-sdk/pull/6543) it appears as though the intent might have been to have these on different lines, however that's not the case in modern mockups (or even the app). 

The `&nbsp;` would have theoretically been joining paragraph tags together, which would collapse the spacing.

**Comment by turt2live** [comment]
@luixxiul if you can add a screenshot of before & after, I can send it off for design review (as a precaution)

**Comment by luixxiul** [comment]
I see, here are cropped screenshots on the proposed change.

before-enafter-en

Also this is the problem this PR tries to fix, based on the latest translation on Weblate:

before-jp

**Review by janogarcia — APPROVED** [review]

**Comment by janogarcia** [comment]
@niquewoodhouse Maybe I hit the "Approve" button too fast. Could you please confirm if that's the expected layout for the intro copy? Should everything be in one paragraph? Same font size for the "You can change this later" note?

**Comment by luixxiul** [comment]
Maybe it was confusing to paste two pictures. I added `Before` and `After` to the post above.

**Comment by luixxiul** [comment]
What is the story on this PR?

**Review by niquewoodhouse — APPROVED** [review]

**Comment by t3chguy** [comment]
@turt2live this is back with you

**Comment by turt2live** [comment]
Thanks!

**Pull request merged**
