### PR TITLE
Fix blowout of waveform of the voice message player on narrow UI

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes https://github.com/vector-im/element-web/issues/22604

|Before|After|
|---------|------|
|before|after|

Essentially same as https://github.com/matrix-org/matrix-react-sdk/pull/8816. The issue probably should happen on any flexbox/grid with fixed width child elements.

https://css-tricks.com/preventing-a-grid-blowout/

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix blowout of waveform of the voice message player on narrow UI ([\#8861](https://github.com/matrix-org/matrix-react-sdk/pull/8861)). Fixes vector-im/element-web#22604. Contributed by @luixxiul.

### CODE REVIEW

**Review by justjanne — APPROVED** [review]
LGTM!

**Comment by luixxiul** [comment]
converting to draft for now to prevent accidental merge- please ping me after review.

**Comment by Johennes** [comment]
It's not ideal that we currently don't have screenshot tests for voice messages. That being said, this looks like a relatively low-risk change to me. So I think we can move ahead here.

@luixxiul if you're still up for it, could you merge `develop` into your branch and fix the conflicts. Afterwards, please re-request review from @justjanne as this has been sitting untouched for a while.

**Comment by luixxiul** [comment]
Since I messed up merge, I force-pushed to apply the same change as the previous commit.

**Review by justjanne — APPROVED** [review]

**Comment by Johennes** [comment]
The static analysis error stems from `develop` itself being broken yesterday. I'll merge this bypassing the check to avoid any further delays. Thanks again for your contribution, @luixxiul!

**Pull request merged**
