### PR TITLE
Fix spoiler command for HTML messages

### PR DESCRIPTION
**Pull request by EECvision**
Fixes https://github.com/vector-im/element-web/issues/21185

Type: defect

Before:
using the /spoiler command does not convert text to HTML, it rather performs the /spoiler action on a text. This PR fixed the issue by converting a text to HTML before passing it to the /spoiler command.

Output:
error

error1

Signed-off-by: Emmanuel Ezeka [eec.studies@gmail.com](mailto:eec.studies@gmail.com)

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix spoiler command for HTML messages ([\#8531](https://github.com/matrix-org/matrix-react-sdk/pull/8531)). Fixes vector-im/element-web#21185. Contributed by @EECvision.

### CODE REVIEW

**Review by gsouquet — CHANGES_REQUESTED** [review]
The code to keep the HTML formatting of the message looks fairly adequate for what you're trying to achieve. However it seems to belong to the slash command itself rather than to the composer `src/SlashCommands.tsx`.

I'd recommend you move all the logic to apply the correct formatting to that file and try to keep the changes to `SendMessageComposer.tsx` to a minimum

**Comment by EECvision** [comment]
> 

Alright, I got that. Thank you for the review.

**Comment by EECvision** [comment]
> > 
> 
> Alright, I got that. Thank you for the review.



> The code to keep the HTML formatting of the message looks fairly adequate for what you're trying to achieve. However it seems to belong to the slash command itself rather than to the composer `src/SlashCommands.tsx`.
> 
> I'd recommend you move all the logic to apply the correct formatting to that file and try to keep the changes to `SendMessageComposer.tsx` to a minimum

Hi @gsouquet, I have updated the changes accordingly. Thank you

**Review by gsouquet — CHANGES_REQUESTED** [review]
Apologies that review was lost! 
That looks more sensible indeed. It looks like there has been a few merge conflicts since the time you contributed this pull request.

It would also be ideal if we could add some tests as defined in the contributing guidelines https://github.com/vector-im/element-web/blob/develop/CONTRIBUTING.md

**Comment by Johennes** [comment]
Closing as we haven't heard back from the contributor since January. @EECvision if you're still interested in following through on this, please let us know and we can reopen the PR.

**Pull request closed without merging**
