### PR TITLE
Send Access Token in Headers to help prevent it being spit out in errors

### PR DESCRIPTION
**Pull request by t3chguy**
Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by ara4n** [comment]
i have a bad feeling that this will wreak havoc on some of the analytics we have which trawl through haproxy logs to spot patterns (and rely on sniffing access_tokens to track sessions)...

**Comment by ara4n** [comment]
i agree it's generally desirable though.

**Comment by t3chguy** [comment]
Fixes
https://github.com/vector-im/riot-web/issues/5551
https://github.com/vector-im/riot-web/issues/5139
https://github.com/vector-im/riot-web/issues/5373
https://github.com/vector-im/riot-web/issues/5374

**Comment by richvdh** [comment]
@ara4n: I'd suggest the solution to the analytics is to add the Authorization header to the list of request headers we capture, so that it is included in the logs. (see `capture request header` in https://www.haproxy.org/download/1.5/doc/configuration.txt).

We'll also need to update the cross-synchrotron load-balancing to look for Authorization headers.

**Pull request merged**
