### PR TITLE
Experiment in managing NotifPanel visibility

### PR DESCRIPTION
**Pull request by ara4n**
This is an experiment that:
 * Stops NotifPanel from being restored when you view a room (given it doesn't make sense within the context of a room)
 * ...unless you are clicking a link from NotifPanel, in which case NotifPanel should still be visible after having followed the link.

I'm not sure it's a success though; it's basically faking the NotifPanel to be a global panel (which it should be anyway), and fighting against the per-room semantics.

It doesn't feel great, as the NotifPanel flickers in/out of existence when you switch to a room which previously had it open - and when you use NotifPanel to jump to permalinks, the NotifPanel gets reloaded, and so loses its scrolloffset etc.

Thoughts welcome on whether there's anything useful to be taken from this.

---
Here's what your changelog entry will look like:

## ✨ Features
 * Experiment in managing NotifPanel visibility ([\#9248](https://github.com/matrix-org/matrix-react-sdk/pull/9248)).

### CODE REVIEW

**Comment by t3chguy** [comment]
The Notifications Pane has had some designs to move to the left panel as part of the IA (iirc) project, so any work here would likely get thrown away

**Review by t3chguy — COMMENTED** [review]
Clearing review while draft

**Comment by t3chguy** [comment]
https://www.figma.com/file/u6xYQamXT4BqUJ5cKnkbWr/iA-Prop?node-id=849%3A142547
https://www.figma.com/file/u6xYQamXT4BqUJ5cKnkbWr/iA-Prop?node-id=840%3A143326

image
image

**Comment by ara4n** [comment]
yup, makes sense; it's in entirely the wrong place in the IA currently, for sure. i guess the question is whether something like this is worth merging as a stopgap (possibly without the whole "reopen notifpanel if you follow a link from it" hack).

would fix https://github.com/vector-im/element-web/issues/21529

**Comment by t3chguy** [comment]
The notif panel is being moved out of the top right by @germain-gg in upcoming changes

**Pull request closed without merging**
