### PR TITLE
Flatten and simplify the memberlist sorting algorithm

### PR DESCRIPTION
**Pull request by turt2live**
The previous algorithm had a bug where it was getting stuck on the power level comparison, leaving the memberlist incorrectly ordered. The new algorithm uses less branching to try and walk through the different cases instead. Additionally, the steps used to determine the order have changed slightly to better represent an active member list.

This change also includes changes to try and re-sort the member list more often during presence changes. Events are not always emitted, however. This may be a js-sdk bug but appears to happen prior to these changes as well.

Fixes vector-im/riot-web#6953

### CODE REVIEW

**Comment by jryans** [comment]
> Events are not always emitted, however. This may be a js-sdk bug but appears to happen prior to these changes as well.

Would it make sense to file a separate issue to track this? It seems like something where we'd want to write a test for the correct behavior (and hopefully also fix whatever prevents it currently).

**Comment by turt2live** [comment]
I think the emit problem may be https://github.com/matrix-org/matrix-js-sdk/issues/404 or a very similar issue.

**Comment by jryans** [comment]
Would be possible to add test coverage for this change? It seems complex enough that test coverage would help me understand what's supposed to happen as a reviewer (who isn't familiar with this area) and also help verify it continues to work that way in the future.

**Comment by turt2live** [comment]
In theory the comments in the diff and the PR description highlight the intended behaviour (and the complexity of the problem). I'll look into some sort of testing though - not sure how we actually do testing for this kind of thing.

**Comment by turt2live** [comment]
@jryans good call on having me write a test, it actually caught a bug: https://github.com/matrix-org/matrix-react-sdk/pull/2381/commits/5a2113e1a9458cbbb346660f54725baeab70f4bd

Also, this should be ready to review. I've left the console.log statements in the test to ease debugging when the test fails again.

**Comment by turt2live** [comment]
> fwiw I'd have probably split out the sorting algorithm and tested it independently of react / the component, but this is fine too

The only reason I did it this way is it try and catch the result being wrong. The sorted list gets passed through several functions with the opportunity for mangling, so it seemed best to ensure the thing wasn't mangled wrongly.

**Pull request merged**
