### PR TITLE
fix timeline search with empty text box should do nothing

### PR DESCRIPTION
**Pull request by EECvision**
### Fix timeline search with an empty text box should do nothing bug

Before: Timeline search in an empty text box trigger the search function.

After: Timeline search in an empty text box does nothing

Fixes https://github.com/vector-im/element-web/issues/21714

Signed-off-by: Emmanuel Ezeka [eec.studies@gmail.com](mailto:eec.studies@gmail.com)

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * fix timeline search with empty text box should do nothing ([\#8262](https://github.com/matrix-org/matrix-react-sdk/pull/8262)). Fixes vector-im/element-web#21714. Contributed by @EECvision.

Preview: https://pr8262--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by dbkr** [comment]
Have fixed your syntax so github (and our changelog generator) knows that you're fixing the bug you mentioned.

**Comment by dbkr** [comment]
Also, would it be possible to write a test for this?

**Comment by EECvision** [comment]
> Have fixed your syntax so github (and our changelog generator) knows that you're fixing the bug you mentioned.

Alright, thank you.

**Comment by EECvision** [comment]
> Also, would it be possible to write a test for this?

yes, I will write it.

**Review by turt2live — CHANGES_REQUESTED** [review]
this is lacking tests which were requested

**Comment by EECvision** [comment]
> this is lacking tests which were requested

Hi, I have added the tests.

**Comment by andybalaam** [comment]
> > Have fixed your syntax so github (and our changelog generator) knows that you're fixing the bug you mentioned.
> 
> Alright, thank you. There are other contributions I made but did not add any label. Please, what should I do? Is it going to affect my contribution recorded on the outreachy page?

No, if you list your contributions on that page they will be reviewed by a person as part of the application process.

**Review by turt2live — APPROVED** [review]
thanks! I believe the original request for tests was just the changed code, but extra tests are very much appreciated :)

**Pull request merged**
