### PR TITLE
Remove a redundant white space

### PR DESCRIPTION
**Pull request by luixxiul**
Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect
element-web notes: none

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Remove a redundant white space ([\#10129](https://github.com/matrix-org/matrix-react-sdk/pull/10129)). Contributed by @luixxiul.

### CODE REVIEW

**Review by weeman1337 — APPROVED** [review]
-

**Review by weeman1337 — CHANGES_REQUESTED** [review]
Thank you for your contribution @luixxiul 

Can you run `yarn run i18n` to update the translation files?

**Comment by luixxiul** [comment]
I've forgot that, thanks for notifying.

**Review by weeman1337 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
