### PR TITLE
Fix VoIP PIP frame color

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes [#16570](https://github.com/vector-im/element-web/issues/16570)
Screenshot_20210427_152456
Screenshot_20210427_152039

### CODE REVIEW

**Review by gaelledel — DISMISSED** [review]
Could we change the frame colours to these?
Light Theme: #F4F6FA 
Dark Theme: #394049

It can then be merged but its core visual style might change again soon.

**Comment by SimonBrandner** [comment]
@gaelledel, it looks great in the dark theme! But I am not so sure about the light theme. I find it quite hard to differentiate it from the panel

Screenshot_20210423_135509
Screenshot_20210423_135551

**Comment by gaelledel** [comment]
@SimonBrandner It doesn't seem that there is a drop shadow on the PIP, is there? if you could add this, it'll help to create levels in the hierarchy and will create a better contrast between components. Regarding the colours, we are currently tidying our themes to a more restricted palette and so it is important to stick with the colours I gave you earlier.
The drop shadow should do the trick.

**Comment by SimonBrandner** [comment]
There is a drop shadow but its alpha was very low. This is how it looks at `45%`. Is that alright?

Screenshot_20210423_152958
Screenshot_20210423_153009

**Comment by gaelledel** [comment]
The shadow is too large in width, could you try that?         
box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.5);

**Comment by SimonBrandner** [comment]
Here: 
Screenshot_20210423_160207

**Review by jryans — APPROVED** [review]
Looks reasonable to me, thanks! 😄

**Comment by gaelledel** [comment]
@SimonBrandner Could I get a screenshot of the PIP in Light and dark with the whole UI in the background? That'll allow me to see the drop shadow better and in context

**Comment by SimonBrandner** [comment]
@gaelledel, sure - I've updated the description with fullscreen images

**Comment by jryans** [comment]
@gaelledel has told me this is good to go with the opacity change.

**Pull request merged**
