### PR TITLE
Remove unused code left over from the old search

### PR DESCRIPTION
**Pull request by justjanne**
Type: Task
Closes: https://github.com/vector-im/element-web/issues/22696

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by t3chguy — COMMENTED** [review]
I think all the Runtime filtering stuff can be removed also, including stuff like https://github.com/matrix-org/matrix-react-sdk/blob/2a396a406d7e13a534bf34350e4d590c68222816/src/stores/room-list/RoomListStore.ts#L564-L571

**Comment by justjanne** [comment]
> I think all the Runtime filtering stuff can be removed also, including stuff like

Are you sure? It looks like that’s used for filtering by space

**Comment by t3chguy** [comment]
Spaces use Prefiltering, not Runtime filtering, that else clause will never be entered to my knowledge

**Review by t3chguy — COMMENTED** [review]
Is FilterKind used any more? Or at least is Runtime filterkind used anymore?

**Review by t3chguy — COMMENTED** [review]
I think all the filter handling in Algorithm.ts is also now dead

**Review by t3chguy — APPROVED** [review]
Looks sane to me, thanks!

**Pull request merged**
