### PR TITLE
Improve URL previews

### PR DESCRIPTION
**Pull request by t3chguy**
Reverts matrix-org/matrix-react-sdk#6135
Requires https://github.com/matrix-org/matrix-js-sdk/pull/1721
Fixes https://github.com/vector-im/element-web/issues/5433
Fixes https://github.com/vector-im/element-web/issues/17889
Fixes https://github.com/vector-im/element-web/issues/5877
Fixes https://github.com/vector-im/element-web/issues/13711
Fixes https://github.com/vector-im/element-web/issues/13143

image
image

Based on designs in https://github.com/vector-im/element-web/issues/5433#issuecomment-339700669

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Nice! Looks good to me!

**Comment by niquewoodhouse** [comment]
Really minor comment - Just to check please, does collapse hide the '3 other previews' or all the previews?

I think 'hide' or 'hide previews' might be better English, as the opening is show, not expand.

**Comment by t3chguy** [comment]
> does collapse hide the '3 other previews' or all the previews?

It takes you back to exactly how it looked before you clicked `Show N other previews`

The *hide* interaction is the `X`

**Review by niquewoodhouse — APPROVED** [review]

**Comment by t3chguy** [comment]
We can tweak copy after playing with it

**Pull request merged**
