### PR TITLE
Temporarily remove decorator

### PR DESCRIPTION
**Pull request by dbkr**
As, for reasons not yet fully understood, it causes riot to crash
on load if babel's targets are set to exclude IE11.

### CODE REVIEW

**Comment by Half-Shot** [comment]
@dbkr you'll want to remove it from the newly merged `BridgeTile.js` too

**Comment by jryans** [comment]
Ah https://github.com/matrix-org/matrix-react-sdk/pull/3953 has also added a few more just now... 😅

**Comment by turt2live** [comment]
sorry Dave, it's time to upgrade to a real computer.

BestBuy has some good Windows deals :p

**Comment by turt2live** [comment]
Closing in favour of fixing decorators

**Pull request closed without merging**
