### PR TITLE
Improve string for leaving space in leave dialog

### PR DESCRIPTION
**Pull request by kittykat**
Doesn't leave subspaces either, but those are in Beta so we probably
shouldn't mention them for now so the user doesn't get confused

Signed-off-by: Ekaterina Gerasimova <ekaterinag@element.io>

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Improve string for leaving space in leave dialog ([\#6826](https://github.com/matrix-org/matrix-react-sdk/pull/6826)). Contributed by [kittykat](https://github.com/kittykat).

Preview: https://614990cd40f456922d85485e--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by novocaine** [comment]
nice. you will need to run `yarn i18n` and commit the change it generated to get CI to pass

see https://github.com/vector-im/element-web/blob/develop/docs/translating-dev.md#adding-new-strings

**Review by t3chguy — APPROVED** [review]

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
It's definitely better (the current one makes no sense after some other changes) but I think it's worth saying at the least `and spaces` at the end.  I understand if we feel saying spaces might be confusing but as the other two options already say it, by this option being different someone could infer it's not an equal option to them.

Or the scope is to change all the options to remove the `and spaces` copy.  It might be safe to assume the user considers spaces/subspaces to ultimately be part of the rooms of a space.

v1
- Don't leave any rooms in Space name
- Leave all rooms in Space name
- Leave specific rooms in Space name

v2

- Don't leave anything in Space name
- Leave everything in Space name
- Leave specific things only

**Comment by kittykat** [comment]
@niquewoodhouse what about this for v1:

> You are about to leave <space.name>. Would you like to leave the rooms in this space?
> - Don't leave any rooms
> - Leave all rooms
> - Leave some rooms

**Comment by niquewoodhouse** [comment]
That's great, thanks.  

**Public space intro**

You are about to leave <space.name>.  Would you like to leave the rooms in this space?

**Private space intro**

You are about to leave <space.name>.  You won't be able to rejoin unless you are re-invited.  Would you like to leave the rooms in this space?


**Options**

Don't leave any rooms
Leave all rooms
Leave some rooms

**Review by niquewoodhouse — APPROVED** [review]

**Review by Palid — APPROVED** [review]
LGTM, just make linter happy

**Review by gsouquet — APPROVED** [review]
💯 Looks good to me!

**Pull request merged**
