### PR TITLE
Add a subtle shadow on message bubbles

### PR DESCRIPTION
**Pull request by andybalaam**
This is an idea from me, not a designer.

Other popular messaging apps display bubbles on web with a subtle shadow, which is an effect I like.

This change adds a subtle shadow on message bubbles:

image

The effect is currently even more subtle in dark mode:

image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Add a subtle shadow on message bubbles ([\#7832](https://github.com/matrix-org/matrix-react-sdk/pull/7832)). Contributed by @andybalaam.

Preview: https://pr7832--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by amshakal** [comment]
Hi Andy, thanks for contributing! We currently don't use a lot of shadows in the design system for components that look and behave like a bubble eg. images, voice messages etc. I am afraid that adding a shadow to the bubbles might make make it look inconsistent with the rest of the design system we have in place. 

We do use a subtle drop shadow for overflow menus, modals and pop ups on web but the purpose of that is to illustrate layers and depth.

**Comment by andybalaam** [comment]
Hi @amshakal thank you so much for finding the time to look at this.

Do you agree with me that the current message bubble view on Web looks a bit washed-out and unfriendly?

I experimented with adding shadows, but maybe it would be more appropriate to add borders, or to brighten up the colours a little:

image
image
image

(wow I am not good at choosing colours)

Is there anything I can do to help?

**Comment by amshakal** [comment]
I think the plan would be to add a new colour for bubbles that makes it stand out a bit more. We are currently expanding our colour palette in the design system, and once we lock a secondary colour(s), I'll be happy to update the bubble colour then. For now, I'd leave it like this. 

Would that work for you?

**Comment by andybalaam** [comment]
@amshakal that sounds like a plan. When we have new colours, feel free to ping me and ask for me to write a PR for them, unless it's already in the hands of a team.

Meanwhile I'll close this PR since we're not going ahead with it.

**Pull request closed without merging**
