### PR TITLE
Allow to reuse sounds for custom notifications

### PR DESCRIPTION
**Pull request by rummatee**
This addresses one point in https://github.com/vector-im/element-web/issues/9687

image

I added a List of already uploaded Sounds, including an option for the default and an option to upload a new Sound.
I changed the behavior of the reset Button to reset the selection to the previously saved option, instead of setting the sound to the default (This is now an option in the list instead)

---
Here's what your changelog entry will look like:

## ✨ Features
 * Allow to reuse sounds for custom notifications ([\#6002](https://github.com/matrix-org/matrix-react-sdk/pull/6002)). Contributed by @rummatee.

### CODE REVIEW

**Comment by t3chguy** [comment]
This UX has already been redesigned and awaiting re-implementation as part of the FTUE Notifications project so this might not get the review in needs based on that

**Comment by MadLittleMods** [comment]
For reference the FTUE Notifications project never made it.

The concept seems decent to ship if this was revived. Haven't looked at the code.

**Comment by daniellekirkwood** [comment]
From my perspective this looks like an ok add for now. 

I would like for Design to review (already pending a design review, have pinged the Design-Internal room for this)

**Comment by amshakal** [comment]
Hello, thanks for contributing! This seems like an acceptable change from my perspective. A few changes I'd request for are:

1. Can we make sure that the title 'Select a custom sound' follows the same typographic style as the 'Sounds' heading above it? (Colour, text style, spacing etc)?
2. Can we change the 'Reset' button to 'Use default sound' just so that it's crystal clear what that button does?
3. Can we use sentence case for the hint/title in the drop down? i.e. change 'custom sound' to 'Custom sound'?

Thank you!

**Comment by gsouquet** [comment]
Converting this to a draft until we have made the updates mentioned above

**Review by germain-gg — CHANGES_REQUESTED** [review]
Let me know once the changes have been made 👍 and we'll give this another review

**Pull request closed without merging**
