### PR TITLE
Replace "community" with "space" of keyboard shortcuts

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes https://github.com/vector-im/element-web/issues/20755
Closes https://github.com/vector-im/element-web/pull/20804

Depends on https://github.com/matrix-org/matrix-react-sdk/pull/8027

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

Notes: Replace "community" with "space" of keyboard shortcuts
element-web notes: none

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

Preview: https://pr7994--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by SimonBrandner — APPROVED** [review]
LGTM - thank you!

**Comment by luixxiul** [comment]
Waiting for @aj-ya 's response...

**Comment by aj-ya** [comment]
Looks good!

**Review by t3chguy — CHANGES_REQUESTED** [review]
https://github.com/vector-im/element-web/pull/20804#issuecomment-1025576379 applies

**Comment by luixxiul** [comment]
As groups (communities) have been deprecated and removed, it is no longer required to consider them.

**Review by t3chguy — APPROVED** [review]
Great, thanks!

**Pull request merged**
