### PR TITLE
Deprecate `mx_RightPanel_headerButton` class

### PR DESCRIPTION
**Pull request by luixxiul**
For https://github.com/matrix-org/matrix-react-sdk/pull/10495

This PR intends to deprecate `mx_RightPanel_headerButton` class in favor of `mx_RoomHeader_button` to update the header buttons of `RoomHeaderButtons` by conforming them to our naming policy.

~~Moving the styles to `_RoomHeader.pcss` or `_RoomHeaderButtons.pcss` should be addressed by another PR.~~

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by luixxiul** [comment]
The Jest snapshot update by https://github.com/matrix-org/matrix-react-sdk/pull/10807 was applied.

**Review by gsouquet — CHANGES_REQUESTED** [review]
I can get behind the renaming of the CSS class, makes sense 👍
Would you be able to move the CSS in the file you suggested now? That would be quite relevant as part of this changeset. And I don't see the need for a different pull request.

**Comment by luixxiul** [comment]
> And I don't see the need for a different pull request.

Some reviewers prefer to review a PR which is dedicated to a single task, rather than including multiple ones.

Because it is intended for the sake of a reviewer, it is no problem for myself to create a new CSS file on this PR.

Please wait for a moment…

**Comment by gsouquet** [comment]
I very much agree with the fact that a pull request should contain one change. I don't think renaming and moving them to a new file should be considered separate in this scenario. It is part of one unit of work.

**Comment by luixxiul** [comment]
Indeed. I just thought the "single" change in terms of the number :wink:

**Comment by luixxiul** [comment]
Since the style rules have been moved and a lot of them have been changed by https://github.com/matrix-org/matrix-react-sdk/pull/10808, I am going to rebase and force-push to ensure the change is applied really as expected.

**Comment by luixxiul** [comment]
The conflict was fixed.

**Review by gsouquet — APPROVED** [review]
Thank you for making the changes! Looks great

**Comment by luixxiul** [comment]
Thanks for the review!

**Pull request merged**
