### PR TITLE
Highlight event when any version triggered a highlight

### PR DESCRIPTION
**Pull request by kerryarchibald**
Fixes https://github.com/vector-im/element-web/issues/24923
Fixes https://github.com/vector-im/element-web/issues/24970

With intentional mentions:
Screenshot 2023-04-04 at 16 41 58
Screenshot 2023-04-04 at 16 42 08
notification after editing to remove mention:
Screenshot 2023-04-04 at 16 43 07
on clicking notification:
Screenshot 2023-04-04 at 16 43 14
Screenshot 2023-04-04 at 16 45 38

Without intentional mentions:
Screenshot 2023-04-04 at 16 49 42
Screenshot 2023-04-04 at 16 49 02
Screenshot 2023-04-04 at 16 48 42
Screenshot 2023-04-04 at 16 48 26

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Highlight event when any version triggered a highlight ([\#10502](https://github.com/matrix-org/matrix-react-sdk/pull/10502)). Fixes vector-im/element-web#24923 and vector-im/element-web#24970. Contributed by @kerryarchibald.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Looks good 👍

**Comment by daniellekirkwood** [comment]
This looks great to me - thanks for all the details in the screenshots. 

In the issue we've discussed making the "edited" text to red when you've been edited out of a message. 

Would it be possible to loop that change in with this PR? 

See comment here: https://github.com/vector-im/element-web/issues/24970#issuecomment-1496244363

**Comment by kerryarchibald** [comment]
Screenshot 2023-04-05 at 14 10 38

**Comment by daniellekirkwood** [comment]
this looks great, thank you! 

happy to approve but when i click "review now" it only lets me add a comment :/

**Pull request merged**
