### PR TITLE
Fix message composer growth to be bound by view height and not 140px

### PR DESCRIPTION
**Pull request by greg-nagy**
## Why

The size of the composer is very limiting when writing a longer message with many details and links. It's hard to review the message before sending or collecting the links after the text is composed. 

## What

This change lets the composer grow to 70% of the current view height. The autocomplete is still visible, but we can also see as much of the message as possible.

## Test 
- open dev tools in a room
- search for `mx_BasicMessageComposer_input mx_BasicMessageComposer_input_shouldShowPillAvatar`
- change the `max-height` from `140px` to `70vh`

Before the change:
CleanShot 2022-10-29 at 15 37 09

After the change:
CleanShot 2022-10-29 at 15 40 03

Signed-off-by: Gergo Nagy <nagy.gergo@3pixel.hu>

## Checklist

* [x] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Fix message composer growth to be bound by view height and not 140px ([\#9521](https://github.com/matrix-org/matrix-react-sdk/pull/9521)). Contributed by @greg-nagy.

### CODE REVIEW

**Review by SimonBrandner — APPROVED** [review]
LGTM codewise

Note 1: This is going to require a review from the design team
Note 2: The team is working on completely reworking the composer and so there is a chance this won't get through since the focus is on the new composer (https://github.com/matrix-org/matrix-wysiwyg)

**Comment by greg-nagy** [comment]
@SimonBrandner Do you think it's possible to give the design team a very subtle and friendly nudge? 

Don't want to push them if they are in deep rewrite land, but I also would like to have this during the day.

**Comment by t3chguy** [comment]
@daniellekirkwood done

**Comment by rufuskahler** [comment]
Thanks for your contribution @greg-nagy !

The current height of the composer optimises for concise, bite-sized messaging behaviours. This allows for faster content creation and faster, more contextual feedback from the receiver, e.g React, Reply (in thread). Increasing the height significantly may hinder these behaviours. On a related note, increasing the height of the composer would also increase the distance between the user’s initial cursor position and the message action icons (Emoji, Attachment… Send) (see Fitt’s Law), though this could be remedied if fixed to the bottom margin.

@callumu – do you feel there’s an opportunity to increase the height somewhat, with these risk factors in mind?

**Pull request closed without merging**
