### PR TITLE
Convert Velociraptor component to a class

### PR DESCRIPTION
**Pull request by turt2live**
I thought I needed this to fix read receipts, but I don't. Instead of throwing away the code we might as well convert it.

### CODE REVIEW

**Comment by bwindels** [comment]
Just checking, but you're aware Dave was working to get rid of it, right? https://github.com/matrix-org/matrix-react-sdk/pull/3674

**Comment by turt2live** [comment]
Yup, though this particular use might still be a Velociraptor in our code with the guts replaced.

**Comment by t3chguy** [comment]
What was the point of the `ReadReceiptStore.js` file?

**Comment by turt2live** [comment]
@t3chguy a failed experiment - I'll remove from develop direct (oops)

**Pull request merged**
