### PR TITLE
Show displayname in non-narrow thread summeries

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/19646

image
image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Show displayname in non-narrow thread summeries ([\#8036](https://github.com/matrix-org/matrix-react-sdk/pull/8036)). Fixes vector-im/element-web#19646.

Preview: https://pr8036--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]

**Review by janogarcia — CHANGES_REQUESTED** [review]
Thanks @t3chguy !

Just some minor tweaks here and there:

Element  5  | 🧪 Playground Encrypted

I tweaked some styles in the web inspector to test it live:

Element  5  | 🧪 Playground Encrypted

The text is now sitting on the same baseline, and the gap between the name and message preview is 4px.

---

I applied `align-items: baseline` to the thread summary container, then `align-self: center` to the thread icon and finally centered the image via old-school relative top 50% + translateY -50% (that was not very elegant, but applying align-self center to it was throwing off the baseline alignment for text), but there's probably a cleaner/simpler workaround (e.g.,  keeping `align-items: center` but making sure all text elements have the same `line-height`).

**Review by janogarcia — CHANGES_REQUESTED** [review]
@t3chguy You're going to hate me for this, but now the caret icon shown on hover is not vertically aligned. Also, I noticed that the baseline alignment workaround I suggested using is slightly throwing the text from the actual vertical center. 

That's why I'd suggest going for the second workaround, which it's actually simpler :D

Keep the `align-items: center` but apply the **same line-height** value for the text elements. That does the trick. It keeps all the text elements on the same baseline and properly centered.

Expected output:

Element  5  | 🧪 Playground Encrypted

**Comment by janogarcia** [comment]
That said, the `baseline` workaround worked for me (correct vertical center) on the [screenshot above](https://github.com/matrix-org/matrix-react-sdk/pull/8036#pullrequestreview-907386182), so I'm not sure what are the implementation differences causing yours to be slightly off centered.

**Comment by t3chguy** [comment]
> but now the caret icon shown on hover is not vertically aligned.

This is unrelated to this PR and the existing behaviour

image

Caused by reliance on the Inter font and a non-centered character in an `::after` pseudo-element which cannot have text alignment manipulation applied to it, I suggest opening a separate issue about that as it requires a few more changes to swap this over to an SVG.

**Comment by t3chguy** [comment]
image

**Review by janogarcia — APPROVED** [review]

**Pull request merged**
