### PR TITLE
Enable ReplyChain text to be expanded on IRC layout

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes https://github.com/vector-im/element-web/issues/22709

This PR fixes the issue that the text on ReplyChain cannot be expanded on IRC layout.

After:

https://user-images.githubusercontent.com/3362943/176830085-ce7a99f4-0ace-4e6a-8290-8607e24408e8.mp4

Other glitches on the tile (such as the left stroke) are out of scope of this PR.

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Enable ReplyChain text to be expanded on IRC layout ([\#8959](https://github.com/matrix-org/matrix-react-sdk/pull/8959)). Fixes vector-im/element-web#22709. Contributed by @luixxiul.

### CODE REVIEW

**Comment by weeman1337** [comment]
The issue mentions to be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/8958 .

On [develop](https://develop.element.io/) I can confirm, that die issue no longer exits → closing this PR.

@luixxiul if you think that was wrong, let me know.

**Comment by luixxiul** [comment]
@weeman1337 please see above.

**Comment by weeman1337** [comment]
Seems to be working with IRC layout:

irc

**Comment by weeman1337** [comment]
Got it :slightly_smiling_face: Tested on the Netlify Deployment. Works.

**Review by weeman1337 — APPROVED** [review]

**Comment by luixxiul** [comment]
@weeman1337 Thanks for reviewing.

**Pull request merged**
