### PR TITLE
fix Reply-quotes of code blocks have unsymmetrical padding

### PR DESCRIPTION
**Pull request by Arnabdaz**
Fixes https://github.com/vector-im/element-web/issues/21870

Here's what your changelog entry will look like:

# 🐛 Bug Fixes

- Unsymmetrical padding in reply code-block fixed  ([#10084](https://github.com/matrix-org/matrix-react-sdk/pull/10084)) Fixes [#21870](https://github.com/vector-im/element-web/issues/21870) Contributed by @Arnabdaz 

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This PR currently has none of the required changelog labels.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

### CODE REVIEW

**Comment by Arnabdaz** [comment]
### the issue to be fixed vertical text alignment  and padding issues in top and bottom

### before the fix:
Screenshot_20230205_024716

### after the fix:
Screenshot_20230205_024653

**Comment by t3chguy** [comment]
> Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md?rgh-link-date=2023-02-04T18%3A37%3A42Z))

Missing sign off, checking the box is not enough, see the linked document.

**Comment by Arnabdaz** [comment]
> > Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md?rgh-link-date=2023-02-04T18%3A37%3A42Z))
> 
> Missing sign off, checking the box is not enough, see the linked document.

@t3chguy done adding sign off and also tried to fix the description of pr ... is there any thing else to fix ?

**Review by gsouquet — CHANGES_REQUESTED** [review]
@HarHarLinks made some very sound comments on the issue https://github.com/vector-im/element-web/issues/21870#issuecomment-1418285080

Overriding the CSS isn't likely the solution here. It seems that highlight.js is either not instanciated when in replies or that its HTML structure or CSS is wrong for some (unknown) reason.

**Comment by Arnabdaz** [comment]
> @HarHarLinks made some very sound comments on the issue [vector-im/element-web#21870 (comment)](https://github.com/vector-im/element-web/issues/21870#issuecomment-1418285080)
> 
> Overriding the CSS isn't likely the solution here. It seems that highlight.js is either not instanciated when in replies or that its HTML structure or CSS is wrong for some (unknown) reason.

@gsouquet thanks a lot for the suggestion I would try my best to look into the issue and solve it ... but 

- can you please tell if there is any documentation to easily get acquainted with the codebase ?

- and also I had some issues running the dev server locally can you please tell where can I get help for that ?

**Comment by gsouquet** [comment]
For all dev related queries, i would suggest https://matrix.to/#/#element-dev:matrix.org

**Comment by HarHarLinks** [comment]
Title of this issue may need adjusting if it ends up addressing all of https://github.com/vector-im/element-web/issues/21870. Feedback from the dev team is needed on design decisions (which is perhaps happening out of band following gsouquet's hint).

**Comment by dbkr** [comment]
Since this hasn't had any activity for a while, I'm going to close it, but of course feel free to open a new PR if you get a different solution.

**Pull request closed without merging**
