### PR TITLE
Improve LinkPreviewWidget

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/vector-im/element-web/issues/22634

- Use spacing variables
- Use gap properties between elements
- Wrap `mx_LinkPreviewWidget_caption` to let it displayed on the narrow message panel

|Before|After|
|---------|------|
|before|after|
|before1|after1|

https://user-images.githubusercontent.com/3362943/176156190-d0c30b6c-2317-448c-b822-320b53be3aec.mp4

Since anything which overflows the tile is set to be hidden globally, the issue that close button is cut off on a narrow UI is out of scope of this PR.

type: enhancement

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

---
Here's what your changelog entry will look like:

## ✨ Features
 * Improve LinkPreviewWidget ([\#8881](https://github.com/matrix-org/matrix-react-sdk/pull/8881)). Fixes vector-im/element-web#22634. Contributed by @luixxiul.

### CODE REVIEW

**Review by weeman1337 — COMMENTED** [review]
Hi @luixxiul thank you for your contribution.

For what reason did you introduce `mx_LinkPreviewWidget_wrap`? A quick test showed, that all required styles can be assigned to `mx_LinkPreviewWidget`. Can you check this again? Less nesting/DOM elements is always better.

**Comment by luixxiul** [comment]
you're right, I've misunderstood the structure (w/o intention of making DOM tree more complex than necessary :-D)

**Comment by luixxiul** [comment]
@weeman1337 I'm going to change the class name to explain what it is required for.

**Comment by weeman1337** [comment]
Hey @luixxiul I wonder if we should not better reorganise the elements to use the available space in a more efficient way:

image

What do you think?

**Comment by luixxiul** [comment]
That looks a fantastic plan but it requires modification of `mx_EventTile_content`'s right margin (34px) outside of `LinkPreviewGroup`, which should be addressed by another PR with wider scope, in order to improve the space usage on EventTile overall.

Removing the right margin from `LinkPreviewWidget` (16px) could be a starting point, though.

**Comment by weeman1337** [comment]
Before the PR the first layout made better use of the space…

image

Can you file an issue for that as a follow-up please @luixxiul ? I will then approve this one because it improves in the way that the text is visible in narrow layouts.

**Comment by luixxiul** [comment]
Ah, the space was added with `column-gap`. I will replace it something else.

**Comment by weeman1337** [comment]
Ok. If you have finished re-request review. Just adding changes requested to get it off my list for now :wink:

**Review by weeman1337 — COMMENTED** [review]
Ok. If you have finished re-request review. Just adding changes requested to get it off my list for now :wink:

**Review by weeman1337 — APPROVED** [review]
LGTM now, thank you :+1:

**Comment by luixxiul** [comment]
@weeman1337 Thanks for reviewing.

**Pull request merged**
