### PR TITLE
Comply with noImplicitAny

### PR DESCRIPTION
**Pull request by t3chguy**
Requires https://github.com/matrix-org/matrix-js-sdk/pull/3079
For https://github.com/vector-im/element-web/issues/21968

Doesn't enable noImplicitAny yet due to it needing strictNullChecking to resolve

image

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]
All looks very sensible to me, so long as the strict errors github is showing are ok?

**Comment by t3chguy** [comment]
Blocked on https://github.com/vector-im/element-web/issues/21967

**Review by andybalaam — APPROVED** [review]
I haven't re-checked every file, but still looks good to me.

**Comment by t3chguy** [comment]
Blocking until after RC cut for stability

**Pull request merged**
