### PR TITLE
Fix some issues with threads rendering

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/21670

The alignment of info events mainly pertains to "show hidden events" but also gives better use of space to event list summaries which will only show up for Redactions without the development setting enabled.

@janogarcia as you could reproduce this, could you test using the Netlify please

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix some issues with threads rendering ([\#8305](https://github.com/matrix-org/matrix-react-sdk/pull/8305)). Fixes vector-im/element-web#21670.

Preview: https://pr8305--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by janogarcia — CHANGES_REQUESTED** [review]
> @janogarcia as you could reproduce this, could you test using the Netlify please

Sure (it's taking ages to download but soon I'll be on Safari 15.4). The hardcoded white color is now failing on dark mode.

Element  4  | 🧪 Playground Non-encrypted

It's a shame we can't perform this color manipulation programmatically/dynamically without introducing new color variables or hardcoded stuff.

**Comment by t3chguy** [comment]
> The hardcoded white color is now failing on dark mode.

Argh of course, because it intepolates the colour as well as the alpha 🤦 

Will introduce a new colour variable, it'll probably break all existing custom themes though

**Comment by janogarcia** [comment]
👍 Will test it as soon as the updated Netlify build gets deployed. What's the best way to know when it's ready?

Fix some issues with threads rendering by t3chguy · Pull Request #8305 · matrix-org-matrix-react-sdk
?

**Comment by janogarcia** [comment]
It seems it's been deployed already. Looking great on both themes! 👍

**Review by janogarcia — APPROVED** [review]

**Review by jryans — APPROVED** [review]

**Pull request merged**
