### PR TITLE
Fix incoming call box on dark theme

### PR DESCRIPTION
**Pull request by dbkr**
Will make another PR to the release branch too

Fixes https://github.com/vector-im/element-web/issues/16040

### CODE REVIEW

**Comment by SimonBrandner** [comment]
@dbkr This fixes [#16040](https://github.com/vector-im/element-web/issues/16040), right?

**Comment by dbkr** [comment]
Oh, in fact it is that bug - will update description

**Comment by t3chguy** [comment]
Presumably design has signed off on the colour change here?

**Review by t3chguy — APPROVED** [review]
LGTM in terms of code

**Pull request merged**
