### PR TITLE
Support changing your integration manager in the UI

### PR DESCRIPTION
**Pull request by turt2live**
Fixes vector-im/riot-web#10161 (this is the last of the PRs in the series for this issue)

Known missing from this PR:
* Terms handling (see https://github.com/vector-im/riot-web/issues/10539)
* The tooltip is the wrong size (destined for a future PR, probably the one which fixes 10539)
* Unresolved TODO comments (destined for a future PR)

**Based upon**:
* ~~https://github.com/matrix-org/matrix-react-sdk/pull/3301~~ merged
* ~~https://github.com/matrix-org/matrix-react-sdk/pull/3302~~ merged
* ~~https://github.com/matrix-org/matrix-react-sdk/pull/3300~~ merged

~~**Changeset: https://github.com/matrix-org/matrix-react-sdk/pull/3308/commits/03d735f4ed03fd3692bf02fdb17eeead490d0239**.~~ changed

Gif:
integration-manager-change mp4

### CODE REVIEW

**Comment by turt2live** [comment]
I'll adopt the use of the mixin and leave fixing it for https://github.com/vector-im/riot-web/issues/10554 (which I also plan to take on, just not here)

**Comment by turt2live** [comment]
@dbkr I've switched this over to using vector-namespaced widget types to avoid having to put MSC1957 through the queue (we only use about a third of it). Please take a quick look.

**Comment by dbkr** [comment]
Bleugh, then people will end up with this `im.vector.integration_manager` in the wild and we'll have to worry about the transition. I think that will ultimately make life even more complex. I'd rather not have it kicking around if at all possible - even if we have to disable this until the MSC is through.

**Comment by turt2live** [comment]
I'll just get the MSC through the process and start writing up the implementation we're missing.

**Comment by turt2live** [comment]
@dbkr done - now just not using vector-namespaced things

**Comment by dbkr** [comment]
Thanks - I've made the MSC slightly closer!

**Pull request merged**
