### PR TITLE
Change a bunch of strings from Recovery Key/Phrase to Security Key/Phrase

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/element-web/issues/15500

Improves https://github.com/vector-im/element-web/issues/14421

### CODE REVIEW

**Review by jryans — CHANGES_REQUESTED** [review]
Thanks for this clean up, overall it looks great! Just a few further tweaks, and then it should be ready to merge.

**Comment by aaronraimist** [comment]
Okay that is fixed

**Comment by jryans** [comment]
> Okay that is fixed

Thanks, sorry for the delay, I am quite behind on notifications. Re-requesting review like you just did is the best way for me to see it promptly. 😄

**Review by jryans — APPROVED** [review]
Thanks again for working on this, I think it will help comprehension quite a lot! 😄

**Pull request merged**
