### PR TITLE
docs: added comment explanation

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Fixes vector-im/element-web#8008
I've added a comment explaining that logged in state also included guest users. Please let me know if something else needs to be done. Thanks.

Signed-off-by: Arsh Sharma arshsharma461@gmail.com

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
This seems fine to me. @jryans if this doesn't solve your concern reasonably enough for the longer term, please open a new issue (or reopen the referenced one here).

**Comment by turt2live** [comment]
@RinkiyaKeDad this needs sign-off so we can merge it.

**Comment by RinkiyaKeDad** [comment]
@turt2live signed please check now.

**Comment by turt2live** [comment]
awesome, thanks!

**Pull request merged**
