### PR TITLE
Edit button on View Source dialog that takes you to devtools -> SendCustomEvent

### PR DESCRIPTION
**Pull request by panoschal**
Requires https://github.com/matrix-org/matrix-react-sdk/pull/5713

Added an Edit button, which for State Events:
image
takes you to SendCustomEvent with prefilled details:
image

This is convenient for users that want to change the room state.

For a normal event (not a State Event):
image
it takes you to SendCustomEvent with an `m.replace` event prefilled:
image

This makes it easy to test the message edit.

[Docs for message editing](https://github.com/uhoreg/matrix-doc/blob/aggregations-edits/proposals/2676-message-editing.md)

I fill the current event both on the top level and in `m.new_content`, and I set the correct event_id.

I reuse the `SendCustomEvent` component, and change it in-place in the View Source dialog. Clicking back takes you to the View Source component. Another option would be to open the DevtoolsDialog and deep link there, so that the Back button takes you to the other devtools components.

Works with events from both encrypted and unencrypted rooms.

Closes https://github.com/vector-im/element-web/issues/6429
Closes https://github.com/vector-im/element-web/issues/11397
Closes https://github.com/vector-im/element-web/issues/10140 although this was working correctly even before my changes

Signed-off-by: Panagiotis Chalimourdas <panagiotis4531@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
/me beat @SimonBrandner to react on a PR for once :D

**Comment by panoschal** [comment]
A question remains as to when we should show the Edit button. Currently, for message events I show it when the user has permissions to edit it, but for state events I show it in every case. We can add the extra complexity to check for power level permissions for state events, or we can have it displayed everywhere. 

In any case, the SendCustomEvent dialog, the user can change the event type, so I'm not sure weather checking at the beginning is relevant.

**Comment by t3chguy** [comment]
There's a method on js-sdk called `maySendStateEvent` or something such that should make that really easy for state events

**Comment by panoschal** [comment]
Alright I'll check this

**Review by jryans — APPROVED** [review]
Thanks for working on this, it looks great to me! 😄

**Comment by jryans** [comment]
@panoschal Oh, I suppose there's a conflict to resolve, so re-request review from me once that's done.

**Comment by panoschal** [comment]
oops done

**Pull request merged**
