### PR TITLE
Aligned and spaced labels and switches.

### PR DESCRIPTION
**Pull request by ankur12-1610**
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>

Fixes: [#20044](https://github.com/vector-im/element-web/issues/20044)

Before:
element-preference

After:

issue-sol

---
Here's what your changelog entry will look like:

## ✨ Features
 * Aligned and spaced labels and switches. ([\#7285](https://github.com/matrix-org/matrix-react-sdk/pull/7285)). Contributed by @ankur12-1610.

Preview: https://61abe9bd238b953a281537e8--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by gsouquet — CHANGES_REQUESTED** [review]
That looks good to me from a code point of view. Thank you for working on that

For consistency I'd try to follow what the "Security & Privacy" panel does and bring the appearance as close to the "Devices list" as this is likely what the design team will raise

**Comment by ankur12-1610** [comment]
> That looks good to me from a code point of view. Thank you for working on that
> 
> For consistency I'd try to follow what the "Security & Privacy" panel does and bring the appearance as close to the "Devices list" as this is likely what the design team will raise

Yeah, sure. Np :)

**Comment by ankur12-1610** [comment]
> That looks good to me from a code point of view. Thank you for working on that
> 
> For consistency I'd try to follow what the "Security & Privacy" panel does and bring the appearance as close to the "Devices list" as this is likely what the design team will raise

Sorry to disturb you, did the design team review it? :sweat_smile:

**Comment by amshakal** [comment]
Hi there, thanks for working on this. Just to double check, what padding have you given between two lines? I'd ask you to make it 8px for consistency with the rest of the platform. Adding a screenshot for reference:
Screenshot 2022-01-12 at 5 21 53 pm
)

**Comment by ankur12-1610** [comment]
> Hi there, thanks for working on this. Just to double check, what padding have you given between two lines? I'd ask you to make it 8px for consistency with the rest of the platform. Adding a screenshot for reference: Screenshot 2022-01-12 at 5 21 53 pm )

@amshakal I didn't give any padding I have used flexboxes:sweat_smile:, I'll give padding of 8px.

**Comment by t3chguy** [comment]
@ankur12-1610 have you had chance to address Amsha's review?

**Comment by ankur12-1610** [comment]
> @ankur12-1610 have you had chance to address Amsha's review?

@t3chguy @amshakal I tried to add padding to `8px` but it was a lot of spacing and was not matching with other polls like the `Lab` ones. I have used flexboxes previously in the Lab polls which actually got merged.

Here is the comparison between flexboxes and adding padding to them: 
Component 9 (1)

**Comment by amshakal** [comment]
Hi there, that's a bit odd. Our current implemented designs on pages within settings with a lot of switches like Notifications have been designed with a 8px padding like the image I shared. Your flexbox implementation looks more in line with what I shared above than the 8px padding one. I just wanted to confirm what the distance between two elements was in pixels to keep it consistent with the rest of the pages.

**Comment by ankur12-1610** [comment]
> Hi there, that's a bit odd. Our current implemented designs on pages within settings with a lot of switches like Notifications have been designed with a 8px padding like the image I shared. Your flexbox implementation looks more in line with what I shared above than the 8px padding one. I just wanted to confirm what the distance between two elements was in pixels to keep it consistent with the rest of the pages.

The scss file([link](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/css/views/settings/tabs/user/_NotificationUserSettingsTab.scss#:~:text=margin%2Dbottom%3A%2010px%3B%20//%20Give%20some%20spacing%20between%20the%20title%20and%20the%20first%20elements)) of Notificiations tab has `margin-bottom: 10px` used in it. So should I use it?

Also, I just took a look at Preferences tab right now and it looks completely fine. Ig the issue is already being solved then ;)
Cause they were not properly spaced when I created this issue :sweat_smile: 
Screenshot from 2022-05-12 16-10-00

**Comment by amshakal** [comment]
I saw that too right after writing my comment :D

**Comment by ankur12-1610** [comment]
> I saw that too right after writing my comment :D 

I'll close the PR and issue then :)

**Pull request closed without merging**
