### PR TITLE
Group Labs flags

### PR DESCRIPTION
**Pull request by t3chguy**
image
image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Group Labs flags ([\#7190](https://github.com/matrix-org/matrix-react-sdk/pull/7190)).

Preview: https://619fb7982897360075eb4957--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
👍 on the layout, no objections

**Review by dbkr — APPROVED** [review]
A thousand times yes.

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
Just a small suggestion:

I think having an Other isn't very helpful, could we break that up into the following:

Message previews
- Show message previews for reactions in DMs
- Show message previews for reactions in all rooms

Themes
- Support adding custom themes

Encryption 
- Offline encrypted messaging using dehydrated devices

**Comment by t3chguy** [comment]
Updated as per review, see updated screenshots

**Review by niquewoodhouse — APPROVED** [review]
💪

**Pull request merged**
