### PR TITLE
Add tooltips to message previews

### PR DESCRIPTION
**Pull request by robintown**
Closes vector-im/element-web#16922.

### CODE REVIEW

**Comment by turt2live** [comment]
@robintown is it possible to get a screenshot of what this looks like? Thanks!

**Comment by robintown** [comment]
tooltip

**Review by turt2live — APPROVED** [review]
code looks fine, though I'm going to double check with Design to see if we prefer the OS/browser tooltips or our own

**Comment by nadonomy** [comment]
@turt2live I'd advocate for us to use the browser tooltips— they benefit from higher information density which seems desirable for this interaction, and they'll be better stress tested when handling longer messages etc.

**Comment by ara4n** [comment]
accessibilitywise native tooltips should work better too, and are lighter weight in terms of DOM footprint.

**Comment by robintown** [comment]
(In case it's not clear, that is a native tooltip in the screenshot, my OS just styles it similarly to Element's custom tooltips)

**Comment by turt2live** [comment]
Thanks for taking a look, all.

**Pull request merged**
