### PR TITLE
Add redesigned dark theme

### PR DESCRIPTION
**Pull request by jryans**
This adds the new unified palette to the dark theme to define a few top level colors and let those flow down to the more specific color names. It also updates some global colors (like accent) that are the same for all themes. Many more icons are also converted to mask in CSS approach to support easy theming.

image

Used in https://github.com/vector-im/riot-web/pull/8540
Implements the bulk of https://github.com/vector-im/riot-web/issues/7578

### CODE REVIEW

**Comment by aaronraimist** [comment]
screen shot 2019-02-12 at 5 30 25 pm
It would be nice to use a white [M] logo here

**Comment by aaronraimist** [comment]
Also the LLP is still using a black scroll bar for me

**Comment by aaronraimist** [comment]
screen shot 2019-02-12 at 5 36 41 pm
Should there be a vertical line here?

**Comment by aaronraimist** [comment]
screen shot 2019-02-12 at 5 40 55 pm

On the Create Community page, it is quite hard to read the + and domain

**Comment by aaronraimist** [comment]
screen shot 2019-02-12 at 5 52 58 pm
"Enter a passphrase..." is hard to read

**Comment by aaronraimist** [comment]
Editing an event in developer tools is hard to read
screen shot 2019-02-12 at 5 56 16 pm

**Comment by aaronraimist** [comment]
screen shot 2019-02-12 at 6 04 09 pm
The markdown button status appears to be reversed

**Comment by ara4n** [comment]
@nadonomy in terms of feedback on the overall theme design, i think we also need to make the hairlines more visible for dragging purposes - plus i wonder if we're too high contrast, at least for a dark theme, especially when compared with the old dark theme.  This feels more like a black theme to me?

I wonder whether the less contrasty primary bg/fg colours from jouni's mockup might be helpful:

screenshot 2019-02-12 at 17 39 19

**Comment by nadonomy** [comment]
> @nadonomy in terms of feedback on the overall theme design, i think we also need to make the hairlines more visible for dragging purposes - plus i wonder if we're too high contrast, at least for a dark theme, especially when compared with the old dark theme. This feels more like a black theme to me?
> 
> I wonder whether the less contrasty primary bg/fg colours from jouni's mockup might be helpful:
> 
> screenshot 2019-02-12 at 17 39 19

Increasing the legibility of the hairlines is a no brainer but let's chat more on Riot about the overall darkness and fg/bg colours as they're extremely multifactorial (unifying accent colours across themes, platforms and branding, avoiding 'shoulder surfing' similarity to Discord, Ryan's comp is taken in FF which has heavier font rendering, exacerbating the contrast compared to the Sketch comp with lighter weights and 40% negative space... etc).

**Comment by jryans** [comment]
Thanks @aaronraimist for the early feedback! I had addressed some of the issues in this branch:

* Composer icons (markdown disabled still needs some work though)
* `<textarea>`, `<input>` text / placeholder color
* Prefix / suffix on create community

For the others, let's track them elsewhere so the feedback isn't lost.

**Pull request merged**
