### PR TITLE
Add a note to use the desktop builds when seshat isn't available

### PR DESCRIPTION
**Pull request by turt2live**
Fixes https://github.com/vector-im/element-web/issues/15184

This is currently temporary design for https://github.com/vector-im/element-web/issues/12896 but does not fix it.

Documentation is left for https://github.com/vector-im/element-web/pull/15190 to figure out

image
image
image
image

### CODE REVIEW

**Comment by t3chguy** [comment]
How does it look with some results, the ones from before it became encrypted

**Review by t3chguy — APPROVED** [review]
LGTM otherwise

**Comment by turt2live** [comment]
> How does it look with some results, the ones from before it became encrypted

exactly the same, which is the intention.

**Comment by turt2live** [comment]
just double checking this is safe to land as-is with design

**Comment by ara4n** [comment]
This copy implies that web can’t view encrypted files at all, which is untrue.

I’d suggest “...use the desktop app to view the encrypted file list” and “does not support viewing the encrypted file list”.

**Comment by nadonomy** [comment]
> This copy implies that web can’t view encrypted files at all, which is untrue.

Good point.

> I’d suggest “...use the desktop app to view the encrypted file list” and “does not support viewing the encrypted file list”.

Just to exercise more brevity what about "Use the desktop app to see all encrypted files"?

**Comment by turt2live** [comment]
@nadonomy that works for me :D

**Comment by turt2live** [comment]
@nadonomy I've also changed the copy for when there's no desktop builds to be "... viewing some encrypted files".

**Review by nadonomy — APPROVED** [review]

**Pull request merged**
