### PR TITLE
Add a checkpoint to index newly encrypted rooms.

### PR DESCRIPTION
**Pull request by poljar**
This intends to fix https://github.com/vector-im/riot-web/issues/13682, it waits for `m.room.encryption` events in the timeline and indexes a room if one is received. Though if a limited timeline was received the `m.room.encryption` event will be missed.

A suggestion was made to use the `RoomState.events` event and catch a `m.room.encryption` event there, but due to the way our locally cached sync gets stored/restored that event will be fired every time Riot gets started.

Suggestions on how to handle a limited sync there are welcome.

### CODE REVIEW

**Comment by dbkr** [comment]
Hmm, but won't this equally apply to rooms that have an `m.room.encryption` event in recent history when starting up, ie. the event will still get replayed? Using RoomState.events does sound like the correct answer, but you will need to check whether you've already started indexing a room. You'll also need to ensure the room is actually encrypted as this will just look for an encryption event with any algorithm which could be one we don't understand. Hopefully you can do this by checking isRoomEncrypted (if that's up to date when you get the event).

**Comment by poljar** [comment]
> Hmm, but won't this equally apply to rooms that have an `m.room.encryption` event in recent history when starting up, ie. the event will still get replayed? 

I don't think I observed that happening, but will re-check.

> Using RoomState.events does sound like the correct answer, but you will need to check whether you've already started indexing a room. 

That's a bit annoying, that'll need a new method in Seshat but I guess other people might find it useful as well.

**Comment by jryans** [comment]
@poljar Do you plan to revise this, or were you waiting for a review here? I wasn't sure if the above:



> That's a bit annoying, that'll need a new method in Seshat but I guess other people might find it useful as well.

...meant you would revise this to address that, or if you see it as future work...?

**Comment by poljar** [comment]
I meant that I'll add the feature to Seshat and I'll update this PR after Seshat gets support. It's just a bit stuck behind getting the paginated search going and keeping the rust-sdk rolling.

**Comment by jryans** [comment]
Okay, for now I'll clear the review request here then.

**Comment by poljar** [comment]
This has now been updated, it requires the following PRs:
https://github.com/matrix-org/seshat/pull/65
https://github.com/vector-im/riot-web/pull/13957
https://github.com/vector-im/riot-desktop/pull/100

Also a Seshat release will be required.

**Pull request merged**
