### PR TITLE
Hide composer buttons if we can't send events

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/20903
Type: defect
Notes: none

---
This change has no change notes, so will not be included in the changelog.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Looks sane to me!
I can not remember whether this used to behave that way or whether this is introducing a new behaviour. Holding off from merging until I find the answer, might have to request a design review

**Comment by t3chguy** [comment]
I think this isn't quite right as you may be able to send stickers but not other things

**Comment by SimonBrandner** [comment]
> I think this isn't quite right as you may be able to send stickers but not other things

Argh, /me never understood why stickers were an event type instead of a message type. I wonder what would be the best way to solve this without making the code unnecessarily complicated

**Comment by t3chguy** [comment]
Tbh I think the check is broken altogether, because it doesn't account for encryption. `Room::EventType.RoomMessage` always checks `m.room.message` perms when it might be `m.room.encryption`

**Comment by SimonBrandner** [comment]
So `Room::maySendMessage()` is wrong yet we use it in several places? /me is a little confused :sweat_smile:

**Comment by t3chguy** [comment]
Indeed, it might predate encryption :P

**Comment by SimonBrandner** [comment]
With https://github.com/matrix-org/matrix-js-sdk/pull/2159 merged, the situation is now better but we still don't handle stickers

**Pull request merged**
