### PR TITLE
Iterate Spaces admin UX around room management

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/17176

image
image
image

### CODE REVIEW

**Review by jryans — APPROVED** [review]

**Comment by niquewoodhouse** [comment]
@t3chguy looks great, I just have 4 notes:

- ~Position of settings cog~
   -  ~Not a big deal but finding it's unbalancing things because it's moving the invite button depending on if I'm an admin of the space or not.  I think next to the space name makes more sense for the current layout.~ Lets wait for more feedback from beta
- Disabled state of management buttons
  - The hollow opaque style feels like it might not be very accessible.  Maybe this is a global issue across Element(?) and not something to fix here.  If it is global, I can take that as a design issue, let me know.
  - Sizing of buttons
    - Now I see the buttons more often I'm finding the different sizes of the buttons a bit awkward.  I think it's caused by different paddings on the buttons causing different heights making the View button bigger.  Maybe it's not relevant to this issue but consistent sizing might be nice.  Again, if a global thing, can pick up seperately.
image
- View room interaction
  - When I tap the view button, the room becomes selected and I'm redirected to the room. Just found it jarring but probably fine for a beta.

**Comment by t3chguy** [comment]
>  If it is global, I can take that as a design issue, let me know.

It is indeed global, its a button `kind=primary_outline` and `kind=danger_outline` but disabled

will fix the button size issue and the untrapped behaviour of the join button click

**Review by niquewoodhouse — COMMENTED** [review]
All looks resolved, it's just this 1 button is 31px for some reason?

It would just be great if possible if it was equal to the others.  

image

**Comment by t3chguy** [comment]
Its 32px here :L

image

I'll give it an explicit rem line-height which should make it more consistent

**Comment by t3chguy** [comment]
Fixed it for that specific button but a more general solution would be good in the future - opened https://github.com/vector-im/element-web/issues/17197 to track it

**Review by niquewoodhouse — APPROVED** [review]

**Pull request merged**
