### PR TITLE
Prohibit WebRTC call when permissions are insufficient

### PR DESCRIPTION
**Pull request by enzingerm**
This PR forbids a user to start a WebRTC call in rooms with 2 participants when his power level is not sufficient to send `m.call.invite` events.

### CODE REVIEW

**Review by turt2live — DISMISSED** [review]
we talked about this briefly on a call with the team, and we think it'd be good to check for all the event types involved in calls because it'd suck real bad if you can start a call but can't continue it.

Also sorry - we converted this file to typescript and created a nasty conflict :(

**Review by turt2live — APPROVED** [review]
Code seems sane, though design may want to take a look at the error dialog to change the copy and give it a title.

**Comment by nadonomy** [comment]
@dbkr @simonkeane can I defer to you for input on the error copy in this PR as you'll likely have better context.

**Comment by dbkr** [comment]
I'd probably add, "in this room" to clarify it's rooms-specific. Also we tend to use 'permission' rather than 'authorised' (bit less formal / technical) so I'd say maybe, "You don't have permission to place a call in this room".

**Comment by turt2live** [comment]
@enzingerm are you able to take dbkr's feedback into account on this?

**Pull request closed without merging**
