### PR TITLE
Add optional search shortcut

### PR DESCRIPTION
**Pull request by SimonBrandner**
This PR adds the optional ability to open search be pressing <kbd>Ctrl</kbd><kbd>F</kbd>

### CODE REVIEW

**Comment by t3chguy** [comment]
Overriding browser shortcuts isn't typically desirable

**Comment by SimonBrandner** [comment]
@t3chguy This crossed my mind. But I thought that since this is a web app it's ok to overwrite it. I can definitely make it opt-in or make it work only in Electron. Should I?

**Comment by SimonBrandner** [comment]
If it were up to me, I'd make it opt-out, and the setting would appear only on the web.

**Review by jryans — APPROVED** [review]
Thanks, I think this seems sensible and safe enough to land, especially since it's opt-in.

**Pull request merged**
