### PR TITLE
Load audioWorklet in a Webpack 5 compatible way

### PR DESCRIPTION
**Pull request by Johennes**
For: https://github.com/vector-im/element-web/pull/26229

We currently use worklet-loader but it isn't designed to work with Webpack 5. The [built-in](https://github.com/webpack/webpack.js.org/issues/6869) worklet support in Webpack 5 requires the use of URLs in the `addModule` call alongside special configuration.

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]

**Comment by Johennes** [comment]
Ah, looks like the dead code scanner doesn't recognize the imports within the worklet as used anymore now. 🤦‍♂️

Will have to look into that.

**Comment by Johennes** [comment]
I'm actually not sure how to properly fix the dead code issues. The problem is that after switching to loading the worklet using its literal path, we don't require the worklet import anymore but without the import the worklet is considered dead code.

If we could specify the worklet as an entry for the dead code analysis, that should fix it but ts-prune doesn't support specifying entries manually from what I can see (though its successor https://github.com/webpro/knip does).

Alternatively, we could also add ignores for the seemingly unused symbols but feels whack-a-mole-ish given that we'll have the same problem with web workers once we ditch worker-loader.

@t3chguy any thoughts on how to proceed here?

**Comment by t3chguy** [comment]
@Johennes could we not trick it by keeping the import and not just not using it with an eslint ignore & ts-ignore for the time being

**Comment by Johennes** [comment]
That would also work. All of these options feel like they have downsides but maybe this would be the easiest one.

**Comment by Johennes** [comment]
Upon further testing, turns out that this doesn't actually work. 😔

Screenshot 2023-11-09 at 21 48 02

Guess this will need some more fiddling.

**Comment by Johennes** [comment]
This now works with Webpack 5 but due to the use of `import.meta.url` doesn't work with Webpack 4 anymore and, like https://github.com/matrix-org/matrix-react-sdk/pull/11860, breaks tests because of the missing mock.

**Comment by Johennes** [comment]
I'm gonna close this in favor of https://github.com/matrix-org/matrix-react-sdk/pull/11860 in which I have merged this pull request. There is a lot of overlap between these two and both will have to land in concert with https://github.com/vector-im/element-web/pull/26229.

**Pull request closed without merging**
