### PR TITLE
Fix paragraph regression which began in 0.14

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/6523
Fixes https://github.com/vector-im/riot-web/issues/6457

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by dbkr** [comment]
Do we know how this regressed?

**Comment by t3chguy** [comment]
I feel like it was https://github.com/matrix-org/matrix-react-sdk/commit/4f4441fb07dcdfb831e4b54b9f8d7e611c172f29

**Comment by t3chguy** [comment]
I feel like it was https://github.com/matrix-org/matrix-react-sdk/commit/4f4441fb07dcdfb831e4b54b9f8d7e611c172f29

**Comment by lukebarnard1** [comment]
This isn't the right fix - we end up with double new lines for plain messages with newlines but without emojis.
2018-04-23-155225_208x119_scrot
^ the above shows the same message twice, but with the emoji not sent in the second one

**Comment by lukebarnard1** [comment]
In fact, the real reason for the above screenshot being possible is because we apply the CSS class `markdown-body` in the message with emoji (because we insert emoji with HTML), which includes the rule `white-space: normal;`. 

Apparently, with `white-space: normal`, "Sequences of whitespace are collapsed..." including newline characters.

Using `white-space: pre-wrap` might be a solution (which is what .mx_MTextBody defines) , but it would be worth:
 - testing this in a whole world of different cases
 - finding out why we're using `white-space: normal` (perhaps something to do with wrapping? or overflowing?)
 - writing a bunch of unit tests for EventTile :hearts:

**Pull request closed without merging**
