### PR TITLE
Changes to url preview formatting and image upload thumbnail size

### PR DESCRIPTION
**Pull request by williamkray**
I've made these changes to appease my users and make the interface a bit more slack-like. The changes are:

+ Image upload thumbnails:
  - Shrink the size of the displayed thumbnail down to a max height of 240px to prevent image uploads from taking over the entire screen
+ URL previews:
  - Grow image thumbnail to 320x240 px for a better view
  - Max width of the preview widget to 360px
  - Preview widget has vertical flow rather than horizontal for less sprawl
  - Preview "close" button moved to the top with a little padding to look nice

A few screenshots of what this looks like in real life:
Screenshot_20201201081215
Screenshot_20201201081246
Screenshot_20201201080902

Signed-off-by: William Kray <github@williamkray.com>

### CODE REVIEW

**Comment by jryans** [comment]
@williamkray Could you merge the latest changes from the develop into your PR branch? This should resolve the CI test failure, and also Netlify should [add a preview site](https://github.com/vector-im/element-web/blob/develop/docs/pr-previews.md) to this PR, which may be helpful for Product review here.

**Comment by williamkray** [comment]
realizing that this change might not be everyone's taste, it might be nice to add a toggle to enable this format in user preferences, however i haven't looked into how to do that.

**Comment by jryans** [comment]
@williamkray Hmm, looks like the preview build failed a while back... Could you try another round of merging develop? Hopefully that will get it going. I'll queue this for Design review as well.

**Comment by williamkray** [comment]
i just merged in my develop branch, but i think i may have busted it a bit... i forgot i had merged some other things into my develop branch from upstream when trying to put a package together.

take a look at the commits and make sure i'm not including anything that isn't supposed to be there, i'm happy to close this PR and create a new cleaner one if needed!

**Comment by jryans** [comment]
@williamkray Hmm, something is still not quite right with the merge it seems... For example, the "files changed" view here should not show the changelog, package.json, yarn.lock, etc. changes as those are unrelated to your work.

**Comment by williamkray** [comment]
@jryans I'm not sure why it's doing that, when I try to recreate this exact pull request it doesn't show those changes. I've gone ahead and created a fresh branch and cherry-picked my commits here: https://github.com/matrix-org/matrix-react-sdk/pull/5637

**Comment by jryans** [comment]
Thanks, I'll close this one then.

**Pull request closed without merging**
