### PR TITLE
Move style rules of MatrixChat_useCompactLayout from _GroupLayout.scss to _EventTile.scss and _RoomView.scss

### PR DESCRIPTION
**Pull request by luixxiul**
This PR moves the style rules of `MatrixChat_useCompactLayout` from `_GroupLayout.scss` to `_EventTile.scss` and `_RoomView.scss`.

Since those declarations are not used to style elements of the group layout exclusively, they should be moved to corresponding SASS files. With #8711 `_GroupLayout.scss` is going to be removed.

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by weeman1337 — APPROVED** [review]
Thank you for your contribution :slightly_smiling_face: 

Tested on the Netlify deployment. The layout still looks good :heavy_check_mark:

**Comment by lieuwex** [comment]
Is it possible that this PR increased the padding and/or margins ever so slightly? I use develop.element.io and I feel like the messages are just a bit more separated.

**Comment by luixxiul** [comment]
I am not sure whether the change has been applied to develop.element.io, but it is possible to dig deeper if you could either provide a screenshot or point out which elements are affected.

Basically this PR fixed the issue that style blocks for EventTile have scattered over multiple files, and it might have changed how style rules are inherited. In this case the issue has been hidden unintentionally.

**Comment by weeman1337** [comment]
> Is it possible that this PR increased the padding and/or margins ever so slightly? I use develop.element.io and I feel like the messages are just a bit more separated.

Going to check that…

**Comment by weeman1337** [comment]
Good spot @lieuwex . Looks like the PR broke the compact layout:

image

**Comment by luixxiul** [comment]
ach it is annoying to see this kind of regression happens only by moving style rules to the file which they should belong...

**Pull request merged**
