### PR TITLE
Fix page up/down scrolling only half a page

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/element-web/issues/3763

### CODE REVIEW

**Comment by grahamperrin** [comment]
Thank you …

**Comment by grahamperrin** [comment]
`0.9` of a page feels/looks good to me. 

----

As far as I can tell, the only oddity, and this is out of scope, is when not enough of the next page is 'buffered' before paging down. When there's relatively little space between the foot of the scroller and the foot of the scrollbar. 

Like, the lowest line of text becomes uppermost (or near uppermost) ☑ momentarily, then a bounce back of around half a page, leaving the line near mid-screen. 

This was not a frequent occurrence. It might occur only when speed-reading. I did not attempt to make it reproducible, but if I recall correctly: when the ~half-page bounce occurs, the next <kbd>Page Down</kbd> will 'revert' the bounce (i.e. ~half a page down) then subsequent strokes of <kbd>Page Down</kbd> will behave normally (`0.9`).

**Comment by grahamperrin** [comment]
Now testing with [Scroll Position Highlight](https://addons.mozilla.org/addon/scroll-position-highlight/) added to Firefox `88` …

**Review by turt2live — APPROVED** [review]

**Comment by grahamperrin** [comment]
Please, how long might it take for this to reach the production server(s)? 

Not chasing, just curious. Thanks. 

In the meantime I'm using a staging server

**Comment by t3chguy** [comment]
See topic of #element-web:matrix.org

image

**Comment by grahamperrin** [comment]
`/me` thanks @t3chguy and switches from the _deploy-preview_ server to https://develop.element.io/

**Comment by grahamperrin** [comment]
👍 before and after a <kbd>Page Down</kbd> in `#freenode_#freebsd-bugs:matrix.org`

**Pull request merged**
