### PR TITLE
Reduce save-restore window in ScrollPanel to reduce scrolling jumps

### PR DESCRIPTION
**Pull request by ollieh**
Hopefully improves: https://github.com/vector-im/riot-web/issues/2646

### CODE REVIEW

**Comment by lukebarnard1** [comment]
So this _seems_ to improve the scroll-jumping and I think it's probably a good way to do it.

**Comment by lukebarnard1** [comment]
Hm. This appears to be causing https://github.com/vector-im/riot-web/issues/4358, where rooms that were previously stuck to the bottom appear scrolled up slightly.

**Comment by ollieh** [comment]
@lukebarnard1 Woops, I'll give it a look in a little bit.

**Comment by lukebarnard1** [comment]
I've reverted this from `develop` for now (57f01b8)

**Pull request merged**
