### PR TITLE
Compact call area, better ui when in call & searching messages

### PR DESCRIPTION
**Pull request by panoschal**
I decreased the size of the call view on small screens, so that it does not need an awkward scrollbar. Due to this, the search box could be hidden, and the user could not understand that he/she had search active.
Fixes https://github.com/vector-im/element-web/issues/16492

Also,
Fixes https://github.com/vector-im/element-web/issues/15922 where a green area was shown.

We can also consider opening the call in PIP mode when the user starts a search, so that the search box is at the top.

Maybe we want to decrease this https://github.com/matrix-org/matrix-react-sdk/commit/fee8d79267484c4ea33116861495bc4fe37c2df9 because now, there is a lot of white area when the search returns no results. (or find another way to fix it)

Before:
image
image
image

After:
image

Signed-off-by: Panagiotis Chalimourdas <panagiotis4531@gmail.com>

### CODE REVIEW

**Comment by SimonBrandner** [comment]
Hopefully, this doesn't cause problems for [#5710](https://github.com/matrix-org/matrix-react-sdk/pull/5710)...

**Comment by panoschal** [comment]
I guess the smaller CallView doesn't make sense because it will be resizable.
I will fix conflicts when we merge https://github.com/matrix-org/matrix-react-sdk/pull/5710

**Comment by panoschal** [comment]
This is ready now. 
I removed the height adjustment I did in the beginning because now we have #5710

**Review by turt2live — CHANGES_REQUESTED** [review]
Thanks for working on this! The code appears to be doing a thing, though it's hard to see at a glance how it fixes the issue. Somewhere in the PR is it possible to get a description as to how making the status bar conditional changes the CSS behaviour? Specifically, I'm concerned that there's no actual CSS being applied here to fix a component sizing issue.

**Comment by panoschal** [comment]
I reverted the CSS changes because we have #5710 and the user can adjust the height manually. We may want to decrease the initial height in small screens though, but I didn't do it here.

Now the only thing left is the conditional statusBarArea which fixes this problem with the green area.

image

**Review by turt2live — DISMISSED** [review]
This still needs a description as to how the changes actually fix the issue. The screenshots help quite a bit, but it's unclear to me why making the status bar conditional will fix the call view, as surely once the user ends up with a status bar it'll just break in the same way over again.

Can we get comments in the code for why we're specifically doing things?

**Comment by panoschal** [comment]
Added a comment explaining the conditional. 

The area is now white instead of green due to css changes in other PRs, but it still takes up unnecessary space and is ugly on small screens when there is an active call & search results.

As for
> as surely once the user ends up with a status bar it'll just break in the same way over again.

it will not break because the conditional will be truthy and `statusBarArea` will appear normally on the bottom of the screen.

**Review by turt2live — COMMENTED** [review]
I'm still confused as to how this fixes the issue, given a conditional just puts the issue off until the condition is true again. Sending back to team review in case someone else understands what is going on.

**Comment by panoschal** [comment]
Adding something more:
`statusBar` is set here
```jsx
        let statusBar;
        let isStatusAreaExpanded = true;

        if (ContentMessages.sharedInstance().getCurrentUploads().length > 0) {
            statusBar = <UploadBar room={this.state.room} />;
        } else if (!this.state.searchResults) {
            isStatusAreaExpanded = this.state.statusBarVisible;
            statusBar = <RoomStatusBar
                room={this.state.room}
                isPeeking={myMembership !== "join"}
                onInviteClick={this.onInviteButtonClick}
                onVisible={this.onStatusBarVisible}
                onHidden={this.onStatusBarHidden}
            />;
        }
```
so if there are no uploads and there **are** search results, `statusBar` is falsy.

If this snippet is rendered while `statusBar` is falsy
```jsx
            <div className="mx_RoomView_statusAreaBox">
                <div className="mx_RoomView_statusAreaBox_line" />
                { statusBar }
            </div>
```
then due to 
```css
.mx_RoomView_statusAreaBox {
    margin: auto;
    min-height: 50px;
}
```
it will appear as a 50px-tall white area, which takes unnecessary screen space.

As I said, the problem is now not too important; previously the empty space was green and looked ugly.

**Comment by SimonBrandner** [comment]
Screenshot_20210824_200223

But the parent has `max-height: 0`, so this only seems to decrease the amount of DOM nodes?

**Review by turt2live — APPROVED** [review]
I don't fully understand how this fixes both issues, but other people seem to understand so sending this through. 

The RC is scheduled for Tuesday and this change is somewhat risky (there's a chance that it breaks something else subtle), so I'll land it after that RC is cut for maximum testing time.

**Pull request merged**
