### PR TITLE
General ChatInviteDialog improvements

### PR DESCRIPTION
**Pull request by lukebarnard1**
- Use avatar initial instead of "R" or "?".
- Use Fuse.js to do case-insensitive fuzzy search. This allows for better sorting of results as well as search based on weighted keys (so userId has a high weight when the input starts with "@").
- Added debounce of 200ms to prevent analysis on every key stroke. Fuse seems to degrade performance vs. simple, non-fuzzy, unsorted matching, but the debounce should prevent too much computation.
- Move the selection to the top when the query is changed. There's no point in staying mid-way through the items at that point.

Fixes https://github.com/vector-im/riot-web/issues/2934

### CODE REVIEW

**Comment by lukebarnard1** [comment]
OK, so now fuse has been merged out, `liblevenshtein` is in. The overall feel is that it's faster but the sorting is of much lower quality.

**Comment by ara4n** [comment]
what was the rationale on using liblevenshtein? i thought aviral ended up just using substr() matches in the RTE branch? (based on the convo a few days ago in #riot-dev)

**Comment by lukebarnard1** [comment]
@ara4n I was under the impression that liblevenshtein was what RTE was using for auto complete. The rationale was that I wanted to improve the general case by using something fuzzier than `indexOf`. When it turned out that fuse was too slow, I swapped to liblevenshtein.

### Fuse examples:
gary_miles_fuse
dave_fuse
remmy_fuse
--------------------------
### Libleven examples:
gary_libleven
dave_libleven
remmy_libleven

^ these are just for a vague comparison. Liblevenshtein feels like it's giving a list of spelling corrections. Fuse feels like it's actually fuzzy searching.

**Comment by ara4n** [comment]
https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$14878731671017013PjCAe:matrix.org was the convo in question - i suggest checking whatever aviral actually ended up doing. i wouldn't be surprised if just doing a substring comparison was the fastest!

**Comment by lukebarnard1** [comment]
@ara4n looking at the most recent `rte-fixes` over at @aviraldg/matrix-react-sdk, liblevenshtein is being used. This is what I have based this PR on (now). If @aviraldg is no longer using the "substring" method, then I suggest we do the same here. Also I have no idea what that method is or if considers sorting items.

**Comment by aviraldg** [comment]
I still believe proper fuzzy search would work best, although the criteria used in liblevenshtein and Fuse are less than ideal for the purpose, and in cases slower than desired. So I switched to a simple substring match (like Matthew said) which works well enough for now that RTE can be merged (with my eventual intention being to rewrite it correctly when I have time)

**Comment by lukebarnard1** [comment]
IRL @ara4n and I discussed and we're going to try fuse live on /develop. If that's too slow we'll do a substring matching option which prioritises prefix matches by scoring them higher and prefers user_id matches if the query starts with \@. 

I will re-PR 439bde3

**Comment by lukebarnard1** [comment]
This has been ditched in favour of the new server-side user directory and when that's not available, a simple `indexOf` matching is done across user IDs, display names.

See https://github.com/matrix-org/matrix-react-sdk/pull/1050

**Pull request closed without merging**
