### PR TITLE
Refresh look of the member list

### PR DESCRIPTION
**Pull request by SimonBrandner**
Type: feature

<hr>

The next step would be some saner grouping (admins, online, offline...) ala Discord

<hr>

Public room:
Screenshot_20211204_143939

Encrypted room:
Screenshot_20211204_143859

---
Here's what your changelog entry will look like:

## ✨ Features
 * Refresh look of the member list ([\#7284](https://github.com/matrix-org/matrix-react-sdk/pull/7284)). Contributed by @SimonBrandner.

Preview: https://pr7284--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by t3chguy** [comment]
Whilst we're here it might be nice to improve a11y and use lazy rendering instead of having to expand the list manually

**Comment by SimonBrandner** [comment]
> Whilst we're here it might be nice to improve a11y and use lazy rendering instead of having to expand the list manually

I would actually prefer to do that in a separate PR to keep the size manageable

**Review by t3chguy — APPROVED** [review]
Looks sane code-wise, thanks!

**Comment by DoM1niC** [comment]
some code brick Spotlight Avatars 
grafik

**Review by janogarcia — COMMENTED** [review]
Please refer to previous comment. https://github.com/matrix-org/matrix-react-sdk/pull/7284#issuecomment-1154156676

**Comment by janogarcia** [comment]
I also wanted to note that we recently have introduced some product contribution guidelines that we'll be referring to when reviewing any PR that touches Product/Design:

https://github.com/vector-im/element-meta/wiki/Review-process#contributing-enhancements

**Comment by SimonBrandner** [comment]
@janogarcia, thank you for taking a look. Arguably, you're right about the PR not exactly making the UI more simple. I am going to close the PR though I'd be very happy to work on implementing a new design once one exists

**Comment by janogarcia** [comment]
Thank you Simon for the exploration, though. I've shared it with the design team. 👍

**Pull request closed without merging**
