### PR TITLE
Show "Message" in the user info panel instead of "Start chat"

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/17877

https://user-images.githubusercontent.com/25768714/124659606-7216d080-dea5-11eb-97b7-92918ad4f843.mp4

Preview: https://6141f63c5015b63edae8f5b9--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by t3chguy** [comment]
I think the copy might need tweaking for consistency, @niquewoodhouse any ideas?

**Review by t3chguy — APPROVED** [review]
code-wise lgtm

**Comment by niquewoodhouse** [comment]
Cool iteration!

**Copy**

Honestly, I'm not sure what's right. I'm happy to proceed with Start chat, but I do admit there's maybe some inconsistency.

The tooltip on the `+` under People says `Start chat` so Open chat has some precedent in the product.  I think that was recently changed so maybe that's the latest product thinking (to call it a chat instead of DM).  

`Open direct message` is an option, when you open to `+` dialog on people the title is Direct messages.  But then the first section has a heading of `recent conversations`, so `Open conversation` is an option.

Just to think out loud, if we're aiming for conistency, what about a CTA that would work for either case - whether you have a pre-existing DM or not.  Would `Message` as the copy work for both scenarios?

**Comment by SimonBrandner** [comment]
@niquewoodhouse, `Message` sounds alright to me

**Comment by MadLittleMods** [comment]
@SimonBrandner Does the PR need to be updated with the new `Message` copy?

**Comment by SimonBrandner** [comment]
> @SimonBrandner Does the PR need to be updated with the new `Message` copy?

Oops, this has somehow totally slipped through. I've updated the PR:
Screenshot_20210915_152916

@niquewoodhouse, does this look better now? Are you happy with the `Message` copy?

**Review by turt2live — APPROVED** [review]
code lgtm

**Review by niquewoodhouse — APPROVED** [review]
👌🏽

**Pull request merged**
