### PR TITLE
Improve _FilePanel.scss

### PR DESCRIPTION
**Pull request by luixxiul**
This PR intends to improve `_FilePanel.scss`.

- Create space between elements with `space-between`, instead of using `flex: 1` with `text-align`
- Remove obsolete declarations which are not used

|Before|After|
|---------|------|
|before|after|

type: enhancement

---
Here's what your changelog entry will look like:

## ✨ Features
 * Improve _FilePanel.scss ([\#9031](https://github.com/matrix-org/matrix-react-sdk/pull/9031)). Contributed by @luixxiul.

### CODE REVIEW

**Review by duxovni — CHANGES_REQUESTED** [review]
I believe the difference in color between the display name and the ellipsis is deliberate. The display name color is important so that different users with the same display name can still have some visual distinction; and the ellipsis should still be a different color to represent a semantic distinction; the ellipsis isn't part of the display name, it's an indicator that the display name has been truncated.

**Comment by luixxiul** [comment]
I would agree with you. Since the current implementation is not clear enough about it, I will change the style rules to reflect your point explicitly.

**Comment by duxovni** [comment]
Thank you! I'm rerunning the failing cypress tests to see if it's random flakiness; in the meantime, could you add updated screenshots?

**Comment by luixxiul** [comment]
@duxovni The screenshot was replaced.

**Review by duxovni — APPROVED** [review]

**Pull request merged**
