### PR TITLE
Slightly less bad message notification sound

### PR DESCRIPTION
**Pull request by piegamesde**
[Due to popular request](https://github.com/vector-im/element-web/issues/5031#issuecomment-1574023415)

Closes https://github.com/vector-im/element-web/issues/5031, related to https://github.com/vector-im/element-web/issues/5891

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Slightly less bad message notification sound ([\#11078](https://github.com/matrix-org/matrix-react-sdk/pull/11078)). Fixes vector-im/element-web#5031. Contributed by @piegamesde.

### CODE REVIEW

**Comment by harmathy** [comment]
No offence, but for me the current sound is much less annoying than this sound. In my opinion, solving https://github.com/vector-im/element-web/issues/5891 is the only solution.

**Comment by lectrode** [comment]
Unfortunately, as-is, this does not resolve #5031. This changes the notification sound to something less jarring (opinions of those with a different taste not withstanding), but does not address the ringtone, which is arguably the bigger concern of the two (i.e. the sound that is played upon receiving a call).

**Comment by piegamesde** [comment]
@harmathy I stand by my point made in https://github.com/vector-im/element-web/issues/5891#issuecomment-1582500716 – most other messengers don't have customizable notification sounds, and nobody is complaining. Customization here is a bonus, but providing a sane default is a necessary requirement.

My goal of this pull request is to show that making something less bad than the status quo takes at most two hours, and somebody actually skilled could come up with something actually good in an evening or so. So feel free to one-up me.

If you could go into detail what you find annoying about my proposed sound that would be appreciated, I might be able to improve it.

-------

@lectrode You are right that technically https://github.com/vector-im/element-web/issues/5031 is only about the ringtone, while this is only about the notification sound. I'll update the wording to "partially fixed" accordingly in my PR description. I've unfortunately lost track of all the issues and closed duplicates across several repositories on this topic, if you know a better issue to mention here let me know. IMO though, the title of https://github.com/vector-im/element-web/issues/5031 should be expanded to also include notification sounds, like in https://github.com/vector-im/element-web/issues/5891.

I did only the notification sound because I don't use element calls so I never hear the ringing sound. Also, I had only the stuff lying around for making a notification sound. So, one improvement at a time I guess.

**Comment by harmathy** [comment]
> If you could go into detail what you find annoying about my proposed sound that would be appreciated, I might be able to improve it.

I'm not an expert. I guess the increasing tone is in slightly reminiscent of a siren. Notification sounds, I usually use, have only a single tone pitch.

**Comment by langleyd** [comment]
Thanks for taking the time to contribute @piegamesde  but changing the notification sound is something that would require broader research from our design team. Unfortunately I don’t have a timescale to share on when that research might happen.

**Comment by piegamesde** [comment]
Oh, fortunately, I *can* share a timescale on when that research will happen: *not within the last six years, and not within the next six years*.

I made this pull request to prove a point: It really does not take lots of work to come up with something less bad than the status quo. No need for fancy "research", no need for perfect to be the enemy of the good.

At this point, the Element notification sound has become a meme. I'm not sure if you are aware to which extent the sounds are a poster child of the bad Element UX. This is not a resources issue, but a prioritization issue, and I urge you to reconsider your priorities on this.

**Comment by lectrode** [comment]
> that would require broader research from our design team

Please consider shifting the burden from being solely on the "design team" to something a bit more shared. They do not need to work in a dark room on a black box and only release something if they've determined it to be absolutely *perfect*.

Instead, maybe have them put together a handful of feasible (royalty free/creative commons/otherwise unencumbered) options (maybe 4 or 5) in a poll and let the user base vote on what to make default. Then do that again for the ring tone.

They can still work on their grand plan of sound themes or whatever down the line. Sane default sounds for now would be a substantial step forward toward increased usability and wider adoption.

**Pull request closed without merging**
