### PR TITLE
sliding sync: Add test to verify we send `unsubscribe_rooms` for every room switch

### PR DESCRIPTION
**Pull request by S7evinK**
This adds a test to verify that we send `unsubscribe_rooms` for every room switch.
CI is going to fail for this test, as of now, as it needs https://github.com/matrix-org/matrix-js-sdk/pull/2991

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)) 

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by kegsay — APPROVED** [review]
I didn't know you could do this in Cypress! Might need a check from @t3chguy with his Cypress-fu, but this LGTM.

**Comment by t3chguy** [comment]
Looks sane to me, but in future if you name your branches the same then the CI will run them against each other, presumably the fail right now is due to the js-sdk changeset not being considered. Also might be worth probably checking the content of the `room_subscriptions` - to ensure the wrong room isn't being unsubbed?

**Comment by richvdh** [comment]
oh I see, that's expected. Still, we can't merge this until it is unblocked by https://github.com/matrix-org/matrix-js-sdk/pull/2991.

**Comment by S7evinK** [comment]
> oh I see, that's expected. Still, we can't merge this until it is unblocked by [matrix-org/matrix-js-sdk#2991](https://github.com/matrix-org/matrix-js-sdk/pull/2991).

Thanks for approving this one, now lets wait for CI. :)

**Review by kegsay — APPROVED** [review]

**Review by richvdh — APPROVED** [review]

**Pull request merged**
