### PR TITLE
Ignore VS16 char in RTE

### PR DESCRIPTION
**Pull request by pafcu**
Fixes https://github.com/vector-im/riot-web/issues/5049

### CODE REVIEW

**Comment by lukebarnard1** [comment]
It seems that @richvdh has been in this area recently (https://github.com/emojione/emojione/issues/320) and apparently the issue should have been resolved in emojione `2.2.7`.

**Comment by pafcu** [comment]
@lukebarnard1 So it seems that there is either still a bug in emojione, or an old version of emojione is being used for some reason. Because current develop does not seem to work correctly (test e.g. by copy-pasting symbols from https://en.wikipedia.org/wiki/Dingbat#Emoji)

VS15 should definitely also be handled, but that is a separate issue. Similarly the per-symbol default presentation is ignored and everything seems to be treated as emoji-by-default.

**Comment by pafcu** [comment]
Finally it seems like the fix in Emojione is not the one we needed. There are no longer the duplicate entries (as reported in https://github.com/emojione/emojione/issues/320) but the VS16 variant also does not map to the same character as the variant-less version. I think this is actually "correct" in the sense that for eg. U+2709 (the envelop) the default presentation is text, so it _should_ look different / be separate from the variantless version.

Therefore I think that Emojione is not strictly wrong here, and that the proposed change here is the correct way to go.

**Comment by lukebarnard1** [comment]
WFM, worst case this will affect the display of other emoji.

LGTM

**Pull request merged**
