### PR TITLE
Replace readBlobAsDataUri with URL.createObjectURL

### PR DESCRIPTION
**Pull request by walle303**
This fixes vector-im/riot-web#2678 and vector-im/riot-web#2866 and provides an overall performance increase when handling embedded media in encrypted rooms.

### CODE REVIEW

**Comment by ara4n** [comment]
We should review & consider this alongside https://github.com/vector-im/riot-web/issues/6173

**Comment by lukebarnard1** [comment]
@ara4n, for those of us not "in the know", why does https://github.com/vector-im/riot-web/issues/6173 need considering here?

**Comment by dbkr** [comment]
This ought to fix https://github.com/vector-im/riot-web/issues/2770

**Comment by dbkr** [comment]
Another couple of points on this:

1. You've removed the braces from the import of `decryptFile` which changes the meaning of the import which means this fix doesn't work as it stands.

2. More importantly, whereas data URLs are from their own unique origin, blob URLs inherit the origin of the page they were created in which means if the user manages to open the URL in a browser tab their entire account is compromised, private keys and all. I engineered this by sending an HTML file as an `m.audio` then, as the user, right clicking, picking, "Copy Audio Address" and pasting that URL into a new tab, which is reasonably contrived but given the consequences, I don't think this is viable I'm afraid.

**Comment by ara4n** [comment]
So, i was just looking at this in the context of vector-im/riot-web#2866, and the thing that worries massively me is that the reason readBlobAsDataUri was added in the first place was: https://github.com/matrix-org/matrix-react-sdk/commit/8f778f54fd10428836c99d08346cf89f038dd0ce#diff-d3d5b76e1f38f26633799c4c6b61105a

whose commit message of "Use data:// URI rather than blob: URI to avoid XSS" sounds worthwhile not ignoring.

I assume this is because the blob URI could be sculpted to contain a javascript: URI or something?  Anyone know the specific XSS?

**Comment by ara4n** [comment]
Having looked into this a bit more, I can reproduce this attack but only if the mime-type passed in when instantiating the Blob is a type which can access JS when rendered in a browser (e.g. text/html or image/svg or application/pdf or whatever).

Might it be good enough just to whitelist the mime-types which we trust to be rendered from blobs (e.g. image/jpeg, image/png, image/gif, video/mp4) and for the rest of them set the mime-type to application/octet-stream so they just get downloaded as a plain old file?

**Comment by ara4n** [comment]
@walle303 heads up that i'm experimenting with the mime-type whitelisting idea atm (lest we collide)

**Comment by ara4n** [comment]
Right, i think i've finished the remaining bits here and have opened up a new PR for it (#1864), which supersedes this one. @walle303; sorry for picking it up; i assumed you had shelved it as you didn't respond to the earlier feedback. many thanks for doing all the original legwork!

**Pull request closed without merging**
