### PR TITLE
Add a 4chan-style greentext Lab

### PR DESCRIPTION
**Pull request by TheStranjer**
This creates a Lab that creates text akin to 4chan's greentext when you prepend messages with `>`.

Here is what greentext looks like in the wild:
readinglist

It's quite routine for users on certain Matrix homeservers to try to greentext in their conversations:
```
>implying it won't make a blockquote instead
```

However, blockquotes are not the intended output for those users. It is my belief that while those users are a minority of Riot users (hence setting the feature to `false` by default), they are significant enough of one to merit allowing them to use this software as it suits their needs.

**NOTE:** I am aware that my implementation of this is a bit hacky. However, unless the very idea of a greentext Lab is _a priori_ rejected, I would like to resolve any flaws in my thinking in code review

```
Signed-off-by: Bob Arctor neetzsche@tutanota.com
```

### CODE REVIEW

**Comment by t3chguy** [comment]
Overriding the commonmark spec is akin to rolling a custom markdown dialect which is something the team has expressed they wish not for. Putting this in Product review

**Comment by poljar** [comment]
Shouldn't this override the rendering, not the parsing and the underlying format that gets sent out? [Weechat-Matrix](https://raw.githubusercontent.com/benparsons/matrix-notes/master/twim/weechat-matrix.png) already renders replies and block quotes like green text.

**Comment by t3chguy** [comment]
I'd argue it should be parsing, so the user can *send* a quote or send greentext. Matrix HTML subset spec supports sending both (it is just coloured text after all) so how would you discern what a user meant to send if not at the parsing level

**Comment by TheStranjer** [comment]
The intention on my end is not to change rendering, but instead to change what gets sent out. So if a user with this feature on types greentext, my goal is to have others see greentext regardless of their settings.

**Comment by dkasak** [comment]
What exactly *is* greentext? You say that a blockquote is not the intended output, but is it the intended *meaning*? Is it simply a blockquote that's specifically green in colour or something else?

**Comment by doom3wasagoodgame** [comment]
@dkasak It's text that's green that starts with a `>`

**Comment by Loon-Toon** [comment]
I don't care about how it's implemented, but ability to write greentext style would be neat. [Greentext explanation](https://knowyourmeme.com/memes/greentext-stories) doesn't quite do justice to the subject, I would dare to say that greentext is modern art form.

**Comment by KingTerrytheTerrible** [comment]
Greentext is a great idea, I have yet to see anyone use block quotes purposefully.

**Comment by Ham-Syde** [comment]
I use block quotes all the time, but I agree, we NEED greentext. Block quotes should be prepended with something else.

**Comment by t3chguy** [comment]
As stated before, changing to a custom Markdown dialect, as would be needed to make quotes a different character would be confusing to the majority of users, the devs expressed they do not wish to do that.

> Overriding the commonmark spec is akin to rolling a custom markdown dialect which is something the team has expressed they wish not for.

**Comment by TheStranjer** [comment]
I think the negative consequences of that are by and large addressed by making this an opt-in option. I think you're right that the majority of users would not want this feature, but I also think that the discussion on this PR indicate that quite a few people would, and so should be free to opt-in.

That said, I'm still going to work on this branch even if the Matrix team deems greentext to be an inappropriate feature, because I intend to deploy it on my own instance regardless, and think that other Riot instance owners should be free to deploy it as well.

**Comment by TheStranjer** [comment]
Yeah. For now, I want to go through the process to see if a "greentext" option in place of blockquotes is a reasonable feature to begin with, and if so, go into code review. If it isn't, then I'll just have to settle for deploying this on my own instance.

I can say that I've already had a lot of fun with this Lab on my Riot instance, though!

**Comment by starcraft66** [comment]
I would be interested in an option to enable this feature. I frequently find myself trying to greentext in rooms only to be met with a quote I need to edit. This is especially confusing on mobile clients that have different horrible ways to markup text.

**Comment by doom3wasagoodgame** [comment]
This is *very* *very* important to our community, and I feel like we not getting the attention we deserve as decent human beings.

**Comment by j0w0** [comment]
discord does something simular
`>example` doesnt create a block quote
`> example` creates a block quotw
nice and simple!

**Comment by t3chguy** [comment]
> discord does something simular
> `>example` doesnt create a block quote
> `> example` creates a block quote
> nice and simple!

This would have to be a suggestion to be changed in the commonmark spec as that is the dialect of Markdown in use.

**Comment by nadonomy** [comment]
Hey everyone— chiming in on behalf of @matrix-org/product. Firstly, it's exciting to see fun PRs come in from the open source community. :) Some of the fun 'unnecessary' things (like spoiler tags) made it in this way, and it's always nice to see.

1. **Accessibility.** The current green doesn't pass WCAG standards, and would need to for us to merge. We can't simply use the accent colour green either as this would clash with affordance elsewhere in the app causing users to think the greentext is interactive.

2. **Cross-platform.** We'd need to be confident in how this performs on Riot on iOS & Android, as well as other Matrix clients, which leads me to 3.

3. **Technical implementation.** @t3chguy from your comments in this PR so far it looks like overriding the common mark spec is intractable. Can you input on other potential options, and their impact on point 2? 

4. **Niche appeal & user confusion.** We design & build Riot for a wide range of users and use cases, and greentext only appeals to a very niche subculture. Iy will certainly cause confusion and we'd receive bug reports if enabled by default. That said, I know the folk who are passionate about greentext are passionately so— we could include this as an opt in labs flag if we can resolve all the outstanding issues in this PR.

However, it's worth noting that things in labs are on the quick chop cutting board to be removed if they're proving problematic, and with all of the above said you can always run your own fork of Riot! :)

@TheStranjer we're quite preoccupied at the moment on the product/design teams to help shepherd all of the above through, but if you're able to resolve those points then we'd be happy to review again.

**Comment by t3chguy** [comment]
> it looks like overriding the common mark spec is intractable.

It is tractable in the current library we are using but it is not guaranteed for when we change libraries which is planned soon if we decide to go back to GFM.

**Comment by TheStranjer** [comment]
Let me sleep on it for a few days, through the weekend. @nadonomy

**Pull request closed without merging**
