### PR TITLE
Improve remove recent messages dialog

### PR DESCRIPTION
**Pull request by robintown**
This improves the remove recent messages dialog by never redacting room encryption events, adding an option to keep state events, and showing the new UserMenu spinner while redactions are in flight.

Screenshot_2021-05-28 Element Unencrypted test room(1)

Closes vector-im/element-web#12331.
Closes vector-im/element-web#15490.
Closes vector-im/element-web#17445.
Closes https://github.com/vector-im/element-web/issues/20990.

---
This PR currently has no changelog labels, so will not be included in changelogs.

A reviewer can add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is, or add `Type: [enhancement/defect/task]` to the description and I'll add them for you.

Preview: https://pr6114--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by gsouquet** [comment]
> Apparently the spinner is useful despite the UI freezing for a few seconds initially

Did you get a chance to figure out what is causing the UI to freeze? It'd be interesting to see a flame graph at least to pinpoint the issue and see whether something can be done to improve the user experience

**Comment by robintown** [comment]
@gsouquet The issue is that every `cli.redactEvent` call fires `localEchoUpdate` twice (once on "encrypting", once on sending, I think) and every one of these is listened to by TimelinePanel which then does a force update. I could try to figure out how to address that by signaling that events are being sent in bulk, but I'm not sure what the most pragmatic way to do that would be… the freezing is nothing new at least.

**Comment by gsouquet** [comment]
> @gsouquet The issue is that every `cli.redactEvent` call fires `localEchoUpdate` twice (once on "encrypting", once on sending, I think) and every one of these is listened to by TimelinePanel which then does a force update. I could try to figure out how to address that by signaling that events are being sent in bulk, but I'm not sure what the most pragmatic way to do that would be… the freezing is nothing new at least.

Thank you for investigating!

If this is not tracked already, would you mind creating an issue? I'll try and take a look into
A frozen UI is probably one of the worst thing that can happen and I feel your pain regarding the `forceUpdate` in `TimelinePanel`

**Review by turt2live — APPROVED** [review]
Code overall looks fine, just need confirmation from design

**Comment by erkinalp** [comment]
Bans should also be kept, to prevent abuse.

**Comment by robintown** [comment]
@erkinalp The substance of all state changes is kept no matter what - if you redact a join, leave, or ban event, it will just redact the displayname and avatar_url from it.

**Comment by janogarcia** [comment]
@robintown Thank you for the contribution! I'd suggest keeping that option **enabled by default**, so that no system messages are redacted unexpectedly, and updating the copy to give a bit more context:

```
[✓] Preserve system messages. Uncheck if you also want to remove system messages on this user (e.g. membership change, profile change…).
```

**Comment by janogarcia** [comment]
@robintown As for the checkbox layout, please refer to the attached mockup.

PR6114

**Comment by robintown** [comment]
@janogarcia Done!

Screenshot 2021-11-28 at 16-08-58 Element Test room

**Review by janogarcia — APPROVED** [review]

**Review by turt2live — APPROVED** [review]
Sorry, I missed the re-review request. Let's send it :)

**Comment by turt2live** [comment]
I can't seem to push to the branch to fix the conflicts, but it'd look like this in `RoomListHeader`:

```diff
-    useEventEmitter(cli, "Room", (room: Room) => removeAction(PendingActionType.JoinRoom, room.roomId));
+    useTypedEventEmitter(cli, ClientEvent.Room, (room: Room) => removeAction(PendingActionType.JoinRoom, room.roomId));
```

```diff
         { pendingActionSummary ?
             <TooltipTarget label={pendingActionSummary}><InlineSpinner /></TooltipTarget> :
             null }
-        <ContextMenuTooltipButton
+        { canShowPlusMenu && <ContextMenuTooltipButton
```

@robintown

**Pull request merged**
