### PR TITLE
Scaled Creating Polls dialog box for small windows

### PR DESCRIPTION
**Pull request by ankur12-1610**
Signed-off-by: ankur12-1610 <anknerd.12@gmail.com>

Fixes: [vector-in/element-web/#21855](https://github.com/vector-im/element-web/issues/21855)

https://user-images.githubusercontent.com/76884959/167274517-82b9cc56-6e2b-4a4a-b2a1-101ebe8c0cff.mp4

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Scaled Creating Polls dialog box for small windows ([\#8530](https://github.com/matrix-org/matrix-react-sdk/pull/8530)). Contributed by @ankur12-1610.

### CODE REVIEW

**Comment by ankur12-1610** [comment]
@t3chguy can I give a look at it? :sweat_smile:

**Review by SimonBrandner — CHANGES_REQUESTED** [review]
I think this would result in ^ (double scrollabars)

**Comment by ankur12-1610** [comment]
> 
> 
> I think this would result in ^ (double scrollabars)

@SimonBrandner but I haven;t changed anything related to scrollbars I've just played with footer of the dialog :thinking: 
And ig current element version has the same dialog box? or am I wrong?

**Comment by SimonBrandner** [comment]
Then I am unsure as to how this PR improves the situation - the dialog still seems to behave unideally in small windows. What am I missing?

**Comment by ankur12-1610** [comment]
> Then I am unsure as to how this PR improves the situation - the dialog still seems to behave unideally in small windows. What am I missing?
In small windows the footer used to overlap over the content due to its absolute position and also there wasn't any background given to footer so as soon it overlapped the content in small windows the content was visible through the footer.

**Comment by SimonBrandner** [comment]
Ah, I see - I am not sure if we would accept this as a bugfix for the mentioned issue as this only slightly changes the situation but the dialog still feels very much confusing/unusable

**Comment by SimonBrandner** [comment]
Do you think you would be able to fix the other issue - mainly the scrolling weirdness?

**Comment by ankur12-1610** [comment]
> Do you think you would be able to fix the other issue - mainly the scrolling weirdness?

Yeah, but I'll need to recreate the dialog from the base cause there are two scrollable divs which are creating a little bit of problem :')

**Comment by ankur12-1610** [comment]
> Ah, I see - I am not sure if we would accept this as a bugfix for the mentioned issue as this only slightly changes the situation but the dialog still feels very much confusing/unusable

Ah! I just saw the issue and gave it a try was not sure end result will be significant or not :sweat_smile:

**Comment by SimonBrandner** [comment]
> > Do you think you would be able to fix the other issue - mainly the scrolling weirdness?
> 
> Yeah, but I'll need to recreate the dialog from the base cause there are two scrollable divs which are creating a little bit of problem :')

As long as that is the best way to fix the problem and we retain all the features, that would be ideal :)

**Comment by ankur12-1610** [comment]
> > > Do you think you would be able to fix the other issue - mainly the scrolling weirdness?
> > 
> > 
> > Yeah, but I'll need to recreate the dialog from the base cause there are two scrollable divs which are creating a little bit of problem :')
> 
> As long as that is the best way to fix the problem and we retain all the features, that would be ideal :)

Cool, then I'll create a new issue on resolving two scrollbars, is it okay?

**Comment by SimonBrandner** [comment]
> > > > Do you think you would be able to fix the other issue - mainly the scrolling weirdness?
> > > 
> > > 
> > > Yeah, but I'll need to recreate the dialog from the base cause there are two scrollable divs which are creating a little bit of problem :')
> > 
> > 
> > As long as that is the best way to fix the problem and we retain all the features, that would be ideal :)
> 
> Cool, then I'll create a new issue on resolving two scrollbars, is it okay?

Sure, go ahead

**Comment by ankur12-1610** [comment]
@SimonBrandner  I guess the current issue I'm working on is related to the scrolling weirdness, I'll make the changes to this PR itself rather than creating a new issue. Does that work?

**Comment by SimonBrandner** [comment]
> @SimonBrandner I guess the current issue I'm working on is related to the scrolling weirdness, I'll make the changes to this PR itself rather than creating a new issue. Does that work?

Sure!

**Comment by gaelledel** [comment]
note: We should already have a component for this type of modal on the web
It should all be 100% opaque including the sticky footer

**Comment by Johennes** [comment]
Since this seems abandoned, I opened #9873.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/matrix-react-sdk/pull/9873 - thanks for your contribution!

**Pull request closed without merging**
