### PR TITLE
Add raw error to analytics E2E error event context

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Related to https://github.com/vector-im/element-meta/issues/224

Currently most of errors reported by EW are UnknownError.
We need to get more information on what the actual underlying error is.

This PR is adding the raw error as part of the context of the analytic event.
This is a quick first step to get us more information. We will transition next to a new dedicated Error Event for E2EE

---
This PR currently has no changelog labels, so will not be included in changelogs.

Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
it's a bit difficult to review this with failing CI

**Comment by BillCarsonFr** [comment]
> it's a bit difficult to review this with failing CI

Yep sry @turt2live 
I fixed the code style issues. I rebased and it did fix the e2e failing test.
But there still the SonarQube check failing, not sure what to do, it says `Set the SONAR_TOKEN env variable.`

**Comment by turt2live** [comment]
SonarQube can be ignored

**Comment by t3chguy** [comment]
(fixing sonar check)

**Review by turt2live — APPROVED** [review]
Thanks!

**Pull request merged**
