### PR TITLE
Improve text of account deactivation dialog

### PR DESCRIPTION
**Pull request by justjanne**
Type: Enhancement
Closes: https://github.com/vector-im/element-web/issues/17421

## Summary
* Updates text of "Deactivate Account" dialog

---
Here's what your changelog entry will look like:

## ✨ Features
 * Improve text of account deactivation dialog ([\#8371](https://github.com/matrix-org/matrix-react-sdk/pull/8371)). Fixes vector-im/element-web#17421. Contributed by @justjanne.

Preview: https://pr8371--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by justjanne** [comment]
## In Action

* New text of “Deactivate Account” dialog  
  Screenshot of the “Deactivate Account” dialog with new text

**Review by kerryarchibald — COMMENTED** [review]
Code looks good, but based on your screenshot I think the space between 'Would you like to hide your send messages?' and the checkbox is too big - there should probably only be one newline between them.

**Comment by justjanne** [comment]
@kerryarchibald I’ve updated it now to remove the spacing that was previously used in the deactivate account dialog.

**Review by kerryarchibald — APPROVED** [review]
LGTM!

**Pull request merged**
