### PR TITLE
Replace breadcrumbs with recently viewed menu

### PR DESCRIPTION
**Pull request by t3chguy**
Requires https://github.com/vector-im/element-web/pull/19700/
Fixes https://github.com/vector-im/element-web/issues/19528

---
Here's what your changelog entry will look like:

## ✨ Features
 * Replace breadcrumbs with recently viewed menu ([\#7073](https://github.com/matrix-org/matrix-react-sdk/pull/7073)). Fixes vector-im/element-web#19528.

Preview: https://61a74b92eaa3d216b723d1e5--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
- [ ] Menu should appear on hover (per spreadsheet).  
- [x] Can it be repositioned to appear to the right of the button, not underneath it?  I just realized, if we're going for hover, it might be more annoying for it to appear underneath instead of to the side of the room list

- [x] Need a hover state for the button (could we pls use same from other buttons in the project, eg the `+` and `explore` buttons)



- [x] The Space name and 3 others is meant to be dynamic for each room so it says a space it's in and X others if in any others.  No deep thoughts on the logic that determines which name to say first, open to any suggestions but was thinking it would be the space they selected it from, unless its Home and then it defaults to alphabetical or position in space list, or whatever's easiest.

- [x] The list could do with some minor tweaks to introduce a hover state for each item.  This might need further tweaks.
   - [x] .mx_RecentlyViewedButton_ContextMenu .mx_ContextualMenu .mx_AccessibleButton border radius 8px
   - [x] .mx_RecentlyViewedButton_ContextMenu .mx_ContextualMenu .mx_AccessibleButton hover background rgba(141,151,165,.2) (same as button that opened menu)
   - [ ] .mx_RecentlyViewedButton_ContextMenu .mx_ContextualMenu .mx_AccessibleButton margin-top:2px padding:4px
   - [ ] .mx_RecentlyViewedButton_ContextMenu .mx_ContextualMenu>h4 margin: 0 0 12px 0

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
Some quite small things:

**Recently viewed context menu**

- 1px solid border (the same as the feedback box on space home)

- Border radius 8 
- Bonus (not sure if we're ok with bespoke box shadows but as we're experimenting maybe it's ok for now) I'd like to add a box-shadow to it box-shadow: 0px 24px 8px rgb(17 17 26 / 4%), 0px 8px 32px rgb(17 17 26 / 4%) This seemed alright but I struggled to get it right with the hover state

**Item within menu**

- Seeing it in practice, can the hover state bg be the same as the room list please?

**Comment by t3chguy** [comment]
> 1px solid border (the same as the feedback box on space home)

Done

> Border radius 8

Done

> Box shadow

Done, that is the funkiest box shadow definition i've ever set eyes on

> Seeing it in practice, can the hover state bg be the same as the room list please?

Done

---

Also had to tweak the scrollable region so now the heading sticks & also made the buttons with/without microcopy have matching heights

**Review by dbkr — COMMENTED** [review]
Sort of amusing that the majority of this PR is for the tooltip the thing lives in rather than the actual feature. :) I wonder if we'll also want a short grace period where you can wander outside the area without it closing, but I'll leave that between you & design.

Would it be possible to write a test for the tooltip stuff? It feels like the kind of thing that could end up breaking quite easily & without us noticing. The region calculation stuff is also pretty complex and would be easy to test.

**Comment by t3chguy** [comment]
The tooltip stuff is the original reactions implementation reborn from the depths of git history, iirc written by Ryan :P

**Comment by nadonomy** [comment]
This is feeling great! 'Fresh eyes' feedback from smoke testing, mostly visual @t3chguy @niquewoodhouse. Adding as checkboxes so we can tick off as we discuss: 

- [ ] [History button is too opaque](https://user-images.githubusercontent.com/4626865/142998568-7782ee5f-08c4-45ec-81f2-bacab420771e.png), doesn't match existing styles. Same as my [bugs/quality feedback on 1.1](https://github.com/matrix-org/matrix-react-sdk/pull/7052#pullrequestreview-811520736).
- [ ] [Hover state and scrollbar would benefit from more spacing](https://user-images.githubusercontent.com/4626865/142998823-1e4b6d69-0900-4cb0-8f33-f08c87cdbe74.png). On Chrome/macOS at least.
- [ ] [Initials misaligned by a couple of px](https://user-images.githubusercontent.com/4626865/142998919-04606b47-2415-4cfc-bc18-920df0d8f31c.png) (looks like slightly top and left) on space avatars.
- [ ] [Collapsed state lacking button background](https://user-images.githubusercontent.com/4626865/142999008-b7fb1143-431d-440c-8cd3-d0b16bf34e26.png). Is this intentional?
- [ ] [Overflow menu looks unstyled on hover](https://user-images.githubusercontent.com/4626865/142999008-b7fb1143-431d-440c-8cd3-d0b16bf34e26.png).
- [ ] Labs is super difficult to navigate. Is it trivial to split it into a few sections with relevant headers? I think it would aid managing labs more generally, and aid quality of user feedback within IA.

Screenshots in dark mode, but also echoed on light.

**Review by nadonomy — CHANGES_REQUESTED** [review]
This is feeling great! 'Fresh eyes' feedback from smoke testing, mostly visual @t3chguy @niquewoodhouse. Adding as checkboxes so we can tick off as we discuss: 

- [ ] [History button is too opaque](https://user-images.githubusercontent.com/4626865/142998568-7782ee5f-08c4-45ec-81f2-bacab420771e.png), doesn't match existing styles. Same as my [bugs/quality feedback on 1.1](https://github.com/matrix-org/matrix-react-sdk/pull/7052#pullrequestreview-811520736).
- [x] [Hover state and scrollbar would benefit from more spacing](https://user-images.githubusercontent.com/4626865/142998823-1e4b6d69-0900-4cb0-8f33-f08c87cdbe74.png). On Chrome/macOS at least.
- [ ] [Initials misaligned by a couple of px](https://user-images.githubusercontent.com/4626865/142998919-04606b47-2415-4cfc-bc18-920df0d8f31c.png) (looks like slightly top and left) on space avatars.
- [x] [Collapsed state lacking button background](https://user-images.githubusercontent.com/4626865/142999008-b7fb1143-431d-440c-8cd3-d0b16bf34e26.png). Is this intentional?
- [x] [Overflow menu looks unstyled on hover](https://user-images.githubusercontent.com/4626865/142999008-b7fb1143-431d-440c-8cd3-d0b16bf34e26.png).
- [x] Labs is super difficult to navigate. Is it trivial to split it into a few sections with relevant headers? I think it would aid managing labs more generally, and aid quality of user feedback within IA.

Screenshots in dark mode, but also echoed on light.

**Comment by t3chguy** [comment]
> Labs is super difficult to navigate. Is it trivial to split it into a few sections with relevant headers?

Yup, would be doable

**Comment by ShadowJonathan** [comment]
>  Labs is super difficult to navigate. Is it trivial to split it into a few sections with relevant headers? I think it would aid managing labs more generally, and aid quality of user feedback within IA.

(I could kinda argue this be properly done in a separate issue, like it has been done for Settings' appearance tab)

**Comment by t3chguy** [comment]
Made a spin-off PR to group Labs - https://github.com/matrix-org/matrix-react-sdk/pull/7190 - input on better groupings appreciated

**Comment by niquewoodhouse** [comment]
@nadonomy 

>  History button is too opaque, doesn't match existing styles. Same as my bugs/quality feedback on 1.1.

I think it matches existing styles now?

https://user-images.githubusercontent.com/1587166/144060003-c5e2d220-1c90-4509-88a4-719697a60d9a.mp4

It does have a hover state the same as the "add" button next to space name.

**Review by niquewoodhouse — CHANGES_REQUESTED** [review]
One comment from me:

- [ ] When you select an item in the list, could the menu then disappear?

It feels like it gets in the way once you've selected somewhere to go.

**Comment by nadonomy** [comment]
> @nadonomy
> 
> > History button is too opaque, doesn't match existing styles. Same as my bugs/quality feedback on 1.1.
> 
> I think it matches existing styles now?

Awesome thx. Checked off from my list along with the others!

**Review by nadonomy — APPROVED** [review]
This interaction is feeling great! Few notes, but not to block merging on:

1. Lots of space panel jiggling when hovering, but I'm assuming unrelated to the new breadcrumbs interaction.
2. Enabling/disabling meta spaces (favs/people) incurs a few hundred ms lag for me. Wonder if the UI/checkbox should respond instantly?

**Comment by t3chguy** [comment]
> Enabling/disabling meta spaces (favs/people) incurs a few hundred ms lag for me. Wonder if the UI/checkbox should respond instantly?

This PR is entirely unrelated to metaspaces though? Related https://github.com/vector-im/element-web/issues/19749 (I think there is an issue tracking your exact issue but I can't seem to find it right now)

**Comment by nadonomy** [comment]
> > Enabling/disabling meta spaces (favs/people) incurs a few hundred ms lag for me. Wonder if the UI/checkbox should respond instantly?
> 
> This PR is entirely unrelated to metaspaces though? Related [vector-im/element-web#19749](https://github.com/vector-im/element-web/issues/19749) (I think there is an issue tracking your exact issue but I can't seem to find it right now)

Yup, hence mentioning it as an FYI while I can reproduce in the test build from this PR, but not blocking on it.

**Review by dbkr — APPROVED** [review]
Yay, thanks!

**Review by niquewoodhouse — APPROVED** [review]
Thanks, looks good.

@nadonomy  I think this is one change we'll need to prep for a lot of feedback on as a few people will _really_ depend on the breadcrumbs to use element today.

**Comment by t3chguy** [comment]
@nadonomy I can't reproduce any jiggling, when you get a chance could you please screencap?

> Lots of space panel jiggling when hovering, but I'm assuming unrelated to the new breadcrumbs interaction.

**Pull request merged**
