### PR TITLE
Add tool to automatically update translation file

### PR DESCRIPTION
**Pull request by pafcu**
To check if changes are needed:
~~`scripts/update_translation.py src/i18n/strings/en_EN.json src/**/*.js`~~
`scripts/update_translation.py src/i18n/strings/en_EN.json "src/**/*.js"`

To automatically update translation:
~~`scripts/update_translation.py --auto-add --auto-remove src/i18n/strings/en_EN.json src/**/*.js`~~
`scripts/update_translation.py --auto-add --auto-remove src/i18n/strings/en_EN.json "src/**/*.js"`

(note added quotes to avoid shells doing incorrect non-recursive expansion)

### CODE REVIEW

**Comment by ara4n** [comment]
ooh, this looks good. @dbkr wdyt?

**Comment by lukebarnard1** [comment]
Right, the plan is that I'll review this and test it out in the process of doing the "Groups" -> "Communities" UI rename.

**Comment by pafcu** [comment]
BTW, I realized that this does not handle commented-out calls yet. I'll add that later, but I think it it not critical at this point yet.

**Comment by lukebarnard1** [comment]
I've encountered a few issues with this:
 - I'm finding I have to specify the src file glob for every directory level (i.e. `src/**/**/**/*.js`). It'd be nice if we could just specify a directory.
 - The translations should be reinserted into the translation JSON blob with the items ordered alphabetically on the key.

**Comment by pafcu** [comment]
> I'm finding I have to specify the src file glob for every directory level (

This is probably because you don't have recursive globs in your shell. I intentionally wanted to keep the Python code as simple as possible and let the shell handle that. Use `shopt -s globstar` in Bash.

> The translations should be reinserted into the translation JSON blob with the items ordered alphabetically on the key.

OK, but this is not how it is done now, right? So it will definitely break every merge request that has modified strings (as they are no longer in the same place). But it's trivial to sort alphabetically.

**Comment by pafcu** [comment]
Apparently Python 3.5 makes it trivial to do recursive globbing, so I will add that directly to the code, rather than rely on the shell.

**Comment by pafcu** [comment]
You should not have to install typing, as it is a standard module. However, it seems like it was introduced in Python 3.5. Python 3.5 was released over two years ago, so I'm kind of leaning towards _not_ being compatible with Python 3.4, unless really necessary. Do we expect to run the script on old systems?

**Comment by pafcu** [comment]
Issues should be fixed now. Still requires Python 3.5, bit should complain about it now. I can make it Python 3.4 compatible, but rather would not as it just makes the code more complicated with little benefit (IMHO).

**Comment by lukebarnard1** [comment]
>OK, but this is not how it is done now, right?

No, but now is a good time to enforce a consistent ordering on the keys in the translation files.

>You should not have to install typing

It turns out I was using python 3.4.3.

>Do we expect to run the script on old systems?

We're basically asking "can we expect developers working on the codebase to have python3.5 installed or if not, to install it". This seems like an unfortunate dependency to pick up, although I suppose I'm biased towards minimising dev dependencies.

**Comment by lukebarnard1** [comment]
>I don't think it is unreasonable to expect developers to update their tools

No, I agree it's not unreasonable and it's not too painful to do.

I am however seeing a `KeyError` when I run it on `develop`:
```python
Traceback (most recent call last):
  File "../update_translation.py", line 130, in <module>
    sys.exit(main())
  File "../update_translation.py", line 73, in main
    del ref[string]
KeyError: 'and %(count)s others...'
```

**Comment by pafcu** [comment]
Ah, I see what the problem is, even though I can't reproduce it. It fails to account for the |one, |other stuff when removing things. Should be a pretty easy fix, and should only happen with "--auto-remove".

**Comment by lukebarnard1** [comment]
Forgot to mention, the command I ran was:
`python3.5 ../_snipets/update_translation.py --auto-add --auto-remove src/i18n/strings/en_EN.json src/**/*.js`

**Comment by pafcu** [comment]
Plurals should now be handled correctly

**Comment by pafcu** [comment]
Made obsolete by https://github.com/matrix-org/matrix-react-sdk/pull/1493

**Pull request closed without merging**
