### PR TITLE
Fix new URL previews

### PR DESCRIPTION
**Pull request by SimonBrandner**
### Description
Fixes [#16479](https://github.com/vector-im/element-web/issues/16479)

### Image
Screenshot_20210219_171415

### Non-image
Screenshot_20210219_171426

### Additional info
This is going to need some input from the Design team

### CODE REVIEW

**Comment by t3chguy** [comment]
/me missed the Draft label and got over-excited :D

**Comment by williamkray** [comment]
as the guy who introduced the thing that nobody liked, i agree this is a much more graceful way of accomplishing what i wanted to do :smile:

**Comment by williamkray** [comment]
after checking this out in action using the netlify deployment, i think it could handle even more restrictive use-case... specifically if the url ends in a known image mimetype (.jpg, .jpeg, .png, .gif). the issues with blurb text wrapping is still in place with the narrower div. the more compact horizontal url preview should probably be used more frequently, only depending on a larger image preview if it's specifically an image link.

**Comment by SimonBrandner** [comment]
Closing as this PR is probably quite outdated by now

Related issues: https://github.com/vector-im/element-web/issues/7897 and https://github.com/vector-im/element-web/issues/20109

**Pull request closed without merging**
