### PR TITLE
Display subspaces in minimized space panel

### LINKED ISSUE #17472: View subspaces while the Spaces-bar is minimised.
#### Is your suggestion related to a problem? Please describe.
When viewing subspaces in a space, the space-bar automatically expands, and takes up a huge amounts of valuable screen real-estate. This makes Element take up a lot more space than what's necessary, and it looks very clunky, aseptically on small screens.
Screenshot 2021-05-26 at 20 27 23 (2)

#### Describe the solution you'd like.
You should be able to view sub-spaces while the space-bar is minimised.

#### Describe alternatives you've considered.
It could be solved like this:
view all Subspaces at once
My inspiration is from Discords server folders:

#### Additional context
This does mean that you won't be able so see the names of the subspaces unless you hover over them. But if it's a space you use a lot, it won't matter, since you know it well. And this won't be an issue if #17378 is added, since it will show the subspaces in the room list anyway.

### PR DESCRIPTION
**Pull request by robintown**
Screenshot 2021-08-04 at 23-19-55 Element off-topic

There's definitely room for improvement to make the layout more readable, but I hope this should be a good enough start for design to be able to provide feedback on.

Closes https://github.com/vector-im/element-web/issues/17472.

Preview: https://611a88fe1baa5c009fa5d77b--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
The code looks fine, though personally I'm not sure I'd be using this functionality. Subspaces are useful for organizing massive collections of rooms, but in practice I (personally) rarely ever actually jump into a subspace. 

For metrics: Element's company space is ~40-50 subspaces with up to 4 levels deep of subspaces. I only really go digging through the tree if I'm looking for a particular room, but otherwise I'm just looking to filter by coarse area as a sort of account switching.

**Comment by nadonomy** [comment]
Hey @robintown thanks for the contribution. We'll need to review/think on this somewhat internally before accepting this.

One of the goals we set ourselves with Spaces was that we want to meet peoples expectations from other platforms and abstract away more complex capabilities. This resolves into ensuring the non-expanded state of the space panel being no more complex than peoples expectations from incumbents today.

It might be that we'd consider this behind a settings flag instead, but we'll discuss more internally and follow up!

**Comment by robintown** [comment]
@nadonomy Good to know, and of course if this ultimately isn't desired functionality for mainline Element I'll definitely understand.

To add my two cents, the main reason for me suggesting this functionality is this: A number of my spaces are organized under personal spaces by their general topic, as is visible in the screenshot above. However, I rarely find myself wanting to view things from the perspective of the topic spaces, as they end up mixing together many separate, though related, subjects. So instead, I end up having to keep the space panel expanded all the time in order to be able to actually visit subspaces and see subspace-level notification states (as activity in one subspace might be a lot more important to me than activity in another).

Given @turt2live's comments this does sound like the sort of thing that might work best under a settings flag, though I'll wait to see what comes out of the internal discussion. 👍

**Comment by robintown** [comment]
I'm retracting this PR since it seems from the recent IA things that the design team has other plans for subspaces anyways, which I'd rather not get in the way of :)

**Comment by niquewoodhouse** [comment]
Hey @robintown

> I'm retracting this PR since it seems from the recent IA things that the design team has other plans for subspaces anyways, which I'd rather not get in the way of :)

Just to say the team is not necessarily following through on any other plans at the moment.  I think there's value in what you're proposing, and the issue it closes has a lot of useful ideas/feedback too.  Lots of promise here.

We just need to find time later to focus on this specific interaction so we'll keep this in mind when we get to it.  This will be of use then, so leaving it assigned to myself for then.

**Pull request closed without merging**
