### PR TITLE
Add missing space in SecurityRoomSettingsTab

### PR DESCRIPTION
**Pull request by gefgu**
Signed-off-by: gefgu <gefgu@hotmail.com>

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [X] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Type: Defect

Notes: Add missing space in SecurityRoomSettingsTab. It fixes vector-im/element-web#22402

Before: vector-im/element-web#22402
After: 
add_missing_space

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Add super cool feature ([\#9222](https://github.com/matrix-org/matrix-react-sdk/pull/9222)). Contributed by @gefgu.

### CODE REVIEW

**Review by SimonBrandner — APPROVED** [review]

**Comment by SimonBrandner** [comment]
Please run the `yarn i18n` script

**Review by robintown — CHANGES_REQUESTED** [review]
You'll need to run `yarn i18n` to regenerate the strings file. Otherwise, this looks good.

**Comment by gefgu** [comment]
Thanks for the quick feedback. I'm going to run the script.

**Comment by gefgu** [comment]
Should I run `yarn prunei18n` too? (because of this https://github.com/vector-im/element-web/blob/develop/docs/translating-dev.md#editing-existing-strings)

**Comment by SimonBrandner** [comment]
> Should I run `yarn prunei18n` too? (because of this [https://github.com/vector-im/element-web/blob/develop/docs/translating-dev.md#editing-existing-strings](https://github.com/vector-im/element-web/blob/develop/docs/translating-dev.md?rgh-link-date=2022-08-25T19%3A21%3A37Z#editing-existing-strings))

`yarn i18n` should be enough

**Comment by robintown** [comment]
No, `yarn prunei18n` has to be done in coordination with locking the Weblate project, so is impractical to do often.

**Review by robintown — APPROVED** [review]

**Pull request merged**
