### PR TITLE
Fix: Edited message remove button is hard to reach.

### PR DESCRIPTION
**Pull request by manancodes**
## Checklist

- [x] Tests written for new code (and old code if feasible)
- [x] Linter and other CI checks pass
- [x] Sign-off given on the changes (see [CONTRIBUTING.md] (https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Fixes https://github.com/vector-im/element-web/issues/24917
Signed-off-by: Manan Sadana manancodes.dev@gmail.com

It was hard to reach the remove button for a particular message, the remove button only shows up if a particular message row is hovered. When the cursor is moved out of the message row, the remove button goes away. For better user experience, the hovered message is highlighted, which clarifies the confusion.
I matched the hover behaviour with the normal reply messages.

This was the behaviour before the fix:
Before

And this is the behaviour after the fix:
After

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix: Edited message remove button is hard to reach. ([\#11674](https://github.com/matrix-org/matrix-react-sdk/pull/11674)). Fixes vector-im/element-web#24917. Contributed by @manancodes.

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]
Thank you, this is a nice improvement.

I suspect there will be no existing Percy (screenshot) tests covering this, and since this dialog is quite rarely-used I prefer to merge this improvement rather than waiting for us to get around to writing tests.

**Comment by andybalaam** [comment]
Blocked behind https://github.com/matrix-org/matrix-react-sdk/pull/11692

**Comment by andybalaam** [comment]
Force-merged since this is blocking everything else that might otherwise be in the merge queue.

**Comment by manancodes** [comment]
Thankyou.

**Comment by andybalaam** [comment]
> Force-merged since the merge queue was blocked on #11692 and this should help throughput.

I actually force-merged the wrong PR :facepalm: but this change should fine.

**Pull request merged**
