### PR TITLE
Fixed a minor typo

### PR DESCRIPTION
**Pull request by ankur12-1610**
Fixes: [#21396](https://github.com/vector-im/element-web/issues/21396)

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

Preview: https://pr8041--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by ankur12-1610** [comment]
My easiest and quickest bug fix till now :P

**Review by turt2live — APPROVED** [review]
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

(thanks!)

**Review by t3chguy — COMMENTED** [review]
Iff is not a typo.
https://en.m.wikipedia.org/wiki/If_and_only_if#:~:text=In%20logic%20and%20related%20fields,true%20or%20both%20are%20false.

**Comment by ankur12-1610** [comment]
> Iff is not a typo.
> https://en.m.wikipedia.org/wiki/If_and_only_if#:~:text=In%20logic%20and%20related%20fields,true%20or%20both%20are%20false. 

Oh! no,It didn't clicked me at all🥲

Really sorry for it, will a PR which reverts this change.

**Comment by SimonBrandner** [comment]
> > Iff is not a typo.
> > [en.m.wikipedia.org/wiki/If_and_only_if#:~:text=In%20logic%20and%20related%20fields,true%20or%20both%20are%20false](https://en.m.wikipedia.org/wiki/If_and_only_if#:~:text=In%20logic%20and%20related%20fields,true%20or%20both%20are%20false).
> 
> Oh! no,it didn't clicked me at allsmiling_face_with_tear
> 
> Really sorry for it, will a PR which reverts this change.

I would suggest making it `if and if only` to be more explicit...

**Comment by t3chguy** [comment]
Don't worry about it, it doesn't change the meaning in this case, just for future ref iff is fairly common in maths and programming

**Comment by turt2live** [comment]
well, that explains why WebStorm didn't yell at me about it. Thanks for the link :D

**Pull request merged**
