### PR TITLE
Rename Sessions to Devices throughout the app

### PR DESCRIPTION
**Pull request by dbkr**
I've left the keys as-is so this will also need doing in each language, but will continue to say whatever it says currently until then, rather than suddenly needing all new translations.

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Review by t3chguy — COMMENTED** [review]
I think it ought to be consistent with all other places we chose Sessions over Device previously, these are just a sampling:

image

**Comment by americanrefugee** [comment]
@t3chguy I'll pitch in with some product perspective...

When developing the new flows for the first time user experience (FTUE), the new MAS OIDC experience, and QR code sign in, @pmaier1 and I have been advocating for this change.

Although "sessions" has been the historical term we've used, and is the most accurate technically, it's not a word most users encounter in other apps. For example, both WhatsApp and Telegram use the term "Devices". Furthermore, the only time when a "session" becomes a technical distinction is if a user is signed into both Element Web and Element Desktop, which should be rare. In the vast majority of cases for normal users, they will be signed into Element only in one app per device.

In order to avoid confusion and to avoid having to explain what a "session" is, we therefore strongly suggest changing it to "devices".

Not sure how we handle the breaking changes this would create. Maybe @pmaier1 has some insight?

**Comment by t3chguy** [comment]
> if a user is signed into both Element Web and Element Desktop

Or multiple Element Webs, or multiple Element Desktops, or either of the aforementioned + Element X on macOS (Apple Silicon), or a mix of any of those. Or more concretely, they log out and back in, often users expect that to be the same device.

**Comment by americanrefugee** [comment]
> > if a user is signed into both Element Web and Element Desktop
> 
> Or multiple Element Webs, or multiple Element Desktops, or either of the aforementioned + Element X on macOS (Apple Silicon), or a mix of any of those. Or more concretely, they log out and back in, often users expect that to be the same device.

Ok, so there are more scenarios possible... but how common are those for our clients?

More importantly, I'm not convinced that users will get confused when signing in. With QR code sign in, for example, they need to use another device, not just another "session". And it's much clearer to say "Open Element on your mobile device/a desktop device" rather than "Open a session of Element of your mobile/desktop device". Also, if not authenticating with another device then they use a recovery code which has nothing to do with devices. 

WDYT @pmaier1 ?

**Comment by t3chguy** [comment]
> With QR code sign in, for example, they need to use another device, not just another "session"

Not necessarily true. Element X on macOS could be used to scan a QR code from Element Web/Desktop on the same device.

**Comment by t3chguy** [comment]
> ...how? Even if the desktop camera could detect the code, there's no way to actually point it at the screen it's connected to. Right? Unless the use has an external camera... but then that's WAY deep in the weeds of edge cases.

One can have multiple monitors, Apple devices also allow you to use your iPhone as a webcam.

**Comment by richvdh** [comment]
> We should only switch all the wordings and align behavior with EX once it supersedes the existing mobile apps.

Sounds like we're not ready for this yet, then. @dbkr: shall we close it for now, to avoid cluttering the pull-request list?

(We should probably have an issue for this, which can be tracked by https://github.com/element-hq/element-meta/issues/2487)

**Comment by dbkr** [comment]
Oh, yes - this has lots of conflicts so may as well be closed.

**Pull request closed without merging**
