### PR TITLE
Paragraph integration for rich text editor

### PR DESCRIPTION
**Pull request by alunturner**
There has been a large piece of work ongoing in the rich text editor repo to change a fundamental design assumption. This work is dependent on - _all work now complete_.

- ~~paragraph work being merged~~
- ~~release being generated from the rich text editor~~
- ~~and then finally a package.json change here to change to that release version~~

This work will ensure that that refactor plays nicely with element web.

Good news is that this will also fix [issue 24331](https://github.com/vector-im/element-web/issues/24331) in element web as well as resolving [issue 491](https://github.com/matrix-org/matrix-rich-text-editor/issues/491) in the rich text editor.

Changes:

- CSS change to rich text editor
- CSS change to timeline to reflect the fact the message html will now be broken down into paragraphs in some cases
- dependency bump to 0.22.0 for `@matrix-org/matrix-wysiwyg`

Video of performance for multiple cases:

https://user-images.githubusercontent.com/56027671/215100865-0fa02ae5-07c5-43ae-a1d7-3d3e015a2543.mov

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Paragraph integration for rich text editor ([\#10008](https://github.com/matrix-org/matrix-react-sdk/pull/10008)). Contributed by @alunturner.

### CODE REVIEW

**Comment by weeman1337** [comment]
Shift + Enter now produces two new lines. Cursor is on the first line:

Test

Tested on Firefox 109.0.1

**Comment by weeman1337** [comment]
Deleting inside the editor also has some issues:

Test2

They do not appear on develop.

**Review by weeman1337 — CHANGES_REQUESTED** [review]
My tests on the deployment didn't go so well.
Can you have a look?

Do we have Cypress tests, that can cover these cases?
For example, we could take screenshots of the editor in some states.

**Comment by alunturner** [comment]
Thanks for the review @weeman1337.

1. The extra line appearance issue is a discrepancy between Firefox and Chrome behaviour. Fixed in [3a2fb52](https://github.com/matrix-org/matrix-react-sdk/pull/10008/commits/3a2fb52d63d8b773c6ec2d813d74a64903f21098)
2. The select all behaviour is going to require changes to the rich text editor library (and so another release of that before the changes can be seen in element web), [issue has been raised here](https://github.com/matrix-org/matrix-rich-text-editor/issues/540)

I think the best way ahead is to merge this, then fix the issue linked in point 2 as part of the next release

**Review by weeman1337 — APPROVED** [review]

**Review by t3chguy — APPROVED** [review]

**Comment by alunturner** [comment]
PR to fix the cmd a issue is here: https://github.com/matrix-org/matrix-rich-text-editor/pull/548

**Pull request merged**
