### PR TITLE
Fix alignment of RTL messages

### PR DESCRIPTION
**Pull request by dbkr**
Screenshot 2024-07-29 at 17 46 50

Inspired by https://github.com/matrix-org/matrix-react-sdk/pull/5453 but hopefully with the edited marker in the right place.

This is now passing type checking now (albeit not hugely elegantly).

One kicker is that I've had to fix emote bodies. I've done this by wrapping them in the same way. This does mean that if you have an rtl display name, *all* your emotes will be right-justified, even if you're emoting in an ltr language, like so:

Screenshot 2024-07-31 at 12 54 26

...this is a bit weird perhaps? But possibly the least weird of all options.

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Comment by ahangarha** [comment]
Good move.

But it seems there are some spacing issues
image

**Comment by dbkr** [comment]
I think the right hand side one was just an erroneous space character in the actual text. The one between the text and the edited marker should hopefully be simple enough to fix.

**Review by t3chguy — APPROVED** [review]
Looks sane

**Comment by SPiRiT369** [comment]
As RTL user, rtl support is very useful for me. But in my opinion, this change makes the chat experience worse and not aesthetic.
If the browser window is large or maximized and you have a flow of messages, this makes it unclear who wrote what, and your eyes need to jump to the left to see who wrote the messages.
IMHO without aligning the avatars+names to the right as well, this change is irrelevant and does not serve the purpose.
The proper way to do that (IMHO) is to keep the previous style (rtl text aligned to the left). The decision about aligning messages to the right should be based on the UI language (and if that's a problem then by a system setting). And when in RTL mode, the WHOLE conversation (including LTR messages, avatars and names) should align to the right as well.

Excuse my poor gimp abilities, it's just to demonstrate how more aesthetic it looks having the messages on the same side with the avatars+names, even when ltr/rtl text is not adjusted correctly.

image

**Pull request merged**
