### PR TITLE
don't collapse spaces in inline code blocks

### PR DESCRIPTION
**Pull request by HarHarLinks**
Fixes vector-im/element-web#6051

before:
image

after:
image

Signed-off-by: Kim Brose <kim.brose@rwth-aachen.de>

Notes: don't collapse spaces in inline code blocks (https://github.com/vector-im/element-web/issues/6051)

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * don't collapse spaces in inline code blocks (https ([\#7328](https://github.com/matrix-org/matrix-react-sdk/pull/7328)). Fixes vector-im/element-web#6051. Contributed by @HarHarLinks.

Preview: https://61b368100619ce41696a3e49--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by andybalaam** [comment]
Nice! It really is a simple as that. Thank you.

Needs a lint fix:
```
res/css/views/rooms/_EventTile.scss
--
 <span class="term-fg2">472:4</span>  <span class="term-fg31">✖</span>  Unexpected whitespace at end of line   <span class="term-fg2">no-eol-whitespace</span>
```

**Review by andybalaam — APPROVED** [review]

**Comment by HarHarLinks** [comment]
I just noticed that the room list preview still collapses spaces. I currently have no idea how to fix that.

**Comment by andybalaam** [comment]
> I just noticed that the room list preview still collapses spaces. I currently have no idea how to fix that.

I think that can be dealt with separately.

**Comment by HarHarLinks** [comment]
what's up with the changelog?
> don't collapse spaces in inline code blocks (https (#7328).

**Comment by andybalaam** [comment]
> what's up with the changelog?

No idea, but I think it gets the message across ;-)

**Comment by andybalaam** [comment]
Thank you, nice change!

**Comment by t3chguy** [comment]
Going to revert this as it causes a much worse issue:

`docker run -it --rm --mount type=volume,src=synapse-data,dst=/data -e SYNAPSE_SERVER_NAME=localhost -e SYNAPSE_REPORT_STATS=no -p 8008:8008 matrixdotorg/synapse:v1.47.1` gets clipped

image

**Comment by t3chguy** [comment]
actually switching to `pre-wrap` is the right thing to do

**Pull request merged**
