### PR TITLE
upgrade to twemoji 13.0.0

### PR DESCRIPTION
**Pull request by ara4n**
This upgrades twemoji-mozilla font to use twemoji 13.0.0 using https://github.com/matrix-org/twemoji-colr/, following the README instructions pretty much verbatim.

I've given the new glyphs a quick test on the COLR font and they all look to come out okay, apart from the transgender flag on Chrome (🏳️‍⚧️); Firefox however gets it right.  Also, Chrome doesn't combine together some new ligatures (e.g. 🐻‍❄️ for polar bear) in the composer correctly.

~~However, there are lots of missing glyphs on SBIX :(~~

Fixes vector-im/riot-web#13365

### CODE REVIEW

**Comment by ara4n** [comment]
should fix https://github.com/vector-im/riot-web/issues/13365, but marking as draft until the SBIX mess is sorted

**Comment by ara4n** [comment]
By reverting https://github.com/matrix-org/twemoji-colr/commit/ec37f7d95d0cadd080abb3e05bef980138bffe7b I now have an SBIX variant that works on Chrome (albeit with wrong vertical offset) but not on FF, so need to fiddle with that patch some more.

**Comment by ara4n** [comment]
note to self: re-saving it in Glyphs.app might fix it

**Comment by ara4n** [comment]
The existing SBIX font also doesn't work on Firefox on macOS (comes up all black squares :/)

**Comment by ara4n** [comment]
https://github.com/matrix-org/twemoji-colr/commit/407a1f4 unbreaks SBIX on Chrome/macOS.  Firefox is still all black squares, but i just realised that's because Firefox doesn't do SBIX (duh).

So, I think this is good to go.

**Comment by ara4n** [comment]
(still needs testing on windows & linux tho)

**Comment by ara4n** [comment]
...and this now also updates the reaction picker to support them.

**Comment by t3chguy** [comment]
Works in latest stable Windows and Firefox on Windows 10

Doesn't work for some things in the composer on Chrome:
image
image
In firefox it is fine:
image


Does lead to a fun condition of trying to backspace remove the emoji it instead turns into a bear:
image

**Comment by ara4n** [comment]
i /think/ the chrome composer thing is a chrome bug.

**Pull request merged**
