### PR TITLE
Add eslint rule to disallow spaces inside of curly braces

### PR DESCRIPTION
**Pull request by lukebarnard1**

### CODE REVIEW

**Comment by t3chguy** [comment]
does this hit both props and elements?
I.e 
```
<Foo thing={true}>
    { thing }
</Foo>
```

or does it prevent spaces for `{ thing }` too?

**Comment by lukebarnard1** [comment]
@t3chguy it does now!

**Comment by t3chguy** [comment]
AWESOME!!

**Comment by dbkr** [comment]
The spaces look a bit weird to me in things like: 

```
{ _t(...
) }
```

...but it is nice that it's consistent.

**Pull request merged**
