### PR TITLE
Autocomplete on Return

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/4721

### CODE REVIEW

**Comment by lukebarnard1** [comment]
I'm not sure this does fix the issue referenced. https://github.com/vector-im/riot-web/issues/4721 is about pressing Enter when the Autocompleter already has focus.

**Comment by t3chguy** [comment]
@lukebarnard1 but when does the Autocompleter actually have focus? Surely focus is always on the composer input, this PR basically says if there is a completion selected (Tabbed in) and you hit enter, it'll complete instead of sending

**Comment by dbkr** [comment]
For me, typing `:p`, waiting a bit and then pressing enter actually gives me a pill for the test user whose display name starts with 'p' with this PR (if I press tab I still get the pig).

However, yes, what you say in the bug about typing `:p` and then maybe getting a pig rather than sending the ascii smiley (depending on exactly how long you took between pressing the 'p' key and the return key) feels distinctly ropey. I'm not sure what the answer is here.

**Comment by lukebarnard1** [comment]
I thought the issue was distinctly about the scenario when you:
 1. type ":tr" or anything that causes the AutoCompleter to appear,
 1. press <kbd>tab</kbd> a few times,
 1. press <kbd>enter</kbd> expecting the AutoCompleter to hide and for your completed thing to be in the composer with your cursor after it.

With that in mind, I find it strange that `moveAutocompleteSelection` is used, which would move the selection before forcing the completion.

**Comment by lukebarnard1** [comment]
@t3chguy are you likely to do anything on this?

**Comment by lukebarnard1** [comment]
@t3chguy should I close this or are you likely to be able to return to it?

**Comment by t3chguy** [comment]
I will redo it post-Slate.

**Pull request closed without merging**
