### PR TITLE
Align input area with event body's first letter in a thread on IRC/modern layout

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/vector-im/element-web/issues/22252

|Before|After|
|---------|------|
|before1|after1|

I guess those declarations became obsolete when the latest spacing update was implemented for the thread panel.

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Align input area with event body's first letter in a thread on IRC/modern layout ([\#8636](https://github.com/matrix-org/matrix-react-sdk/pull/8636)). Fixes vector-im/element-web#22252. Contributed by @luixxiul.

### CODE REVIEW

**Comment by t3chguy** [comment]
I think this specifically was made wider as otherwise its a bit too narrow, lets ask design

**Review by t3chguy — COMMENTED** [review]
Clearing review

**Review by t3chguy — APPROVED** [review]
Ah yes you reminded me, I did this work to begin with based on an ask from Jano to align it, so all good, thanks!!

**Comment by luixxiul** [comment]
Fixed!

**Review by t3chguy — APPROVED** [review]
Thanks!

**Comment by luixxiul** [comment]
@t3chguy thanks for reviewing!

**Pull request merged**
