### PR TITLE
Fix flaky Percy tests of `ReplyChain`

### PR DESCRIPTION
**Pull request by luixxiul**
For https://github.com/vector-im/element-web/issues/24881

This PR intends to address the flaky Percy snapshot tests of `ReplyChain` by applying a media query for Percy.

Here is the list of the snapshots which should be addressed with this PR:

- [`EventTile with reply chains on modern layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26062349/changed/1452736595?browser=chrome&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested%2Capproved&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920)
- [`EventTile with reply chains on compact modern layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26062349/changed/1452736597?browser=chrome&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested%2Capproved&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920)
- [`EventTile with reply chains on IRC layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26062349/changed/1452736596?browser=chrome&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested%2Capproved&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920)
- [`EventTile with reply chains on bubble layout`](https://percy.io/dfde73bd/matrix-react-sdk/builds/26062349/changed/1452736598?browser=chrome&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested%2Capproved&viewLayout=overlay&viewMode=new&width=1920&widths=1024%2C1920)

This PR also adds another step to check whether a sent receipt is rendered, so snapshots should capture the receipt consistently, mitigating the risk of flakiness.

For a reviewer: before merging, please add `X-Needs-Percy` to check whether the strokes color and the profile name color is same (`$username-variant1-color`, which is `#368bd6` on light theme).

type: task

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]
Looks plausible. Let's see how the percy snapshots come out.

**Comment by luixxiul** [comment]
The border color issue seems to have been fixed (`$username-variant1-color` seems to be applied to the border), but this time the different list style was applied (except Firefox).

| |After|
|-|-|
|Screenshot from 2023-03-27 19-30-27|Screenshot from 2023-03-27 19-30-40|

I guess it is because the declaration "list-style-type: none" of `.mx_RoomView_MessageList` this style block is not applied to `mx_EventTile_last` on the tests above:

It can be seen on [another test](https://percy.io/dfde73bd/matrix-react-sdk/builds/26180847/changed/1458319335?browser=safari&browser_ids=33%2C34%2C35%2C36&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=303&widths=133) as well. 

Screenshot from 2023-03-27 19-55-59

Adding a commit which should fix the issue.

**Comment by andybalaam** [comment]
Percy snapshots look reasonable, so I think this leaves us in a better state than we were in before.

**Comment by luixxiul** [comment]
The previous commit failed to fix the list style issue. I'm going to create an issue for it!

**Pull request merged**
