### PR TITLE
Tidy devDeps, all the webpack stuff lives in the layer above

### PR DESCRIPTION
**Pull request by t3chguy**

### CODE REVIEW

**Comment by turt2live** [comment]
these were required at a time to load the webpack stuff correctly in higher layers - is this no longer the case?

**Comment by jryans** [comment]
@t3chguy Please see the question above. 😄

**Comment by t3chguy** [comment]
Given that we don't do the js-sdk loader hack anymore I believe so.
I will double check on a fresh checkout just to make sure.

**Review by jryans — APPROVED** [review]
Assuming it looks good in a fresh checkout, it seems reasonable to me.

**Comment by t3chguy** [comment]
Works fine in a fresh checkout!

**Pull request merged**
