### PR TITLE
Fix: Clicking on members pile does nothing.

### PR DESCRIPTION
**Pull request by manancodes**
## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Fixes https://github.com/vector-im/element-web/issues/26164
Signed-off-by: Manan Sadana manancodes.dev@gmail.com

This was the behaviour before the fix:

Clicking on pile does nothing.

https://github.com/matrix-org/matrix-react-sdk/assets/54790263/587d5eff-7565-49f0-bad7-220059027900

And this is the behaviour after the fix:

Clicking on pile opens members list.

https://github.com/matrix-org/matrix-react-sdk/assets/54790263/4975d7db-61ec-484a-a180-6b4522bda12b

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix: Clicking on members pile does nothing. ([\#11657](https://github.com/matrix-org/matrix-react-sdk/pull/11657)). Fixes vector-im/element-web#26164. Contributed by @manancodes.

### CODE REVIEW

**Review by germain-gg — CHANGES_REQUESTED** [review]
I'm not sure I understand why there's two PRs? https://github.com/matrix-org/matrix-react-sdk/pull/11656 seems to already fix the problem?

Moreover the solution here with `onClick` on a `div` element is not accessible thus requiring more work. as well as some tests to avoid regressions on this in the future.

**Comment by manancodes** [comment]
> I'm not sure I understand why there's two PRs? #11656 seems to already fix the problem?
> 
> Moreover the solution here with `onClick` on a `div` element is not accessible thus requiring more work. as well as some tests to avoid regressions on this in the future.

@germain-gg The output of these 2 PRs is different. 

1. #11656 - If I click on a user icon, the user profile opens up. If I click the more(...) button, the members list opens.(Explained in detail with recordings in the PR itself)

> This solution makes more sense to me, but the problem is, hovering over this pile shows a tooltip which says "See all 3357 Members" which makes it confusing and is a bad user experience because only the more(...) button will open the list.
> Screenshot 2023-09-25 at 2 42 49 PM

2. #11657 - Clicking anywhere on the pile will open the members list. Which is more aligned with the tooltip and the previous implementation before the regression. But again, it is not a complete solution.


Which one should I go ahead with? 

Meanwhile I'll research about best workarounds for onClick on non-accessible elements, any assistance or ideas will surely help.

**Review by richvdh — DISMISSED** [review]
> Fix: Clicking on pile opens members list

In addition to @germain-gg's comments: I'm not sure this is a good description of what this PR is doing, and I'm having a little trouble wrapping my head around what we are trying to achieve in this PR.

The wording "Fix: Clicking on pile opens members list" makes it sound like the fact that the members list opens when you click on the [avatar?] pile is a bug that you are trying to fix, but I don't think that is the case?

**Comment by manancodes** [comment]
@richvdh  I'm sorry for the confusion.

I have created 2 pull requests for 2 possible solutions for this issue https://github.com/vector-im/element-web/issues/26164 , please see my latest comment on the issue explaining both the fixes.

I have updated the description.

**Comment by manancodes** [comment]
@germain-gg 
I have updated the snapshots for the tests but it is still failing the tests. I think it is because of the ids that are appended to the css classes. What can I do to fix this?

**Comment by manancodes** [comment]
All tests are passing now. Thanks for the guidance.

**Comment by manancodes** [comment]
I think you need to resolve the requested changes.

**Review by germain-gg — APPROVED** [review]

**Pull request merged**
