### PR TITLE
Show room alias in plain/formatted body

### PR DESCRIPTION
**Pull request by SimonBrandner**
This is an alternative to [#5747](https://github.com/matrix-org/matrix-react-sdk/pull/5747)
Fixes [#16660](https://github.com/vector-im/element-web/issues/16660)

### CODE REVIEW

**Comment by turt2live** [comment]
This doesn't seem to be doing what it should be. 

This PR:
image

Old (expected behaviour):
image

**Review by turt2live — CHANGES_REQUESTED** [review]
github says I need a comment to request changes, and I forgot to put my comment in this box

**Comment by SimonBrandner** [comment]
I was focusing on the `formatted_body` field so much I totally missed the `body` :facepalm: I am not sure how to fix this, but I'll try to find out

**Review by turt2live — APPROVED** [review]
that seems to do the right thing :D

**Comment by turt2live** [comment]
have cherry-picked to release too

**Comment by SimonBrandner** [comment]
@turt2live, I was just going to ask if I should do that :D

**Pull request merged**
