### PR TITLE
Display redaction reason

### PR DESCRIPTION
**Pull request by SimonBrandner**
This PR adds displaying redaction reason.

Depends on [Decrypt redaction events #1589](https://github.com/matrix-org/matrix-js-sdk/pull/1589).

### CODE REVIEW

**Review by turt2live — CHANGES_REQUESTED** [review]
We don't display redaction reasons because they are an abuse vector. This is the sort of thing that probably needs design work before much progress can be made.

**Comment by SimonBrandner** [comment]
@turt2live Oh, I didn't know that. Should I leave this open?

**Comment by turt2live** [comment]
up to you, I'd say. I'm not sure how soon a designer will be able to visit to take a look.

**Comment by SimonBrandner** [comment]
Closing to lower the number of open PRs in the repo. I might reopen this one day.

**Pull request closed without merging**
