### PR TITLE
Add jsx-a11y eslint plugin

### PR DESCRIPTION
**Pull request by kerryarchibald**
~~Using recommended rules for the plugin generates too many errors, so while this is still a WIP the plugin is added in this repo and rules are enabled one by one. 
After we reach a reasonably fixed state this should be moved to the matrix-org/react eslint plugin.~~

- Updates `eslint-plugin-matrix-org`
- adds `matrix-org/a11y` plugin to eslint config
- fixes two low hanging fruit - `anchor-has-content` and `no-redundant-roles` 

All other violated rules are ignored in eslint, will be enabled as they are fixed (eg https://github.com/matrix-org/matrix-react-sdk/pull/7444)

Report with recommended rules on latest develop:
Screenshot 2021-12-21 at 17 32 12

[report.html.txt](https://github.com/matrix-org/matrix-react-sdk/files/7756765/report.html.txt)

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

Preview: https://61d2c15586686adaa42e6716--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
yessssssssssssss

**Comment by t3chguy** [comment]
Shouldn't this be in our matrix-org eslint plugin instead?

**Comment by turt2live** [comment]
my excitement blinded me. Yes, it should.

**Comment by kerryarchibald** [comment]
@turt2live @t3chguy eslint repo PR: https://github.com/matrix-org/eslint-plugin-matrix-org/pull/19

**Review by turt2live — APPROVED** [review]
Thanks :)

In general, please avoid force pushing after a review has been given - it puts extra work on the reviewer and is more time consuming for everyone.

**Pull request merged**
