### PR TITLE
Fix screensharing in 1:1 calls

### PR DESCRIPTION
**Pull request by dbkr**
Interface got changed in the group call branch and the modals don't have enough typing to catch it.

Fixes https://github.com/vector-im/element-web/issues/23808

Draft while I see if there's a test or better typing that could be added to catch this.

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix screensharing in 1:1 calls ([\#9612](https://github.com/matrix-org/matrix-react-sdk/pull/9612)). Fixes vector-im/element-web#23808.

### CODE REVIEW

**Comment by dbkr** [comment]
I've failed to get typescript to pass the types through correctly and this calls the static Modal interface and is in the desktop app, so it going to be very difficult to write a test for until we have desktop app tests. Un-drafting so we can get the fix out.

**Review by robintown — APPROVED** [review]

**Review by t3chguy — CHANGES_REQUESTED** [review]
Did the js-sdk have a breaking change for this? Did we somehow miss this change? Can we add better typing or tests to prevent a re-regression?

**Comment by dbkr** [comment]
Indeed - we missed a breaking change in https://github.com/matrix-org/matrix-js-sdk/pull/2530

I've published my thus far unsuccessful type experiments on https://github.com/matrix-org/matrix-react-sdk/pull/9614/files - if someone with more typescript-fu than I can see where I'm going wrong then we could type the modal stuff properly to catch this.

**Review by SimonBrandner — APPROVED** [review]

**Comment by t3chguy** [comment]
image

As a stopgap you can use this typing mechanism

**Comment by robintown** [comment]
@t3chguy Feel free to merge this yourself before the release as I may not be available tomorrow

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
