### PR TITLE
Support data-mx-border-color on blockquotes

### PR DESCRIPTION
**Pull request by turt2live**
This is useful for those looking to create warning, error, or otherwise slightly more colorful notices. 
image

### CODE REVIEW

**Comment by dbkr** [comment]
Looks reasnable to me. @ara4n ?

**Comment by ara4n** [comment]
hm. need to think about this.

**Comment by turt2live** [comment]
Notably, this is probably possible with https://github.com/matrix-org/matrix-doc/pull/828 and may be a better solution, instead of blockquote custom coloring.

**Comment by ara4n** [comment]
Yeah. the options here feel to be:
 * Cosmetic voodoo specifically for borders on blockquotes (as per here)
 * More generic voodoo for applying select bits of CSS to contents (e.g. `data-mx-css-border-left-color` which could apply to anything, rather than specialcasing blockquotes)
 * Metadata on the event to let the client decide how to show the severity.
   * This could either be as per @Half-Shot's proposal in https://github.com/matrix-org/matrix-doc/pull/828 - i.e. a custom status field specifically for `m.notice` events...
   * ...or as per my proposal, where you mix-in an `m.severity` event, which then becomes a consistent matrix-wide manner for flagging severities of arbitrary events (and would be symmetrical also with the idea of having `m.confidentiality` mixins or similar in future).  Predictably this is still my preferred option in an ideal world, as it preserves the semantic significance that is being conferred (e.g. you could conceivably have a client which only shows high-severity messages, etc; a bit like log levels).  And it separates the cosmetics from the semantics.  I'm not sure I want to think how a cmdline client with ANSI colour codes would handle an HTML data-mx-border-color for instance).

So, I would still like to change events so that they can have mixins like this (e.g. you mixin a thumbnail if you want your event to have a thumbnail; you mixin a severity if you want it to have a nice red border or equivalent; you mixin an `net.arasphere.temperature` event if you want to include some semantic metadata about the messages; etc).  https://docs.google.com/document/d/1hB9PV-3cj4GB2qRQYXFUJykgl0QmrKoBtHhRXf4SKP0/edit is my latest iteration to try to close this.

However, i feel guilty about having this PR be blocked on that :/  @turt2live: thoughts from an relatively independent perspective would be hugely appreciated, as every time the core team has tried to solve this one we've tied ourselves up in knots :(

**Comment by turt2live** [comment]
For reference: This PR came about because someone was PRing Slack attachments to my webhooks bridge. Blockquotes were the quick and easy route based on how Riot renders them and how similar it is in structure to Slack attachments.

The idea of mixins makes sense, as it seems to allow event senders to suggest how an event should look, or at least provide the information needed for a client to render it. This is close to how [Slack does attachments](https://api.slack.com/docs/message-attachments), [Discord does embeds](https://discordapp.com/developers/docs/resources/channel#embed-object), and even [Minecraft does messages](http://wiki.vg/Chat#Current_system_.28JSON_Chat.29). Having the ability to throw the individual parts of a message at a client to render makes sense, although it would mean that clients would have to support the individual fields as well. Requiring a fallback of HTML or text in the event would mean that clients not willing to build support for the fields could still display a reasonably close approximation on how it should look. 

Being able to mix in behaviour would possibly be useful as well. For instance, being able to flag a message as important has some kind of different audio cue on the client (paging alerts), or being able to supply a couple buttons for users to click on.

Of course, these are all wishlist items. Blocking the PR is no problem at all. Like I mentioned earlier in this wall of text, it was part of a quick and easy solution, not necessarily the right one.

**Comment by turt2live** [comment]
Closing this in hopes that it can be resurrected when/if mixins land.

**Pull request closed without merging**
