### PR TITLE
Fix EventIndex crashing with response from Dendrite

### PR DESCRIPTION
**Pull request by handlerug**
Dendrite returns null, not undefined. Check for null as well.

Signed-off-by: Umar Getagazov <umar@handlerug.me>

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Notes: Fix a bug where indexing E2E rooms would fail with Dendrite as the homeserver

Type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix a bug where indexing E2E rooms would fail with Dendrite as the homeserver ([\#9913](https://github.com/matrix-org/matrix-react-sdk/pull/9913)). Contributed by @handlerug.

### CODE REVIEW

**Comment by t3chguy** [comment]
Your PR needs to be against develop, not master.

**Comment by handlerug** [comment]
Oops, sorry! Changed the base branch.

**Comment by t3chguy** [comment]
https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv3roomsroomidmessages doesn't say anything about `state` being allowed to be null? Nor is that ever used as an example, I'd argue this is a spec compliance bug in Dendrite

**Comment by handlerug** [comment]
Hm, indeed. I agree. Sent a PR to the Dendrite project. Thanks and sorry for the noise!

**Pull request closed without merging**
