### PR TITLE
Fix message search summary text

### PR DESCRIPTION
**Pull request by jryans**
This repairs the message search summary text, which regressed in
https://github.com/matrix-org/matrix-react-sdk/pull/5416. We can't use the `one`
/ `other` syntax here since there are two numbers and they are both strings.

Fixes https://github.com/vector-im/element-web/issues/15766

### CODE REVIEW

**Comment by t3chguy** [comment]
Oh right, we *can* use `one` `other` here by passing a numeric count variable which we do not use and renaming the `count` string variable to countStr or something.

**Review by t3chguy — APPROVED** [review]
LGTM other than comment

**Comment by jryans** [comment]
Right, the `count` was messing things up, including the string generation script. I renamed it to `rooms` instead.

**Comment by t3chguy** [comment]
Okay, but we can still use count for pluralisation to fix the room(s)

**Comment by jryans** [comment]
> Okay, but we can still use count for pluralisation to fix the room(s)

Oh, I see what you mean now, have both `count` and `countStr`, okay.

**Review by t3chguy — APPROVED** [review]
Thanks!

**Pull request merged**
