### PR TITLE
Do not honor string power levels

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/element-web/issues/16018
Requires https://github.com/matrix-org/matrix-js-sdk/pull/1754

### CODE REVIEW

**Comment by aaronraimist** [comment]
CI failure seems unrelated to these changes

**Comment by gsouquet** [comment]
> CI failure seems unrelated to these changes

Could you maybe pull and merge the latest `develop` into this branch and that should fix the CI failure you experienced?
Apologies about that, it appears that something unexpected landed in `develop` and the CI is a bit too rigid

**Comment by jryans** [comment]
> CI failure seems unrelated to these changes

Merging develop may resolve this CI error.

**Review by jryans — APPROVED** [review]
Thanks, these all seem reasonable to me! 😄

**Comment by jryans** [comment]
@aaronraimist Does it actually require the JS SDK side...?

**Comment by aaronraimist** [comment]
Goes with the JS PR is probably a better way to put it, probably doesn’t require it

**Comment by jryans** [comment]
@aaronraimist Could you resolve the conflict that has appeared here?

**Comment by aaronraimist** [comment]
Done

**Comment by aaronraimist** [comment]
@jryans does anything else need to happen here?

**Comment by jryans** [comment]
Ah no, looks good. 😄 Sorry, I check my review queue more often than general GH notifications, so re-requesting review is a faster way for me notice things. Perhaps I need to change my notifications workflow again... 😅

**Pull request merged**
