### PR TITLE
Add dummy translation function to mark translatable strings

### PR DESCRIPTION
**Pull request by pafcu**
Signed-off-by: Stefan Parviainen <pafcu@iki.fi>

Add a new function `_td()` which is used to mark strings as translatable in contexts where `_t()` does not work (i.e. before translations have been initialized). It does not actually do anything with the strings, just returns the input. You still need to call `_t()` later to do the actual translation.

### CODE REVIEW

**Comment by ara4n** [comment]
this is great, thanks!  I suspect it needs to be added to the translation readme otherwise nobody will understand how to use it...

**Comment by pafcu** [comment]
Sure, I'll add it to the documentation too. However, I wanted to see if I get some protests regarding e.g the function name (I suppose it _might_ be better with e.g. `translatable()`, or not having the leading underscore), but I decided to go with something as similar as possible to the existing `_t()` function. The one-letter difference does make it easier to extract strings using a regular expression since you can just find everything using `_t(d|Jsx)?` rather than something more complex.

**Comment by ara4n** [comment]
`_td()` is fine by me; we already have `_tJsx` and huffmanizing super-common special functions like this.  plus it'll be trivial to change in future!

**Comment by pafcu** [comment]
https://github.com/vector-im/riot-web/pull/5110 now also includes a commit to document when to use `_td()`

**Comment by ara4n** [comment]
lgtm - thanks!

**Comment by lukebarnard1** [comment]
@pafcu I've reviewed https://github.com/vector-im/riot-web/pull/5110

**Pull request merged**
