### PR TITLE
Remove margin from E2E icon between avatar and hidden event

### PR DESCRIPTION
**Pull request by luixxiul**
Closes https://github.com/vector-im/element-web/issues/22186

This PR removes margin from warning E2E icon between an avatar and a hidden event.

|Before|After|
|---------|------|
|before|after|
||after|

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Remove margin from E2E icon between avatar and hidden event ([\#8584](https://github.com/matrix-org/matrix-react-sdk/pull/8584)). Fixes vector-im/element-web#22186. Contributed by @luixxiul.

### CODE REVIEW

**Comment by luixxiul** [comment]
The same style should be applied to the normal E2E icon as well.

**Review by turt2live — COMMENTED** [review]
clearing code review while in draft

(please open as a draft to start so it doesn't request our review, pinging the entire team).

**Comment by luixxiul** [comment]
This time I noticed that the solution was not enough after creating the PR so I changed the status to address the remaining issue

**Comment by luixxiul** [comment]
Fixed the conflict.

**Review by turt2live — APPROVED** [review]
argh, another ancient PR :(((((

**Pull request merged**
