### PR TITLE
Fix broken thread list timestamp display

### PR DESCRIPTION
**Pull request by gsouquet**
Fixes https://github.com/vector-im/element-web/issues/20556

I have encountered a browser issue on Chromium that makes the ellipsis not work for the display name at the coloured element level. Which means that it does not fulfill the requirement set by @janogarcia to have the ellipsis match the colour and font weight

Screen Shot 2022-01-14 at 16 21 14

---
This PR currently has no changelog labels, so will not be included in changelogs.

Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.

Preview: https://61e6e1a08c22dc0fc49ab71a--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]

**Review by janogarcia — CHANGES_REQUESTED** [review]
**Thread summary issues**

Now the thread summary content doesn't truncating correctly and it's overflowing the container. Plus, the background on hover the thread is split into two areas.

thread-summary

**Display name truncation**

As for the display name truncation I'd suggest trying a slightly different approach, if possible.

In a quick test, I disabling just the `text-overflow` property for `.mx_SenderProfile` and applied the following styles to `.mx_SenderProfile_displayName`

```
display: block;
overflow: hidden;
text-overflow: ellipsis;
```

and it worked as expected, see screenshot below, but I haven't tested it in other contexts or under other conditions (e.g. displaying a disambiguated name).

truncation

**Comment by gsouquet** [comment]
> and it worked as expected, see screenshot below, but I haven't tested it in other contexts or under other conditions (e.g. displaying a disambiguated name).

The approach that you suggest above will not work when displaying disambiguated sender profiles. The solution that I brought here is not ideal but will truncate things correctly for all scenarios

**Comment by janogarcia** [comment]
@gsouquet You're going to hate me for this, but I'm still pushing for the correct behavior and styling to get implemented. Here's a quick attempt at it, showing a worst case scenario (long display name, plus Matrix ID for sender profile disambiguation).

text-truncation

---

Added styles:

```
.mx_SenderProfile {
    display: inline-flex;
    /*
    not a fan of the magic number here, but I just tweaked 
    the hardcoded value of the current implementation
    */
    max-width: calc(100% - 96px);
}

.mx_SenderProfile_displayName {
    flex: none;
    max-width: 100%;
}

.mx_SenderProfile_mxid {
    flex: 1;
}
```

**Review by janogarcia — CHANGES_REQUESTED** [review]
I always seem to forget to hit the Review button before posting my PR review comments. Please find them in [my previous comment](https://github.com/matrix-org/matrix-react-sdk/pull/7549#issuecomment-1015225388). Hope it helps! 🤞

**Review by janogarcia — APPROVED** [review]
@gsouquet Thanks for updating the truncating behavior. :)

**Pull request merged**
