### PR TITLE
[WIP] Rewrite MFileBody

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/16668

Screenshot_20210620_143010

This is a _very rushed_ attempt to fix the above-mentioned issue. 

+ [ ] Fix behaviour in file panel
+ [ ] Check if everything works as expected

### CODE REVIEW

**Comment by robintown** [comment]
How is this supposed to work for encrypted files, given that those currently require two clicks on the hyperlink to decrypt and then download? I just tried downloading an encrypted file, and it looks like it downloaded in an encrypted form.

**Comment by SimonBrandner** [comment]
> How is this supposed to work for encrypted files, given that those currently require two clicks on the hyperlink to decrypt and then download? I just tried downloading an encrypted file, and it looks like it downloaded in an encrypted form.

It should decrypt the file and then download it but as I say in the PR description, this is _very_ rushed, so it doesn't work :P

**Comment by robintown** [comment]
Makes sense, though not sure if you're aware but you might run into some problems with that approach: vector-im/element-web#16087

**Comment by turt2live** [comment]
Just FYI that I'll be in this same area this week to move and fix the download button, which includes potential architecture changes.

**Comment by SimonBrandner** [comment]
Closing in favour of https://github.com/matrix-org/matrix-react-sdk/pull/6386

**Pull request closed without merging**
