### PR TITLE
Bridge limitation warnings

### LINKED ISSUE #701: "Long messages" are annoying; prefer to disallow entering them on the Matrix UI
When a Matrix user is connected to a channel which is bridged to IRC, limitations on message length should be communicated to the Matrix client, which should enforce them. I find the "long message, click here to read" links incredibly irritating and won't be reading them, and may ban Matrix users from my channels if they use them.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes https://github.com/matrix-org/matrix-appservice-irc/issues/701

Paired with https://github.com/matrix-org/matrix-appservice-irc/pull/1057

Example of the popover: 
alertv2

Example of the new settings page details:

image

This feature looks at the bridge state event(s) for a room, and then checks limitations described in those events against the message content a user is about to send. The objective is to avoid matrix users sending messages that are incompatible or badly represented in a bridge rather than mangling the format on the bridge and upsetting remote users.

This PR currently fixes one problem: Matrix users send long messages which the IRC bridge is forced to store in a pastebin, rather than sending over the wire as IRC traditionally dislikes long messages.

There will be an extension MSC coming soon to cover the new keys added to MSC2346.

In terms of what's left to do:
- [ ] ~~Limit users ability to send messages that breach limitations~~ (N/A - I don't think we want this)
- [ ] ~~Allow users to permanently disregard the warning~~ (N/A - we no longer block the user from sending)
- [x] Highlight the limitations in the bridge settings tab

### CODE REVIEW

**Comment by t3chguy** [comment]
What about reactions/edits/redactions? Shouldn't they warn too?

**Comment by Half-Shot** [comment]
> What about reactions/edits/redactions? Shouldn't they warn too?

Yep, this is just a first pass. Once there is general happiness noises from product/design about the idea of a bridge interrupting your messaging, I'll want to add limitation categories for event types.

**Comment by t3chguy** [comment]
> Matrix users send long messages which the IRC bridge is forced to store in a pastebin, rather than sending over the wire as IRC traditionally dislikes long messages.

The copy in the dialog doesn't explain that this is what would happen if they ignore the warning.

**Comment by Half-Shot** [comment]
>The copy in the dialog doesn't explain that this is what would happen if they ignore the warning.

Yeah, this is a sore point. The IRC bridge can't send it's own warnings because they will appear as English in the client, and I want to keep the ability for i18n. Riot however doesn't know about the pastebin aspect, unless we stick some sort of key into the event content to state this.

I was tempted to have a `"consequeneces": ["pastebin"]` and leave it up to Riot to translate that to words, but I think it's a bit too bridge specific to spec. The one thing we could do is a `"consequeneces": ["org.matrix.appservice-irc.pastebin"]` and Riot would know to translate irc bridge specific issues into words.

Alternative solutions I might have missed v.welcome though :)

**Comment by ptman** [comment]
I'm sure you've already covered splitting long messages (splitlong.pl & similar), but where?

**Comment by Half-Shot** [comment]
>I'm sure you've already covered splitting long messages (splitlong.pl & similar), but where?

We've not covered line splitting on the client-side. This a deliberately dumb metric that counts characters to give a rough warning. I'm not sure how best to factor in line splitting as a warning.

**Pull request closed without merging**
