### PR TITLE
Remove suffix and prefix from login input username

### PR DESCRIPTION
**Pull request by lukebarnard1**
This is an attempt reduce confusion when entering a custom home server: https://github.com/vector-im/riot-web/issues/3736

### CODE REVIEW

**Comment by lukebarnard1** [comment]
>to merge to unstable

Where is said unstable?

**Comment by lukebarnard1** [comment]
Blocked on asking @lampholder whether we want this releasable (it'd be quite annoying to flip-flop between different UIs)

**Comment by dbkr** [comment]
(For the record, the answer to these question was that the branch is 'experimental' and you just merge it in manually and push, right now).

**Comment by lukebarnard1** [comment]
This was pushed to `experimental`

**Pull request merged**
