### PR TITLE
Initialize line-height for room name on IRC layout

### PR DESCRIPTION
**Pull request by luixxiul**
This PR resets `line-height` value of the room name, inherited from `mx_IRCLayout` and applied globally, whether elements are messages or not. This change ensures space between lines when the room name is wrapped, and improves UX especially in languages whose characters fill space for each line, such as CJK.

Fixes https://github.com/vector-im/element-web/issues/24742

|Before|After|
|---------|------|
|Screenshot from 2023-02-20 17-42-28|Screenshot from 2023-02-20 17-39-30|

Signed-off-by: Suguru Hirahara <luixxiul@users.noreply.github.com>

type: defect
Notes: Ensure space between wrapped lines of room name on IRC layout

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Ensure space between wrapped lines of room name on IRC layout ([\#10188](https://github.com/matrix-org/matrix-react-sdk/pull/10188)). Fixes vector-im/element-web#24742. Contributed by @luixxiul.

### CODE REVIEW

**Comment by luixxiul** [comment]
Blocks on https://github.com/matrix-org/matrix-react-sdk/pull/10273, which implements a Percy screenshot test with long strings on IRC layout.

**Review by florianduros — APPROVED** [review]
Tested ✅

Thanks for your contribution!

**Comment by luixxiul** [comment]
Thanks for the review!

**Comment by luixxiul** [comment]
Yes, I assume so.

**Pull request merged**
