### PR TITLE
replace text Inputs in Devtools with Field bcuz prettier

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes part of https://github.com/vector-im/riot-web/issues/8835

image
image

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by t3chguy** [comment]
image

**Comment by t3chguy** [comment]
Hmm, do you think the Event Type and State Key should be on the same row so when you toggle State/Timeline it doesn't change the modal height

**Comment by turt2live** [comment]
That would be a good optimization, if it's not too difficult

**Comment by t3chguy** [comment]
image

**Pull request merged**
