### PR TITLE
refactor: sliding sync: convert to lists-as-keys rather than indexes

### PR DESCRIPTION
**Pull request by kegsay**
Sister PR to https://github.com/matrix-org/matrix-js-sdk/pull/3086

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
What is the failure mode for someone updating their client but not their proxy?

**Comment by kegsay** [comment]
Outbound HTTP requests will fail as the request types have changed. You'll never get a 200 OK on /sync so it will infini-spinner.

**Comment by t3chguy** [comment]
@kegsay can we detect this and tell the user their server is incompatible in a modal or something?

**Comment by kegsay** [comment]
I lie, it actually is more graceful than I thought:

Screenshot 2023-01-20 at 18 51 17

Good enough @t3chguy ?

**Comment by t3chguy** [comment]
@kegsay if a user tries to enable SS with a non-lists-as-keys will they get an unsupported error? Otherwise a user is bound to click the red button, then enable SS and just get stuck in a loop otherwise

**Pull request merged**
