### PR TITLE
UI Feature Flag: Disable advanced options and tidy up some copy

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/15179

Outstanding questions:

>  Hide "Advanced" in room/user settings

Which one in user settings?

>  Hide advanced settings under user security

This means hiding the ability to unignore users, is that intentional?

### CODE REVIEW

**Comment by turt2live** [comment]
> Which one in user settings?

All of them

**Review by turt2live — APPROVED** [review]

**Comment by t3chguy** [comment]
So the ones in

+ Appearance
+ Security & Privacy
+ Help & About

?

**Comment by turt2live** [comment]
I think so. @lampholder would be the person to ask

**Comment by t3chguy** [comment]
Have made attempts

**Pull request merged**
