### PR TITLE
Add active speaker indicators

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/vector-im/element-web/issues/17627
**Requires https://github.com/matrix-org/matrix-js-sdk/pull/1865**
Type: enhancement

<hr>

https://user-images.githubusercontent.com/25768714/130052281-8f4d1480-27ab-4151-8b06-a6614412d2ea.mp4

Enjoy my awful mic quality and my awful voice :smile: 

---
Here's what your changelog entry will look like:

## ✨ Features
 * Add active speaker indicators ([\#6639](https://github.com/matrix-org/matrix-react-sdk/pull/6639)). Fixes vector-im/element-web#17627 and vector-im/element-web#17627. Contributed by [SimonBrandner](https://github.com/SimonBrandner).

Preview: https://6122072deef4b11e219c2b98--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
Seems great! Going to send this over to design.

**Comment by turt2live** [comment]
also, what is this blocked on?

**Comment by SimonBrandner** [comment]
> also, what is this blocked on?

The js-sdk part of this. I am not 100% sure if I should assign this when I depend on a PR on another layer, but I had stuff merged partially before so better safe than sorry 😄

**Comment by turt2live** [comment]
Ah, we tend to use the blocked tag for stuff that can't progress even through review: it's on us to make sure we land and review both halves.

**Review by gaelledel — APPROVED** [review]

**Comment by DavyLandman** [comment]
Is there a place where dropping this feature is discussed? We had it for a while, and very useful to figure out if your microphone setup is wrong (which happens 50% of the time).

**Comment by SimonBrandner** [comment]
> Is there a place where dropping this feature is discussed? We had it for a while, and very useful to figure out if your microphone setup is wrong (which happens 50% of the time).

It was decided in https://github.com/vector-im/element-web/issues/19513, it will probably come back with native Matrix group calls in the future

CC @gaelledel

**Comment by SimonBrandner** [comment]
> ok, thanks for clarifying. I can understand it's a bit noisy, but some kind of subtle indication your microphone is picking up signals (meaning you configured the right source) is quite useful. Should I open an issue about that?

Yeah, a new issue will probably be the best

**Pull request merged**
