### PR TITLE
Apply tweaks to Thread list as per design spec

### PR DESCRIPTION
**Pull request by t3chguy**
For https://github.com/vector-im/element-web/issues/21502
Fixes https://github.com/vector-im/element-web/issues/21538
Fixes https://github.com/vector-im/element-web/issues/21472

image
image
image
image
image
image
image
image

---
This PR currently has no changelog labels, so will not be included in changelogs.

Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.

Preview: https://pr8149--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by gsouquet — APPROVED** [review]
Code looks great 👍

**Review by janogarcia — CHANGES_REQUESTED** [review]
I've unchecked and added notes to all tasks that need some attention:
https://github.com/vector-im/element-web/issues/21502#issue-1175865083

Update the truncating behavior for the thread summary:
https://github.com/vector-im/element-web/issues/21472#issuecomment-1086273272

**Comment by janogarcia** [comment]
Already reported/handled internally:

- [ ] 🐛 Regression: Right border of container should be 8px (instead of 14px).
- [ ] 🐛 Not fixed yet: Barely visible, the dot is almost completely cut off 

---

cropped-unread-dots

thread panel

**Comment by karlicoss** [comment]
Hi, sorry if it's not the right place to ask, but figured it's the MR where this behavior was introduced.
What's the reason for truncating the width of the thread summary? 

image

Gone through the linked issues, but not sure I understand the `max-width` restriction in particular. There is enough space to fit much more in the preview.
I've undone the `max-width` locally with Stylus extension in the meantime: 

```
@-moz-document domain("app.element.io") {
    .mx_ThreadSummary {
       max-width: unset !important;
    }
}
```

image

Thanks!

**Pull request merged**
