### PR TITLE
Add context menu to breadcrumbs

### PR DESCRIPTION
**Pull request by jaiwanth-v**
Fixes https://github.com/vector-im/element-web/issues/24083

ezgif com-gif-maker (19)

Signed-off-by: Jaiwanth <jaiwanth2011@gmail.com>

---
Here's what your changelog entry will look like:

## ✨ Features
 * Add context menu to breadcrumbs ([\#6058](https://github.com/matrix-org/matrix-react-sdk/pull/6058)). Fixes vector-im/element-web#24083. Contributed by @jaiwanth-v.

### CODE REVIEW

**Comment by t3chguy** [comment]
> Do you have any accessibility concerns or feedback on the implementation here? Between focus context, how tabbing will behave after right clicking, etc?

I haven't tested the build but wrote the context menu and roving tab index stuff, it should all happily interplay in the correct manner. For keyboard or screen reader users it'd behave identically, except also have a context menu which can be opened using the keyboard shortcut for such or a simulated right click.

> The right click interaction is unreliable and causes the UI to glitch (scroll bar can flicker, native menu can flicker, etc). I'd imagine the testing, engineering and maintenance cost of this to be great. Is there anything we can learn from the right click implementation on the space panel which could help?

Indeed the right click after right clicking behaviour looks strange, its not a problem we seem to have on the space panel or room list tiles, so a solution should be found by copying those.

**Review by nadonomy — CHANGES_REQUESTED** [review]
Thanks @t3chguy for the input. @jaiwanth-v it would be great if you could try to strengthen the implementation based on the comments above, for us to re-review. The specific things to avoid are:

1. Flickering of UI elements.
2. General robustness, especially when right clicking multiple times in a row.

**Comment by t3chguy** [comment]
oh yes indeed, its sporadic on the room list too, probably quite non-trivial to avoid altogether

**Comment by Johennes** [comment]
@jaiwanth-v thanks again for your contribution. Are you still interested in following up on this?

**Comment by jaiwanth-v** [comment]
Sure. At the time, it seemed to me like the issues mentioned were
unavoidable. If there is any reasonable solution, please let me know. I'd
be happy to implement.

**Comment by Johennes** [comment]
@jaiwanth-v, right, I _think_ these should be fine given that the experience is the same on the room list currently. Could you merge `develop` into your branch so that we can re-test it?

**Comment by jaiwanth-v** [comment]
Okay

**Comment by Johennes** [comment]
@jaiwanth-v are you still planning to work on this?

**Comment by jaiwanth-v** [comment]
I'm really sorry, I don't think I'll be able to work on it right now.
Someone else can take it up.

**Comment by Johennes** [comment]
I'll be closing this for now to help reduce the number of unfinished PRs. Somebody else may follow up separately.

Thanks for your contribution in any case @jaiwanth-v! 🙏

**Pull request closed without merging**
