### PR TITLE
fix file size display from kB to KB

### PR DESCRIPTION
**Pull request by NSV1991**
Fixes https://github.com/vector-im/element-web/issues/24866

Type: enhancement

Signed-off-by: Neeraj Vageele [neerajvageele451@gmail.com](mailto:neerajvageele451@gmail.com)

Previous/incorrect display size
image

updated/correct display size
image

reference for solution
https://www.npmjs.com/package/filesize

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * fix file size display from kB to KB ([\#10561](https://github.com/matrix-org/matrix-react-sdk/pull/10561)). Fixes vector-im/element-web#24866. Contributed by @NSV1991.

### CODE REVIEW

**Comment by NSV1991** [comment]
> Could we maybe abstract it behind a util somewhere which defaults these parameters so we don't accidentally forget to set them in new code?

added a common function

**Review by t3chguy — APPROVED** [review]
Looks great, thanks for this!

**Comment by luixxiul** [comment]
I am wondering if this should fix megabyte/mebibyte or gigabyte/gibibyte too.

**Comment by richvdh** [comment]
> fix file size display from kB to KB

This description confused me for a while, so for the record, here's what I learnt:

* `kB` can only mean 1000 bytes, and `KB` can only mean 1024 bytes. I wasn't aware the distinction was so well-defined, but despite falling down a Wikipedia rabbit hole, I could find no evidence of `kB` to mean 1024 or `KB` to mean 1000 (though `K` on its own is often used to mean 1000 in general).
* The previous implementation was therefore *correct*, if unhelpful. It did show the correct size of the file in `kB` (or in *metric* `MB`).

**Comment by luixxiul** [comment]
FWIW the original issue this PR closed mentioned inconsistency, rather than incorrectness.

Here is a cropped screenshot of an audio file (audio player) on file panel. The unit should have been either `kB` or `KB`.
> Screenshot from 2023-03-19 05-24-05

The implementation has been indeed correct since `3.56 KB` is equal to `3.65 kB`. 

I have updated the title of the issue: https://github.com/vector-im/element-web/issues/24866#event-8981536029

**Comment by richvdh** [comment]
> FWIW the original issue this PR closed mentioned inconsistency, rather than incorrectness. [Here](https://github.com/vector-im/element-web/issues/24866#issue-1630585824) is a cropped screenshot of an audio file (audio player) on file panel. The unit should have been either `kB` or `KB`.
> 
> > Screenshot from 2023-03-19 05-24-05
> 
> The implementation has been indeed correct since `3.56 KB` is equal to `3.65 kB`.



> [Here](https://github.com/vector-im/element-web/issues/24866#issue-1630585824) is a cropped screenshot of an audio file (audio player) on file panel.

Ah ok so it said "KB" in one place and "kB" in another? That was particularly confusing! Thanks for the clarification.

**Pull request merged**
