### PR TITLE
Reduce volume of ring sounds to normalised levels

### PR DESCRIPTION
**Pull request by JMoVS**
Reduces the volume of the sounds to be roughly at the same level of system sounds - used Signal Desktop for reference of LUFS levels. Adjusted to roughly ~-20LUFS and TP of -8 for sounds.

Signed-off-by: Justin Scholz git@justinscholz.de

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Reduce volume of ring sounds to normalised levels ([\#9143](https://github.com/matrix-org/matrix-react-sdk/pull/9143)). Contributed by @JMoVS.

### CODE REVIEW

**Review by turt2live — DISMISSED** [review]
code-wise, the files are not replaced appropriately here. The file names do not match.

**Comment by JMoVS** [comment]
should be fixed now, thanks for bringing it up @turt2live

**Review by turt2live — COMMENTED** [review]
code-wise seems fine, but needs product review.

**Comment by JMoVS** [comment]
> code-wise seems fine, but needs product review.

ok - according to githbub though, you are still requesting changes - anything else to be done in the review so it passes yours?

**Comment by turt2live** [comment]
I'm somewhat intentionally holding the requested changes so it doesn't accidentally merge before the product team gets to it. It looks fine otherwise.

**Review by janogarcia — CHANGES_REQUESTED** [review]
@JMoVS Thanks for the contribution. There are indeed some annoyingly loud sounds (message.mp3, ring.mp3), and to make things worse, the perceived loudness across the different sounds is a bit over the place. 

**Loudness normalization**

Rather than lowering all the sounds by a fixed dB level, we think the right approach is applying some loudness normalization processing with a target level in LUFS/LKFS. Otherwise, we wouldn't fix the inconsistent loudness across the different sounds.

LUFS, the current industry standard for audio normalization, is based on human perception and thus more accurately represents how loud sounds are perceived. I've validated this approach with our internal audio engineer, and we're testing different target LUFS levels (which will also be used as a target for new UI sounds).

Let me get back to this with some target LUFS.

**Loop length**

Other than that, it seems you've also modified the length of some/most sounds. Unsure if that was intentional or not, but that shouldn't be desired, as it would change the loop rate for those sounds that need to be played on repeat (e.g. ring.mp3). Unless we have a different loop logic implemented on the app.

**Comment by JMoVS** [comment]
@janogarcia Thanks for your reply

Indeed, I did not intend to change the length of the loop - I can get that changed.

I can figure out how to export at a specific LUFS level in Logic - please prepare the respective LUFS levels - I just tried to adjust the level to be roughly similar to the system sound level - but LUFS is probably a better approach. Looking forward to the levels, then I can update this PR

**Comment by JMoVS** [comment]
@janogarcia Ringend, ringback and ring are really loud - if I provide loudness reduced versions with correct looplength now - would you accept that? They are really loud and I would like to avoid having to wait for the perfect LUFS adjusted levels and version and would prefer a quick fix now with a proper fix with proper LUFS levels afterwards - would that work for you?

**Comment by JMoVS** [comment]
Bump @janogarcia

**Comment by DashieTM** [comment]
Perhaps a volume slider for element sounds might be the better temporary fix if this won't be accepted? 
Right now the sounds really are too loud, and turning the volume for element down will make things like calls impossible.

**Comment by JMoVS** [comment]
@janogarcia Is there any news now on LUFS targets so I could update this PR?

**Comment by justjanne** [comment]
@JMoVS From the research I did, a LUFS reference of -10 RMS and peak at -0.2 seems to be relatively standard. Would you be able to normalize the sounds at those levels again so we can take action on this?

**Comment by JMoVS** [comment]
> a LUFS reference of -10 RMS and peak at -0.2

LUFS and RMS are two separate measurements. I tried LUFS -10 but that would have made them louder.

What I did instead now is look at the sounds from Signal Desktop, which are at a nice volume level and took those values (consistently ~-20LUFS and TP of -8 or higher) as the input. I didn't need to adjust busy as it was already at ~-20.

**Comment by justjanne** [comment]
@JMoVS awesome, thanks! I'll take a look on tuesday, after the holiday weekend.

**Comment by JMoVS** [comment]
@justjanne I went ahead and adjusted the name of the PR and initial comment

**Comment by justjanne** [comment]
> any news on this one @justjanne or anything that I still need to adjust?

So far I haven't been able to review it yet, but I've put it at the top of my list of PRs to review.

**Review by justjanne — CHANGES_REQUESTED** [review]
Looks good so far, but please make sure to do the sign-off as required by [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md).

Once that's done, you'll get an :+1: from me :)

**Comment by JMoVS** [comment]
> Looks good so far, but please make sure to do the sign-off as required by [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md).
> 
> Once that's done, you'll get an 👍 from me :)

awesome, if I saw it correctly, adding that I signed off to the pull request comment (first message) is enough - I just added it there - is that sufficient?

**Comment by Johennes** [comment]
> @justjanne Let me know if I need to adjust or include it in the commit itself - the Contributing.MD isn't super clear - I interpreted it as in the "pull request comment" to be fulfilled with the addendum in the very first message on top (I edited it)

That should be alright, I believe. @justjanne shall we get this landed?

**Comment by JMoVS** [comment]
really looking forward to getting this merged finally :)

**Review by justjanne — APPROVED** [review]
:rocket:

**Comment by Johennes** [comment]
@justjanne and I synced up in DM. This seems like a clear improvement to me and, therefore, I'm proposing that we land this without sending it through another design review which would further delaying things. Subsequent improvements can still be applied on top if needed.

**Comment by t3chguy** [comment]
> How long does it take from develop to an SDK release to landing in Element? 🚀

Releases are done every 2 weeks. RC happened 2 days ago so this missed that, so it won't be in next week's release but rather the one after.

**Comment by JMoVS** [comment]
awesome!

**Pull request merged**
