### PR TITLE
Fix misaligned timestamps for thread roots which are emotes

### PR DESCRIPTION
**Pull request by justjanne**
Type: Defect
Fixes: https://github.com/vector-im/element-web/issues/23897

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix misaligned timestamps for thread roots which are emotes ([\#9875](https://github.com/matrix-org/matrix-react-sdk/pull/9875)). Fixes vector-im/element-web#23897. Contributed by @justjanne.

### CODE REVIEW

**Review by weeman1337 — APPROVED** [review]
Tested on the deployment. Works :+1:

**Review by weeman1337 — COMMENTED** [review]
I cannot reproduce the targeted issue on develop:

image

Can you please check if this problem still exists?

**Review by weeman1337 — COMMENTED** [review]
See previous comment. Layer 8 fail from my side when using GitHub :wink:

**Review by gsouquet — APPROVED** [review]

**Comment by justjanne** [comment]
@weeman1337 The issue is less severe on Firefox (where you seem to have tested), but it's still there – the timestamp should be right-aligned.

**Pull request merged**
