### PR TITLE
Resolved overlapping of Space name and Appearance tab in Preferences.

### PR DESCRIPTION
**Pull request by ankur12-1610**
Fixes: [vector-im/element-web/#20331](https://github.com/vector-im/element-web/issues/20331)

Before:
preferences-error

After:
preferences-solved

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Resolved overlapping of Space name and Appearance tab in Preferences. ([\#7449](https://github.com/matrix-org/matrix-react-sdk/pull/7449)). Contributed by @ankur12-1610.

Preview: https://61ca006d6b80650baed74eaa--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Comment by UwUnyaa** [comment]
The code looks fine, but I've noticed you signed off with your user name rather than your legal name. That might block this PR from getting merged.

**Comment by ankur12-1610** [comment]
> The code looks fine, but I've noticed you signed off with your user name rather than your legal name. That might block this PR from getting merged.

@UwUnyaa I've been signing of by the same name till the date and this test never failed:thinking:
I used `git commit -s` so I doubt it will give an error:sweat_smile: as it is auto generated.

**Comment by ankur12-1610** [comment]
> The code looks fine, but I've noticed you signed off with your user name rather than your legal name. That might block this PR from getting merged.

@UwUnyaa Done :) updated the commit.

**Comment by ankur12-1610** [comment]
@UwUnyaa sorry to disturb but can you please review the PR :sweat_smile:

**Review by UwUnyaa — APPROVED** [review]

**Comment by UwUnyaa** [comment]
@ankur12-1610 I gave you an approval, but I'm not able to really move things forward.

**Comment by ankur12-1610** [comment]
> @ankur12-1610 I gave you an approval, but I'm not able to really move things forward.

Thanks, np 😅. Sorry for disturbing:')

**Comment by t3chguy** [comment]
The space name there was intentional, it shouldn't be hidden by having its text colour set to background.

**Comment by t3chguy** [comment]
Closing as wrong approach, should look more like 

image

**Comment by ankur12-1610** [comment]
> The space name there was intentional, it shouldn't be hidden by having its text colour set to background.

Ah! Okay got it 😅

**Pull request closed without merging**
