### PR TITLE
Hide composer and call buttons when the room is tombstoned

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/element-web/issues/21286

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Hide composer and call buttons when the room is tombstoned ([\#7975](https://github.com/matrix-org/matrix-react-sdk/pull/7975)). Fixes vector-im/element-web#21286.

Preview: https://pr7975--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by andybalaam — CHANGES_REQUESTED** [review]
Is it practical to write a test for this?

**Comment by luixxiul** [comment]
WIth the commit of this PR, audio/video call from the top tool bar can be still created.

I am not sure about the spec or its implementation, but is it fine to let them created on a tombstoned room?

**Review by andybalaam — APPROVED** [review]
Great, thank you!

**Comment by t3chguy** [comment]
@luixxiul fixed that now

**Review by andybalaam — APPROVED** [review]
Much better, thanks!

**Comment by luixxiul** [comment]
Is it only me to see that composer itself got enabled on the tombstoned room?

**Comment by t3chguy** [comment]
Yup, found the issue, making another PR now

**Pull request merged**
