### PR TITLE
Revamp notification dot for better readibility

### PR DESCRIPTION
**Pull request by gsouquet**
Fixes https://github.com/vector-im/element-web/issues/21496

Screen Shot 2022-03-30 at 16 34 55
Screen Shot 2022-03-30 at 16 40 23

---
This PR currently has no changelog labels, so will not be included in changelogs.

Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.

Preview: https://pr8197--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]

**Review by janogarcia — CHANGES_REQUESTED** [review]
Change requests in previous comment: https://github.com/matrix-org/matrix-react-sdk/pull/8197#issuecomment-1083358549

**Review by janogarcia — CHANGES_REQUESTED** [review]
Unsure if the Netlify deploy failed but I'm only seeing one of the [suggested changes](https://github.com/matrix-org/matrix-react-sdk/pull/8197#issuecomment-1083358549) being implemented:

> Use Compound’s secondary color for the dot, instead of #61708b.

I'm unchecking the other three.

**Comment by gsouquet** [comment]
It looks like the deploy to the netlify preview failed because it was missing variables in the legacy themes.
Can you please check again?

**Review by janogarcia — APPROVED** [review]
@gsouquet It worked this time. Thanks! 👍

**Pull request merged**
