### PR TITLE
Element-R:  Include crypto info in rageshake

### PR DESCRIPTION
**Pull request by florianduros**
## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Related to https://github.com/vector-im/element-web/issues/24443

---
Here's what your changelog entry will look like:

## ✨ Features
 * Element-R:  Include crypto info in rageshake ([\#11797](https://github.com/matrix-org/matrix-react-sdk/pull/11797)). Contributed by @florianduros.

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]
Might you want to also send whether it is R or not? You can't rely on the feature flag as it only kicks in once the user re-logs with the flag enables. LGTM otherwise

**Comment by florianduros** [comment]
> Might you want to also send whether it is R or not? You can't rely on the feature flag as it only kicks in once the user re-logs with the flag enables. LGTM otherwise

Normally, it's working with both EW and EWR. The used api are implemented for both crypto.

**Comment by t3chguy** [comment]
@florianduros sure, but knowing in the rageshake which is running would likely be good, no? Otherwise you don't know whether the bug is specific to R or not

**Comment by florianduros** [comment]
@t3chguy Oh right, it's a good idea. I'll used the new `getVersion` api that we added in the `cryptoApi`

**Pull request merged**
