### PR TITLE
Treat lists with a single empty item as plain text, not Markdown.

### PR DESCRIPTION
**Pull request by dkasak**
This allows users to send simple messages such as `-`, `+`, `*` and `2021.` without Element Web mangling them into a nonsensical empty list. As soon as any non-whitespace content is added to the item, it switches back to treating it as a list of one item.

Fixes vector-im/element-meta#1265.

Signed-off-by: Denis Kasak <dkasak@termina.org.uk>

The following screenshots were produced by sending the following sequence of messages:

```
-
- foo
+
+ foo
*
* foo
2021.
2021. foo
```

# Before
image

# After
image

---
Here's what your changelog entry will look like:

## ✨ Features
 * Treat lists with a single empty item as plain text, not Markdown. ([\#6833](https://github.com/matrix-org/matrix-react-sdk/pull/6833)). Fixes vector-im/element-meta#1265.

Preview: https://6144dbd806a1fba26b2c36ec--matrix-react-sdk.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
Code-wise this is looking correct, though historically we have wanted to avoid diverging from the commonmark spec, so requesting product review.

**Comment by dkasak** [comment]
Thanks. I'd like to note this can be viewed as not really deviating from CommonMark but as an earlier short-circuit deciding that a given input is not Markdown at all. From a product perspective (IMO), this edge case is not really useful to the user at all and is just a weird/surprising quirk.

**Comment by chagai95** [comment]
Also interested in this fix, maybe we'll pull it into our fork and test it for a while thanks @dkasak

**Comment by t3chguy** [comment]
> Thanks. I'd like to note this can be viewed as not really deviating from CommonMark but as an earlier short-circuit deciding that a given input is not Markdown at all. From a product perspective (IMO), this edge case is not really useful to the user at all and is just a weird/surprising quirk.

Sure, that's how it can be seen, but someone could be using https://spec.commonmark.org/dingus/ to author and preview what they're about to send and now that won't match, so it is still a deviation

**Comment by dkasak** [comment]
Though if we are worried about things like that, we already have [far larger deviations](https://spec.commonmark.org/dingus/?text=Hello%20there%2C%0Athis%20is%20a%20single%20line%0Abut%0AElement%20will%20render%20it%20all%20broken%20up%20%3A%27).

**Comment by t3chguy** [comment]
> Though if we are worried about things like that, we already have far larger deviations.

Yup but this is considered a defect. e.g https://github.com/vector-im/element-web/issues/18299 and https://github.com/vector-im/element-web/issues/8786 and probably more

**Comment by dkasak** [comment]
We're veering quite a bit off-topic, but that's actually a different issue. The linked issues are showing a real defect in which *multiple paragraphs* are incorrectly joined into a single one. This too is a deviation from Commonmark and you'll note dingus [does the right thing](https://spec.commonmark.org/dingus/?text=%3E%20test%0A%3E%0A%3E%20test) here.

What I'm talking about is something else. Markdown is supposed to ignore hard newlines *inside a single paragraph* and reflow the text, but this is purposefully not done in Element (AFAIK) even though it is also most certainly a deviation from Commonmark.

**Comment by dkasak** [comment]
@chagai95: Did you perhaps have a chance to test this in your fork? I'm curious if you have feedback.

**Comment by chagai95** [comment]
Nope, sorry I completely forgot about this I'll never it now and it'll be on protection next week 🙃

**Comment by chagai95** [comment]
It looks like I can not send these messages at all now

**Comment by dkasak** [comment]
Yeah, I've heard that something broke. I need to rebase the PR and figure out what's going on.

**Comment by chagai95** [comment]
Thanks, I'll revert the change on our prod env but I'll gladly test again if you get around to fixing this, just ping me, thx!

**Comment by chagai95** [comment]
I ended up just fixing on our end it's very simple, don't know why git got it wrong...

**Review by daniellekirkwood — APPROVED** [review]

**Comment by andybalaam** [comment]
@dkasak  I just discussed this with @daniellekirkwood and we previously discussed as Element Web team, and we are happy that Element Web's use case is sufficiently different from commonmark's normal use case (EW is often for short, unstructured comments and responses whereas commonmark is often applied to entire documents), that we think this deviation is justified.

So TL/DR if you resolve the conflicts I will happily merge.

**Comment by andybalaam** [comment]
Thank you, finally merged!

**Pull request merged**
