### PR TITLE
Support for MSC2285 (hidden read receipts)

### PR DESCRIPTION
**Pull request by SimonBrandner**
Requires https://github.com/matrix-org/synapse/pull/10413
Documentation: https://github.com/vector-im/element-web/pull/18418

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
Code looks fine, though because this is a real settings flag and not a labs flag it needs design/product review to go through.

**Comment by SimonBrandner** [comment]
> Code looks fine, though because this is a real settings flag and not a labs flag it needs design/product review to go through.

But it's hidden in labs, so does it? Sorry if I am missing something here 😅

**Comment by turt2live** [comment]
If it's meant to be in labs, it should be a `feature_words` setting with `LEVELS_FEATURE`, otherwise it's a real setting.

**Comment by turt2live** [comment]
(also a partner PR to element-web to update the labs docs)

**Comment by SimonBrandner** [comment]
> If it's meant to be in labs, it should be a `feature_words` setting with `LEVELS_FEATURE`, otherwise it's a real setting.

Ah, I'll do that

**Comment by SimonBrandner** [comment]
> (also a partner PR to element-web to update the labs docs)

And that too

**Review by turt2live — APPROVED** [review]
Thanks!

**Comment by turt2live** [comment]
I'm assuming netlify is just angry about lack of develop being merged. Will monitor CI.

**Pull request merged**
