### PR TITLE
Remove hosting link provider from Element

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes https://github.com/vector-im/element-web/issues/23306
Fixes https://github.com/vector-im/element-web/issues/22808
Fixes https://github.com/vector-im/element-web/issues/16578

This PR removes the ability to specify a hosting provider iframe / link to link through to a hosted web service. This was used in the past on the app.element.io instance to send potential customers to Element Home. We've since stopped offering Element Home, so this functionality can now be removed.

## Checklist

-   [N/A - Removing code] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [N/A] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by weeman1337** [comment]
There should be also another PR in Element Web to update [the documentation about that](https://github.com/vector-im/element-web/blob/a26be2665fc1ba55842a613a154cddab5bdb32e6/docs/config.md).

**Review by weeman1337 — COMMENTED** [review]
Looks good :+1: 

There should be also another PR in Element Web at the same time to update [the documentation about that](https://github.com/vector-im/element-web/blob/a26be2665fc1ba55842a613a154cddab5bdb32e6/docs/config.md).

**Comment by Half-Shot** [comment]
@weeman1337 should be there in the linked PR.

**Review by weeman1337 — APPROVED** [review]
:+1:

**Pull request merged**
