### PR TITLE
Add button to clear all notification counts, sometimes stuck in historical

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/4586

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

Edit by TravisR:
**Design**: Please review a use case for https://github.com/matrix-org/matrix-react-sdk/pull/3676 too.
image

### CODE REVIEW

**Comment by turt2live** [comment]
A bit of text to explain what the button does would be nice, also a screenshot/gif of it in action please.

**Comment by t3chguy** [comment]
/me has no good gif tooling on Windows atm :(

**Comment by turt2live** [comment]
a screenshot of the button is fine then, just to show what the placement is and how it looks for future maintainers

**Comment by turt2live** [comment]
@t3chguy: it would be good to get this in. I think it now needs review from design, and possibly product. :(

**Comment by turt2live** [comment]
Blocking on design (or possibly product) review.

**Comment by turt2live** [comment]
alright, will merge this then get the other button through code review independently.

**Comment by Biep** [comment]
A button (or preferably a hotkey) "Go to next room with unread messages" might be more helpful in several use cases.  If one just wants to catch up, the proposal here is great - but if one wants to get rid of a stuck notification it might not be (one might want to keep one's valid notifications).  And having a hotkey that just moves to the next "task at hand" can be very useful in daily work.
I write this here, because I feel there is a way to factor out the options here in a more orthogonal way - but I haven't found that way yet.

**Comment by turt2live** [comment]
@Biep please file an issue rather than commenting on a merged PR. We do not track feedback from closed/merged PRs.

**Comment by Biep** [comment]
I already proposed the "Go to next room with unread messages" function somewhere.  I wrote this here for in case someone saw a more orthogonal division of functions.

**Pull request merged**
