### PR TITLE
Release the irc layout from labs.

### PR DESCRIPTION
**Pull request by JorikSchellekens**
Release it into the wild!

https://github.com/vector-im/riot-web/pull/14350

### CODE REVIEW

**Comment by t3chguy** [comment]
All things exiting Labs need Product review
and given this touches the UI it'll need Design as well

**Comment by JorikSchellekens** [comment]
Ah yes, thank you. i18n done.

**Comment by nadonomy** [comment]
@JorikSchellekens can you add screenshots or point to an ad hoc build to aid review pls?

**Comment by JorikSchellekens** [comment]
It's on riot.im develop. If you turn on the irc flag in labs: the thing to review are the layout options in the appearance tab.

**Comment by JorikSchellekens** [comment]
I can make the width of the name div smaller for the compact layout on this option. But it's a bit arbitrary how wide it is. Perhaps just making it narrow enough to fit the rest of the content on a single line would be ideal.

For the hover state, fixing it for the current behaviour would require a little bit of js fiddling. Which I'd wanted to avoid for something so simple. However, I've just realised an alternative option which may be better over all:

Currently long names on hover cover the text of the message:
image

I propose it should go the other way and cover the avatar and time instead:
image

This way we won't get the hover jump either. However for reaaaaalllly long names this could be a bit of a problem since there's not much space to the left of the names in room view but at that point I think it's pretty obvious who you're talking to.


If the spacing of the modern layout is off I can fake it to make it better but this is currently the exact layout used.

**Comment by JorikSchellekens** [comment]
@nadiaholmquist I wasn't very clear, this pr also exposes the irc layout to general public so this review is also a sign off that we're happy enough with it.

**Comment by jryans** [comment]
@JorikSchellekens After chatting more with @nadonomy and @ara4n, we'd like to make this available without changing the layout itself for launch, but exposing the option in a way that clearly represents it is experimental and only for power users for now.

To do that, can we move the setting into the advanced area, and instead of the fancy radio buttons with preview, use a simple toggle with "Enable experimental compact, IRC style layout [Toggle]"?

**Comment by JorikSchellekens** [comment]
Is the intent to make it available to the general user eventually?

**Comment by jryans** [comment]
> Is the intent to make it available to the general user eventually?

Yes, there would be future work to resolve the polish issues @nadonomy mentions and then expose the setting like you have it here at the moment once that's done.

**Comment by jryans** [comment]
We seem to have done this separately, as it's currently accessible on app via the Appearance tab, so this PR is not needed.

**Pull request closed without merging**
