### PR TITLE
feat(faq): remove keyboard shortcuts button

### PR DESCRIPTION
**Pull request by gefgu**
Signed-off-by: Gustavo Santos <gefgu@hotmail.com>

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [X] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-react-sdk/blob/develop/CONTRIBUTING.md))

Closes: https://github.com/vector-im/element-web/issues/22625

Before
Screenshot
After:
Screenshot

Type: [enhancement/defect/task]

---
Here's what your changelog entry will look like:

## ✨ Features
 * feat(faq): remove keyboard shortcuts button ([\#9342](https://github.com/matrix-org/matrix-react-sdk/pull/9342)). Fixes vector-im/element-web#22625. Contributed by @gefgu.

### CODE REVIEW

**Review by turt2live — DISMISSED** [review]
It's not obvious to me that we'd want to do this - is there an issue link which can accompany this change?

**Review by SimonBrandner — DISMISSED** [review]
Could a screen-shot please be included

**Comment by turt2live** [comment]
(removing request for design until we figure out what the motivation for the change is)

**Comment by SimonBrandner** [comment]
> (removing request for design until we figure out what the motivation for the change is)

I think [the issue (and comments on it)](https://github.com/vector-im/element-web/issues/22625) explains this

**Comment by gefgu** [comment]
@SimonBrandner I've added the screenshot. Excuse me for forgetting to adding it.

**Comment by SimonBrandner** [comment]
> @SimonBrandner I've added the screenshot. Excuse me for forgetting to adding it.

No worries :)

**Review by gsouquet — APPROVED** [review]

**Pull request merged**
