### PR TITLE
Persist pinned message open-ness between room switches

### PR DESCRIPTION
**Pull request by turt2live**
Addresses part of https://github.com/vector-im/riot-web/issues/5405

### CODE REVIEW

**Comment by turt2live** [comment]
part of epic: https://github.com/vector-im/riot-web/issues/6606

**Comment by t3chguy** [comment]
to me it would make sense to throw it into the RoomViewStore, since its part of the RoomView rather than settings

**Comment by turt2live** [comment]
The RoomViewStore doesn't persist anything between sessions as far as I can tell though.

**Comment by t3chguy** [comment]
This pr is entitled between room switches, so I assumed that was the intent...

**Comment by turt2live** [comment]
Ah, sorry, it's meant to behave like the AppsDrawer, as mentioned in https://github.com/vector-im/riot-web/issues/5405#issuecomment-352713921

The AppsDrawer also remembers it's open state between sessions.

**Pull request merged**
